### ISSUE TITLE
delete confirmation dialog shows behind other windows

### ISSUE THREAD

**Issue by tortino** [tablacus/TablacusExplorer#100]
Hi,
I'm using tablacus on win10 x64.
Usually I delete permanently a file by keeping pressed shift, right clicking on the file, and choosing delete. When I do this the delete confirmation dialog appears under the other windows, so I have to minimize all windows and click yes to delete the file.
Is it possible to show the confirmation dialog to the front?
Thanks.

**Comment by tablacus** [comment]
It works without a problem in my machines.
Please tell me your environment.

Are you using an add-on "Multi Process".
If you are using it please use an add-on "Multi Thread" instead.

https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt

Best regards,

**Comment by tortino** [comment]
Hello, here is the info about my system.
TE64 17.8.27 Win 10.0.15063 WS 300 IE 11 it_it Windows Defender

I use Multi Process. Disabling it the dialog appears correctly on front of other windows, however without Multi Process I cannot keep using Tablacus during file operations. 
I have tried Multi Thread, but it doesn't work at all: during a file copy of some gigabytes the whole tablacus is frozen, until the copy is completed. Only Multi Process work correctly.

**Comment by tablacus** [comment]
Please update "Multi process" and "Multi thread".

Open options of Multi process and uncheck "Delete"
![22](https://user-images.githubusercontent.com/5156977/29774684-558bed74-8c3d-11e7-8024-ed4fa458f3de.png)

Open options of Multi thread and unckeck "Copy" and "Move"
![23](https://user-images.githubusercontent.com/5156977/29774702-70c7691a-8c3d-11e7-86cd-5173b1713745.png)

Best regards,

**Comment by tortino** [comment]
Hello,
I configured Multi Process like you said, and it works. Thank you!
I have a last question: at this time I installed only Multi Process.
Do I have to install Multi Thread too? (to me it seems I don't nedd both)
Thanks again.

**Comment by tablacus** [comment]
If you don't think to need "Multi Thread", you won't need that for now.

Best regards,

**Comment by tortino** [comment]
I'm really not sure what Multi Thread does: I was thinking it is the same
as Multi Process but using threads instead of processes.
However it doesn't seem to work for that purpose.


2017-08-30 15:21 GMT+02:00 Gaku <notifications@github.com>:
