### ISSUE TITLE
Allow toolbars to be enabled/disabled in the View menu

### ISSUE THREAD

**Issue by spocko** [tablacus/TablacusExplorer#103]
Most other file explorers allow toolbars to be easily enabled/disabled in the View menu. TE doesn't seem to include any toolbars by default, but I have added a few via add-ons, specifically Horizontal Favorites Bar and Status Bar.

Currently the only way I can see to enable/disable those toolbars is to go into the add-ons menu and enable/disable the add-ons. It would be nicer if they could be listed in the View menu, with checkmarks to enable/disable them. 

On a similar note, I think the View menu should have an option to enable/disable the tree pane.

**Comment by tablacus** [comment]
Please install an add-on "Add-on Switcher".

1.Select "Type" to "Addon Switcher".
2.Click [Browse ...] and select an add-on you want to switch.
![12](https://user-images.githubusercontent.com/5156977/31543769-acdc2e7a-b052-11e7-97fe-324ea0c67e8d.png)

Thank you,

**Comment by spocko** [comment]
That works, thank you.

A possible enhancement to "Add-on Switcher" would be to show a check mark next to the menu item if the add-on is enabled.
