### ISSUE TITLE
Inner Breadcrumbs Address Bar not changing to edit mode

### ISSUE THREAD

**Issue by acambule** [tablacus/TablacusExplorer#105]
After updating to Tablacus 17.10.11 following doesn't work anymore:

![grafik](https://user-images.githubusercontent.com/22659382/31547564-16aaf230-b028-11e7-8a05-3ce7d16974d7.png)

![grafik](https://user-images.githubusercontent.com/22659382/31547594-3c7bf9fa-b028-11e7-8c3a-65a8c127cd35.png)

I have an other installation with Version 17.0.17 where this worked. 
Now you have to click on the folder icon at the beginning of the bar, that is 
a very unusual behaviour. As the function is known as described.

regards
Antonio

**Comment by tablacus** [comment]
I've adjusted it on "Inner Breadcrumbs Address 1.23".
Please try this.

Best regards,

**Comment by acambule** [comment]
Thank you, great. Now it works again.
