### ISSUE TITLE
inner search bar: always search subfolders

### ISSUE THREAD

**Issue by tortino** [tablacus/TablacusExplorer#107]
Hello,
I'm using addon "inner search bar" on win10 and works correctly.
But everytime I have to click on "Did you find what you were searching for? Subfolders".
Please can you a new configuration option, like:
1) always search subfolders
or:
2) search subfolder only if no results were found in current folder
or
3) works like it is now (default): user must click to search the subfolders.
What do you think?
Thanks.

**Comment by tablacus** [comment]
There is no configuration option because the search function is a black box.
In other words,　I don't know how making it.

Thank you,

**Comment by tortino** [comment]
Hello,
so are you using a search function provided by windows 10?

**Comment by tablacus** [comment]
I realize the search function using this function.

https://msdn.microsoft.com/en-us/library/windows/desktop/bb761289(v=vs.85).aspx

This function has only a string argument.

**Comment by tortino** [comment]
ok thanks
