### ISSUE TITLE
Tablacus as default explorer; can't open folder with spaces from another program.

### ISSUE THREAD

**Issue by janbatist** [tablacus/TablacusExplorer#111]
Hi,

I've set Tablacus as my default explorer using Shell execute hook (after reading [this](https://github.com/tablacus/TablacusExplorer/issues/74)).
When I try to open a folder with spaces from Deluge, my torrent client ("Files" tab, right-click, Open), Tablacus actually try to open one tab for each space-separated string.
Example: Torrent in Deluge saved in "D:\Torrents\" with the folder "Torrent 1 2 3\", Tablacus try to open the following tabs: "D:\Torrents\Torrent", "2" and "3".

Information: TE64 17.11.11 Win 6.3.9600 WS 300 IE 11 fr_fr Windows Defender
Addons: mouse,key,addressbar,treeview,mainmenu,tabs,filterlist,tabplus,findfiles,recentlyclosedtabs,clipboardhistory,history,usercss,undoclosetab,tabposition,foldersettings,remember,searchbar,statusbar,sizestatus

Anything I can do about that?

Thank you, Tablacus is amazing!

**Comment by tablacus** [comment]
I will try to check up on that.
Thank you,

**Comment by tablacus** [comment]
Would you tell me command line?

Input following text on Address bar and push Enter key.
`javascript:alert(api.GetCommandLine());`
![image](https://user-images.githubusercontent.com/5156977/32894286-b4a0d8ee-cb1f-11e7-8f74-9e23f562976f.png)

Tell me dialog box message like this.
![image](https://user-images.githubusercontent.com/5156977/32894404-107adc50-cb20-11e7-8185-d984443d86b4.png)

Best regards,

**Comment by janbatist** [comment]
The dialog bos message is:
"C:\Programe Files (x86)\Tablacus\TE64.exe"

**Comment by tablacus** [comment]
Then, please close Tablacus Explorer once.
And Open "D:\Torrents\Torrent 1 2 3" in Tablacus Explorer from Torrent.

Input following text on Address bar and push Enter key once again.
`javascript:alert(api.GetCommandLine());`

Tell me dialog box message.

One more time, please.
Thank you,

**Comment by janbatist** [comment]
You can also see the tabs TE tried to open (the screenshot will be deleted in 7 days):
![](https://lut.im/gallery#E5U0Kmwvny/xHQrXGKxeh0E3l1h.png)

**Comment by tablacus** [comment]
Thank you for your information.

I've adjusted it on Tablacus Explorer 17.11.20.
Please try to update.

Best regards,

**Comment by janbatist** [comment]
Awesome, it works perfectly.

Thank you very much.

**Comment by tablacus** [comment]
My pleasure.
Thank you,
