### ISSUE TITLE
MTP device drag and drop broken

### ISSUE THREAD

**Issue by tortino** [tablacus/TablacusExplorer#112]
Hello,
I use Tablacus with four multi panels. I open the MTP device (android) in a panel, and Windows Hard Disk into another tablacus panel.
I have recently found that it doesn't work copy/move from MTP device to Windows Hard Disk, but only when using drag and drop! I drag the file and then drop it, and it simply does nothing.
However if I drag and drop using right mouse button, and then choose "move" then the file is deleted from android, and it's NOT copied to Windows, so it is lost!
If I use copy/cut in Android and paste in Windows it works ok.
Please note that some versions ago it was working correctly.
Thanks.

**Comment by tablacus** [comment]
Hello,

I confirmed that drag and drop from MTP device fine with my PC.

Tablacus Explorer does not process MTP because Windows process MTP.
It may be a recently updated Windows problem.

Tablacus Explorer releases
https://github.com/tablacus/TablacusExplorer/releases

Thank you,

**Comment by tortino** [comment]
Hello,
I did some more testing and it's the MultiProcess plugin: when it's enables it doesn't copy files, when it's disabled it works correctly.
This is my MultiProcess configuration:
![image](https://user-images.githubusercontent.com/26486758/32791079-6b8ee120-c960-11e7-9993-720eace3e2f5.png)

**Comment by tablacus** [comment]
Thank you for your information.
I've adjusted an add-on "Multi process" for now.

Best regards,

**Comment by tortino** [comment]
yes, now it works perfectly.
thank you.

**Comment by tablacus** [comment]
I've found the problem part on Tablacus Explorer 17.11.16.
Thank you,
