### ISSUE TITLE
Column widths not remembered in details view

### ISSUE THREAD

**Issue by bobasaurus** [tablacus/TablacusExplorer#114]
When in details view, if you increase the width of the "Name" column (for example) to show large filenames then change directories, it will revert back to the default width.  Returning to the directory I originally resized again reverts to the default column width and hides the large filenames.  So I find myself widening columns constantly and it gets annoying.  

Is there an option to remember your column width settings individually per directory?  Or is there at least a way to change the default column size to be bigger?

**Comment by bobasaurus** [comment]
As an example, here is a column I resized to show big names:
![tabalcus resized to show large names](https://user-images.githubusercontent.com/450407/32972715-f803bf98-cbb0-11e7-9779-7ded255cd94b.png)

But after returning to the directory again, it reverts to the default column width and I have to resize it again:
![tabalcus after returning to directory](https://user-images.githubusercontent.com/450407/32972722-fd24362e-cbb0-11e7-82da-5e8ef84fe074.png)

**Comment by tablacus** [comment]
Please install an add-on "Remember folder view settings".
Best regards,

**Comment by bobasaurus** [comment]
That works great, thanks a lot.  Nice to have an easy fix.  You might consider making this a default plugin in the future.

**Comment by tablacus** [comment]
My pleasure.
It may be difficult because there are similar add-ons.
Thank you,
