### ISSUE TITLE
Unable to restart and install new version after update

### ISSUE THREAD

**Issue by dasu88** [tablacus/TablacusExplorer#115]
In recent editions, it is not possible to restart and install a new version after the update. Does anyone have a similar situation? I use windows 10

**Comment by dasu88** [comment]
I found the reason that caused the update to fail to restart because of an anti-virus software Kaspersky protection that prevented tablacus from restarting its execution instructions and was blocked from executing.

**Comment by tablacus** [comment]
Thank you for letting me know.
