### ISSUE TITLE
Tabs opening network folders turn to Results Folder

### ISSUE THREAD

**Issue by hoshizaki** [tablacus/TablacusExplorer#116]
From a recent version (not the latest, but don't remember from which, and still happening on the latest version too), all tabs opening folders on network drives turn to "Results Folder" at once when PC comes back from suspend. When I move to those tab, the tab's name changes to "::{2965E715-EB66-4719-B53F-1672673BBEFA}", showing "This folder is not available (このフォルダーは利用できません)" message in the file list area.
Network drives take several seconds to be reconnected when PC comes back from suspend, and it seems during this several seconds Tablacus considers those folders unavailable and changes to Result Folder.
I'm using TE64 17.11.20 on Win7 in Japanese.

**Comment by tablacus** [comment]
Thank you for your report.
I've adjusted it on Tablacus Explorer 17.11.28.
Please try to update.
Best regards,

**Comment by hoshizaki** [comment]
Thank you for the new version. I've been trying it for a few days and it seems the problem is not happening any more. Thank you again!

**Comment by tablacus** [comment]
My pleasure.
