### ISSUE TITLE
TE issue list + add-ons by category document

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#117]
Hi Gaku san,

I have been trying out TE since September and have found many issues. I have highlighted the most critical issues in red in the spreadsheet. Could you please help?

Besides, I have written some notes about the add-ons. We can share it with the public if you agree to. Please let me know if you want to correct or update anything in the document. I am going to update the document as my tryout continues.

Note: The spreadsheet and the document are in LibreOffice format.

Regards,

ccfs

[ccfs171201.zip](https://github.com/tablacus/TablacusExplorer/files/1521034/ccfs171201.zip)

**Comment by tablacus** [comment]
Thank you for finding issues.
I will adjust these problems.

Of course, I agree with your share of the add-on document.
I want to share your document to ["Tablacus Explorer Add-ons wiki"](https://github.com/tablacus/TablacusExplorerAddons/wiki) too if you agree to.

Best regards,

**Comment by ccfs** [comment]
Yes you can share the odt and pdf files at http://www.eonet.ne.jp/~gakana/tablacus/explorer_en.html and/or https://github.com/tablacus/TablacusExplorerAddons/wiki.

Regards,

**Comment by tablacus** [comment]
Thank you so much,

**Comment by ccfs** [comment]
some updates
[ccfs171205.zip](https://github.com/tablacus/TablacusExplorer/files/1530447/ccfs171205.zip)

**Comment by tablacus** [comment]
Many thanks again!!!

**Comment by ccfs** [comment]
more updates
[ccfs171211.zip](https://github.com/tablacus/TablacusExplorer/files/1547325/ccfs171211.zip)

**Comment by tablacus** [comment]
I've shared the zip files at http://www.eonet.ne.jp/%7Egakana/tablacus/explorer_en.html

Thank you very much,

**Comment by ccfs** [comment]
more updates
[ccfs171219.zip](https://github.com/tablacus/TablacusExplorer/files/1570147/ccfs171219.zip)

How is the progress of the fixes to the issues in red?

**Comment by tablacus** [comment]
I'm on it.
Could you please wait for a while? 

Best regards,

**Comment by ccfs** [comment]
more updates
[ccfs171224.zip](https://github.com/tablacus/TablacusExplorer/files/1584622/ccfs171224.zip)

Merry Christmas and Happy New Year!

**Comment by tablacus** [comment]
Thank you,
Merry Christmas and Happy New Year to you too!

**Comment by ccfs** [comment]
more updates
[ccfs171229.zip](https://github.com/tablacus/TablacusExplorer/files/1592707/ccfs171229.zip)

**Comment by ccfs** [comment]
some minor updates
[ccfs180107.zip](https://github.com/tablacus/TablacusExplorer/files/1609732/ccfs180107.zip)

How is the progress of the fixes to the issues in red?
Please let me know in case you do not understand or do not agree to some issues.

The issues in red are the most critical ones. I will highlight some others for your action when the former are resolved.

**Comment by tablacus** [comment]
I don't know how to remove the upward arrow from the column.

Thank you,

**Comment by ccfs** [comment]
Please focus on the issues in RED first.
Please let me know in case you do not yet have a solution on any other issues. We can hold them on until someday you find out a solution.
Thanks.

**Comment by tablacus** [comment]
I've adjusted "Address bar", "Inner breadcrumbs address bar", "Inner Address bar", "Everything" and "Fix selection on sort".

----

"Multi process" "Filter list"
I could not find a problem.
![image](https://user-images.githubusercontent.com/5156977/34672389-98ab731c-f4c1-11e7-815f-17c04ab3152d.png)

[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

"Multi thread" has a different method from "Multi process".

----
I've added these to the todo list.
But I have lots of todos from many people.
Please wait for that without a lot of expectations.

Thank you,

**Comment by ccfs** [comment]
I am restructuring the issue list and assign a priority to each issue. Currently 7 issues have the highest priority. Please help to fix the 7 problems first. Thanks.
[ccfs180116.zip](https://github.com/tablacus/TablacusExplorer/files/1635112/ccfs180116.zip)

**Comment by tablacus** [comment]
I've adjusted some problems.
Thank you,

**Comment by ccfs** [comment]
I have tested the changes and updated the documents accordingly.
I have raised some issues to the highest priority. Now there are 8. Please help to fix.
Thank you very much. 
[ccfs180119.zip](https://github.com/tablacus/TablacusExplorer/files/1646351/ccfs180119.zip)

**Comment by tablacus** [comment]
I can’t open issue.ods with Google Sheet.
So, I think that it is not good to tell the issues with ods.

- Clipboard history
I haven't encountered this.
It seems that there is a lack of information.

[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

**Comment by ccfs** [comment]
- Please download LibreOffice from https://ja.libreoffice.org/download/libreoffice-fresh/ and install it to your computer. It can be used to open ods and odt files.
- Clipboard history problem: I will try to re-generate the problem and post the information later.
- I have raised 3 more problems about Control Panel to the highest priority. They seems to be caused by the recent change about "Open in Explorer" tab context command.
Thanks.
[issue list.zip](https://github.com/tablacus/TablacusExplorer/files/1649677/issue.list.zip)

**Comment by tablacus** [comment]
I know it but I don't want to install more office software anymore.

Best regards,

**Comment by ccfs** [comment]
** regarding new version for filter **

* The new version does not working correctly when a filter is in the format *text1;text2. For example:
A folder has 12 files:
A
AA
AB
AC
B
BA
BB
BC
C
CA
CB
CC
Input filter: *a;b
Then 9 files should be shown:
A
AA
AB
B
BA
BB
BC
CA
CB
But only 6 files are shown:
AB
B
BA
BB
BC
CB

* If a user inputs consecutive *, TE may change the input incorrectly, e.g.:
- input **b, TE incorrectly removes b together.
- input **b*, TE incorrectly changes it to *b.

**Comment by tablacus** [comment]
Thank you for your report.
I've adjusted it on Tablacus Explorer 18.1.22
Please try to update.
Best regards,

**Comment by ccfs** [comment]
Regarding "Filter bar”:
1. Click one item in folder tree (a folder or a “Control Panel” item). Click it again. TE shows an error message about “TypeError”.
2. With the 12 test files listed above:
- input *a;b*: correct, 7 items are shown
- input *A;B*: incorrect, 8 items are shown (AB should not be matched)
I don't know why uppercase leads to a different result.
Besides, I tried "Wildcard Select" add-on. It produced a similar result.
Please see the ods file for other issues.
Thanks.
[ccfs180123.zip](https://github.com/tablacus/TablacusExplorer/files/1655651/ccfs180123.zip)

**Comment by ccfs** [comment]
Regarding "Filter bar”:
1. Click one item in folder tree (a folder or a “Control Panel” item). Click it again. TE shows an error message about “TypeError”.
2. With the 12 test files listed above:
- input "*a;b*": correct, 7 items are shown
- input "*A;B*": incorrect, 8 items are shown (AB should not be matched)
I don't know why uppercase leads to a different result.
Besides, I tried "Wildcard Select" add-on. It produced a similar result.
Please see the ods file for other issues.
Thanks.
[ccfs180123.zip](https://github.com/tablacus/TablacusExplorer/files/1655679/ccfs180123.zip)

**Comment by ccfs** [comment]
Regarding "Filter bar”:
1. Click one item in folder tree (a folder or a “Control Panel” item). Click it again. TE shows an error message about “TypeError”.
2. With the 12 test files listed above:
- input `*a;b*`: correct, 7 items are shown
- input `*A;B*`: incorrect, 8 items are shown (AB should not be matched)
I don't know why uppercase leads to a different result.
Besides, I tried "Wildcard Select" add-on. It produced a similar result.
Please see the ods file for other issues.
Thanks.
[ccfs180123.zip](https://github.com/tablacus/TablacusExplorer/files/1655684/ccfs180123.zip)

**Comment by hdmyt** [comment]
> \* stands for any number of any characters
> ? stands for any one character

I think this means `*` matches empty.
For example.
`*test` should match `test` and `atest` .
`?test` should not match `test` and should match `atest`.

**Comment by tablacus** [comment]
1.

I haven't encountered this.

Please read this and tell me your environment and concrete operation method etc. as much as possible.
[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

2.

I've adjusted it on Tablacus Explorer 18.1.23
Please try to update.

----

I can’t open issue.ods.

![image](https://user-images.githubusercontent.com/5156977/35281538-8287a7c8-0096-11e8-9c77-1479ee904e0f.png)

Best regards,

**Comment by tablacus** [comment]
Dear hdmyt

There was a bug.
I really appreciate it.

**Comment by hdmyt** [comment]
Hello.

> Click one item in folder tree (a folder or a “Control Panel” item). Click it again. TE shows an error message about “TypeError”

This bug happened to me, but i don't know how to reproduce exactly. 
<img width="303" alt="type_error" src="https://user-images.githubusercontent.com/26209339/35308964-77906cae-00ed-11e8-9d34-1308174e9c9b.png">

**Comment by ccfs** [comment]
The issues in highest priority are now published in pdf.
[ccfs180124.zip](https://github.com/tablacus/TablacusExplorer/files/1659585/ccfs180124.zip)

**Comment by ccfs** [comment]
I have tested the fixes. They are OK. Thank you very much.
Here is an updated issue list.
[issue list.pdf](https://github.com/tablacus/TablacusExplorer/files/1663362/issue.list.pdf)

**Comment by ccfs** [comment]
new version of ShellExecuteHook tested ok
Here is an updated issue list.
[issue list 180127.pdf](https://github.com/tablacus/TablacusExplorer/files/1669824/issue.list.180127.pdf)

**Comment by tablacus** [comment]
> ## Shell execute hook
> When I chose:
> - “open folder location” from the context menu of a folder
> shortcut on Windows desktop, or
> - “open file location” from the context menu of a file
> shortcut on Windows desktop,
> the mouse pointer changed to “background processing”
> mode for over 10 seconds. I could not use the Windows
> desktop during that time period.
> [The problem occurs in Windows desktop. No problem for
> “desktop” folder opened in a tab in TE nor “desktop” folder
> opened in Windows Explorer]
> [The problem does not occur if the target location is
> already opened in Windows Explorer]
> [Occurs under Windows 7 and 10]

It occurred only by canceling Explorer with Shell Execute Hook.
I suspect that "Open folder location" is waiting until Explorer opens folder or time passes.
It may be a problem on a MS side.

**Comment by ccfs** [comment]
* I have marked the above case as "no solution yet" in the issue list.
* Shell execute hook version 1.05 has a problem. Please see the updated issue list.
[issue list 180129.pdf](https://github.com/tablacus/TablacusExplorer/files/1672113/issue.list.180129.pdf)
Thanks.

**Comment by tablacus** [comment]
> [Windows 7 + TE 18.1.23 + Shell execute hook 1.05]
> There is a side effect regarding control panel:
> 1. Click a control panel item in Windows Explorer.
> 2. TE shows up unexpectedly (the side effect).
> 3. The control panel item is opened normally in Windows
> Explorer.
> The side effect happens EXCEPT for those items NOT
> shown in the folder tree of TE, e.g.
> - Task Bar and Start Menu
> - Folder Options
> - Sound
> - Date and Time
> - Region and Language
> - Index Options
> - Realtek HD Sound
> - Intel Graphics
> (I have tried re-booting the computer but still the same)
> Shell execute hook 1.04 does not have this problem.

I haven't encountered this.

- Normal

![Normal](https://user-images.githubusercontent.com/5156977/35512616-bd323468-0543-11e8-8671-426355881e34.png)

- Enable Shell execute hook 1.05

![Enable Shell execute hook](https://user-images.githubusercontent.com/5156977/35512662-e41e566a-0543-11e8-8c84-fcf21b7fb395.png)

Can you upload images?

Best regards,

**Comment by hdmyt** [comment]
Hello Gaku.

I investigated "Open folder location" logic by Windbg.

Explorer calls SHELL32!SHOpenFolderAndSelectItems.
SHOpenFolderAndSelectItems calls SHELL32!SHOpenOrGetWebBrowserApp(undocumented api).
It creates ShellWindows object.
If IShellWindows::FindWindowSW returns S_FALSE(this means Not Found),
it calls SHELL32!ShellExecuteExW and then retry IShellWindows::FindWindowSW.
If the result is S_FALSE, it calls SHELL32!CWaitForWindow::WaitForWindowToOpen.
CWaitForWindow waits until DIID_DShellWindowsEvents event is invoked.

[This question](https://stackoverflow.com/questions/22118653/shopenfolderandselectitems-for-explorer-replacement-program) seems to be related this problem.

**Comment by tablacus** [comment]
Hello hdmyt.

Thank you for your useful information.
Thank you so much,

**Comment by ccfs** [comment]
Regarding Shell execute hook 1.05:

Step 1: Open Control Panel - Appearance and Personalize
![image](https://user-images.githubusercontent.com/34089121/35547966-5c978490-05b7-11e8-9387-5826c1ba2c9f.png)

Step 2: Click "Display". TE shows up (unexpectedly) and then Control Panel - Display shows up.
![image](https://user-images.githubusercontent.com/34089121/35548025-c397ae22-05b7-11e8-904f-a4a192b4a3c2.png)

Alternate Step 2: But if I click "Folder Options", correctly only Control Panel - Folder Options shows up.
![image](https://user-images.githubusercontent.com/34089121/35548077-08f6f766-05b8-11e8-8b60-a11b1ed7f201.png)

Shell execute hook 1.04 does not have the problem at step 2. Only Control Panel - Display shows up.

**Comment by ccfs** [comment]
"Missing control panel items in folder tree" is actually another issue (which is in low priority and can be fixed later), but may give you a hint to fix Shell execute hook. In Step 1 above there are 6 control panel items, but in folder tree there are only 4. Interestingly "Display" exists but not "Folder Options".
![image](https://user-images.githubusercontent.com/34089121/35548291-7109e326-05b9-11e8-9352-14a38cf499f6.png)

**Comment by ccfs** [comment]
Regarding "Open folder location", I will re-assign the issue to highest priority if you want to fix it now. Thanks hdmyt.

**Comment by tablacus** [comment]
Thanks for your images, I've adjusted.
Please update "Shell execute hook" once again.

Best regards,

**Comment by ccfs** [comment]
Here is an updated issue list.
[issue list.pdf](https://github.com/tablacus/TablacusExplorer/files/1691574/issue.list.pdf)
TE now seems to allow no tab in a pane. Is this intentional or a bug?
Regards,

**Comment by ccfs** [comment]
Now "TE Add-ons by Category" document is published at https://github.com/ccfs/TablacusExplorer/issues/1 so that TE users do not need to read through this thread to find out the updated document.

**Comment by tablacus** [comment]
Thanks a lot,

**Comment by ccfs** [comment]
How is the progress to the fix to the issues I posted on Feb 3?

**Comment by tablacus** [comment]
I'm sorry but I'm in the middle of something.

Thank you,

**Comment by ccfs** [comment]
The fix to "Shell Execute Hook" can be postponed for now. I have raised some other issues to the highest priority. Hopefully they are easy to fix.
[issue list 180219.pdf](https://github.com/tablacus/TablacusExplorer/files/1735795/issue.list.180219.pdf)

**Comment by tablacus** [comment]
I've adjusted add-ons "Clip folder", "Extension icon changer", "Filter icon changer", "Folder settings" and "History".
Please update them.

Best regards,

**Comment by ccfs** [comment]
The new versions are tested ok. But one more bug is found in "Folder settings". Please see the updated issue list.
[issue list 180220.pdf](https://github.com/tablacus/TablacusExplorer/files/1739475/issue.list.180220.pdf)

**Comment by tablacus** [comment]
I've adjusted add-ons "Add all tabs to favorites", "Folder settings", "Mixed sort" and "Tab groups".
Please update them.

Best regards,

**Comment by ccfs** [comment]
1. The new version of "Folder settings" does not work as I expected.
2. Some other bugs about Favorites are found.
![1](https://user-images.githubusercontent.com/34089121/36474174-a9cf6ba2-1731-11e8-8c8e-077762b59b62.png)
![2](https://user-images.githubusercontent.com/34089121/36474183-afdcf352-1731-11e8-9c55-d152d7dd43ed.png)
[issue list 180221.pdf](https://github.com/tablacus/TablacusExplorer/files/1743564/issue.list.180221.pdf)

**Comment by tablacus** [comment]
I've adjusted add-ons "Horizontal Favorites bar", "Favorites bar" and "Folder settings".
Please try updating them.

Best regards,

**Comment by ccfs** [comment]
1. New version of "Horizontal Favorites bar" and "Favorites bar" are OK.

2. "Folder settings" version 1.17 has 2 problems (see the updated issue list for details). The problems can be solved by changing "options.js" back to version 1.15. Please fix the add-on in this way.
![foldersettings](https://user-images.githubusercontent.com/34089121/36577594-2ae1c3cc-1893-11e8-9c9f-878c14d45392.png)

3.  Please help to fix a problem in Count Bar and Status Bar (see the updated issue list for details).

[issue list 180223.pdf](https://github.com/tablacus/TablacusExplorer/files/1750459/issue.list.180223.pdf)

Thanks.

**Comment by tablacus** [comment]
I've adjusted Tablacus Explorer 18.2.24 and add-ons "Count bar" and "Folder settings".
Please try updating them.

Best regards,

**Comment by ccfs** [comment]
- "Folder settings" is tested OK.

- Last problems of Count Bar and Status Bar are solved, but 2 new problems come up:

1. Nothing is shown for an empty result list
![empty](https://user-images.githubusercontent.com/34089121/36625882-2ba860b0-1963-11e8-8be5-b31340eca788.png)

2. "Searching" is shown after sorting a file list
![sort](https://user-images.githubusercontent.com/34089121/36625894-6d4a91a0-1963-11e8-91c1-66c7f47a556c.png)

[issue list 180224.pdf](https://github.com/tablacus/TablacusExplorer/files/1754064/issue.list.180224.pdf)

Thanks.

**Comment by tablacus** [comment]
I've adjusted Tablacus Explorer 18.2.24 and add-ons "Count bar".
Please try updating them.

Best regards,

**Comment by ccfs** [comment]
Status Bar is ok now.
But Count Bar shows nothing when any item is selected.
![incorrect count bar](https://user-images.githubusercontent.com/34089121/36641222-0432e8fc-1a67-11e8-99bd-ea120d927984.png)
Regards,

**Comment by tablacus** [comment]
Count bar had a problem in Chinese Windows.
I've adjusted an add-on "Count bar".
Please try updating it.

Best regards,

**Comment by ccfs** [comment]
Count bar is ok now.
Please see the updated issue list.
[issue list 180226.pdf](https://github.com/tablacus/TablacusExplorer/files/1758415/issue.list.180226.pdf)
Regards,

**Comment by ccfs** [comment]
The fix to script\options.js tested ok.
Please see the updated issue list.
[issue list 180227.pdf](https://github.com/tablacus/TablacusExplorer/files/1762252/issue.list.180227.pdf)

Regards,

**Comment by ccfs** [comment]
The fixes have some problems.
Please see the updated issue list.
[issue list 180228.pdf](https://github.com/tablacus/TablacusExplorer/files/1766387/issue.list.180228.pdf)
Regards,

**Comment by tablacus** [comment]
I've adjusted Tablacus Explorer 18.2.28 and add-ons "Size status", "Total file size".
Please try updating them.

Best regards,

**Comment by ccfs** [comment]
1. "Total file size" is ok.
2. "Size status" still has some problems. Please see the updated issue list.
[issue list 180301.pdf](https://github.com/tablacus/TablacusExplorer/files/1769877/issue.list.180301.pdf)
Regards,

**Comment by tablacus** [comment]
I've adjusted Tablacus Explorer 18.3.1 and add-ons "Size status".
Please try updating them.

Best regards,

**Comment by ccfs** [comment]
1. I have re-tried with TE 18.3.1 + "Size status" 1.06 (the latest version in the download page). The result is still the same as in "issue list 180301.pdf"
2. 2 other problems are found. Please see 
[issue list 180301 more.pdf](https://github.com/tablacus/TablacusExplorer/files/1774402/issue.list.180301.more.pdf)
Regards,

**Comment by ccfs** [comment]
Regarding the "TypeError" of "Size status bar" problem, I tried to re-produce it on Windows 10 but have found out that **TE on Windows 10 does not show any item stored in a zip file in a result list, but TE on Windows 7 does**. Therefore TE on Windows 10 does not have the problem.

Currently TE on Windows 7 can show items stored in a zip file in a result list  produced by:
- history
- speed dial
- flat
- clip folder
- label
- badge
But both "Size Status Bar" and "Full Path Bar" have a problem in handling items stored in a zip file in the above result lists.

My suggestion is to amend TE and/or the above 6 add-ons so that they do the same on Windows 7 and 10 - do not show any item stored in a zip file in a result list,

Anyway, a zip file can still be opened in a tab like a regular folder. "Size Status Bar" and "Full Path Bar" can handle the items stored in a zip file shown in a tab properly.

Regards,

**Comment by tablacus** [comment]
I've adjusted it on Tablacus Explorer 18.3.3.
Please try updating it.

Best regards,

**Comment by ccfs** [comment]
I notice that TE on Windows 10 now can show items stored in a zip file in a result list.
Please see the pdf for some problems regarding result list.
[TE 18.3.3 result list problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1780592/TE.18.3.3.result.list.problems.pdf)
Regards,

**Comment by ccfs** [comment]
I have tested TE 18.3.6. Result lists are OK now (only some minor problems in low priority).
Please see the latest issue list.
[issue list 180307.pdf](https://github.com/tablacus/TablacusExplorer/files/1788336/issue.list.180307.pdf)
Regards,

**Comment by ccfs** [comment]
- Enabling/disabling add-ons are tested OK.
- Size status bar is tested OK (only some minor problems in low priority).
- Please see the latest issue list.
[issue list 180308.pdf](https://github.com/tablacus/TablacusExplorer/files/1792429/issue.list.180308.pdf)
Regards,

**Comment by ccfs** [comment]
Please help to solve 2 more problems.
[nonexistentoverlay problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1799332/nonexistentoverlay.problem.pdf)
[attributescolor problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1799333/attributescolor.problem.pdf)
Regards,

**Comment by ccfs** [comment]
I have tested TE 18.3.11. Findings:
- “TypeError” in “Overlay icon of nonexistent items” seems be solved.
- "Colored with attributes": partially solved. No problem in removable drive but still a problem in NTFS drives.
- A serious problem in showing a new tab:

<When Speed dial is disabled>
If all tabs are closed, the default new tab becomes "about:newtab" but shows "This folder cannot be used". (TE 18.3.7 shows "Desktop")

<When Speed dial is enabled>
The speed dial list is incorrectly shown in the current tab, not in a new tab, when:
- double click tab area
- Ctrl+T
- choose "New tab" from tab context menu
- click the + button (when Tab Plus is used)

Regards,

**Comment by tablacus** [comment]
> Colored with attributes": partially solved. No problem in removable drive but still a problem in NTFS drives.
I think that it's in the specifications.
NTFS drives root has attributes "HSDI".
If this part bothers you,  please use "Root".

Best regards,

**Comment by ccfs** [comment]
Please proceed to the following 2 issues:
[code instead of name.pdf](https://github.com/tablacus/TablacusExplorer/files/1806021/code.instead.of.name.pdf)
[Folder image problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1806022/Folder.image.problem.pdf)
Here is a set of test data to show the first 2 problems of folder image:
[folder-image-test.zip](https://github.com/tablacus/TablacusExplorer/files/1806020/folder-image-test.zip)
You can try it:
- with "Folder" option ticked and cleared, and then
- move "file 10" to "Test Folder" and re-try

Thank you very much for your quick action.

Regards,

**Comment by tablacus** [comment]
> Folder image Problem 1: Fix
> - 10 or more non-image items are sequenced before an image file in the selected folder, and
> - “Expanded” is NOT opted for,
> > This add-on cannot find that image file.

 It's isn't problem. it's in the specifications.
Default “Number of items” is 10.
If you need further search, please enter "number of items".

Best regards,

**Comment by ccfs** [comment]
- New version of "Folder image" is tested ok.
- New version of "Back" and "Forward" are tested ok. Please fix the problem in "Inner Back" , "Inner Forward" and "Recently closed tabs" too.
- A problem about non-existent item is found:
[non-existent item problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1810769/non-existent.item.problem.pdf)
Here is a set of test data to show the problem
[non-existent item test.zip](https://github.com/tablacus/TablacusExplorer/files/1810765/non-existent.item.test.zip)

Regards,

**Comment by ccfs** [comment]
Please see a latest issue list for your action.
[issue list 180319.pdf](https://github.com/tablacus/TablacusExplorer/files/1824386/issue.list.180319.pdf)
[Flat add-on problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1824389/Flat.add-on.problems.pdf)
[Everything add-on problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1824390/Everything.add-on.problems.pdf)
 Thanks.

**Comment by ccfs** [comment]
- New version of "Recently closed tabs" and "Everything" are ok
- New version of "Flat" solves the "undeleted file" problem, but not the "new file" problem.
- Please see a latest issue list for your action.
[issue list 180320.pdf](https://github.com/tablacus/TablacusExplorer/files/1828695/issue.list.180320.pdf)
[Find Files add-on problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1828696/Find.Files.add-on.problems.pdf)
Thanks.

**Comment by tablacus** [comment]
> Check box Select
> When a Windows Aero theme is used:
> In “small icon view”, the check boxes for the leftmost column of items are displayed in half and cannot be clicked.
> When a Windows classic theme is used:
> In “small icon view”, no check box is displayed for the leftmost column of items

I think that there is no way to fix them.

Best regards,

**Comment by ccfs** [comment]
- "Flat" add-on is tested ok (with a minor problem, can be ignored for now)
- new version of "Check box" add-on is good, but with a small problem
[Check Box add-on v1.04 Problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1837336/Check.Box.add-on.v1.04.Problem.pdf)
- new version of "Tab Groups" does not solve the double-click problem completely.
- please see the latest issue list 
[issue list 180322.pdf](https://github.com/tablacus/TablacusExplorer/files/1837343/issue.list.180322.pdf)
Regards,

**Comment by ccfs** [comment]
I have added more cases to the problem description of Check Box add-on.
Please see the latest issue list.
[issue list 180323.pdf](https://github.com/tablacus/TablacusExplorer/files/1840692/issue.list.180323.pdf)
[Check Box add-on v1.04 problem (revised).pdf](https://github.com/tablacus/TablacusExplorer/files/1840694/Check.Box.add-on.v1.04.problem.revised.pdf)
[Favorites Bar add-on v1.25 problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1840696/Favorites.Bar.add-on.v1.25.problems.pdf)
[Label add-on v1.23 problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1840698/Label.add-on.v1.23.problems.pdf)
[Label button add-on v1.07 problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1840699/Label.button.add-on.v1.07.problem.pdf)
[Startup settings add-on problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1840700/Startup.settings.add-on.problem.pdf)
Regards,

**Comment by ccfs** [comment]
1. Favorites Bar
- "default icon" problem is fixed
- "cannot show a correct icon" problem still occurs
2. Label
- "search for label with space" is fixed
- only 1 leading / trailing space is removed, but ALL leading / trailing space characters should be removed
3. Label button
- "Shift+Click" problem still occurs
4. Please see the latest issue list
[issue list 180326.pdf](https://github.com/tablacus/TablacusExplorer/files/1846220/issue.list.180326.pdf)
[Type Drop-Down Box Problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1846222/Type.Drop-Down.Box.Problems.pdf)
[Multiple panes with Tab groups problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1846224/Multiple.panes.with.Tab.groups.problems.pdf)
Regards,

**Comment by tablacus** [comment]
>     Label button
>     "Shift+Click" problem still occurs

It's in the specifications.
This is a refine search.

Best regards,

**Comment by ccfs** [comment]
- "Favorites Bar" problems are solved.
- "Type Drop-Down Box" problems are solved.
- "Multiple panes with Tab groups problems" are solved.
- New version of "check box" is excellent, except a small problem.
- 2 new issues about "Startup settings".
- Please see the latest issue list
[issue list 180328.pdf](https://github.com/tablacus/TablacusExplorer/files/1855300/issue.list.180328.pdf)
- Label button: What is a "refine search"?

Regards,

**Comment by ccfs** [comment]
I have re-tried "Label button" and have understood what "refine search" is. Thanks.

**Comment by tablacus** [comment]
> Check box
> <When “All” check box is ticked>
> “Click an empty space of a file list to deselect all items” does not
> work when 2 or more items are selected

It's in the specifications.

Best regards,

**Comment by ccfs** [comment]
- New version of "Startup settings" is tested ok.
- Regarding "Check box": Why not deselect all items in that case?
- Please see the latest issue list
[issue list 180329.pdf](https://github.com/tablacus/TablacusExplorer/files/1859627/issue.list.180329.pdf)
[Folder settings add-on v1.19 problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1859628/Folder.settings.add-on.v1.19.problems.pdf)
Regards,

**Comment by tablacus** [comment]
> Regarding "Check box": Why not deselect all items in that case?

It will not be deselected even if you mistake clicking.

Regards,

**Comment by tablacus** [comment]
> Tab groups
> 1. Right click an inactive workspace tab, then
> 2. Do any one of the followings:
> - press Esc
> - choose “Rename”, then press Esc or click Cancel
> - choose “Close tab”, then press Esc or click Cancel
> - choose “Close other tabs”, then press Esc or click Cancel
> - choose “Load”, then press Esc or click Cancel
> - choose “Save” (then do whatever)
> then
> 3. Click the inactive workspace tab
> Cannot switch to the workspace

I can't encounter this.
Please read this!
https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt

Best regards,

**Comment by ccfs** [comment]
please see the problem description here
[Tab groups add-on v1.22 problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1863333/Tab.groups.add-on.v1.22.problem.pdf)
Regards,

**Comment by tablacus** [comment]
Thanks for the detailed information.
I've adjusted it on Tab groups 1.23
Please try to update.
Best regards,

**Comment by ccfs** [comment]
Thanks. So far the changes are ok.
Please see the latest issue list.
[issue list 180331.pdf](https://github.com/tablacus/TablacusExplorer/files/1865322/issue.list.180331.pdf)
Regards,

**Comment by ccfs** [comment]
- New version of "Multi process" is ok. Thanks!
- Please help to fix a problem.
[TE 18.4.2 pane activation problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1871484/TE.18.4.2.pane.activation.problem.pdf)
Regards,

**Comment by ccfs** [comment]
Please see the latest issue list.
[issue list 180406.pdf](https://github.com/tablacus/TablacusExplorer/files/1883711/issue.list.180406.pdf)
[TE 18.4.5 problems in Folder Settings sorting instruction.pdf](https://github.com/tablacus/TablacusExplorer/files/1883713/TE.18.4.5.problems.in.Folder.Settings.sorting.instruction.pdf)
[TE 18.4.5 pane activation problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1883715/TE.18.4.5.pane.activation.problem.pdf)
[TE 18.4.5 pane activation grace period.pdf](https://github.com/tablacus/TablacusExplorer/files/1883716/TE.18.4.5.pane.activation.grace.period.pdf)
Regards,

**Comment by ccfs** [comment]
Thank you very much. Last problems are all solved.
All result lists can now be sorted and grouped correctly.
A few problems are found. Please see the latest issue list.
[issue list 180411.pdf](https://github.com/tablacus/TablacusExplorer/files/1898565/issue.list.180411.pdf)
[TE 18.4.10 statistics problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1898568/TE.18.4.10.statistics.problems.pdf)
[TE 18.4.10 re-open result list problems.pdf](https://github.com/tablacus/TablacusExplorer/files/1898569/TE.18.4.10.re-open.result.list.problems.pdf)
[TE 18.4.10 initial sort by name problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1898570/TE.18.4.10.initial.sort.by.name.problem.pdf)
[Remember folder view settings 1.30 problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1898572/Remember.folder.view.settings.1.30.problem.pdf)
Regards,

**Comment by tablacus** [comment]
Thank you for the information.

> TE 18.4.10 statistics problems

I've adjusted it on Tablacus Explorer 18.4.11.
Please try to update.

> TE 18.4.10 re-open result list problems

I've adjusted it on Empty folder, Flat and Find files.
Please try to update.

> TE 18.4.10 initial sort by name problem

This is probably in specification.
There's nothing I can do about it.

Thank you,

**Comment by tablacus** [comment]
> “Remember folder view settings” + “Speed Dial”
> When all tabs are closed, the speed dial list shows but does not follow
> the lastly used folder view.

I've adjusted it on Tablacus Explorer 18.4.12.
Please try to update it.

Best regards,

**Comment by ccfs** [comment]
Thank you. So far the changes are ok.
This thread becomes too long. I am closing this and re-open a new thread.
Regards,
