### ISSUE TITLE
Problem with the desktop on startup.

### ISSUE THREAD

**Issue by VladDraculTepes** [tablacus/TablacusExplorer#118]
Hello,

I have an issue : I have a tab always set on the Desktop, when I start the program, the tab is always put on "Big Icons". I set this tab on "detail" each time, but when I restart my computer and start Tablacus again, the Desktop tab is put again on "Big Icons".
I have not the problem with all other tabs, only with the Desktop one.

Could you please correct this ?

**Comment by tablacus** [comment]
Are you using the add-on "Remember folder view settings" or "Folder settings"?
If you are not using them try installing an add-on "Remember folder view settings".

Thank you,

**Comment by VladDraculTepes** [comment]
Thank you, it seems to work.

Have a nice day

2017-12-27 13:07 GMT+01:00 Gaku <notifications@github.com>:
