### ISSUE TITLE
split bar error

### ISSUE THREAD

**Issue by bobasaurus** [tablacus/TablacusExplorer#119]
When trying to drag the split bar, I get this error popup:

![tablacus error](https://user-images.githubusercontent.com/450407/35651039-7889424e-069b-11e8-9057-673f38760c96.png)

I have these addons installed:

![tablacus addons](https://user-images.githubusercontent.com/450407/35651091-a4c3d5cc-069b-11e8-8359-c1fa349e3531.jpg)

**Comment by bobasaurus** [comment]
Nevermind, I installed the latest version and the bug went away.  If it comes up again I'll add a new comment here.

**Comment by tablacus** [comment]
Thank you for your report.
Thanks anyway,
