### ISSUE TITLE
[TE.cpp] tePathAppend causes Buffer over-read

### ISSUE THREAD

**Issue by hdmyt** [tablacus/TablacusExplorer#120]
Hello Gaku.

tePathAppend uses SysAllocStringLen.
From [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/ms221639(v=vs.85).aspx)
> SysAllocStringLen function
Allocates a new string, copies the specified number of characters from the passed string, and appends a null-terminating character.

``` c++
VOID tePathAppend(BSTR *pbsPath, LPCWSTR pszPath, LPWSTR pszFile)
{
	*pbsPath = SysAllocStringLen(pszPath, lstrlen(pszPath) + lstrlen(pszFile) + 1);
	PathAppend(*pbsPath, pszFile);
}
```

tePathAppend is used like this.
``` c++
BSTR bslib;
wchar_t path[] = L"c:\\windows\\system32";
tePathAppend(bslib,path,"shell32.dll");
```
In this case, the first argument of SysAllocStringLen is the address of path,
the second argument is 31(19+11+1).

SysAllocStringLen copies **31 characters** from the first argument  to new allocated memory.
But the valid length of the first argument is **20**(19+null).

**Comment by tablacus** [comment]
Thank you for your information.
Anyway, I will check my sources again. 
Thanks a lot,

**Comment by tablacus** [comment]
I've adjusted it on Tablacus Explorer 18.2.2.
Thank you for your advice.
Thank you,

**Comment by hdmyt** [comment]
Thanks for fixing so quickly :smile:

**Comment by tablacus** [comment]
My pleasure.
