### ISSUE TITLE
Delete Key does not remove files

### ISSUE THREAD

**Issue by OldCityCat** [tablacus/TablacusExplorer#121]
I'm assuming I should be able to use the Delete key or Shift Delete to remove files in Details View.
As of now I have to use Right Mouse Menu.
Do I need a Add-on? If so which one.

Thanks
OldCityCat

**Comment by tablacus** [comment]
I haven't encountered this.
Would you like to tell me more about your environment?

[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

Best regards,

**Comment by OldCityCat** [comment]
Thank you for your response and sorry for not providing more info to begin with.
I'm running Windows 10 with the latest updates.
Simply selecting a file to delete, pressing delete key, hear a ding
Tried adding a check to the check boxes, same just hear ding

TE Information 
TE64 18.1.31 Win 10.0.10586 WS 100 IE 11 en_us 96 Windows Defender AVG Internet Security

Add-ons
mouse,key,addressbar,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabs,statusbar,findfiles,remember,tabname,run,checkbox,openinstead,gridlines,delete,stripes,notepadalternative,stripeslite

![image-0020](https://user-images.githubusercontent.com/32240880/35748270-77aaae68-081b-11e8-8fd3-0c45041e2dbf.png)

**Comment by tablacus** [comment]
Thank you for your information.

Please input following code to Address bar and press Enter key.
`javascript:alert(eventTE.Key.List[339])`

![1](https://user-images.githubusercontent.com/5156977/35768754-9dc70e6e-0944-11e8-944d-0f6f8c5afbef.png)

Please tell me the dialog string.

Then, please input following code to Address bar and press Enter key.
`javascript:alert(eventTE.Key.All[339])`

Please tell me the dialog string.

----

Next, Open the option of "key" add-on.

1. Select "List"
2. Click on "Input" and push "Delete" key and click on "OK".
3. Select Type to "Context"
4. Click on "Browse..." and choose "Delete".
5. Click on "Add" and "OK".

![2](https://user-images.githubusercontent.com/5156977/35768898-0f83cafa-0946-11e8-9bef-97c0a186b5c7.png)

Best regards,

**Comment by OldCityCat** [comment]
Navigated to "C:\Program Files (x86)\te160821" copied the code to Address bar and pressed Enter key.
javascript:alert(eventTE.Key.All[339])

Received this popup window;

![image-0011](https://user-images.githubusercontent.com/32240880/35769216-cffccbe0-08d5-11e8-9225-9bb918cdbd5b.png)

**Comment by OldCityCat** [comment]
Sorry, I completed the steps and Delete Key is working as expected.

Thanks you

**Comment by tablacus** [comment]
My pleasure,

I forgot to put a Context in the image.

![2](https://user-images.githubusercontent.com/5156977/35773776-5af23d42-099f-11e8-8a87-fc6ea3c4186c.png)
