### ISSUE TITLE
teGetCommandLine may cause obscure bugs

### ISSUE THREAD

**Issue by hdmyt** [tablacus/TablacusExplorer#123]
Hello Gaku.

teGetCommandLine creates bsCmdLine from the command line.
bsCmdLine does not seem to  be null-terminated.
If teSysAllocStringLenEx is called with bsCmdLine , SysStringLen returns a unexpected value.

**Comment by tablacus** [comment]
Hello hdmyt

It is probably not a problem.
I think SysStringLen doesn't need a null-terminated like lstrlen.
A BSTR has a length prefix.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms221069(v=vs.85).aspx
http://keicode.com/com/bstr-alloc-free.php (Japanese)

**Sample code**
```
BSTR bs = ::SysAllocStringLen(NULL, 9);
lstrcpy(bs, L"ABC");
int a = ::SysStringLen(bs);
int b = lstrlen(bs);
```
**Results**
- a : 9
- b : 3

Thanks always,

**Comment by hdmyt** [comment]
Sorry, I got it all wrong. 
But I have found the bug that causes Access Violation.
This bug is happened when using Restart add-on.

From line no 10467
```
			while (hwndTE = FindWindowEx(NULL, hwndTE, szClass, NULL)) {
				if (GetWindowLongPtr(hwndTE, GWLP_USERDATA) == nCrc32) {
					BSTR bs = teGetCommandLine();
					COPYDATASTRUCT cd;
					cd.dwData = 0;
					cd.lpData = bs;
					cd.cbData = ::SysStringByteLen(bs) + sizeof(WCHAR);
					DWORD_PTR dwResult;
					LRESULT lResult = SendMessageTimeout(hwndTE, WM_COPYDATA, nCmdShow, LPARAM(&cd), SMTO_ABORTIFHUNG, 1000 * 30, &dwResult);
					::SysFreeString(bs);
```

'bs' address is the same as g_bsCmdLine.
'bs' is freed by SysFreeString, g_bsCmdLine is freed ,too.
So, teGetCommandLine returns an invalid address when it is called from teApiGetCommandLine.

**Comment by tablacus** [comment]
Thank you for debugging information.
I will fix it with the next version.

Thanks a lot,

**Comment by tablacus** [comment]
I've adjusted it on Tablacus Explorer 18.2.11.
Thanks always,

**Comment by hdmyt** [comment]
I have confirmed this bug was fixed.
Thank you!

**Comment by tablacus** [comment]
My pleasure,
