### ISSUE TITLE
Not really an issue, but need help on a few things

### ISSUE THREAD

**Issue by craigalan** [tablacus/TablacusExplorer#124]
First let me say, that I just stumbled upon Tablacus.  I have been using Q-Dir for YEARS...love it, but it was missing somethings that I really wanted...like CheckBoxes!!!  Found them as an add-on with Tablacus.  ;)

So my questions.  I have looked all over and can't seem to find an answer for these. I will admit, I am still trying to understand the inner working of all of the options of this little program.  There are so many!!!

1) I have saved a couple of layouts, is there a way to put a layout selection right on the menu bar?  Each individual layout that I want would be ideal, rather than a menu/dropdown.

2) Finally, I realize I can just back up my entire folder, but is there a way to export all of the custom settings I made, so I can import later if I have to?

Thank you!!!!

Craig

**Comment by craigalan** [comment]
Finally figured it out!  :)

**Comment by tablacus** [comment]
That's great!!
I've made a layout selector with script.
https://gist.github.com/tablacus/328852c66880fe31445fcd5d956f75af

Thank you,

**Comment by craigalan** [comment]
Cool.  I put 3 layouts on the toolbar in the lower left-hand corner.  I am using icons to show them, along with a “+” icon, which allows quick access to the add-ons.

Seriously loving this program.  It has all the things that I ever wanted when I was using Q-Dir…an more

Craig
![2018-02-11_050123](https://user-images.githubusercontent.com/17946784/36072335-35886ef8-0eec-11e8-9cf3-5e25195fbe86.jpg)

**Comment by tablacus** [comment]
My pleasure,
