### ISSUE TITLE
[Feature] Resize split windows

### ISSUE THREAD

**Issue by saatomic** [tablacus/TablacusExplorer#125]
I would love to see the feature to resize split windows.
Like so:

```
┌────┬────┐
│    │    │
│    │    │
│    │    │
└────┴────┘
```

Resize >>

```
┌───────┬─┐
│       │ │
│       │ │
│       │ │
└───────┴─┘
```

**Comment by tablacus** [comment]
1.Click on left pane
2.Open Options...
![image](https://user-images.githubusercontent.com/5156977/36486486-df4a5488-1761-11e8-9628-8ba954fb2d5b.png)

3.Click Tabs->Advanced
4.Input "Width" to "70%" or any data( 70% or 70 (pixel))
5:Click "Move" and"OK"
![image](https://user-images.githubusercontent.com/5156977/36486538-014bc332-1762-11e8-9f77-842200e71eac.png)

6.Click on right pane
7.Open Options...
![image](https://user-images.githubusercontent.com/5156977/36486654-54450ef4-1762-11e8-9eec-031f2f2c682b.png)

8.Click Tabs->Advanced
9.Input "Left" to "70%" or any data(70% or 70 (pixel))
10:Click "Move" and"OK"
![image](https://user-images.githubusercontent.com/5156977/36486707-79a3a7d2-1762-11e8-9ee4-23be6ff7094c.png)

11.Like this
![image](https://user-images.githubusercontent.com/5156977/36486741-9721273a-1762-11e8-87ee-223b63c46c93.png)

12.Save layout.. to save layout.
![image](https://user-images.githubusercontent.com/5156977/36486874-f43b8e24-1762-11e8-9ac5-f261f5340307.png)

Best regards,

**Comment by saatomic** [comment]
Perfect, thank you very much!

**Comment by tablacus** [comment]
My pleasure,
