### ISSUE TITLE
[Feature] Custom split windows

### ISSUE THREAD

**Issue by saatomic** [tablacus/TablacusExplorer#126]
I used to use the Q-Dir explorer, which offered more freedom with split windows.
I'd love to see the ability to use custom split windows. Maybe a window could be split again, based on the existing split window options. 

![SplitWindowOptions](https://i.imgur.com/gPWFNKv.png)

What I'm thinking is if you split the main vertically window (Option number 3 from the image above):

```
┌────┬────┐
│    │    │
│    │    │
│    │    │
└────┴────┘
```

Then split the window on the right again horizontally (Option number 2 from the image above):

```
┌────┬────┐
│    │    │
│    ├────┤
│    │    │
└────┴────┘
```

**Comment by tablacus** [comment]
1.Split 2x1
2.Click on right pane.
3.Open options...
![image](https://user-images.githubusercontent.com/5156977/36487503-6ad682a4-1764-11e8-991e-5b9e1a7fbd91.png)

4.Click Tabs->Advanced
5.Input Height to "50%"
6.Click "Move"
![image](https://user-images.githubusercontent.com/5156977/36487617-bff3be5a-1764-11e8-81c1-b9b9d97b3135.png)

![image](https://user-images.githubusercontent.com/5156977/36487730-f72bd538-1764-11e8-8260-11293723506b.png)

7.Input Top to "50%"
8.Click "Add".
9.Click "OK".
![image](https://user-images.githubusercontent.com/5156977/36487888-55c56c44-1765-11e8-8e6b-053b8deeafd4.png)

10.Like this
![image](https://user-images.githubusercontent.com/5156977/36487952-86bffb48-1765-11e8-8120-1f74ae14534a.png)

Best regards,

**Comment by saatomic** [comment]
Perfect, thank you very much!

**Comment by tablacus** [comment]
My pleasure,
