### ISSUE TITLE
Blocking during copying

### ISSUE THREAD

**Issue by saatomic** [tablacus/TablacusExplorer#129]
Tablacus seems to block any interaction when copying.

When you copy/paste a large file with Tablacus, any other activity is impossible until the copying is finished.

**Comment by tablacus** [comment]
Please install an add-on [Multi Thread](https://github.com/tablacus/TablacusExplorerAddons/wiki/multithread).

Best regards,

**Comment by saatomic** [comment]
perfect, thank you!

**Comment by tablacus** [comment]
My pleasure,
