### ISSUE TITLE
Folder menu and hot button issues

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#134]
please see the following PDFs
[Folder menu and hot button issues.pdf](https://github.com/tablacus/TablacusExplorer/files/1937662/Folder.menu.and.hot.button.issues.pdf)
[Hot button causing address bar problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1937663/Hot.button.causing.address.bar.problem.pdf) _[solved 2018/4/24]_
Regards,

**Comment by ccfs** [comment]
I have revised this issue to adapted for recent changes to address bar add-ons.
[Folder menu and hot button issues (revised).pdf](https://github.com/tablacus/TablacusExplorer/files/1946468/Folder.menu.and.hot.button.issues.revised.pdf)
[Hot button add-on 1.04 problem.pdf](https://github.com/tablacus/TablacusExplorer/files/1946469/Hot.button.add-on.1.04.problem.pdf)
Regards,

**Comment by tablacus** [comment]
> Hot button
> When “Up” is not ticked:
> The button should appear for a supported result list item or a clip folder.

I think that it becomes slow when it corresponds.

Best regards,

**Comment by ccfs** [comment]
Having considered the potential performance issue you mentioned, I have a new suggestion:

1. When the current tab is a folder:
(a) show hot button for folders only
(b) "../parent" is useless and should always be omitted, because "../parent" IS the current folder.

2. When the current tab is a result list or a clip folder:
(a) show hot button for any item
(b) show "../parent" in the menu. It can be used to open the folder where the hovered item is stored.

By then:
- hot button and "../parent" will show only when it is probably useful.
- "Up" option is not necessary.
- In case you still have any concern, "Up" option can be retained to control case 2(b) above.

Regards,

**Comment by ccfs** [comment]
1. New version of hot button add-on is tested OK.
2. Do you have any comment on my suggested enhancement to Folder Menu (new option to show hidden items)?
Regards,

**Comment by ccfs** [comment]
New "Include hidden items" option is tested OK. Thanks.
