### ISSUE TITLE
how to hidden content line

### ISSUE THREAD

**Issue by cweijan** [tablacus/TablacusExplorer#136]
![tim 20180428124903](https://user-images.githubusercontent.com/27798227/39392127-b5e7b55e-4ae2-11e8-97c8-03acc7915a5b.png)

How to hidden this line, these line is so ugly, I can't found css set the content style.
TE is very cool!  Thanks!

**Comment by tablacus** [comment]
Please install an add-on [Classic Style](https://github.com/tablacus/TablacusExplorerAddons/wiki/classicstyle).

![Classic Style](https://user-images.githubusercontent.com/5156977/34878182-a07db018-f7ec-11e7-8812-9a9cd0d8885b.png)

Best regards,
