### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by skintfr** [tablacus/TablacusExplorer#137]
Hi,
When an update is available, i have  pop-up to download and install the code automatically.
Process failes with error :    
"Network error (404)
http://github.com/tablacus/TablacusExplorer/releases/download/18.5.1/te180501.zip"

I have this issue only since few weeks. I was working well before
The URL is ok becuase if i put it in my browser it download the code without pb.

Thanks

**Comment by tablacus** [comment]
I haven't encountered this.

Please read this and tell me your environment.
[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

Do you use an add-on "Download"?

Best regards,

**Comment by skintfr** [comment]
Hi,
TE64 18.5.1 Win 10.0.16299 WS 100 IE 11 fr_fr 96 McAfee VirusScan Enterprise Windows Defender

mouse,key,addressbar,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,download,autoupdate,addfavorites,controlpanelbutton,drivebutton,inactivepane,multiprocess,multithread,refresh,sidetreeview,speeddial,split,systemfolders,dragdrop

I am using the download add-on (you have created "for me" after i report an issue with get add-on view that was not working)

Thanks

**Comment by tablacus** [comment]
I checked around.
BITSAdmin has a SSL problem.

Domain | Windows 10 | Windows 7
----|----|----
https://api.github.com | OK | Failed
https://www.githug.com | Failed |Failed
https://tablacus.github.io | OK | Failed

I will consider about alternative URLs.

Best regards,

**Comment by tablacus** [comment]
I've adjusted in Tablacus Explorer 18.5.3
This version supports alternative URLs for SSL error.

Best Regards,

**Comment by skintfr** [comment]
Great works as usual.

Thanks a lot.

Bye
