### ISSUE TITLE
Copy and paste resulting in duplicate files does not prompt anything

### ISSUE THREAD

**Issue by saatomic** [tablacus/TablacusExplorer#142]
I've noticed that if I copy and paste a file in the same directory Tablacus does not do anything.

Is there a way to create a new copy of the file (e.g. Original file: `file.txt`, Copy/Pasted file: `file-COPY.txt`) or show a prompt asking what to do (e.g. overwrite, skip or create new copy).

---

TE64 18.5.21 Win 10.0.14393 WS 100 IE 11 de_de 96 Windows Defender

mouse,key,addressbar,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabs,colorlabels,color,split,split6,split3,remember,shellexecutehook,foldersettings,multithread

Process:

 - Move to an existing location
 - Copy random file
 - Paste random file

Expected: A duplicate copy of the file.
What happens: Nothing.

I can not always reproduce this. I'm using split windows and multiple tabs. On some tabs it works just fine, on others I have this problem. I can't determine why and it does not have anything to do with the directory, because on some tabs I can copy/paste just fine and on others it doesn't work in the same directory.

**Comment by tablacus** [comment]
I haven't encountered it.

Please read this and tell me your environment.
[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

Best regards,

**Comment by saatomic** [comment]
Sorry about my vague description, I've updated the original issue.

**Comment by tablacus** [comment]
I see.
I will try to do it with add-on.

Best regards,

**Comment by saatomic** [comment]
Thank you very much for your work and awesome tool!

**Comment by tablacus** [comment]
I can't think of any name of this add-on.
Can you help me?

* Multiple items dialog
![image](https://user-images.githubusercontent.com/5156977/40661389-98102ea2-638e-11e8-8499-a203914368c8.png)

* Single item dialog
![image](https://user-images.githubusercontent.com/5156977/40661960-fb0d3b8e-638f-11e8-9205-152fec87dc1f.png)

Best regards,

**Comment by saatomic** [comment]
Oh wow! That was quick! Thank you so much!

Maybe something like "Duplicate copy"?

**Comment by tablacus** [comment]
How nice!
I've made an add-on "Duplicate copy".
Please try it.

Best regards,

**Comment by saatomic** [comment]
very cool - thank you very much for the effort!
I'll test it right away!

**Comment by saatomic** [comment]
The plug-in works perfectly for most files, but with some files I still have the same issue.

If I copy/paste these files, Tablacus flashes, but does nothing with the file. I can't reproduce this behavior, but it's always the same with these files.

I'll try and find out what makes those files special for Tablacus.

**Comment by tablacus** [comment]
Thank you for your report.
I've adjusted it in "Duplicate copy 1.01".
Please try it.

Best regards,

**Comment by saatomic** [comment]
It works as intended now!

Thank you again for your effort!

**Comment by tablacus** [comment]
My pleasure,
