### ISSUE TITLE
How can hide fie listview border

### ISSUE THREAD

**Issue by cweijan** [tablacus/TablacusExplorer#143]
I use css beautify the tablacus , but I found the style is valid for file listview , how can hide these border
![image](https://user-images.githubusercontent.com/27798227/41272477-df778614-6e47-11e8-9d92-6f04cb645a02.png)

And when I use plugin Classic Style , the selected color is very ugly , How can change it?
![image](https://user-images.githubusercontent.com/27798227/41272524-12824940-6e48-11e8-9d7d-c0da43ed1da6.png)
![image](https://user-images.githubusercontent.com/27798227/41272515-06b8137e-6e48-11e8-80bd-2d53f2d577bd.png)

**Comment by tablacus** [comment]
* How to hide the border of the list view.

1.Open Options -> List view -> Style
2.Check "No client edge".
3.Restart Tablacus Explorer.

![image](https://user-images.githubusercontent.com/5156977/41291108-be408f3a-6e89-11e8-919e-578878157e8f.png)

* How to change the selected color

https://answers.microsoft.com/en-us/windows/forum/windows_10-start-winpc/how-to-change-desktop-selection-box-color/ce3a5fa8-54b5-4270-a97c-df53a63a78e1?auth=1

Best regards,

**Comment by cweijan** [comment]
It is effective , thans!
