### ISSUE TITLE
Sort folder menu when file system is FAT, FAT32 or exFAT

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#145]
Enhancement request: Sort the folder menu by name
- when the menu is requested from an address bar (right arrow or download arrow), and
- when the folder is under a FAT, FAT32 or exFAT drive, and
- except when the folder is under a ZIP file (probably already sorted)
- Let user enable this function by a new option under "Tools > Options > General > Menus"

Please let me know if you have any comment.

Thanks.

**Comment by tablacus** [comment]
Please try Tablacus Explorer 18.6.16.

Thank you,

**Comment by ccfs** [comment]
I have tested TE 18.6.16. I have the following comments:

1. My request is to let user opt for the sorting. But this version does not provide the option and just sorts the menus. This causes a performance problem when a menu has a thousand items or more, e.g. C:\Windows\System32. TE holds up much longer than the prior version. The option is to let user sacrifice sorting to performance if he/she often gets the problem.

2. My request is to sort only for FAT, FAT32 and exFAT. But this version sorts the menus unconditionally. Since the menus for NTFS and ZIP files are already sorted, additional sorting just slows down TE.

Regards,

**Comment by tablacus** [comment]
Please try to install a new add-on "Folder menu settings".

![image](https://user-images.githubusercontent.com/5156977/41809817-da365ba4-772e-11e8-8026-4a90fc9557ce.png)

Best  regards,

**Comment by ccfs** [comment]
I have tested TE 18.6.21 together with the new add-on. My request is basically fulfilled. Thank you.
But I find a small problem in the add-on. Please see the PDF for details.
[Folder menu settings 1.00 problems.pdf](https://github.com/tablacus/TablacusExplorer/files/2132501/Folder.menu.settings.1.00.problems.pdf)
Regards,

**Comment by ccfs** [comment]
Folder menu settings 1.01 has been tested OK. Thanks.
