### ISSUE TITLE
Backup Settings

### ISSUE THREAD

**Issue by washere** [tablacus/TablacusExplorer#147]
Hi

Thanks for this great software. I am new to it. It is better than the File Commanders I tired for years. Over 40 file commanders over 25 years.

I set this up nicely on one laptop. I want to set it up on another laptop.

I installed many Add-ons today. I searched but found no Settings Backup/Restore.
Can we have an Add-on created for:

*** Settings Back-up
* Settings Restore**

Can we have an Add-on for Settings Backup/Restore ?

________________________________________________

**Or** if not a complete Tablacus Explorer System Settings Backup/Restore, at least:

*** Add-ons Backups/Restore ?**

So I can install the same Add-ons on another computer?

________________________________________________

Just like we have Layout Save/Load, it would be great for settings or at least add-ons list.

I took 4 screen-shots of my add-ons to install on another laptop one by one.

**Thanks again.**

**Comment by tablacus** [comment]
This software save the setting in the folder.

Open Help -> About Tablacus Explorer
![image](https://user-images.githubusercontent.com/5156977/42135501-c07e3462-7d86-11e8-8377-4ffbea3ad2e5.png)

![image](https://user-images.githubusercontent.com/5156977/42135509-d3db3e4c-7d86-11e8-9d1c-df78c93f0251.png)

Click on the blue rectangle to open the tablacus folder.

Copy the tablacus folder.

In case you installed Tablacus Explorer to the Program Files directory:

Copy the folder "%AppData%\tablacus" too.
(red rectangle)

![image](https://user-images.githubusercontent.com/5156977/42135543-4cb18902-7d87-11e8-9eb0-612a686d3d98.png)

Best regards,

**Comment by washere** [comment]
Thank you my friend. I will do these when I get back home tonight and close the issue.

Thank you again.

**Comment by washere** [comment]
Thanks. I installed in C:\PortableApps.

I can zip for backup.

Thanks again. Specially for wonderful help with images and highlights.

You are very kind :)

Doumo Arigatou Gozaimasu
(どうもありがとうございます

**Comment by tablacus** [comment]
My pleasure, I’m glad it work well.

Best regards,
