### ISSUE TITLE
Shortcut to Jump from Pane to Pane + ShortCuts Section in Settings or Help?

### ISSUE THREAD

**Issue by washere** [tablacus/TablacusExplorer#148]
Hi, thanks for TE, I LOVE IT.

2 Issues:

**1) ShortCuts Section in Settings or Help**

Most of us coders or professional users of Windows often use shortcuts on keyboards instead of mouse.

Most Productivity software have a lot of shortcuts and usually a ShortCuts Section in Settings.

Some are customizable, some are not and some are a mix of both.

Can we have some basic ones.

**_______________________________________________________**

**2) Shortcut to Jump from Pane to Pane**

For example the most basic for File Commanders is jumping from Pane to Pane.
Like jumping from left pane to right pane.

Can we have something like:

**Shift + Tab

To jump from pane to pane?**

Can jump to next pane if more than 2 panes.
This is a must for most File Commanders.

**_______________________________________________________**

Other shortcuts can be:
jump to sections, run commands, etc etc.

A list of current shortcuts in settings (or a help file) would be good too.
I know CTRL(+Shift) + Tab or CTRL + 1 (2,3,4,..) goes through tabs in a pane. But could not find shortcut for jumping from left pane to right pane. I searched in software and online.

_A shortcut section with a list (later with cuztomization) would be great in settings or a help section anyway._

Thanks again for this great software.

**If there is a shortcut for jumping from left pane to right pane, please tell me.**

**Comment by tablacus** [comment]
**1) ShortCuts Section in Settings**

Basically use an add-on "key".
https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/configuration/customize-keyboard.txt

**2) Shortcut to Jump from Pane to Pane**

Install an add-on "Switch to next pane".
![image](https://user-images.githubusercontent.com/5156977/42135661-d4bb758c-7d88-11e8-904a-b1300ab08b49.png)

Add keyboard settings.

1. Open an  add-on "Key".
2. Set "Key" to "Shift+Tab"
3. Choose "Type" to "Add-ons"
4. Click on "Browse..." and select "Switch to next pane".
5. Click on "Add" and "Ok".
![image](https://user-images.githubusercontent.com/5156977/42135701-aa05efe2-7d89-11e8-9769-ee3608f372b3.png)

Best regards,

**Comment by washere** [comment]
Thank you my friend. I will do these when I get back home tonight and close the issue.

Your work is great and you are such a gentleman and a sensei.

**Comment by washere** [comment]
Thanks my friend. Works well. I have to press TAB again to go to file list.

Thanks very much. :)

**Comment by tablacus** [comment]
My pleasure,
