### ISSUE TITLE
Addon 'Open instead' does too much

### ISSUE THREAD

**Issue by LightTempler** [tablacus/TablacusExplorer#15]
With option 'Take over the Explorer View' the addon 'Open instead' catches all Explorer Windows and takes them to a Tablacus Explorer tab. That 's a great feature!

Sometimes you want to have an "original" Explorer window. You can select this in context menu of tabs with 'Open in Explorer'. But this Window gets immediatly catched by addon, too :-)

Is it possible to prevent this?

Thx and regards
LiTe

**Comment by herohuyongtao** [comment]
The problem still exists in **Tablacus Explorer 17.4.24 Gaku**. Please have a check.

**Comment by tablacus** [comment]
There is no problem here.
Are you using an add-on "Shell execute hook"?

https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt

Thank you,

**Comment by herohuyongtao** [comment]
@tablacus Yes, I'm using the add-on `Shell execute hook`, and the TE version info is `TE64 17.4.24 Win 10.0.14393 WS 100 IE 11 en_us`. The problem will happen whenever I want to `Open in Explorer` in TE. Thanks.

**Comment by tablacus** [comment]
Unfortunately, It's in the specifications.
"Shell execution hook" always catches Explorer.
Please stop "shell execution hook".

Best regards,
