### ISSUE TITLE
Request for an Environment Variable that points to the current path of Tablacus Explorer

### ISSUE THREAD

**Issue by AmicusPlaga** [tablacus/TablacusExplorer#153]
I'm requesting an Environment Variable that points to the directory that Tablacus Explorer was started from.
For example, "%TablacusDir%\..\Test\App.exe" would launch App.exe by starting in Tablacus Explorer's starting directory, going up a folder, into the "Test" folder, and launching App.exe. This would be useful for custom file associations, I believe. %Installed% almost accomplishes this.
Here's an example of the syntax Double Commander uses:
"%COMMANDER_PATH%\..\foobar2000\foobar2000.exe"

Additionally, is it possible to use relative paths?
Thank you for your time!

**Comment by tablacus** [comment]
1. Install an add-on "X-Finder"

![image](https://user-images.githubusercontent.com/5156977/44345175-86b41580-a4cd-11e8-8102-06b326529d19.png)

2. Use "%X-Finder%" as an Environment Variable that points to the directory that Tablacus Explorer was started from.

![image](https://user-images.githubusercontent.com/5156977/44345335-02ae5d80-a4ce-11e8-9af5-636811b9c6ad.png)

Best regards,

**Comment by AmicusPlaga** [comment]
Thanks so much! That's exactly what I needed!
