### ISSUE TITLE
Window not redrawing upon F5

### ISSUE THREAD

**Issue by chrissv** [tablacus/TablacusExplorer#154]
If I refresh the view of a folder (F5), sometimes the window is blank, and only draws in the lines when my mouse moves over it (without clicking). There is also a blank space at the top of the window. Attached is a recording of my experience. It shows up mostly when there are more items in the window and scrolling is enabled.

[Refresh.zip](https://github.com/tablacus/TablacusExplorer/files/2380875/Refresh.zip)

Time 0:00 to 0:09 - scrolling and refreshing (always refreshing with the window at the top of the list)
0:10 - scrolled down, and hit F5. The screen went blank
0:12 - moving the mouse (not clicking) and observing the lines are appearing.
Note that the top half of the screen remains blank.

I am using version 18.9.9, 64 bit.

**Comment by tablacus** [comment]
Let me know the version of Windows 10.

![image](https://user-images.githubusercontent.com/5156977/45544143-70da0c00-b851-11e8-8e3b-9a7702c69bca.png)

Windows 10 Creators Update (RS2) has such a problem.
Please update Windows 10 or install an add-on "Fix Windows 10 Creators Update (RS2) bug" if you use this version.

![image](https://user-images.githubusercontent.com/5156977/45544256-c9a9a480-b851-11e8-8477-b299b89dbed7.png)

Best regards,

**Comment by chrissv** [comment]
Here is what I have.

![tab](https://user-images.githubusercontent.com/3324281/45556593-a1965300-b809-11e8-991a-6e4c9322a63f.PNG)


I installed the fix you recommended and it resolved the problem. Thanks!!

**Comment by tablacus** [comment]
My pleasure,
