### ISSUE TITLE
clipfolder: different display name

### ISSUE THREAD

**Issue by chrissv** [tablacus/TablacusExplorer#155]
I like the functionality of clip folder, but there is something which would make it even better.

Is it possible to display a different string in the folder window, which is different from the actual target directory name?

For example, if I have a directory: C:\test123, in the *.cfu file I would like to refer to that directory, but the display in the folder window would say "test directory for project 123".
When you double-click on that name "test directory for project 123", it takes you to C:\test123

It is sort of like a shortcut with a different name, but is implemented in clip folder entirely.

**Comment by chrissv** [comment]
Just an additional comment - I would be fine if this could only be done by editing the *.cfu file with an editor

**Comment by tablacus** [comment]
I will try to do future examination on that.

Thank you,

**Comment by tablacus** [comment]
How about an add-on "Virtual name"?

![image](https://user-images.githubusercontent.com/5156977/46292398-cf321900-c5cb-11e8-8802-a72b1719c943.png)

Thank you,

**Comment by chrissv** [comment]
Yes! Virtual name satisfies my requirement. Thank you for the suggestion.
