### ISSUE TITLE
Question: How to change the icon of a special folder?

### ISSUE THREAD

**Issue by AmicusPlaga** [tablacus/TablacusExplorer#156]
Hello! I understand how to change the icon of file types (*.jpg), but is there a way to change the icon of folders like "Documents", "Desktop", "Recycle Bin", or "This Computer"? Additionally, can icons in the address bar and toolbar be changed? Thank you for your time and work!

**Comment by tablacus** [comment]
I've adjusted an add-on "Path icon changer 1.04".
Please try to install it.

![image](https://user-images.githubusercontent.com/5156977/45689670-8a4fc080-bb8f-11e8-9cab-ff2417455fd7.png)

Best regards,

**Comment by AmicusPlaga** [comment]
Almost perfect! Can I change the icons in the file tree?


![tetest](https://user-images.githubusercontent.com/42520062/45700459-74a3b200-bb21-11e8-87e6-edab04f2b037.png)


Thank you so much for your time!

**Comment by tablacus** [comment]
I've adjusted an add-on "Path icon changer 1.05".
Please try to update this.

P.S.
I recommend that you update Tablacus Explorer 18.9.20 manually.
https://github.com/tablacus/TablacusExplorer/issues/146#issuecomment-423165546

Best regards,

**Comment by AmicusPlaga** [comment]
Super close! The icons lack transparency.
![tablacus2](https://user-images.githubusercontent.com/42520062/45852926-6b6c3e00-bcf7-11e8-81b3-af368e7b4207.PNG)
Thank you so much for your help so far!

**Comment by tablacus** [comment]
I've adjusted an add-on "Path icon changer 1.06".
Please try to update this.

Thank you,

**Comment by AmicusPlaga** [comment]
Perfect! It works! Thank you so much! You have the best file explorer!
