### ISSUE TITLE
Tablacus and config panel

### ISSUE THREAD

**Issue by janbatist** [tablacus/TablacusExplorer#157]
I'm using Tablacus as my default explorer, and I think  (not 100 % sure, since it's been quite a while) at the time I've used the Shell execute hook plugin to do so.

When I'm opening the config panel, it opens in Windows Explorer (which is fine, I don't care) but then, I can't access some menus. Indeed, trying to open the Mouse dialog, or the Date and Time one, fails; it brings the focus on Tablacus but nothing else happens...

Some infos:
Tablacus Explorer 18.9.9 Gaku (64bit)
C:\Program Files (x86)\Tablacus\TE64.exe
C:\Users\<me>\AppData\Roaming\Tablacus\Explorer\config
TE64 18.9.9 Win 6.3.9600 WS 300 IE 11 fr_fr 96 Windows Defender
mouse,key,addressbar,treeview,mainmenu,tabs,filterlist,tabplus,findfiles,recentlyclosedtabs,clipboardhistory,history,usercss,undoclosetab,tabposition,shellexecutehook,foldersettings,remember,searchbar,statusbar,sizestatus

Not sure what else you need to know.

Thanks!

**Comment by tablacus** [comment]
I've adjusted an add-on "Shell execute hook 1.06".
Please try to update it and re-install dll.

![image](https://user-images.githubusercontent.com/5156977/45690136-9be59800-bb90-11e8-8465-0e8a45024962.png)

Best regards,

**Comment by tablacus** [comment]
My pleasure.
