### ISSUE TITLE
Help with file association syntax

### ISSUE THREAD

**Issue by AmicusPlaga** [tablacus/TablacusExplorer#158]
I'm having trouble adding multiple file associations. I know I can do 1 per entry. Is there a way to have multiple associations in the filter list? Thanks for your time!
![te3](https://user-images.githubusercontent.com/42520062/45961681-043eda00-bfd4-11e8-85c1-3cb70fac5183.PNG)

**Comment by tablacus** [comment]
Please use semicolon as a separator.

`*.jpg;*.png`

Best regards,

**Comment by AmicusPlaga** [comment]
Thanks! You are so helpful!

**Comment by tablacus** [comment]
My pleasure,
