### ISSUE TITLE
Subdirectory for Entries in Context Menu?

### ISSUE THREAD

**Issue by AmicusPlaga** [tablacus/TablacusExplorer#159]
Thanks for helping me so much! I have one final question before I completely switch to using Tablacus permanently. Is it possible to add a subdirectory in the context menu? For example, instead of 
**_Right Click->Custom Action_**
Could it be nested like this?
_**Right Click->List of Actions->Custom Action**_
A good example of this is 7zip's context menu
_**Right Click->7zip->List of 7zip Actions**_
I understand if this isn't currently possible.
Thank you for your time and dedication!

**Comment by tablacus** [comment]
**How to create Multilevel / Hierarchical menus in Tablacus Explorer.**

Enclose menus with "Menus - Open" and "Menus - Close".

Open
![image](https://user-images.githubusercontent.com/5156977/46154428-18bef300-c2b0-11e8-9543-5c3a73228b75.png)

Close
![image](https://user-images.githubusercontent.com/5156977/46154389-ffb64200-c2af-11e8-8ad5-3d9cceb5252b.png)

Best regards,

**Comment by AmicusPlaga** [comment]
Thank you so much! You are the most active and helpful developer I've ever met. Again, thank you!
