### ISSUE TITLE
How Can I Change Icons Using Environment Variables for Current User folders?

### ISSUE THREAD

**Issue by AmicusPlaga** [tablacus/TablacusExplorer#162]
Hi again! Using the PathIconChanger addon, I can successfully change nearly every icon using simple Display Names, like "Desktop" or "Documents". However, these Display Names don't work on the icons under the user directory. Because of changing usernames and workstations, I'd like a universal way to change the icons for these user folders without using a path containing the profile name. Sorry if this is confusing. Maybe this will help:

**BAD  _"C:\Users\Amicus\Desktop\"_**
**GOOD  _"C:\Users\%Username%\Desktop\"_**
or
**GOOD  _"%UserProfile%\Desktop\"_**

Additionally, circled in blue in the picture, a very small amount of the icon underneath is showing. Somehow, in" pathicon/script.js",  I think the line 
_**image.DrawEx(nmcd.hdc, rc.Left - cx - 4 * screen.logicalYDPI / 96, rc.Top + (rc.Bottom - rc.Top - image.GetHeight()) / 2, 0, 0, GetSysColor(COLOR_WINDOW), CLR_NONE, ILD_NORMAL);**_
Has something to do with the problem, as changing the _**cx - 4**_ to _**cx - 3**_ seemed to fix it. Maybe an error? My desktop resolution is 1366x768 currently.

![te4](https://user-images.githubusercontent.com/42520062/46996532-0a176f00-d0eb-11e8-8d73-cad08deed067.PNG)

Thank you so much for your time.

**Comment by tablacus** [comment]
Thank you for your tips!
I've adjusted an add-on "Path icon changer".

Best regards,

**Comment by AmicusPlaga** [comment]
Cool, that fixed the icon overlay issue! Thanks! Any idea on how to accomplish what I asked above?

**Comment by tablacus** [comment]
Tablacus Explorer 18.10.17 (https://tablacus.netlify.com/dl/te181017.zip)

![image](https://user-images.githubusercontent.com/5156977/47089915-bf1d6900-d25c-11e8-8740-7b64f79a19b8.png)

Click "Portable"

![image](https://user-images.githubusercontent.com/5156977/47090015-f7bd4280-d25c-11e8-89af-e60edfa5bc06.png)

How about this?

Best regards,

**Comment by AmicusPlaga** [comment]
Almost perfect! It works on every folder except the UserProfile folder itself. Thank you for your continued support!
![capture](https://user-images.githubusercontent.com/42520062/47130228-a1550180-d266-11e8-9428-f55b577fe195.PNG)

**Comment by tablacus** [comment]
Tablacus Explorer 18.10.17 has been released.
Please try the "Portable" button.

Best regards,

**Comment by AmicusPlaga** [comment]
Not sure why,but it's still not working on the icon circled in red. I have downloaded the latest version as well. It's the little "person" icon that will not change. Thanks again!

**Comment by tablacus** [comment]
Probably try using "AetherealFox" instead of "%UserProfile%".

Best regards,

**Comment by tablacus** [comment]
You can use "::{59031A47-3F72-44A7-89C5-5595FE6B30EE}" instead of "shell:UsersFilesFolder".

![image](https://user-images.githubusercontent.com/5156977/47162322-abdace00-d32e-11e8-9533-38b870504955.png)

Best regards,

**Comment by AmicusPlaga** [comment]
It works perfectly! Thank you so much! You are the best!
