### ISSUE TITLE
How to Change the Default Tab Color

### ISSUE THREAD

**Issue by CollinChaffin** [tablacus/TablacusExplorer#163]
After literally an hour of being bounced between the wiki, the actual addon source code for tab plus, tab color, and tab color plus, and the couple old Github issues here that seem to be nothing more than dumping ground for unsorted addon screenshots.....I have to open this issue because I see no other way to simply determine (as much as I love this app) how to simply change the default tab color from grey to something else - that 's all.

Also, I already know how to use "tab color plus" addon to key off of a specific location but that is not what I want.  I just want the base default color changed not based on any filters.

I also already have used the CSS code to change the shape in tab designer, but it doesn't seem like that is the easiest/simplest way to change default tab colors especially since tab design addon may not always be loaded.  Based on the short description, "tab color" addon I am guessing is what I want but for the life of me I cannot figure out how to use that addon options and there seems to be zero documentation for it.

Any help is greatly appreciated and perhaps in answering this issue here you can then just past that info into the wiki where it is currently missing.  TIA!

**Comment by tablacus** [comment]
There are ways to use the above methods, add-on "User style sheet" or "Tab design".

Best regards,

**Comment by CollinChaffin** [comment]
@tablacus  Gaku LOL can you at least give me a hint of some code/example?  Those 2 things you mention don't tell me at all and all I want to do is something so simple that's the only thing holding back this explorer replacement when I talk to folks that are much less technical than me because of things like this.  I've been a DEV 30 yrs and I fully understand CSS and addons etc. and even I can't figure it out which is why I opened the issue. :)

I just need to know first of all WHICH add-on is best to change the base color of ALL tabs, and then just a single example changing to any other color and I can go from there.  Thanks!

**Comment by tablacus** [comment]
When using "User style sheet".

```
.tab, .tab2, .tab3 {
	color: white;
	background: black;
	box-shadow: none;
}
```
![image](https://user-images.githubusercontent.com/5156977/47604417-9bb0a600-da34-11e8-99bf-fb6eaf146ebe.png)

Regards,

**Comment by CollinChaffin** [comment]
Gaku,

Thank you so much for responding so quickly and for continuing to create and add to what I can confirm in my over 30yrs in this industry is by far the most feature-rich, customize-able Windows file manager/explorer replacement.

Your answer above was spot-on and I will eventually be opening a different issue/post to go quite a bit further and hopefully help collect more info for the Wiki!  Thanks!

-C
