### ISSUE TITLE
Cannot Change Folder Icons Above Medium Size

### ISSUE THREAD

**Issue by AmicusPlaga** [tablacus/TablacusExplorer#164]
Hey there! Sorry to bother you so soon, but I need some help, if you can. I am not able to use the Icon Changer plugin to change folder icons if I display them above medium size. Not sure what to do, I've tried clearing Windows Icon Cache and disabling thumbnails, but I still cannot change the icons. It may have something to do with how windows handles folder thumbnails, or perhaps it's because the Icons in windows 7 and up are 256px. Not sure what to do. Here is an example:
![tef](https://user-images.githubusercontent.com/42520062/47265778-f6a94100-d4fa-11e8-902b-3ce361290df7.PNG)
The icons on the left are displayed at medium size, while the right are displayed at large size.
Thanks for your help and dedication! Take your time with this, I am patient.

**Comment by tablacus** [comment]
Perhaps I think that thumbnails of folders are displayed instead of icons.
I've made an add-on "Folder large icon changer".
Give it a try!

Regards,

**Comment by AmicusPlaga** [comment]
It almost works! From what I can tell, sometimes I can see the custom folder icon, but it is quickly replaced by the thumbnail image. Not sure what is wrong. Thanks for your continued effort!

**Comment by tablacus** [comment]
I haven't encountered it yet.
Let me know more information.

[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

Regards,

**Comment by AmicusPlaga** [comment]
I did some testing and set up a new installation of both windows and Tablacus, and the problem is gone! Thank you! You are the best!

**Comment by tablacus** [comment]
You’re welcome.
