### ISSUE TITLE
Unnecessary security alert at drag-and-drop

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#169]
Please fix this problem. Windows unnecessarily shows a security alert when an item is dragged and dropped from a result list (such as History, Flat, Find Files, Clip Folder, etc.) to:
1. a file folder in another tab (file copy/move)
2. a desktop icon (to open the item with an application)

Example:
Drag a text file from a Flat list:
![image](https://user-images.githubusercontent.com/34089121/49696257-878ac780-fbe2-11e8-8b10-ce8ef3005863.png)
Case 1 - Drop it to another tab (file copy)
![image](https://user-images.githubusercontent.com/34089121/49696271-d173ad80-fbe2-11e8-9790-1a39fbce26f6.png)
Case 2 - Drop it to a desktop icon (open the file with Notepad)
![image](https://user-images.githubusercontent.com/34089121/49696278-f536f380-fbe2-11e8-818d-2c4dab6fce34.png)
Then Windows shows:
![image](https://user-images.githubusercontent.com/34089121/49696285-05e76980-fbe3-11e8-966c-5389e8e5d2cb.png)
This alert is unnecessary.

**Comment by tablacus** [comment]
I have adjusted it onTablacus Explorer 18.12.11.
Please try to install it.

Regards,

**Comment by ccfs** [comment]
Tested OK. Thanks.
