### ISSUE TITLE
What is this 'Portable' button good for?

### ISSUE THREAD

**Issue by LightTempler** [tablacus/TablacusExplorer#17]
Plz tell me: What is this 'Portable' button in Option dialogs good for?
It asks 'Are you sure?' and always I'm not ;-)

Thx&regards
LiTe

**Comment by duarteframos** [comment]
Are there any other variables like this? Is it possible to get a variable that is the current Tablacus install folder (where `TE64.exe` resides) instead of the drive?

Relative paths like `..\..` unfortunately don't seem to work, if I am not mistaken

**Comment by tablacus** [comment]
Please try to install an add-on "X-Finder" and use %X-Finder%

https://github.com/tablacus/TablacusExplorer/issues/153#issuecomment-414329384

Regrads,
