### ISSUE TITLE
Name column disappears after a USB drive is formatted

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#170]
Please help to fix this problem.
After a USB drive is formatted, TE cannot show a name column in any tab during navigation. This happens when:
1. user interface language is ZH (Traditional Chinese), and
2. "Folder settings", "Remember folder view settings" or "Take over folder view settings" add-on is enabled

_Example_
Language is zh
![image](https://user-images.githubusercontent.com/34089121/49726082-23323b80-fca8-11e8-9f2d-b45c92568357.png)
Folder Settings (4 columns: Name, Type, Modified Date, Size)
![image](https://user-images.githubusercontent.com/34089121/49726139-4230cd80-fca8-11e8-99b9-8c6bc903e865.png)
Drive T is a USB drive
![image](https://user-images.githubusercontent.com/34089121/49726272-88862c80-fca8-11e8-9227-4539ac5229bd.png)
Format drive T
![image](https://user-images.githubusercontent.com/34089121/49726289-9340c180-fca8-11e8-8d25-c9c07d0a8d31.png)
Completed
![image](https://user-images.githubusercontent.com/34089121/49726300-a0f64700-fca8-11e8-96bc-fc6b7e447609.png)
Click drive T in "Computer" system folder. Name and Size columns are missing.
![image](https://user-images.githubusercontent.com/34089121/49726316-ab184580-fca8-11e8-86d7-3c6efc73854b.png)

I tried "Remember folder view settings" and "Take over folder view settings" add-ons. Similar problems occurred.

I tried setting the language to ZH_CN (Simplified Chinese).
![image](https://user-images.githubusercontent.com/34089121/49726792-c59eee80-fca9-11e8-9a4b-24db77a53ca5.png)
Size column is missing.
![image](https://user-images.githubusercontent.com/34089121/49726815-d2234700-fca9-11e8-9923-ac6db7fc2a38.png)

I tried setting the language to EN (English). There is no problem. Therefore I suspect that there is something wrong in handling Chinese or Unicode characters in the three add-ons.

**Comment by tablacus** [comment]
Anyway, please try to change "Advanced" to "Path" or "Key".

![image](https://user-images.githubusercontent.com/5156977/49740493-acad3200-fcd7-11e8-948a-3c1bf633a244.png)
 Regrards,

**Comment by ccfs** [comment]
I have tried all 3 - Normal, Path and Key - the problem occurs.
Please try changing TE language to ZH at your side at testing. If you cannot reproduce the problem, the language of Windows (mine is ZH_HK while yours is JA) may also contribute to the problem.

Regards,

**Comment by tablacus** [comment]
I have adjusted it onTablacus Explorer 18.12.11.
Please try to install it.

Regards,

**Comment by ccfs** [comment]
Tested OK. Thanks.
