### ISSUE TITLE
Speed up initial grouping during folder navigation

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#172]
If any grouping is preset in a folder view, the grouping can show but after a delay of 1 second. Please try to eliminate the delay.

_Example_
Folder Settings
![image](https://user-images.githubusercontent.com/34089121/49919991-878d0f00-fee3-11e8-97c8-f073b0f95503.png)
Open a folder
![image](https://user-images.githubusercontent.com/34089121/49920001-907de080-fee3-11e8-96f6-11e97526599c.png)
Go to "C:\Windows". The folder shows, but without grouping.
![image](https://user-images.githubusercontent.com/34089121/49920014-9d023900-fee3-11e8-9869-8092272f2d43.png)
Then after 1 second the grouping shows.
![image](https://user-images.githubusercontent.com/34089121/49920054-cd49d780-fee3-11e8-863d-845e28642239.png)

----
On the other hand, this delay does NOT occur in result lists. Example:
Folder settings
![image](https://user-images.githubusercontent.com/34089121/49920225-71cc1980-fee4-11e8-8e92-7a28fc4fb65d.png)
Go to a folder
![image](https://user-images.githubusercontent.com/34089121/49920231-785a9100-fee4-11e8-990c-fdc0c0e26c3c.png)
Do a "Find Files"
![image](https://user-images.githubusercontent.com/34089121/49920247-81e3f900-fee4-11e8-93b4-1f8f29c6b0d2.png)
The result list shows with grouping WITHOUT any dalay
![image](https://user-images.githubusercontent.com/34089121/49920255-86101680-fee4-11e8-81f4-3fe615cd0557.png)

**Comment by tablacus** [comment]
Unfortunately it can not set group during sorting.
Please try to put "FV.GrpupBy" before "FV.SortColumns".

Regards,

**Comment by ccfs** [comment]
My test on the new version of "Folder settings" add-on, which includes the above amendment, is OK. Thanks.
