### ISSUE TITLE
New feature, Ctrl+D. if select a file, delete file; if not, add folder to favorite.

### ISSUE THREAD

**Issue by cvster** [tablacus/TablacusExplorer#173]
I hope that when select a file, Ctrl + D will delete file.
When not select any files, Ctrl + D will add to favorite.

Thanks.

**Comment by cvster** [comment]
I tried to config key, but it seems not work.

![image](https://user-images.githubusercontent.com/26502072/49924255-be1d5680-fef0-11e8-8814-b0e3e90ea339.png)

**Comment by tablacus** [comment]
"List" takes precedence over "All".

![image](https://user-images.githubusercontent.com/5156977/49944098-f04ca980-ff2c-11e8-85c1-a44fd8e0e0c2.png)

Regards,

**Comment by cvster** [comment]
Thank you. It works.

It's so good to talk to the developer.

**Comment by tablacus** [comment]
My pleasure,
