### ISSUE TITLE
Enhancement request: Show default icons for custom menu items

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#176]
Currently TE can show default icons for custom menu items:
- in Vertical Favorites Bar, and
- in Horizontal Favorites Bar, and
- in Link Bar

However TE cannot show any default icon:
- in a menu under Horizontal Favorites Bar
- in a menu under Link Bar
- in a menu under Tool Bar
- in main menu

![m1](https://user-images.githubusercontent.com/34089121/50397742-81354780-07ad-11e9-9768-8885fa29e020.png)
![m2](https://user-images.githubusercontent.com/34089121/50397740-809cb100-07ad-11e9-8251-7a3e595e2cca.png)
![m3](https://user-images.githubusercontent.com/34089121/50397741-809cb100-07ad-11e9-819b-f03b305e0a51.png)
![f1](https://user-images.githubusercontent.com/34089121/50397745-8b574600-07ad-11e9-9568-a4d966aa05b9.png)
![f2](https://user-images.githubusercontent.com/34089121/50397747-8b574600-07ad-11e9-9a68-b84df823f8eb.png)
![f3](https://user-images.githubusercontent.com/34089121/50397748-8befdc80-07ad-11e9-83b0-f45188db4b72.png)

Although users can specify icons with "Tools > Options", doing this one by one is very inconvenient.

My suggestion:
- TE can find out and show default icons for custom menu items, in a way similar to Vertical Favorites Bar
- (optional) Let users turn off this feature, in case of any performance or preference issue

Regards,

**Comment by tablacus** [comment]
I have adjusted it on Tablacus Explorer 18.12.25.
Please try to update this and open the option to check General -> Menus -> Icon.

![image](https://user-images.githubusercontent.com/5156977/50423893-106e5800-089f-11e9-87c6-7d89cc9b2c63.png)

Regards,

**Comment by ccfs** [comment]
I have tested it. It is generally OK, but I find 3 problems:

Problem 1: Group item is incorrectly shown as non-existent
![group2](https://user-images.githubusercontent.com/34089121/50475354-665a1180-09ff-11e9-8ded-faa8184ab887.png)
![group3](https://user-images.githubusercontent.com/34089121/50475355-678b3e80-09ff-11e9-829f-517f3a1fb3db.png)
It seems that both Horizontal Favorites Bar and Vertical Favorites Bar use the first item of the group for  the default icon. I suggest to handle a group item in a similar way.


Problem 2: The icon of Label query is missing
![q2](https://user-images.githubusercontent.com/34089121/50475722-9e158900-0a00-11e9-84ba-a9f430416300.png)
Both Horizontal Favorites Bar and Vertical Favorites Bar can show the icon correctly, but Favorites menu cannot.


Problem 3: The icons of queries change to something else after TE restarts
Just after the queries are added to Favorites:
![r1](https://user-images.githubusercontent.com/34089121/50475856-f9e01200-0a00-11e9-9bd1-77fa31b11a6b.png)
After TE restarts:
![r2](https://user-images.githubusercontent.com/34089121/50475869-02d0e380-0a01-11e9-9fff-9e019e8ebd0a.png)

Regards,

**Comment by ccfs** [comment]
Tested TE 18.12.29 with latest versions of the add-ons. Problem 1 and 3 are solved. Thanks.

**Comment by tablacus** [comment]
Thanks for your report.
Please try to update Tablacus Explorer 18.12.30.

Regards,

**Comment by ccfs** [comment]
Latest version tested OK. Problem 2 is also solved. Thanks.

**Comment by ccfs** [comment]
I re-open this issue because Problem 1 is found not completely solved.

**Problem A**

A group item is incorrectly indicated as non-existent if:
- the folder paths contain space, or
- the folder paths are in quotes

Example:
![2019-01-02_182539](https://user-images.githubusercontent.com/34089121/50589467-b1719a00-0ec1-11e9-801a-1471c2fe2095.png)
![2019-01-02_182646](https://user-images.githubusercontent.com/34089121/50589471-b33b5d80-0ec1-11e9-8e71-4da80cfd81b5.png)
![2019-01-02_182654](https://user-images.githubusercontent.com/34089121/50589477-ba626b80-0ec1-11e9-865e-f68a17359df6.png)
![2019-01-02_182704](https://user-images.githubusercontent.com/34089121/50589479-bd5d5c00-0ec1-11e9-9467-eac7771ad726.png)

**Problem B**

An incorrect icon is shown for an EXEC item that runs an application with a file, while the file path contains space. This problem occurs in:

- Favorites menu
- Horizontal favorites bar
- Vertical favorites bar
- Link bar

Example:
![menu](https://user-images.githubusercontent.com/34089121/50589791-fe09a500-0ec2-11e9-8cec-f9b4df2e34e6.png)
![vbar3](https://user-images.githubusercontent.com/34089121/50589798-02ce5900-0ec3-11e9-84b8-6a5bc0ddf2c7.png)
![1](https://user-images.githubusercontent.com/34089121/50589810-0e218480-0ec3-11e9-94b7-c00bac0aeb5c.png)
![2](https://user-images.githubusercontent.com/34089121/50589813-111c7500-0ec3-11e9-8c82-1df7d3e55800.png)
![4](https://user-images.githubusercontent.com/34089121/50589815-14176580-0ec3-11e9-92e9-44495f132c14.png)

Regards,

**Comment by ccfs** [comment]
TE 19.1.5 is tested OK. Problem A and B are solved. Thanks.
