### ISSUE TITLE
Pass selected files as parameter to portable application

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#180]
Hello, I've just discovered Tablacus and have been fascinated with my short time with it. Thanks for this great application.

I 'm currently trying to build a portable environment where all files are opened from portable apps.
How can I pass all currently selected items to an external application if the application requires specific syntax? Is this possible to specify custom parameters?

I'd like to add multiple items to an external file renamer, according to documentation of [KuknetRenamer](https://www.kuknet.de/en/filerenamer) the following launch arguments should be used
`%Installed%:\Path\To\Applications\FileRenamer.exe /rule:"BBB.xml" /f:"AAAAAA"`
where `AAAAAA` is the list of files and `BBB.xml` is a preset file.

![tablacus](https://user-images.githubusercontent.com/8735426/50674719-ab260f80-0fe0-11e9-8fa8-185581ed94b5.jpg)

Ideally I'd be able to do something like
`%Installed%:\Path\To\Applications\FileRenamer.exe /rule:"BBB.xml" /f:"{Selected.Items}"`
where `{Selected.Items}` would pass the files currently selected in the Tablacus.

I can't even seem to get the `/rule:"BBB.xml"` to work correctly from within Tablacus, even though it works well from an external batch file.

Also are there variables other than %Installed% for portable paths? How are relative paths resolved by Tablacus, is it relative to currently open folder? Using relative paths like `..\..\Foo.exe`  to launch external applications doesn't seem to work reliably.

**Comment by tablacus** [comment]
1. Please change type to "Exec".
2. Use %Selected% at {Selected.Items}

![image](https://user-images.githubusercontent.com/5156977/50691650-b9257000-1074-11e9-9c78-972511645bf5.png)

https://github.com/tablacus/TablacusExplorer/issues/153#issuecomment-414329384

Regards,,

**Comment by duarteframos** [comment]
This seems to be working well for other applications, but for KukNet Renamer specifically it throws an error about incomplete or duplicate parameters.

It appears to fail whenever I use a parameter that requires a either a colon `:` like or quotation mark `"` like `/rule:"AAA"` or ` /f:"AAA"`, other parameters work well.
Somewhere in the process some parameters are probably getting corrupted, maybe. Not sure if it is a bug, or how to diagnose it.

Anyway, thanks for the help.

**Comment by duarteframos** [comment]
Are there any other variables, like for the current folder? Something like say `%CurrentDir%`

Is there any place where I can find documentation about Tablacus in general? Maybe a wiki, an official help or tips? It feels awfully inefficient to be opening issues for requests or asking questions, and I feel like I'm bothering you with all these inquiries.

I see there is an attempt to start a [Wiki](https://github.com/tablacus/TablacusExplorerAddons/wiki) but it is mostly empty or missing basic info.
I'd like to help with this, would I be able to contribute with documentation?

I'm not a coder but if I could find info somewhere about how things work, maybe I could help write some helpful guides and complete those pages. I see some scattered info here in issue tickets, maybe this could be complied and incorporated into the wiki.

Let me know if I can help.

**Comment by duarteframos** [comment]
That is perfect, really useful. many thanks.

Took the liberty to suggest a few improvements, hope that you don't mind.
If you dislike them feel free to roll them back, no hard feelings,

**Comment by duarteframos** [comment]
Any reason why launching [KuKNet Renamer](https://www.kuknet.de/en/filerenamer) `%X-Finder%\Utilities\FileRenamer.exe /nosplash /rule:"EML.xml""` would fail from Tablacus, while launching from a .bat file works.

The program always launches but the parameters are not correctly passed. The problem seems to be specifically at the `/rule:"EML.xml"` part, `/nosplash` alone passes the parameter correctly, but `/rule:"EML.xml" makes i fail and the renamer complains that parameters are incorrect or incomplete.

I suspect some bug in Tablacus is eating part of the parameters because of the colon `:` or quotation mark `"`

**Comment by tablacus** [comment]
Thank you fpr your report.
I have adjusted it on Tablacus Explorer 19.1.5.
Please try to install it.

Best regards,

**Comment by tablacus** [comment]
Thank you for editing wiki.
That would be great.

Thank you,

**Comment by duarteframos** [comment]
@tablacus Nice improvements on the variables page, I've been wondering if those existed at all.

Thanks for updating the documentation, appreciate it!
