### ISSUE TITLE
Version 19.1.16 is obviously much slower than 18.10.20 when open folders

### ISSUE THREAD

**Issue by cvster** [tablacus/TablacusExplorer#185]
When open a folder, 19.1.16 has a pause about 0.3-1 seconds, which is very slow. And version 18.10.20 is  much faster.  I would like to say that 18.10.20 is even faster than windows explorer, which is great!

19.1.16:
TE64 19.1.16 Win 10.0.15063 WS 100 IE 11 en_us 120 Windows Defender Trend Micro OfficeScan Antivirus
mouse,key,addressbar,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,multithread,remember,undoclosetab

18.10.20:
TE64 18.10.20 Win 10.0.15063 WS 100 IE 11 en_us 120 Windows Defender Trend Micro OfficeScan Antivirus
mouse,key,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,remember,undoclosetab,innerbreadcrumbsaddressbar,takeoverfoldersettings,innerrefresh,clipfolder,statusbar,favbar,samelockedtab

**Comment by tablacus** [comment]
Let me know more information.
1. What kind of view mode do you use?
2. What kind of sorting do you use?
3. Do you use grouping by?
4. Do you use Explorer browser?
![image](https://user-images.githubusercontent.com/5156977/51323715-42449a00-1aac-11e9-9cc0-bb85abaec58e.png)

**Release version 19.1.17**
https://github.com/tablacus/TablacusExplorer/releases/download/19.1.17/te190117.zip

**Test version 19.1.17**
https://tablacus.github.io/dl/te190117a.zip

Are there any differences between the two above?

Best regards,

**Comment by cvster** [comment]
Hi Gaku,

The problem disappered today, for version 190116, 190117 and 190117a they are all fast. Windows Explorer is faster too. Maybe it's because I have a reboot and everything goes well.

Besides, I use List view, sorting by name.
TE is quite a great explorer tool.

Thank you.
Best.
