### ISSUE TITLE
Feature - Open new tab in right-most side

### ISSUE THREAD

**Issue by cvster** [tablacus/TablacusExplorer#187]
Hi,

I hope to open new tabs in the right most side. 

For fixed tabs, when open a folder it will create a new tab near by right side. Is it possible to open the new tab in the most right side?  So that all the fixed tabs will stay in right and its position won't move.

Thanks.
Best.

**Comment by ccfs** [comment]
Try "Tab position" add-on. Set "New tab" to "Last".

**Comment by cvster** [comment]
> Try "Tab position" add-on. Set "New tab" to "Last".

Great! 
It works well.

Thank you.
