### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by Gpinchon** [tablacus/TablacusExplorer#189]
I can't change the language from the default french to english. My whole system is in english but I am using french input method.
Every times I change the language to english and close the settings, Tablacus reverts its language to french.
Tablacus installed via Chocolatey.

**Comment by tablacus** [comment]
When installing with Chocolatey, it seems that setting folder can not be created well.
I will try to adjust it.

Thank you,

**Comment by Gpinchon** [comment]
Fixed in new release :+1:
