### ISSUE TITLE
Hidden files/folders not displayed

### ISSUE THREAD

**Issue by Gpinchon** [tablacus/TablacusExplorer#191]
The hidden files and folders are not displayed anymore since update 19.2.10.
Tablacus installed via Chocolatey.
Process to reproduce bug :
- Load layout (tree_1tab.xml)
- Go to Tools->Options
- Tick "Include hidden items", then "OK"
- Create an hidden file or folder
- Watch it disappear

**Comment by tablacus** [comment]
It is only affected in the tree view.
Anyway, please try to check Options -> List -> General -> Show all files.
![image](https://user-images.githubusercontent.com/5156977/52786270-cf741200-309d-11e9-9e2a-2f1967520f04.png)

Regards,

**Comment by Gpinchon** [comment]
Not a bug
