### ISSUE TITLE
请问如何修改布局，让所有窗口共用一个树状结构？

### ISSUE THREAD

**Issue by 1983shake** [tablacus/TablacusExplorer#192]
请问如何修改布局，让所有窗口共用一个树状结构？
现在每个窗口都有树状结构，若共用一个，那么将会有更多的空间提供给每个窗口。

**Comment by 1983shake** [comment]
总算找到了一个附加组件：Side tree view。

**Comment by tablacus** [comment]
I can't read Chinese.
Would you write in English next time?

Regards,

**Comment by 1983shake** [comment]
It doesn't matter. I found an add-on to implement this function.Side tree view.
