### ISSUE TITLE
Problems when switching tab groups with panes and filters

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#200]
No problem after loading layout file 
[2groups-2panes-filter.zip](https://github.com/tablacus/TablacusExplorer/files/2897644/2groups-2panes-filter.zip)
![1](https://user-images.githubusercontent.com/34089121/53295868-a42cb800-383f-11e9-9b0e-5c3667cfc545.png)

But the pane states and filters are incorrect when I switch groups:
![2](https://user-images.githubusercontent.com/34089121/53295869-a4c54e80-383f-11e9-85b3-c9de04d2efe9.png)

![3](https://user-images.githubusercontent.com/34089121/53295870-a4c54e80-383f-11e9-8457-1bc26a52bc67.png)

Please help to solve the problem. 

Regards,

**Comment by ccfs** [comment]
The incorrect filter problem has disappeared in recent versions of TE.
However when I switch group and back, TE still cannot remember the previous pane status.

Example:

After loading the layout file
![20200825_171758](https://user-images.githubusercontent.com/34089121/91156736-11503080-e6f7-11ea-85a1-6710b0a46772.png)
Activate the right pane
![20200825_171816](https://user-images.githubusercontent.com/34089121/91156744-1319f400-e6f7-11ea-9423-3de51c1d3c1f.png)
Switch to Group2
![20200825_171824](https://user-images.githubusercontent.com/34089121/91156746-1319f400-e6f7-11ea-8a06-149dd0a18d07.png)
Switch back to Group1. The active pane unexpectedly becomes the left pane.
![20200825_171830](https://user-images.githubusercontent.com/34089121/91156748-13b28a80-e6f7-11ea-892c-ecad97cd6cae.png)

Regards,

**Comment by tablacus** [comment]
I have adjusted this issue with Tab groups 1.31.
Please try to install it.

Regards,

**Comment by ccfs** [comment]
The incorrect pane state and filter problem re-appears in Tab groups 1.31.
In addition, if the active group is closed, TE malfunctions.

Example:

After loading the layout file
![20200826_163900](https://user-images.githubusercontent.com/34089121/91285710-25ac3000-e7c0-11ea-8ba3-e7d320ae8124.png)
Switch to Group2. The left pane should be active but actually not.
![20200826_163932](https://user-images.githubusercontent.com/34089121/91285716-26dd5d00-e7c0-11ea-8270-05cbb3126769.png)
Switch to Group1
![20200826_164101](https://user-images.githubusercontent.com/34089121/91285718-2775f380-e7c0-11ea-8446-adda9cc9112d.png)
Switch to right pane
![20200826_164109](https://user-images.githubusercontent.com/34089121/91285720-2775f380-e7c0-11ea-8c81-bf22afbcdba3.png)
Switch to Group2 and back to Group1. The active filter should be f12.
![20200826_164131](https://user-images.githubusercontent.com/34089121/91285721-280e8a00-e7c0-11ea-8381-8ad9d8205646.png)
Close Group1
![20200826_164516_cr](https://user-images.githubusercontent.com/34089121/91285724-28a72080-e7c0-11ea-85c0-0ddedde4b9a5.png)
Reply Yes
![20200826_164539](https://user-images.githubusercontent.com/34089121/91285726-28a72080-e7c0-11ea-83cb-9c05f2b204c7.png)
TE malfunctions
![20200826_164546](https://user-images.githubusercontent.com/34089121/91285727-293fb700-e7c0-11ea-9487-ada8a831bf18.png)

Please help to solve the problems. Thanks.

**Comment by ccfs** [comment]
The problems are solved with latest TE version 20.8.27 and add-ons. Thanks.
