### ISSUE TITLE
Feature: search tab

### ISSUE THREAD

**Issue by cvster** [tablacus/TablacusExplorer#206]
Hi, recently I;m using phpstorm and it has a very useful function: 

when double click space, it will show a window that can search file by name and quickly open the file.

![image](https://user-images.githubusercontent.com/26502072/54342882-88674580-4678-11e9-9808-41e7d5612e17.png)

And I hope to have a similar feature that I can search tab for all opened (or recently opend) tab, and quickly open the tab.
For example, if in all openedtabs there is a tab(folder) whose name is "license". I double press "space" key, a window will show. And I input "lic", the window will generate a list to choose. Then I choose one of them and press "enter" key I will active the tab.

Do you thick it's useful?

**Comment by tablacus** [comment]
His new add-on looks good.

http://revolver2011.blog96.fc2.com/blog-entry-280.html

Regards,

**Comment by cvster** [comment]
That's great.

I have installed the add-on "x-finder", but I don't know how to open it. Could you help?

Thank you!

**Comment by tablacus** [comment]
Production in progress.

**Comment by cvster** [comment]
Cool!
Thanks for providing such good software and functions.
