### ISSUE TITLE
Horizontal Favorites Bar - Loading time with Network Folders

### ISSUE THREAD

**Issue by acambule** [tablacus/TablacusExplorer#215]
In the horizontal favorites bar i have something like this:

* Folder - Folder - Hierarchy - Folder - Folder etc.

* On the Hierarchy i have SubItems like this:
  - Folder - points to local
  - Folder - points to network folder
  - Folder - points to network folder
  - Folder - point to local

When i open up a Hierarchy to access the SubItems that contain only local destinations everything is smooth.
But when the hierarchy also contains destinations to network folder, then it is extremely slow,
especially when i'm not connected to that network.

I suspect that you do some precheck but the problem is, that these folders are only available when i have a VPN to the network open. This if often not the case.

It would be nice if there would be no checks to the folder until i really click on it or something like that, to smoothen the loading time when clicking on a hierarchy.

thanks and regards
Antonio

**Comment by ccfs** [comment]
Try changing the network "timeout" setting in Tools > Options > List to 500 or less. Not sure if this helps.

**Comment by acambule** [comment]
Ok, that helps a bit. The loading time is much better, not optimal, but a lot better. Thank you.
