### ISSUE TITLE
Column auto-size issue

### ISSUE THREAD

**Issue by I-Vladimir** [tablacus/TablacusExplorer#222]
Hi there,
Think there is an issue auto-sizing columns double clicking on the right column header edge.
When set cursor at a column edge, to resize "Name" column, cursor gets changed to resize-cursor and when I double click on it another window get activated. In my case I clicked on the top locked window and the next locked activated. I.e. instead of resizing of the current window the next activated.
![2019-04-23 10_02_34-Window](https://user-images.githubusercontent.com/46606150/56587310-4d2d3000-65af-11e9-9ab4-fe29d0a1b3d0.png)

**Comment by I-Vladimir** [comment]
It might be because of UP plugin where mouse click configured as List-2U.
Parent directory gets activated.

**Comment by tablacus** [comment]
I have adjusted it on Tablacus Explorer 19.4.24.
Please try to update.

Regards,

**Comment by I-Vladimir** [comment]
Fixed. tnx.
