### ISSUE TITLE
Since 19.6.22, Missing label of column header.  And Missing background-color and drop down arrow when mouse hover over the header.

### ISSUE THREAD

**Issue by alice0775** [tablacus/TablacusExplorer#231]
TE64 19.6.22 Win 10.0.18362 WS 300 IE 11 ja_jp 96 Windows Defender
mouse,key,addressbar,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,multithread,remember,undoclosetab

This is regression since 19.6.22.  And TE only failure.
Windows Explorer shows label and hover action properly.

STR:
1. Install 19.6.22
2. run TE64.exe

Actual Results:
Screenshot: https://imgur.com/M9o8DFc
No column header label is displayed.
No background-color and dropdown arrow is displayed when mouse hover over the column header.

Expected Results:
Column header label should be displayed.
Background-color and dropdown arrow should be displayed.

**Comment by tablacus** [comment]
I have adjusted it on Tablacus Explorer 19.6.25.
Please try to update!

Regards,

**Comment by alice0775** [comment]
> 
> 
> I have adjusted it on Tablacus Explorer 19.6.25.
> Please try to update!
> 
> Regards,

I verified that the issue was fixed on version 19.6.25.

Thanks.
