### ISSUE TITLE
アドオン「重複コピー」を使用すると余分にコピーが作られる

### ISSUE THREAD

**Issue by yuru7** [tablacus/TablacusExplorer#234]
アドオン「重複コピー」を利用してファイルやフォルダを同じフォルダ内にコピーすると、余分なファイルがコピーされて残ります。

下図では、「aaa.txt」を同じフォルダへ「重複コピー」を使ってコピーし、「bbb.txt」を作っています。
その際、下図にあるエラー表示がされ、「bbb.txt」以外に「aaa - コピー.txt」も生成されてしまいます。

![image](https://user-images.githubusercontent.com/13458509/63396335-b019c100-c401-11e9-832b-a332140f65a7.png)

**Comment by tablacus** [comment]
重複コピー 1.06で調整しました。

**Comment by yuru7** [comment]
ご対応ありがとうございました。正常に動作するようになりました。
