### ISSUE TITLE
How to display the number of files in a folder? 

### ISSUE THREAD

**Issue by onmyouji** [tablacus/TablacusExplorer#242]
Hi all,

Is there any way to display the number of files in a folder? On Windows Explorer, you can view the number of files on bottom left.

![Image 001](https://user-images.githubusercontent.com/8424198/64574997-e82a7900-d39b-11e9-80a0-7b8f1a260603.png)

**Comment by tablacus** [comment]
There are several ways.

1. Use an add-on "Status bar"

![image](https://user-images.githubusercontent.com/5156977/64608838-7cc9c100-d406-11e9-9386-a22d9c10f7e1.png)

2. Use an add-on "Count bar"

![image](https://user-images.githubusercontent.com/5156977/64608870-90752780-d406-11e9-868c-d6c3f6bb5c65.png)

3. Right click on Tab -> check "Show frames"

![image](https://user-images.githubusercontent.com/5156977/64609166-40e32b80-d407-11e9-82ee-407e8e0ad42d.png)

Regards,

**Comment by onmyouji** [comment]
Thanks!
