### ISSUE TITLE
Disabled mouse gesture but it still eats it up,

### ISSUE THREAD

**Issue by imtrobin** [tablacus/TablacusExplorer#244]
Hi, I use Strokeit for mouse gesture, which is operating on all apps. I have disabled mouse gesture on TablacusExplorer, but it still eats it up so strokeit gesture does not work.

**Comment by tablacus** [comment]
Please try to select Options -> General -> Mouse -> Gestures -> None.

![image](https://user-images.githubusercontent.com/5156977/65373803-33f2f180-dcbd-11e9-96de-b1086cd9d7e3.png)

Regards,

**Comment by imtrobin** [comment]
Hi, yes I have already done that, as I said in first post, but it still eats it up.

**Comment by tablacus** [comment]
I installed StrokeIt but I have not encountered it.

**Comment by imtrobin** [comment]
Ok, so what I did was to send mouse gesture from strokeit to  TablascusExplorer, which fails

1. Setup a custom application id, I use Class and File
2. Setup a custom gesture
3. Added Hotkey Ctrl+T, to open a new tab

When I performed the gesture in Tablascus, it should fire Ctrl+T and open a new tab. But it couldn;t.

**Comment by tablacus** [comment]
I have adjusted it on Tablacus Explorer 19.9.29.
Please try to update!

Best regards,

**Comment by imtrobin** [comment]
Marvellous, working great!
