### ISSUE TITLE
Win 10 OneDrive の状態アイコンが、更新中ステータスのままになっている

### ISSUE THREAD

**Issue by yuru7** [tablacus/TablacusExplorer#246]
とても便利でいつも助かっています。バグと思しき事象を確認したため、以下にご報告します。

## ヘルプ > Tablacus Explorer について より、バージョン情報

* 情報: TE64 19.9.6 Win 10.0.18362 WS 100 IE11 ja_jp 96 Windows Defender カスペルスキー インターネット セキュリティ
* アドオン: mouse,key,treeview,importexplorer,mainmenubutton,titlebar,tabs,favoritesbar,hotkey,undoclosetab,tasktray,split,statusbar,tabplus,innerbreadcrumbsaddressbar,innerfilterbar,innerback,innerforward,innerup,tabgroups,lockedtabstop,label,labelbutton,labelgroups,multithread,replaceslowcolumns,autodisableime,tabposition,remember,duplicatecopy,usercss,clipboardimage,tooltippreview

## バグ内容

OneDrive フォルダの「状態」カラムのアイコンが、ずっと更新中を示すアイコンのままになっています。

下図キャプチャー内での上側の表示が Tablacus, 下側の表示が Explorer です。
全て同期済みのファイル・フォルダなので、全ての状態アイコンがチェックマークになることが期待する結果です。

![image](https://user-images.githubusercontent.com/13458509/65817349-edfbd780-e240-11e9-81fe-1ea4fe0c5e4c.png)

**Comment by tablacus** [comment]
残念ながら当方で調整できる範囲では無いので、そんなもんだと思って使っていただけると幸いです。
もしかしたら、エクスプローラブラウザにチェックした場合は上手く動くかもしれません。

**Comment by yuru7** [comment]
ご確認ありがとうございます。
そうでしたか、承知しました。
(残念ながらエクスプローラブラウザにチェックを入れても、解消できませんでした)
