### ISSUE TITLE
Wish to have a saving sorting order funtion like directory opus.

### ISSUE THREAD

**Issue by w422417869** [tablacus/TablacusExplorer#252]
Hi Gaku,

Thanks for the amazing work. But one feature that I really need is to remember the sorting sequence for dffierence folder.

Could you add this function to this software in the feature? Or guide me how to achieve that if it is already possible..

Since have found this feature in Tablacus, I haven't switch from directory opus to Tablacus fully,  have to use both software based on different situation.

- - - - -

Another feature request:
Prevent locked tab closed if double click, not double click to lock the tab.. 

Here is a gif picture regarding "sorting sequence" for your reference.

![save order](https://user-images.githubusercontent.com/36833177/68268399-fab9e980-0090-11ea-884a-a8b58b8f26a6.gif)

**Comment by duarteframos** [comment]
https://github.com/tablacus/TablacusExplorerAddons/wiki/foldersettings though I don't think it saves custom sort orders

**Comment by w422417869** [comment]
> https://github.com/tablacus/TablacusExplorerAddons/wiki/foldersettings though I don't think it saves custom sort orders

@duarteframos 

Thanks for this suggestion. 

I tried this addons before, but when I activate the addons and tried to adjust the folder sequence by draging, that folder afterwards does not stay in the same folder, it is moved to another folder at the same directory. 

So there is no way for me to proceed further with this addons.

**Comment by duarteframos** [comment]
I think there is a bug with drag &drop reordering when dropping in between folders.
Dropping between two files is fine, and so is dragging between a file and a folder, but if one drops something between two folders it is moved into the folder instead, which is undesirable..

![Tablacus_Order](https://user-images.githubusercontent.com/8735426/68378989-f4854500-0144-11ea-9087-ab534a5f7570.gif)

Maybe @tablacus can say if it is a bug

**Comment by tablacus** [comment]
It is difficult for Tablacus Explorer to implement its own sorting because of the relationships that drive the Explorer controls internally.
Just in case, Mixed sort and Total file size sort add-ons do.

### Trick: Use add-ons "Clip folder" and "Reset sort column"

For a clip folder, you can reset the sort so that it appears in the order you stored it.

Regards,

**Comment by w422417869** [comment]
@duarteframos @tablacus Thanks for you two for the help.
