### ISSUE TITLE
[Requests] Customize right-click drag menu

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#253]
I don't think this is currently possible, so it is more of like a feature request than a question.
Is it possible to customize the rightclick-drag menu?

You can currently customize right click menus for tablacus which is great to integrate portable archiving tools like 7zip without installing to system, but it is not possible to do so for right-click drag actions.

Is there a way to add custom entries to the menu that pops up after you begin a drag action with right-click mouse button?

![Rightclickdrag](https://user-images.githubusercontent.com/8735426/68293869-c0e3e580-0086-11ea-907e-62fe2a168a4e.png)

**Comment by duarteframos** [comment]
Off topic I have recently made a series of pull requests regarding improving several of existing addon descriptions

**Comment by tablacus** [comment]
I think it is possible, but it is complicated and difficult.
Anyway, there are two problems.

1. I don't know how to replace part of the right drag menu.
So, it is possible if it replace everything.
Copy here, move here,Shell extensions such as 7-Zip and FastCopy etc.

2. There is a character limit on the command line.
If many items are selected, they cannot be passed on the command line alone.

Regards,

**Comment by duarteframos** [comment]
Ah I see, that's a shame, it would have been useful.
Anyway, thanks for the explanation though

**Comment by duarteframos** [comment]
If this can't really be implemented easily I suppose the task can be closed.
Thanks nayway
