### ISSUE TITLE
[Request] Drag and drop into breadcrumb and tab

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#255]
Is it possible to support dropping dragged items into the breacrumb bar or tab headers?
XYPlorer allows moving/copying items to the relevant directory by dropping directly over the tab header (without explicitly switching or activating the tab) or one of the parent folders listed in the breadcrumb bar.

![Tab_Drag](https://user-images.githubusercontent.com/8735426/69960341-23eb5f80-1501-11ea-8e20-7004e90a5b34.gif)

**Comment by tablacus** [comment]
I will try to consider it
Which are you using an add-on "Inner breadcrumbs address bar" or an add-on "Address bar"?

Regards,

**Comment by duarteframos** [comment]
Thanks for considering it.
I mostly use inner breadcrumb so I can have one dress bar per pane.

**Comment by tablacus** [comment]
I have adjusted two add-ons.
Please try to update it.

Regards,

**Comment by duarteframos** [comment]
Hell yeah, it works!!!
![Tablacus_MoveCopy](https://user-images.githubusercontent.com/8735426/70337418-f1b06980-1842-11ea-875b-ecdbe43d12df.gif)

This deserves official documentation, will try to update soon.
Which addons specifically provide this functionality? I assume Address Bar and Inner Breadcrumb, but also Tab Plus, am I right?
