### ISSUE TITLE
Software closed unexpectedly and the "Group" information is lost

### ISSUE THREAD

**Issue by w422417869** [tablacus/TablacusExplorer#256]
Hi,

There were several times that this software was closed, when I re open the software.. The group information is gone.. seems like the configuration file is RESET to oringinal.

I tried to use some configuration files which are located at the software directory to restore group layout, but it did not work.

Do anyone who knows how to restore it?

Please check attached picture.
Regards,
Charlie

![截图_20191208125011](https://user-images.githubusercontent.com/36833177/70384464-cdc36400-19b9-11ea-920b-af918dd95fde.png)

**Comment by ccfs** [comment]
Which add-ons have you enabled?
Can you recall what were you doing with TE when it closed unexpectedly?

**Comment by w422417869** [comment]
@ccfs 

Hi, ccfs. I enabled 40+ plugins in total.. So it is very hardly to tell which add on cause the crash..

When TE is closed unexpectly, I was doing nothing but a lot of programs were kept opened as usual.
My guess is the PC out of memory caused the crash...

But I do not know any further.. Also no error log can be found for analysis??

**Comment by ccfs** [comment]
No, I don't think that TE has any error log.
Tabs, panes and groups information of current session are saved to windows*.xml files when TE closes. So if TE crashes, the information is lost.
Alternatively, you can manually save current group layout and load it later by right-click a group tab and choose Save / Load.
![image](https://user-images.githubusercontent.com/34089121/70793616-ac59e200-1dd6-11ea-93d9-d7980792a3bc.png)

**Comment by w422417869** [comment]
@ccfs Thanks, I will manually backup that file weekly.
