### ISSUE TITLE
Long lag when opening folders with TE

### ISSUE THREAD

**Issue by alexbib** [tablacus/TablacusExplorer#257]
Both 32bit and 64bit versions are very slow on my new pc (windows 10, intel 9700, m2 ssd), taking about half a second to open a folder.

I'm using all default options, haven't touched the configuration at all. I've tried both the most recent release (190929) and a random earlier one, and they behave the same. Please let me know what I should try to fix it.

**Comment by ccfs** [comment]
Are you using "single-click" (set in Windows Control Panel > Folder Options)? If so, install and enable "Fix Single click activate" add-on. You must also opt for “Single click activate” in “Tools > Options > List > Style” in TE.

Regards,

**Comment by alexbib** [comment]
That worked, thank you very much!
