### ISSUE TITLE
Right click menu using peazip does not show all entries

### ISSUE THREAD

**Issue by imtrobin** [tablacus/TablacusExplorer#258]
Hi, I use Peazip. When I right click on the file to extract, in Tablacus, only a few commands are shown. In normal explorer, there are more commands.

**Comment by tablacus** [comment]
32-bit shell extension only works with 32-bit apps.
64-bit shell extension only works with 32-bit apps.

Regards,

**Comment by imtrobin** [comment]
Hi, I don't quite understand your reply. I'm using 64bit windows, peazip. Some entries in peazip are shown, not all, compared to explorer.

**Comment by tablacus** [comment]
I have adjusted it on Tablacus Explorer 19.12.22.
Please try to update.

Regards,

**Comment by imtrobin** [comment]
Yes, working now. Thanks!
