### ISSUE TITLE
File meta not shown

### ISSUE THREAD

**Issue by imtrobin** [tablacus/TablacusExplorer#259]
Hi, I notice that in Tile mode, the exe Details like File Version is not shown, unlike normal explorer.

**Comment by tablacus** [comment]
Please try to check Tools -> Options -> List -> Explorer browser -> Tile.
 
![image](https://user-images.githubusercontent.com/5156977/71260505-5e1c8400-237e-11ea-84d2-7dd70c08cb51.png)

Regards,

**Comment by imtrobin** [comment]
Thanks, it is working
