### ISSUE TITLE
delete permanently with shift + del

### ISSUE THREAD

**Issue by tortino** [tablacus/TablacusExplorer#261]
Hi,
sometimes I want to delete permanently some files, without using the windows trashcan.
I use shift + delete to achieve this, but under tablacus this key combination is ignored, and it is always used the trashcan. Instead in Windows Explorer it works correctly.
Please can you fix it? (it doesn't work since a few months, I recall using shift+del in tablacus in the past years and it was working fine).
Thank you.

**Comment by tablacus** [comment]
Which add-on do you use for file operations?
"Multi thread", "Multi process", etc.

Please read this and let me know your environment.
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

If you use the add-on "Multi process", there is a time lag before the process starts.
You need to hold down the SHIFT key until the process starts.

You can delegate "Delete" to the add-on "Multi thread" by doing the following:

Tools->Add-ons->Multi process->Options
![image](https://user-images.githubusercontent.com/5156977/73356108-eb87b800-42dc-11ea-9818-b80966c58f86.png)
Uncheck "Delete"

Tools->Add-ons->Multi thread->Options
![image](https://user-images.githubusercontent.com/5156977/73356160-09edb380-42dd-11ea-9315-a2d347fc376c.png)
Check only "Delete". 

Regards,

**Comment by tortino** [comment]
Hello, 
this is my configuration:
TE64 20.2.2 Win 10.0.17763 WS 100 IE11 it_it 96 Windows Defender
foldersettings,multiprocess,mouse,key,mainmenu,titlebar,tabplus,statusbar,innerback,innerforward,inneraddressbar,innerfilterbar,innersearchbar,innerup,innerrefresh,innernewfolder,gridlines,split,undoclosetab,touchex,findfiles,delete,fastlistmode,autoupdate,addonsupdater,flat,totalfilesizesort,favorites,usercss,iconoverlay,closewhendeleting,split6,switchhidden,closeduplicatetabs

I'll try your suggestion about multi process.
Thanks.

**Comment by tortino** [comment]
hello,
disabling "delete" in multiprocess is working: shift + delete works again.
but then it isn't multiprocess anymore: when deleting big directories I have to wait until finished the delete operation. this way the multiprocess addon is useless :-(

**Comment by tablacus** [comment]
Please try using "multi-thread" instead of "multi-process".

Regards,

**Comment by tortino** [comment]
Hi, I tried multi-thread but it is less useful than multiprocess addon: multithread doesn't work when I drag and drop a file or folder with right mouse button, and then select copy or move in the popup menu. in this situation tablacus is blocked.
instead it works if I right click a folder and select copy, and then I paste it into another folder.
multiprocess work even with drag and drop.

**Comment by tablacus** [comment]
So use both as in the screenshot above.
Make sure to check "Right drop" and uncheck "Delete" for multi-process
Check "Delete" for multi-thread.

Regards,

**Comment by ccfs** [comment]
@tortino,

I do not have any problem using Shift+Del to delete permanently, either with multi-process or multi-thread (with "Delete" ticked). I suggest you to check if you have accidentally made Shift+Del a hot key somewhere in TE (under Tools > Options >Menus, under "Key" add-on, and under other add-ons that have a "Key" option page).

Regards,

**Comment by tortino** [comment]
Hello, after some testing your solution is working.
Thank you.
