### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by w422417869** [tablacus/TablacusExplorer#262]
Hi Taku,

Thanks for the amazing work.

Want a feature that is when you are using the tab group feature, if  exit the program, the unpinned tabs will be closed also.

Hope you can get my meaning..

Thanks and best regards,
Charlie

**Comment by tablacus** [comment]
I don't know what you mean.
Can you explain using screenshots?

Regards,

**Comment by duarteframos** [comment]
I think he wants Tablacus to close all unpinned tab groups when closed, so that when it reopens only pinned tab groups are kept.

In other words only groups that are pinned get saved between sessions

**Comment by w422417869** [comment]
@duarteframos Thanks for explaination. I think your explaination maybe exactly what I want.

English is not my first language, so in case to avoid mistake.. Here I attached a picture and explain again..

What I want is to close the unpinned tabs (left red frame in the picture) automatic when exit the program.. The pinned tabs (right red frame) remain the same when reopen.

Since I am lazy, I do not want to close the unpinned tabs everytime, so the qty of unpinned tabs is getting more and more..

![2020-02-03_20-31-42](https://user-images.githubusercontent.com/36833177/73653718-cfad5900-46c4-11ea-9268-75fa6de2dbba.png)




When I close Tablacus, Tab groups

**Comment by ccfs** [comment]
I think that Charlie wants any unpinned tab (not group) be closed automatically when TE exits. Whether "tab group" is being used does not matter, I suggest.

**Comment by w422417869** [comment]
@ccfs Perfect explaination.. Thanks

**Comment by tablacus** [comment]
No worries!
English is not my first language too.
Screenshots help me understand about issue.
I will try to consider it

@duarteframos @ccfs Thanks for the additional explanation.

Regards,
