### ISSUE TITLE
Display flashes when dark mode addon is enabled.

### ISSUE THREAD

**Issue by yuru7** [tablacus/TablacusExplorer#264]
# バグ報告

以下の通りご報告いたします。

## 内容

ダークモードアドオンを利用していると、フォルダ遷移時に表示が点滅する

![20200206_033132](https://user-images.githubusercontent.com/13458509/73911892-7cbae800-48f6-11ea-8614-b400b6fa2bb9.gif)

## 環境

* 情報: TE64 20.2.2 Win 10.0.18363 WS 100 Dark IE11 ja_jp 96 セキュリティエージェント Windows Defender
* アドオン: mouse,key,treeview,titlebar,tabplus,multithread,undoclosetab,innerbreadcrumbsaddressbar,innerback,innerforward,innerrefresh,innerfilterbar,mainmenubutton,tabgroups,lockedtabstop,favoritesbar,tasktray,hotkey,importexplorer,split,labelbutton,label,darkmode,autodisableime,statusbar,remember,duplicatecopy,usercss,tabname,clipboardimage
* ダークモードアドオン Ver: 1.02

## 再現方法

不明 (Tablacus 起動時は発生しませんが、しばらく使っていると発生します。情報提供できず、申し訳ありません。)

**Comment by tablacus** [comment]
報告ありがとうございます。当分ダークモードオンで試してみます。
あと、ここは多くの国の方が使われているので、タイトルに英語も入れていただけると幸いです。
本文の方は日本語でOKです。

**Comment by yuru7** [comment]
@tablacus 承知しました。早速タイトルを修正しました。表現が変な場合は、修正していただければ幸いです。

ちなみにですが、表示方式をエクスプローラモードにしている際には発生しません。（エクスプローラそのままを表示しているので当たり前なのかもしれませんが…）

**Comment by tablacus** [comment]
開発環境で再現できたので、問題個所を特定できたので、Tablacus Explorer 20.2.8で対策措置を行いました。
試してみて下さい。

**Comment by yuru7** [comment]
ご対応ありがとうございます。
それでは1週間ほど様子を見てみたいと思います。

**Comment by yuru7** [comment]
1週間ほど利用して発生していないため、解消されたかと思います。  
ご対応、ありがとうございました :)
