### ISSUE TITLE
Bug after updating to 20.2.17 - every time I minimize Tablacus and try to restore it back, the window loses half its layout

### ISSUE THREAD

**Issue by onmyouji** [tablacus/TablacusExplorer#268]
TE64 20.2.17 Win 10.0.17763 WS 300 Dark IE11 en_us 120 Windows Defender

Addons:
mouse,key,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,multithread,remember,undoclosetab,split,everything,darkmode,history,addonsupdater,statusbar,innerbreadcrumbsaddressbar

Hello,

After updating to latest 20.2.17, I'm having this problem with my TablacusExplorer.

I'm using 2x1 layout. Every time I minimize my TE to taskbar and try to restore it back, the window loses half part of its layout.

Steps to reproduce:
1. Choose 2x1 layout

2. Your TE will look like this:
![Image 1](https://user-images.githubusercontent.com/8424198/74609254-00f14480-511b-11ea-84d5-e0d459cb6d4c.png)

3. Minimize your TE to taskbar

4. Click your TE in windows taskbar to restore the windows. Your TE layout will lose half its part:
![Image 2](https://user-images.githubusercontent.com/8424198/74609322-a60c1d00-511b-11ea-85cd-5ba4d48e5a08.png)

**Comment by tortino** [comment]
happens to me too (but it was happening in previous version too)

![image](https://user-images.githubusercontent.com/26486758/74643206-9d940080-5174-11ea-901a-db688609de29.png)

**Comment by tablacus** [comment]
Thank you for the report.
I have fixed it on Tablacus Explorer 20.2.18.
Please try to update.

Regards,
