### ISSUE TITLE
Change background color for dark theme Windows 10

### ISSUE THREAD

**Issue by TiagoCant** [tablacus/TablacusExplorer#269]
Hi, I just tried out Windows' 10 dark theme. It gets a little crazy with Tablacus as the background of the Name column for files gets both the background and the font color black though not the other columns.
Any idea how to fix this?
Thanks for such an amazing file explorer btw!
![Untitled](https://user-images.githubusercontent.com/37641793/75184495-74deae80-5712-11ea-83b1-30f5ad83851f.png)

**Comment by tablacus** [comment]
Please try to install add-ons "Dark mode" and "No emphasis".

https://github.com/tablacus/TablacusExplorerAddons/wiki/noemphasis

Regards,

**Comment by TiagoCant** [comment]
Worked perfectly, Thanks!
![Untitled](https://user-images.githubusercontent.com/37641793/75250423-5629f780-57a6-11ea-9a21-76e56f0d808b.png)
