### ISSUE TITLE
detail view does not remeber columns and sizes

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#27]
Hi,
I have find a bug: in detail view it does not remember what column I have chosen, and the sizes of the culumns. As an example it always uses a column name of size 580 (but I want a smaller default size).
I also tried addon FolderSettings but it doesn't work: I add a filter i the option, but then it doesn't use Date Modified, but uses always Date, and doesn't remember other columns.
Can you fix it? Thanks!

**Comment by stefanocaselli** [comment]
thank you! I'll try asap!

**Comment by stefanocaselli** [comment]
Hi,
FolderSettings saves the column sizes, but now the name column is empty! (only for paths set in options).
If I press F2 to rename then the filename appears, but as soon as I press enter the filename disappears again.

**Comment by tablacus** [comment]
I can't find this problem.
Would you tell me your PC information and the setting of your folder settings?

*Tools->Options->Info*
![info](https://cloud.githubusercontent.com/assets/5156977/5593825/c5e9c672-926c-11e4-8bd5-de625b56f276.png)
*Tools->Add-ons...->Folder settings->Options...*
![fs](https://cloud.githubusercontent.com/assets/5156977/5593826/d063213e-926c-11e4-9ab5-5d42ef4b1fc9.png)

Best regards,

**Comment by stefanocaselli** [comment]
Hi, 
here is the info from tool/options:

![image](https://cloud.githubusercontent.com/assets/10347571/5594877/8a114630-9261-11e4-868a-d169eab6573b.png)

and from folder settings:

![image](https://cloud.githubusercontent.com/assets/10347571/5594869/32392ed2-9261-11e4-8e34-1bce562291b0.png)

and here a screenshot of the bug:

![image](https://cloud.githubusercontent.com/assets/10347571/5594894/44fd978c-9262-11e4-93c3-633232e43608.png)

**Comment by tablacus** [comment]
Thank you for your information.
When I installed an Italian language pack in Windows 8.1, I can confirm a problem, too.
I will try to check a cause.
Best regards,

**Comment by stefanocaselli** [comment]
thank you for investigating the problem!


2015-01-02 13:04 GMT+01:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
I've adjusted it on Tablacus Explorer 15.1.2

Best regards,

**Comment by stefanocaselli** [comment]
thanks!

2015-01-02 15:45 GMT+01:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
You are welcome.
