### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#272]
1. What are the font and size used in your screenshots from March 2015?  Really like that one.
2. When the font is changed, the font style (font type and size) does not change in the Frame tree.  How to do that?

**Comment by tablacus** [comment]
1. I think it's "Yu Gothic UI".
"Yu Gothic UI" is the default font for Japanese version of Windows 10.

2. Please try to update an add-on Font settings to 1.08.

Regards,

**Comment by daVe55w** [comment]
Thank you.  I have that font installed and will try it.
I am using Font Settings v1.08.  There may either be a problem with that add-on or another add-on is affecting how it works.   After I changed the settings, the font became scrambled and unreadable.  After restarting Tablacus, it appeared normal.  Also, only the Font style in the Tree changed and not the Frame this time.  Very strange.  

Is there an email address where I may send you a screenshot?

**Comment by tablacus** [comment]
I tried to adjust it with Font setting 1.09.
Try to install it anyway.

You can upload a screenshot here.
Or send an email to gaku@tablacus.com.

Regards,
