### ISSUE TITLE
Permanent file hiding

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#274]
Is it possible to permanently hide certain file types?

XYPlorer has a [Ghost Filter](https://www.xyplorer.com/release_15.60.php#GF) feature that allows you to permanently hide certain file you don't want to see without using NTFS hidden file property.

You can use it to exclude from file browsing things like say bak files, temporary caches, backup files, etc unwanted folders, etc..

Is there an equivalent feature in Tablacus?

It would be nice to be able to permanently specify a list of wildcards (including extension, paths and/or file names) to be able to exclude such files/folders form displaying. Perhaps a pulldown menu listing a pre-made list of filters one can independently toggle on or off, or using existing filter plugin

**Comment by tablacus** [comment]
I have added a hidden filter feature on Tablacus Explorer 20.3.26.
Please try to install it.

Options -> List -> Filter -> Hidden
![image](https://user-images.githubusercontent.com/5156977/77656683-9227c680-6fb7-11ea-9bb3-f6290dbdc123.png)

Regards,

**Comment by duarteframos** [comment]
Works great, that is it., this is perfect, closing now.
Man you are quick!

Is there a way to quickly toggle it on or off? Perhaps an entry in the view menu?

**Comment by duarteframos** [comment]
Feature [documented in the wiki](https://github.com/tablacus/TablacusExplorer/wiki/options-list), again many thanks

**Comment by tablacus** [comment]
Try installing the new add-on "Switch hidden filter".
![image](https://user-images.githubusercontent.com/5156977/77756617-e17efd00-7072-11ea-9161-ba95d649a96b.png)

Regards,

**Comment by duarteframos** [comment]
Absolutely awesome, documented both at [List Options](https://github.com/tablacus/TablacusExplorer/wiki/options-list) and the [addons page](https://github.com/tablacus/TablacusExplorerAddons/wiki/switchhiddenfilter).

I added it to the [Filter category](https://github.com/tablacus/TablacusExplorerAddons/wiki#filter), not sure if that is where you'd want it. Let me know if you prefer it elsewhere
