### ISSUE TITLE
New (?) feature

### ISSUE THREAD

**Issue by rocribera** [tablacus/TablacusExplorer#276]
I don't know if there's an addon or option to enable this, but is there a way for the address bar to display the options while writing on it? On the Windows File Explorer, if I wrote "C:" it would be a dropdown list with the folders inside "C:\" like "Program Files" and "Program Files(x86)". If I were to write down "C:\Program Files" it would show every single folder inside "Program Files", and so on. It could also show places you frequent inside that directory too, like in the example picture.

I use the address bar a lot to move around, and having to know every single name exactly is a bit annoying, since a misspell would just make all the typing useless. Is there a way to implement this? Just exactly like Windows File Explorer has, no need for anything else.

![image](https://user-images.githubusercontent.com/47631356/77821599-d87e4200-70eb-11ea-9089-82909d380648.png)

**Comment by tablacus** [comment]
Unfortunately, no.
I mostly use the filter bar or the button in the address bar.

![image](https://user-images.githubusercontent.com/5156977/77823251-ef00b980-713c-11ea-834a-40f975f5b6ba.png)

Regards,

**Comment by rocribera** [comment]
So no way this is getting implemented anytime soon? Or to be able to use TAB to autofill the rest of the path?

**Comment by tablacus** [comment]
I have adjusted it with Tablacus Explorer 20.3.31.
Please try to update it.

**Comment by rocribera** [comment]
Works great! Thank you very much!

**Comment by rocribera** [comment]
This is just me being picky, but any way we get to autocomplete by pressing tab, instead of it going to the filter box? If not, don't worry, that's more than enough!

**Comment by tablacus** [comment]
I don't know how to make it happen at the moment.
Thank you,
