### ISSUE TITLE
Quick Access

### ISSUE THREAD

**Issue by anonieee** [tablacus/TablacusExplorer#277]
Is there any way we can have the Quick Access feature like in the default Windows Explorer? 
That way we can see our list of pinned folders on our side Tree view. We would also have the ability to pin folders by simply dragging them into the Quick Access list.

**Comment by duarteframos** [comment]
https://github.com/tablacus/TablacusExplorerAddons/wiki/favoritesbar

**Comment by tablacus** [comment]
- Another method
You can use the Quick Access feature.
1. Right-click on a tab.
2. Select "Show frames".

![image](https://user-images.githubusercontent.com/5156977/78367709-806ca180-75fd-11ea-8431-a7c2192289d0.png)

Regards,

**Comment by anonieee** [comment]
Thank you, this is perfect!
