### ISSUE TITLE
Shortcut key

### ISSUE THREAD

**Issue by SinichiTachibana** [tablacus/TablacusExplorer#278]
以前、アドオン、キーにて[Ctrl]+[Shift]+[O]であるフォルダーを開くように設定しました。
正常に動いています。
しかし、止めたいのでもう一度、アドオン、キーを調べると[Ctrl]+[Shift]+[O]がなくなっていました。
キーを押すとフォルダーが開きます。
何回かバージョンアップしています。
どうしたら良いのでしょうか？

**Comment by tablacus** [comment]
アドオンの「キー」の「全体」の部分を別の物、例えば、「キー」等に変えてみてください。
そこに無いですか？

![image](https://user-images.githubusercontent.com/5156977/77915391-5bf98800-72d2-11ea-9f43-e22557b23152.png)


あと、ここは多くの国の方が使われているので、タイトルだけは英語で書いていただけると幸いです。
本文の方は日本語でOKです。

**Comment by SinichiTachibana** [comment]
返信、ありがとうございます。
タイトルの事は了解しました。
質問はここで良かったのでしょうか？

「全体」の所以外に[Ctrl]+[Shift]+[O]を設定している所はありませんでした。
それで別な物に置き換えてしまえと思い、新たに[Ctrl]+[Shift]+[O]に設定したのですが、
以前、設定したフォルダが開いてしまいました。
![クリップボード](https://user-images.githubusercontent.com/62864900/77932598-bac9fc00-72e8-11ea-9890-37044a31cabf.png)

**Comment by tablacus** [comment]
オプション→メニュー以下の項目「お気に入り」等の「キー」の欄に Shift+Ctrl+O を設定している場所は無いでしょうか？
![image](https://user-images.githubusercontent.com/5156977/77970559-7578ef00-7327-11ea-8008-9dc5ba5f5379.png)

置き換えるのであれば「全体」は「一覧」より優先度が下がるので「一覧」の方に追加する方が強いです。

**Comment by SinichiTachibana** [comment]
ありがとうございます。
解決しました。
その通りでした。
お恥ずかしい。
「Tablacus Explorer」は本当に便利なソフトです。
これからも使います。
