### ISSUE TITLE
Network share could not  disapear after deletion

### ISSUE THREAD

**Issue by davidcao2000** [tablacus/TablacusExplorer#279]
A network drive( redirect a network share to a local drive) could be shown in the tree view after it's created,  but if the network drive is deleted, the item in the tree will stay long time and could not disapear. 
Refresh doesn't work.  Only way I found is to  restart the application.

**Comment by tablacus** [comment]
I have adjusted it with Tablacus Explorer 20.3.31.
Please try to update it.

1. Open options of tree view.
2. Check General -> Refresh.

![image](https://user-images.githubusercontent.com/5156977/78039066-959cc280-73a8-11ea-80f4-224cd7429d64.png)

The tree view will also be refreshed when it is refreshed.

Regards,

**Comment by davidcao2000** [comment]
Great!
