### ISSUE TITLE
request: directory size

### ISSUE THREAD

**Issue by jarodsteele** [tablacus/TablacusExplorer#28]
Hi,
I want to use Tablacus because of its add-ons architecture (in the past I used Q-Dir, but it has not add-ons.)
But Q-Dir has a feature that I use: the ability to show the size of directories in the detail view.
It's very important to me, can you add this feature to Tablacus? (as an option, disabled by default).
Thanks!

**Comment by tablacus** [comment]
Thank you for a request.
I think about a realization method of folder size.
Best regards,

**Comment by tablacus** [comment]
Hello.
I handled the directory size in the detail view on Tablacus Explorer 15.1.18.

You click the right button on the column and choose "More...".
![fs1](https://cloud.githubusercontent.com/assets/5156977/5792937/6777c242-9f73-11e4-87d1-73bb5fbc7e08.png)

Check the checkbox of "Total file size" and click "OK".
![fs2](https://cloud.githubusercontent.com/assets/5156977/5792940/745b420e-9f73-11e4-82d4-d9dd7e66ab2b.png)

Like this.
![fs3](https://cloud.githubusercontent.com/assets/5156977/5792942/8075232a-9f73-11e4-8ab1-bbf04f2ebcb2.png)

Best regards,

**Comment by jarodsteele** [comment]
Thank you!
Do you think it possible to enable sorting based on this new column?


2015-01-18 16:39 GMT+01:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
I think it difficult to enable sorting based on this new column.
Best regards,

**Comment by jarodsteele** [comment]
ok, no problem. thank you.


2015-01-19 11:52 GMT+01:00 Gaku <notifications@github.com>:

**Comment by LightTempler** [comment]
Very cool and helpfull feature - thank you!
