### ISSUE TITLE
Auto Refresh

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#280]
Please add the feature for auto refresh of tab contents.  I have the Refresh add-on but that is only for manual refresh.  

I also have Force Refresh installed. However, I want the contents of every tab and folder to auto-refresh, not to have to list folders in the Filter.  There are thousands of folders and that is not feasible.

Perhaps you could add that feature to the current Refresh or Force Refresh add-on.  Would be nice to have the option to specify the auto-refresh interval.

**Comment by tablacus** [comment]
Basically, I think it's automatically refreshing without "Refresh" button.
And, how about an add-on "Force refresh"?

Regards,

**Comment by daVe55w** [comment]
It is not auto-refreshing.  I must click the Refresh button each time.
As I said, Force Refresh is not a good option as every folder must be entered in the Filter section.  I have thousands of folders.  How about including Tabs to be entered in the Filter section of Force Refresh?  That would be a better option.  Thanks.

**Comment by tablacus** [comment]
Let's use the wild card.
Anyway, enter "*"  in textarea of Filter of options of Force refresh.

![image](https://user-images.githubusercontent.com/5156977/78451083-49aa9000-76be-11ea-83d6-3f2ce9a51a5b.png)

|Wildcard|Meaning|
|:---|:---|
|*|All folders|
|?:\\*|Drive folders|
|\\\\*|Network folders|
|C:\\*|C drive folders|
|?:\\*;\\\\*|Local and network file folders|
|C:\\windows\\*|Sub folders of windows|

https://github.com/tablacus/TablacusExplorer/wiki/Filters-and-Queries

Regards,

**Comment by daVe55w** [comment]
That worked.  Thanks!
Another request.  Please add a Search or Filter option for Installed Add-ons, like there is for Get Add-ons.
