### ISSUE TITLE
Execute shell commands?

### ISSUE THREAD

**Issue by tim-lebedkov** [tablacus/TablacusExplorer#282]
I tried the program, but did not find the exact functionality I need: executing shell commands. Is it hidden somehow? Being able to see the last 3 lines of the output, showing the complete output, and changing the directory automatically would also be nice.

**Comment by tablacus** [comment]
Please try it out as follows

Type
`JScript`

Options
```
// Shell command
var cmd = "cmd /c dir";
// Current directory
var current_dir ="C:\\";
// Execute
var results = api.CreateProcess(cmd, current_dir);
// Split into lines
var lines = results.split("\n");
// Show 3 lines of results
alert(lines.slice(0, 3).join("\n"));
// Navigate to windows folder
NavigateFV(FV, "C:\\windows");
```

![image](https://user-images.githubusercontent.com/5156977/78463133-5fe33b00-7714-11ea-872f-8cc1052da766.png)

Regards,

**Comment by tim-lebedkov** [comment]
I see now it all works. Thank you.
