### ISSUE TITLE
Group favorite item problem with about:blank

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#283]
If a pane is showing the “about:blank” page (all tabs are closed), and a user opens a group favorite item, only one folder is opened, but the contents are incorrect.

Case 1: "Open" / "Open in new tab"

![1 fav 1](https://user-images.githubusercontent.com/34089121/79412716-bd12a280-7fd8-11ea-9cb2-f8f5c7b1b2b7.png)
![1 fav 2](https://user-images.githubusercontent.com/34089121/79412713-bbe17580-7fd8-11ea-8617-4d360b0b736f.png)
When "about:blank" shows
![2 blank](https://user-images.githubusercontent.com/34089121/79412756-dae00780-7fd8-11ea-8289-23189251157d.png)
Open the group favorite item
![3 fav 1](https://user-images.githubusercontent.com/34089121/79412838-fc40f380-7fd8-11ea-95a7-8601bf482240.png)
![3 fav 2](https://user-images.githubusercontent.com/34089121/79412836-fb0fc680-7fd8-11ea-881f-38820b07995c.png)

Case 2: "Open in background"
![1 fav 3](https://user-images.githubusercontent.com/34089121/79412866-0b27a600-7fd9-11ea-8b39-1365ca372de5.png)
When "about:blank" shows
![2 blank](https://user-images.githubusercontent.com/34089121/79412756-dae00780-7fd8-11ea-8289-23189251157d.png)
Open the group favorite item
![3 fav 3](https://user-images.githubusercontent.com/34089121/79412884-1549a480-7fd9-11ea-916a-b9ad4e6d5cb2.png)

**Comment by tablacus** [comment]
I have adjusted it on Tablacus Explorer 20.4.16.
Please try it.
Thank you,

**Comment by ccfs** [comment]
Although the new version solves Case 1 problem above, Case 2 now becomes a sequence problem.

![3 fav 3](https://user-images.githubusercontent.com/34089121/79563889-35b05680-80e0-11ea-8a81-36b2946d1fc1.png)

Please help to fix. Thanks.

**Comment by ccfs** [comment]
The problem is solved in TE 20.4.17. Thanks.
