### ISSUE TITLE
Tablacus crashes constantly

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#284]
Since the last update, Tablacus crashes when switching tabs, running EXE files, renaming operations and most other operations.  The last update did not fix this problem.

**Comment by tablacus** [comment]
I have not encountered this.

Please read this and let me know your environment.
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

Regards.

**Comment by daVe55w** [comment]
Info: TE64 20.4.28 Win 10.0.18363 WS 100 IE11 en_us 144 Webroot SecureAnywhere Windows Defender Webroot SecureAnywhere

Add-ons: mouse,key,addressbar,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,multithread,remember,undoclosetab,extract,download,thumbplus,tabcolor,autobackup,multiprocess,systemfolders,countbar,addonsupdater,sizestatus,everything,wcx,wfx,controlpanelbutton,forcerefresh,closebutton,addtabs2fav,properties,restart,refresh,emptyrecyclebin,fastcopy,font,tabname,notepadalternative,maximizebutton,thumbnailengine,mainmenubutton,mixedsort,startup,dragdrop,minimizebutton,paste,delete,newtab,copy,cut,checkbox,autoupdate,fullpathbar,opencpinexp,grabbutton,tabdesign,takeoverfoldersettings,aboutremember,sethome,gohome

**Comment by ccfs** [comment]
You have 2 groups of add-ons that may interfere each other of the same group:
- Multi Thread / Multi process / FastCopy
- Take over folder view settings / Remember folder view settings
Please try with only one enabled in each group.

Regards,
