### ISSUE TITLE
Synching layouts

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#285]
Is there a way to make every current and future tab have the same layout as another?  For example, my default Detail View displays columns Size, Date Modified, Date Created, Type and File Extension.  I would like that view to display in every tab created.

**Comment by tablacus** [comment]
Please try to use an add-on [Folder settings](https://tablacus.github.io/wiki/addons/foldersettings.html).

View -> Customize this folder...
![image](https://user-images.githubusercontent.com/5156977/80653222-aaa66780-8ab4-11ea-99d5-8f3a2f0a8220.png)

Change "Filter" to "*".
![image](https://user-images.githubusercontent.com/5156977/80653116-61eeae80-8ab4-11ea-8dc5-d0aeafda4503.png)

This conflicts with [Remember folder view settings](https://tablacus.github.io/wiki/addons/remember.html).

If there are no exceptions, [Take over folder view settings](https://tablacus.github.io/wiki/addons/takeoverfoldersettings.html) might be a good choice.

Regards,

**Comment by daVe55w** [comment]
I have installed both Remember Folder View Settings and Take Over Folder View Settings.  Will they conflict with each other?  If so, should I only keep Take Over Folder View Settings?  Its Filter is blank.  Is that correct?
<img width="680" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31006631/80659288-84ea7580-8a56-11ea-836b-3a93c4ec1d4a.png">

**Comment by tablacus** [comment]
"Remember Folder View Settings" and "Take Over Folder View Settings" are in conflict.

If the filter in "Take Over Folder View Settings" is empty, it will be enabled for normal drive folders and network folders.

Regards,

**Comment by daVe55w** [comment]
Removing Remember Folder View Settings worked.  Thanks!
