### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by SinichiTachibana** [tablacus/TablacusExplorer#287]
![1](https://user-images.githubusercontent.com/62864900/81077896-86b9aa80-8f28-11ea-976a-845d38c6a13b.png)
Tablacus Explorerを使っていると、たまにスクリプトエラーと言うのが出ます。
何かをした時と言うわけでもなくTablacus Explorerを起動しておいて他のアプリで作業し戻ったら
出ていました。
エラーの「はい」「いいえ」どちらを押しても特に何の変化も見られません。
自分はTablacus Explorerを使って大変便利なのでこのまま使いたいのですが、
なんとなくハテナという感じです。
エラーの出方がわかったらお知らせします。
これからも頑張って下さい。

**Comment by tablacus** [comment]
報告ありがとうございます。
とりあえず、エラーメッセージで対処方法は分かるので20.5.6で対処します。

**Comment by SinichiTachibana** [comment]
めちゃくちゃ早い対応ありがとうございます。
これからもTablacus Explorerは使わせてもらいます。

**Comment by toruyoshino** [comment]
僕もTablacusの大ファンです。
ただ、たまにこんなエラーが出ており、都度、再インストールをしています。
沢山のタブを表示しているので、またゼロから表示をし直すのが大変です。
エラーが少なくなると助かるのですが。
![4B922_TablacusExplorer_このページのスクリプトでエラーが発生](https://github.com/user-attachments/assets/f2dcf633-c43d-4642-a413-896bcaa1d86b)
