### ISSUE TITLE
Several things

### ISSUE THREAD

**Issue by guilhas** [tablacus/TablacusExplorer#29]
Is it possible to open 2 windows? Instead of two panes side by side?

Moving many files or large dragged between panes block tablacus until finish.

Suggestion for default hotkey CTRL+E to focus filter like windows explorer. (I use it)

How can I get bigger line hight in the details view?

**Comment by tablacus** [comment]
1.Two panes side by side

You should use the add-on 'Split'.
Help->Get add-ons
![1](https://cloud.githubusercontent.com/assets/5156977/6206825/69f059b6-b5d6-11e4-96a3-d32b623f8c9b.png)
Input "split", then click  "Filter"
![2](https://cloud.githubusercontent.com/assets/5156977/6206828/7d985bd0-b5d6-11e4-9b17-e7235dafcb42.png)
Click "Install"
![3](https://cloud.githubusercontent.com/assets/5156977/6206839/d4a085ba-b5d6-11e4-96cf-8d71a74db58d.png)
Click "Ok"
![4](https://cloud.githubusercontent.com/assets/5156977/6206841/db21c02a-b5d6-11e4-9ac4-ece08736a27e.png)
Click "Ok"
![5](https://cloud.githubusercontent.com/assets/5156977/6206842/e02f12ac-b5d6-11e4-9643-e849683db561.png)
Click "Vertical split button"
![6](https://cloud.githubusercontent.com/assets/5156977/6206855/0917ecc0-b5d7-11e4-8b53-c46eb9c530d7.png)
Like this
![7](https://cloud.githubusercontent.com/assets/5156977/6206857/0fd6c810-b5d7-11e4-97c9-ccd1c3fed352.png)

2.Moving many files or large dragged between panes block tablacus until finish.

You should use the add-on 'Multi thread' or 'Multi process'.
Help->Get add-ons
![1](https://cloud.githubusercontent.com/assets/5156977/6206825/69f059b6-b5d6-11e4-96a3-d32b623f8c9b.png)
Input "multi", then click  "Filter"
![11](https://cloud.githubusercontent.com/assets/5156977/6206865/5fabeb68-b5d7-11e4-829b-7d313fe08f1c.png)
Click "Install"
![12](https://cloud.githubusercontent.com/assets/5156977/6206867/6f8ee67a-b5d7-11e4-92d9-6af726b7f1d5.png)

'Multi thread' startup overhead is small.
'Multi process' supports the right drag.
I think 'Multi thread' is better.

3. Default hotkey CTRL+E to focus filter like windows explorer.

It might be Windows+E, right?
I will try to consider it.

4.Bigger line hight in the details view?
I'll think about it.

**Comment by LightTempler** [comment]
To 4.) 'line high' or 'font height'? 
To change the font and/or it 's size the addon 'Font Settings' has helped me alot.

**Comment by LightTempler** [comment]
In English/German Windows (I don't know others ;-) ):
WindowsKey+E is shortcut for starting a Windows Explorer, Ctrl+E is focus on search textbox.

**Comment by tablacus** [comment]
> Suggestion for default hotkey CTRL+E to focus filter like windows explorer. (I use it)

I misunderstood that.
This is possible.

Click Tools->Add-on
![filterbar0](https://cloud.githubusercontent.com/assets/5156977/7067737/a3ea867c-df08-11e4-853c-8cc9f2309b00.png)

Click "Options" of Filter Bar.
![filterkey1](https://cloud.githubusercontent.com/assets/5156977/7067611/9c94ec60-df07-11e4-9a5a-25f14b92e0f7.png)

Click the tab of Key.
![filterkey2](https://cloud.githubusercontent.com/assets/5156977/7067628/b632fe14-df07-11e4-8df3-ba1c4938f03c.png)

Click check box of Exec.
![filterkey3](https://cloud.githubusercontent.com/assets/5156977/7067643/da1d5e0a-df07-11e4-9142-95713e6aab8f.png)

Click select bar, then select All.
![filterkey4](https://cloud.githubusercontent.com/assets/5156977/7067653/f1553e30-df07-11e4-817b-51b656bf5a0b.png)

Click "Input" button.
![filterkey5](https://cloud.githubusercontent.com/assets/5156977/7067670/1b017f14-df08-11e4-81c9-d03a28cf91ec.png)

Push "Ctrl" and "E", then click "Ok".
![filterkey6](https://cloud.githubusercontent.com/assets/5156977/7067682/39016736-df08-11e4-9780-744ad2fc735c.png)

Click "Ok".
![filterkey7](https://cloud.githubusercontent.com/assets/5156977/7067687/451907d6-df08-11e4-99f1-d3b2867695d1.png)

Click "Ok" to be completed. 
![filterkey8](https://cloud.githubusercontent.com/assets/5156977/7067690/4d8a6b58-df08-11e4-96d4-cae62af190b2.png)

**Comment by guilhas** [comment]
Yes. All is ok

@LightTemple I've installed 'Font settings' that solved it.
