### ISSUE TITLE
Network shares cannot show immediately in a new tab

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#290]
When I open a network computer in a **new tab**, TE cannot show the list of network shares until I press F5. However this does not happen if I open it in **current tab**. Please help to solve this problem. Thanks.

Example:
Enter a server address and press Ctrl+Enter
![20200523_184734](https://user-images.githubusercontent.com/34089121/82728948-4dee4380-9d26-11ea-81e4-c19a766afa59.png)
The list is empty.
![20200523_184800](https://user-images.githubusercontent.com/34089121/82728950-4e86da00-9d26-11ea-88ac-94ebdfbfa9a2.png)
Until I press F5
![20200523_184813](https://user-images.githubusercontent.com/34089121/82728947-4c248000-9d26-11ea-8f7f-6c56e73e9312.png)

**Comment by ccfs** [comment]
The problem still occurs and is worse in TE 20.5.23. Pressing F5 cannot show the list. I have to switch to another tab and back to get the list.
Regards,

**Comment by tablacus** [comment]
I haven't encountered it.
Maybe it's a network difference.
Regards,

**Comment by ccfs** [comment]
A network difference probably has an effect, but I don't think it is the root cause, because **the problem does NOT occur if I navigate in the CURRENT TAB.**
![1](https://user-images.githubusercontent.com/34089121/83323397-0bca8200-a291-11ea-88fd-39c49232c0c3.png)
![2](https://user-images.githubusercontent.com/34089121/83323398-0d944580-a291-11ea-9018-75fabeb0d444.png)

---
I re-produced the problem with **TE 20.5.29**:
![1](https://user-images.githubusercontent.com/34089121/83323437-5d730c80-a291-11ea-9755-bed050cc53d8.png)
navigated to the server in a NEW TAB
![2](https://user-images.githubusercontent.com/34089121/83323439-5f3cd000-a291-11ea-9ec4-be21ae06acd8.png)
![3](https://user-images.githubusercontent.com/34089121/83323440-5fd56680-a291-11ea-93e7-cc04c23d99dd.png)
I powered off my router to test the no connection case.
![4](https://user-images.githubusercontent.com/34089121/83323442-5fd56680-a291-11ea-8a9f-10cf4495863b.png)
![5](https://user-images.githubusercontent.com/34089121/83323443-606dfd00-a291-11ea-9e0e-dc1fb66a4fe2.png)

---
**TE 20.5.30 gets WORSE about the no connection case**
![1](https://user-images.githubusercontent.com/34089121/83323571-58fb2380-a292-11ea-93bb-158c2cc1382b.png)
navigated to the server in a NEW TAB
![2](https://user-images.githubusercontent.com/34089121/83323572-5993ba00-a292-11ea-8129-57bf66cabbd7.png)
![3](https://user-images.githubusercontent.com/34089121/83323573-5a2c5080-a292-11ea-8d08-911fbeb8f45c.png)
I powered off my router to test the no connection case.
![4](https://user-images.githubusercontent.com/34089121/83323565-56003300-a292-11ea-8eb5-2f0d36156492.png)
![5](https://user-images.githubusercontent.com/34089121/83323569-58628d00-a292-11ea-8e3e-3af7977c189a.png)
Switch to another tab and back. **TE starts to malfunction**.
![6](https://user-images.githubusercontent.com/34089121/83323570-58628d00-a292-11ea-88a5-925cbd810e5d.png)

**Comment by ccfs** [comment]
1. With TE 20.5.32, the "network shares cannot show in a new tab" problem is solved.

2. The "no connection leads to malfunction" problem still occurs (since TE 20.5.30).

3. Likewise, a "non-existent server (or share) leads to malfunction" problem has occurred **since TE 20.5.30**:

![1](https://user-images.githubusercontent.com/34089121/83388139-81b12380-a420-11ea-827c-47bb926434eb.png)
![2](https://user-images.githubusercontent.com/34089121/83388141-8249ba00-a420-11ea-82c1-30b4a1657f06.png)
![3](https://user-images.githubusercontent.com/34089121/83388128-7fe76000-a420-11ea-8f79-ec877ea05e89.png)

The problem **does not occur in TE 20.5.29** (though it has a minor issue with address bar):
![1](https://user-images.githubusercontent.com/34089121/83388413-fd12d500-a420-11ea-8a86-5d9f393cd3d2.png)
![2](https://user-images.githubusercontent.com/34089121/83388416-fdab6b80-a420-11ea-93ba-97f20e327211.png)
![3](https://user-images.githubusercontent.com/34089121/83388408-fb491180-a420-11ea-9929-99503ed29c9d.png)

**Comment by ccfs** [comment]
The problems are solved with TE 20.6.1. Thanks.
