### ISSUE TITLE
folder size

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#293]
How to get TablacusExplorer to display folder sizes?

**Comment by tablacus** [comment]
Take a look at a link below.

https://github.com/tablacus/TablacusExplorer/issues/28#issuecomment-70412675

Regards,

**Comment by daVe55w** [comment]
I just did that and it does not work.  No folder sizes appear even after restarting TablacusExplorer.
See the enclosed screenshot

<img width="607" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31006631/82755525-13c28780-9da2-11ea-8f43-2266e881bf22.png">

**Comment by tablacus** [comment]
Thank you for your report.
You are using ExplorerBrowser, are not you?
Various functions and add-ons do not work with ExplorerBrowser.
Please try to uncheck "Details" in "ExplorerBrowser".
![image](https://user-images.githubusercontent.com/5156977/82758357-0d272500-9e21-11ea-8750-94c4e90255bd.png)

Regards,

**Comment by daVe55w** [comment]
Yes, that worked.  Thanks.
Also, the font size in all columns increased to where I had set it but could never get it to the specified size.  Disabling Details also seems to have fixed that.  :D
