### ISSUE TITLE
Different font sizes in tabs

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#294]
Different font sizes appear in the left and right panes in some tabs. Other tabs have the same size fonts in both panes.

Screenshot below.  How to fix this?

<img width="1257" alt="Screenshot_4" src="https://user-images.githubusercontent.com/31006631/82759118-2ac0a400-9db9-11ea-9600-6c460a37be2e.png">

**Comment by tablacus** [comment]
Please try an add-on "Font settings".
Regards,

**Comment by daVe55w** [comment]
I am using the add-on "Font Settings" and have the font, size and weight specified. 
The fonts appear in different sizes in the left and right panes in most tabs.

<img width="681" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31006631/82823524-bbf55080-9e75-11ea-98e4-9d65f492dd62.png">

**Comment by tablacus** [comment]
What is the “List” option setting?
![image](https://user-images.githubusercontent.com/5156977/82825428-32319b80-9ee6-11ea-8b68-1ffddaf7f13f.png)

**Comment by daVe55w** [comment]
Same as your example except I have "Show frames" checked.

<img width="679" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31006631/82826817-d5010000-9e7b-11ea-95ed-f65db74dd38a.png">

**Comment by tablacus** [comment]
How about if you run "Tools -> Reload customize"?

**Comment by daVe55w** [comment]
That seemed to work, except I had to do it on every tab.  Reload customize should work universally, on all tabs.  Or, perhaps you can make 2 options for it.  Reload customize - Current Tab and All Tabs (in every group)

I'll let you know tomorrow if the Reload Customize Tool worked or the fix was only temporary.

**Comment by ccfs** [comment]
@daVe55w,

I think the font sizes are the same, but icon sizes are different, because you might have pressed Ctrl + Wheel-Up to enlarge the icons. "Remember folder view settings" add-on records the icon size you use on each folder.

To verify my hypothesis, check the icon sizes of your folder views using "About remember" add-on.

Regards,

**Comment by daVe55w** [comment]
The font sizes are also different, as are the icons, but are not showing up that way in the screenshots.  I did not have Remember Folder View Settings add-on installed, so About Remember does not work, as that is dependent on it.

However, your reply gave me an idea. What if I perform Reload Customize for every tab in each group, then reinstall add-on Remember Folder View Settings? I just did that and so far, Tablacus is keeping the correct folder views (normal size icons and fonts in both panes).  I will let you know if that changes again.

However, there may be a deeper issue here and the root problem should be identified.

**Comment by tablacus** [comment]
Thank you for your report.
I adjusted it with an add-on Font settings 1.10.
Give it a try.

Regards,

**Comment by daVe55w** [comment]
It still does not work.  Also, I just realized that every tab was missing the "Total File Size" column and added back the "Size" column that I had changed a few days ago.

What can be causing such strange behavior?  Add-ons conflicts?

**Comment by ccfs** [comment]
@daVe55w,

Please show us the whole add-on list in Help > About, and the screen captures of the whole TE window showing the font size and icon size differences. A small portion of the screen is not enough hint for problem solving.

Regards,

**Comment by tablacus** [comment]
Activate the tabs for both the small and large fonts, one at a time, then type the following in the address bar and press Enter
`javascript:alert(GetFolderView().IconSize);`

![image](https://user-images.githubusercontent.com/5156977/83032885-5cfc2b00-a071-11ea-84a6-f2c3c71207fa.png)

What is the number that appears in the dialog for each tab?

Then, enter the following in the address bar and press Enter.
`javascript:alert(api.GetSystemMetrics(SM_CYSMICON) * 96 / screen.deviceYDPI);`

What is the displayed number?

Regards,

**Comment by daVe55w** [comment]
16 for the first javascript
16 for the second javascript

**Comment by tablacus** [comment]
Thank you.
The first script, is both the small font tab and the large font tab both 16?

Regards,

**Comment by daVe55w** [comment]
Correct.

**Comment by tablacus** [comment]
I'd like to know if the font change isn't working or if it's just a different size.
Could you try changing it to a font with more personality, like Impact?

![image](https://user-images.githubusercontent.com/5156977/83096856-b308b700-a0e1-11ea-8bfc-8965207cb5b3.png)

Regards,

**Comment by ccfs** [comment]
@daVe55w,

Your "left pane" is "folder tree" and "right pane" is "file list", isn't it?
I notice that you put something in "Height (Tree)", which affects folder trees.
Please try empty the field and restart TE.

Regards,

**Comment by daVe55w** [comment]
Emptying the field "Height (Tree)" had no effect on the problem.

**Comment by daVe55w** [comment]
I changed the font 5x, each time to a different font. Each time the font did change but the different sizes still appear.  Also, in the file list pane, if I navigate to a folder other than Home (Set Home), the fonts and icons enlarge.  Clicking Tools - Reload Customization fixes that, temporarily.

**Comment by tablacus** [comment]
Thanks.

What add-ons do you use for folder settings?
e.g. Remember folder view settings, Folder settings, Take over folder view settings.

Could you try disabling all of these add-ons once?

Regards,

**Comment by daVe55w** [comment]
Remember Folder View Settings, About Remember, and Take Over Folder View Settings.
Disabling one by one and all at once have no effect on the resized icons and fonts.  Also, when disabled, the columns in each tab revert to their default setting (Size, Date, Type).  None of them keep the customized view (Total File Size, Date Created, Date Modified, Type, and File Extension).

What could the problem be that is making the fonts and icons different sizes between the left and right panes in nearly all tabs?  The only way to correct it - temporarily - is by clicking Refresh or Tools -> Reload Customize.  This is a very annoying problem.

**Comment by tablacus** [comment]
It's hard to fix because I can't encounter it.
Just in case, I adjusted Font setting 1.13.
Also, if the size is different, try typing the following into the address bar.

`javascript:Addons.Font.Init();`

Will this be like "Tools -> Reload Customize"?

Regards,

**Comment by daVe55w** [comment]
It's still doing it with Font Setting 1.13.  I copied javascript:Addons.Font.Init(); into the address bar for every tab in the 2 groups.  It had the same effect as Tools -> Reload Customize and also was temporary.  The problem remains.

**Comment by daVe55w** [comment]
Here's an idea for a workaround. I'm using the add-ons, Force Refresh 1.03 and Refresh 1.06. Since clicking the Refresh button on the toolbar causes the icons, files, and folders to revert to their correct size, can you update Refresh or make a new add-on named Auto Refresh with options what to refresh (Current Tab, All Tabs, All Groups - All Tabs), and the period (every X seconds - with the user inputting the number for X from 0.1 to 1,000 and upon navigation to a new file, folder or tab)?

**Comment by tablacus** [comment]
I have adjusted an add-on Font settings 1.14.
Please try to update it.

Regards,

**Comment by daVe55w** [comment]
Unfortunately, no effect. The problem persists.
Is it possible to make an auto-refresh add-on as per my previous message?

**Comment by tablacus** [comment]
I'll try to come up with a few scripts for a workaround. 

Regards,

**Comment by tablacus** [comment]
Use an add-on "run at setup" for the following workarounds.

### Workaround 1
Set the font of the list view and the tree view that is displayed every 30 seconds.

**Type**
`JScript`
**Options**
```JavaScript
setInterval(function () {
  var cTC = te.Ctrls(CTRL_TC, true);
  for (var i in cTC) {
    Addons.Font.Exec(cTC[i].Selected);
  }
}, 30 * 1000);
```
![image](https://user-images.githubusercontent.com/5156977/83781080-fefec180-a6c8-11ea-8b27-d43700cc0575.png)

### Workaround 2
Set the font of list view and tree view after 5 seconds of display change.

**Type**
`JScript`
**Options**
```JavaScript
AddEvent("ChangeView", function (Ctrl) {
  (function (Ctrl) { setTimeout(function () {
   Addons.Font.Exec(Ctrl);
  }, 5 * 1000);}) (Ctrl);
});
```
![image](https://user-images.githubusercontent.com/5156977/83781129-0aea8380-a6c9-11ea-93f0-e1b3bf657c57.png)

Regards,

**Comment by daVe55w** [comment]
Either Workaround 1 and 2 are to be implemented, not both, correct?

**Comment by tablacus** [comment]
Maybe it would be better to set the height of the frame tree in the font setting of the add-on to "7".
![image](https://user-images.githubusercontent.com/5156977/83781682-d7f4bf80-a6c9-11ea-8458-36093aba8dcc.png)

Regards,

Regards,

**Comment by tablacus** [comment]
### Workaround 3
Set the font for all list views and tree views every 30 seconds.

**Type**
`JScript`
**Options**
```JavaScript
setInterval(function () {
  var cFV = te.Ctrls(CTRL_FV);
  for (var i in cFV) {
    Addons.Font.Exec(cFV[i]);
  }
}, 30 * 1000);
```
![image](https://user-images.githubusercontent.com/5156977/83787487-d7125c80-a6ce-11ea-98d1-044cb4bac8a2.png)

**Comment by daVe55w** [comment]
Whatever you changed in the v20.6.8 update appears to have finally fixed the problem. What was changed?

However, now there is 1 other problem.  The customized column view is not propagating to other folders automatically. I have installed Take Over Folder View Settings 1.06, Remember Folder View Settings 1.38 and About Remember 1.03.

**Comment by tablacus** [comment]
Those three add-ons are conflicting.
What is the intent of the three add-ons?
Regards,

**Comment by daVe55w** [comment]
The intent is to propagate the folder settings to every folder - the very thing that TE is not doing.
Which should I remove? Will one of these add-ons make the folder view the same in every folder no matter which folder/tab I set as the default view?

**Comment by tablacus** [comment]
It looks like you can leave only Take Over Folder View Settings and turn off the others.
Take Over Folder View Settings is enabled by default for normal drive folders and network folders only.
To enable downloads and libraries as well, set the Filter to "*".
In that case, you can disable the folders you want to exclude, such as PC, by setting to "Disable".

![image](https://user-images.githubusercontent.com/5156977/84398579-17c42580-ac3b-11ea-9f71-cded2cdde692.png)

Regards,

**Comment by daVe55w** [comment]
Awesome.  Thank you. Case closed!
