### ISSUE TITLE
Show "Admin" when "Title bar" add-on is OFF

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#296]
If TE is run with Admin privilege, and Title bar add-on is disabled, it should still show "admin" in title bar. Please help to solve this issue. Thanks.

![0](https://user-images.githubusercontent.com/34089121/83254977-301b5580-a1e2-11ea-9878-b68cb33c17eb.png)
![1](https://user-images.githubusercontent.com/34089121/83254974-2eea2880-a1e2-11ea-95b6-fdfcf8c060e3.png)

**Comment by ccfs** [comment]
The problem is solved with TE 20.5.30. Thanks.

**Comment by ccfs** [comment]
This problem re-occurs recently. Please help to solve it. Thanks.

![20210213_100918](https://user-images.githubusercontent.com/34089121/107840768-8839cc80-6df0-11eb-81e6-7bd1e317e666.png)
![20210213_100927a](https://user-images.githubusercontent.com/34089121/107840775-9851ac00-6df0-11eb-9d7c-86a25c0ba1c9.png)

**Comment by tablacus** [comment]
Please try to update Tablacus Explorer 21.2.13.
Regards,

**Comment by ccfs** [comment]
Tested OK. Thanks.
