### ISSUE TITLE
TE context menu

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#299]
TE context menu does not display Bitdefender.  This is the only difference between the context menus for Windows File Explorer and TE.  How to correct this?

<img width="308" alt="File Explorer context menu" src="https://user-images.githubusercontent.com/31006631/84573312-bcdf1b00-ad6d-11ea-8003-b9dca956e322.png">
<img width="284" alt="TE context menu" src="https://user-images.githubusercontent.com/31006631/84573313-bd77b180-ad6d-11ea-86c7-49b007edf831.png">

**Comment by tablacus** [comment]
I think Bitdefenderis a specification that can be displayed only by the context menu of Explorer.
Please contact Bitdefender.

Regards,
