### ISSUE TITLE
default columns and mtp devices

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#30]
Hi,
I'm using "folder settings" addon to set a default column layout for all folders, using the * character as filter.
It's working as intended for fixed disks, but it doesnt work for mtp device (my android phone).
I have tried configuring the filter, but when I try to "get the current folder view" I get this:

::{20D04FE0-3AEA-1069-A2D8-08002B30309D}\\\?\usb#vid_05c6&pid_6765&mi_00#6&16cc529&0&0000#{6ac27878-a6fa-4155-ba85-f98f491d4f33}\SID-{10001,,58918895616}\{0000005C-0001-0001-0000-000000000000}\{00003745-0001-0001-0000-000000000000}

I have also problems copying files to mtp device when "multi process" addon is enabled.

**Comment by tablacus** [comment]
Hello,
I tried doing it. but it almost go well.
![150217_01](https://cloud.githubusercontent.com/assets/5156977/6229024/1761fa6c-b6f6-11e4-9e35-0ce017611ba3.png)

![150217_2](https://cloud.githubusercontent.com/assets/5156977/6229028/20e63288-b6f6-11e4-8c24-ad8270f9ce2a.png)
I think that this is because it is not "Date modified" that "Modified" is not displayed.

> I have also problems copying files to mtp device when "multi process" addon is enabled.

Thank you. I confirmed it, too.
I've adjusted this on Multi process 1.05

Best regards,

**Comment by stefanocaselli** [comment]
Hi,
thanks for your fast reply. 
I've tried using "Modified" column and it seem to work for MTP devices, but then it doesn't work anymore for fixed disks (for hard disk and pendrives I want to use the "total file size" column).
do you have other suggestions?
Thank you.

**Comment by tablacus** [comment]
Hello,
I see.
Unfortunately MTP device does not support "Total file size" column now.
Best regards,

**Comment by stefanocaselli** [comment]
Well, I could use "total file size" for hard disks/pendrives and the normal "size" column for MTP devices.
Do you think it's possible to set default for each of these two cases?
I'm thinking about a filter like *GT-I9000* or This PC* only for MTP devices. 
If there is no match then fallback to the * default filter. Is it possible?
Thank you.

**Comment by tablacus** [comment]
Hello,
How is that like this?

Hard disks filter
> ?:\\*

![150219_1](https://cloud.githubusercontent.com/assets/5156977/6267498/faa5fd04-b887-11e4-9f2b-5c94a6ea583d.png)

MTP devices filter
>::{20D04FE0-3AEA-1069-A2D8-08002B30309D}\\\\\?\\usb#*

![150219_2](https://cloud.githubusercontent.com/assets/5156977/6267501/0182e52e-b888-11e4-95b8-023d998da8b4.png)

Folder Settings v1.07 supported normal display name path for filter.
The following methods are possible, too
MTP devices filter
>This PC\\GT-I9000*

When path matches plural filters by the folder setting, a lower filter is effective.
![150219_3](https://cloud.githubusercontent.com/assets/5156977/6267508/07c8a536-b888-11e4-80c4-aba9d51f6970.png)

Best regards,

**Comment by stefanocaselli** [comment]
Hi,
I'm trying the new version. 
First thing is that the filter ?:\* doesn't work for special folders like "Download", so I reverted to * as the first filter (at the top).
I'll continue testing your solution, and let you know my findings.
Thanks!

**Comment by stefanocaselli** [comment]
Hi,
I did some more testing and it works correctly. 
this program keeps getting better at every release!

**Comment by tablacus** [comment]
That's great.
Thank you!
