### ISSUE TITLE
How to display Quick Access in the side tree view?

### ISSUE THREAD

**Issue by onmyouji** [tablacus/TablacusExplorer#304]
Hello,

I'm not sure what I did, but I lost access to the Quick Access feature, it disappeared from the side tree view.

How to activate it again?

**Comment by tablacus** [comment]
### Method.1 (using a frame)

1. Right click on the tab.
2. Select "Show frames".

![image](https://user-images.githubusercontent.com/5156977/87226093-8af0c100-c3cc-11ea-9199-30efb8c9f0ad.png)

### Method.2 (new features on Tablacus Explorer 20.7.11)

1. Open Options -> Tree -> Root
2. Enter the following values for Root.

```
::{679F85CB-0220-4080-B29B-5540CC05AAB6}
0
```
(Quick access and Desktop)

![image](https://user-images.githubusercontent.com/5156977/87226261-88429b80-c3cd-11ea-9098-4ecf6707d427.png)

3. Show tree view (normal tree view or side tree view)

![image](https://user-images.githubusercontent.com/5156977/87226331-fc7d3f00-c3cd-11ea-934f-c316f13f25c6.png)

Regards,

**Comment by onmyouji** [comment]
Thanks!

Method 2 solved my problem.

Method 1 doesn't work for me, my layout becomes like this, it shows two tree view:

![Image 1](https://user-images.githubusercontent.com/8424198/87226919-43186c80-c3c1-11ea-992b-4ae067e07c3c.png)

TE64 20.7.11 Windows 10 Home 1809 (10.0.17763) Dark IE11 en_us 120 Windows Defender

mouse,key,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,multithread,remember,undoclosetab,split,everything,darkmode,addonsupdater,statusbar,innerbreadcrumbsaddressbar,forcerefresh
