### ISSUE TITLE
System folder (This PC) doesn't remember column width

### ISSUE THREAD

**Issue by onmyouji** [tablacus/TablacusExplorer#305]
TE64 20.7.12 Windows 10 Home 1809 (10.0.17763) Dark IE11 en_us 120 Windows Defender

mouse,key,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,multithread,undoclosetab,split,everything,darkmode,addonsupdater,statusbar,innerbreadcrumbsaddressbar,forcerefresh,takeoverfoldersettings

Hi Gaku,

Whenever I restart Tablacus, the column width for `This PC` reverts back to wide. This doesn't happen with normal files folder (it can remember the column width).

Is there any way to make it save the column width?

Before restart
![Image 2](https://user-images.githubusercontent.com/8424198/87240612-20c83280-c445-11ea-8d44-ce7ebeb71cfd.png)

After restart, it goes back to wide
![Image 3](https://user-images.githubusercontent.com/8424198/87240615-2b82c780-c445-11ea-839d-dae9deb8a762.png)

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 20.7.13.
Please try to update.

Regards,

**Comment by onmyouji** [comment]
It's still the same. After restart, the column width goes back to wide.
This problem only happens on `This PC`. 

Other system folder (e.g. Pictures, Download, Videos) are okay.

**Comment by tablacus** [comment]
Add-on "Remember folder view settings" is required.


Regards,

**Comment by onmyouji** [comment]
Thank you 🙏
