### ISSUE TITLE
Expired SSL Certificate of the penflip URL on the Read Me page

### ISSUE THREAD

**Issue by perplexityjeff** [tablacus/TablacusExplorer#306]
Expired SSL Certificate of the penflip URL on the Read Me page.

**Comment by perplexityjeff** [comment]
Does the website even work anymore?

**Comment by tablacus** [comment]
It may be impossible.
Regards,

**Comment by tablacus** [comment]
Anyway, here's an archive page.
https://web.archive.org/web/20160830063329/https://www.penflip.com/LightTempler/tablacus-explorer

**Comment by perplexityjeff** [comment]
Maybe remove it and migrate the content to the wiki?

**Comment by perplexityjeff** [comment]
Closing the issue as it is fixed with commit: 

https://github.com/tablacus/TablacusExplorer/commit/2cbd7553c3fc4d7503cf4bfcae387c4177abce6d
