### ISSUE TITLE
Could you keep the release filename (.zip) and its first folder name identical ?

### ISSUE THREAD

**Issue by integzz** [tablacus/TablacusExplorer#309]
Hi, I found this useful tool two weeks ago. I really like its extensible design. 

As I maintain a Scoop bucket, I decided to write a manifest to help other users to install and update Tablacus easily. (P.S. [Scoop](https://scoop.sh/) is a Windows Package Manager).

However, there is one problem, that is, due to the filename changes in every new release, the manifest can not auto-update, which means that the manifest only can be updated manually.

So, could you keep the release filename (.zip) and its first folder name identical or in the same format as its version (i.e. 20.8.6)?

**Comment by tablacus** [comment]
You can also download Tablacus Explorer from the following fixed address.

tablacus.github.io/TablacusExplorerAddons/te/te.zip

Regards,

**Comment by integzz** [comment]
Great! Problem solved. Thank you, Gaku !
