### ISSUE TITLE
bug: parameter incorrect

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#31]
Hi,
I'm using split plugin 4x4. sometimes while dragging a file between two windows I get this error:
![capture](https://cloud.githubusercontent.com/assets/10347571/6460669/7878b09a-c199-11e4-90fe-6e389c2bbc79.PNG)
The problem goes away if I restart the application.

**Comment by tablacus** [comment]
Hello,
I try to check it out.
Thank you.

**Comment by stefanocaselli** [comment]
Maybe... something is messed up when I add some system environment variable... I have just added one new env var and immediately got the error.

**Comment by tablacus** [comment]
Thank you for additional information.
I've adjusted it on Tablacus Explorer 15.3.4
Best regards,

**Comment by stefanocaselli** [comment]
thanks, it works now.

**Comment by tablacus** [comment]
My pleasure.
