### ISSUE TITLE
Request: Show confirmation dialog when move files or folders

### ISSUE THREAD

**Issue by timarupopoka** [tablacus/TablacusExplorer#315]
はじめまして。英語が苦手なので日本語で失礼します。

ファイルやフォルダを誤って隣のフォルダにドラッグして移動してしまうのを防ぐ機能が欲しいです。
ドラッグによる移動自体は有用なので、できれば移動そのものを禁止するのではなく、
確認ダイアログを表示する方向にしていただけると安心して使えます。
X-Finderにあった、移動時やコピー時に指定したスクリプトを実行する形式でも構いません。
ご検討よろしくお願いします。

**Comment by tablacus** [comment]
アドオンの「ドロップを確認」を作成しました。試してみてください。

**Comment by timarupopoka** [comment]
期待通りの動作でした。
ユーザーが意思を持ってCtrlを押さない限りコピー動作にはならないので
個人的にはコピー時の確認は不要かなと思っていましたがこれも悪くないですね。

今まで共有フォルダなどではマウスの誤爆が怖くてキーボードで操作していましたが
これで安心して使うことができます。本当にありがとうございました。
