### ISSUE TITLE
Bug: Cannot double-click a file or folder when renaming

### ISSUE THREAD

**Issue by timarupopoka** [tablacus/TablacusExplorer#317]
フォルダが名前変更状態になっているときにダブルクリックすると、
一旦確定状態に戻り、また名前変更状態になるという挙動になってしまいます。
TEダウンロード直後のバニラでも再現しました。
エクスプローラーではならないのでダブルクリック速度が遅すぎることはないと思います。

そもそも最初のダブルクリックに失敗して意図せず名前変更状態になってしまう頻度が、
エクスプローラーやX-Finderに比べてかなり多い気がします。
（ダブルクリックの判定がOSの設定とは別で相当シビアに設定されている？）
ご確認よろしくおねがいします。

TE64 20.8.19 Windows 10 Home 1909 (10.0.18363) Dark IE11 ja_jp 96 Avira Antivirus Windows Defender
mouse,key,addressbar,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,multithread,remember,undoclosetab

**Comment by tablacus** [comment]
Tablacus Explorer 20.8.24でエクスプローラと同様にテキスト部分以外をダブルクリックした場合に実行するように調整しました。
試してみてください。

**Comment by timarupopoka** [comment]
一日使ってみて完全に直っていることを確認できました。
とても快適です。どうもありがとうございました。
