### ISSUE TITLE
Tab reordering by  Drag and Drop tab is no longer working

### ISSUE THREAD

**Issue by alice0775** [tablacus/TablacusExplorer#318]
This problem is reproducible 20.8.24 with default settings

Regression window:
20.8.22: good
20.8.24: bad

Steps to reproduce:
1. Extract te20824.zip and run te64.exe
2. Open many tabs
3. Try to reorder tabs  by  Drag and Drop tab

Actual Results:
Cannot reorder the tabs.  Mouse cursor changes to "not-allowed" while dragover tabs.
It is only possible to move to the next last tab

**Comment by tablacus** [comment]
I have adjusted this issue in Tablacus Explorer 20.8.25.
Please try to install it.

Regards,

**Comment by alice0775** [comment]
> 
> 
> I have adjusted this issue in Tablacus Explorer 20.8.25.
> Please try to install it.
> 
> Regards,

20.8.25 works as expected. 
Thanks
