### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by jarodsteele** [tablacus/TablacusExplorer#32]
Hi,
I found some bugs:
1) if I cut (ctrl-x) a file saved on the Desktop and then I paste in a Tablacus window it doesn't move the file (or copy if I use ctrl-c).
2) I have enabled total size for directories in the details view. Here is how to reproduce the bug: I have two dirs, one saved into another (nested), like innerDir contained into outerDir. In innerDir there are some files. I go to outerDir and cut (ctrl-x) the innerDir. Then I go in another dir and I paste the dir (ctrl-v). The bug is that the outerDir size is not updated. Even if I hit refresh the dir has the wrong size. To see the right size I have to change dir and then go back.
3) I see some strange behaviour regarding auto refresh: after file operations (like copy) sometime the detail view is auto refreshed, but often it isn't. (in Windows Explorer auto refresh always work). Can you fix it? (I like auto refresh, but maybe making it optional is better for other people).

thank you for this great program!

**Comment by tablacus** [comment]
(1)
Did you run Tablacus Explorer as administrator?
If you do, It is a Windows specifications.
It is not permitted to copy and paste from a normal applications(Explorer) to an elevated one(Tablacus Explorer) by UAC.

(2)
Okey, I'll adjust the refresh.
However, the total file size is heavy processing.
Therefore, automatic update is a future consideration.

(3)
Auto refresh works almost well here.
In fact, there is not the automatic update routine in Tablacus Explorer because Explorer control in Tablacus Explorer updates it automatically.
If you run Tablacus Explorer as administrator, a notice of update may be interfered with in UAC.

Best regards,

**Comment by jarodsteele** [comment]
Hello, Thanks for the fast reply.

Regarding (1) I'm running administrator (or a normal user added to the Administrators group) under windows7 x64 with UAC DISABLED, and under Windows 8.1 x64 with UAC enabled. I experience the bug under both of the OS. But I have to note that Q-DIR works: I'm able to copy a file from Desktop and paste into a Q-Dir window. So it seems it is possible to do, or am I missing something?

For point (2) I agree that it's possibily an heavy operation, maybe you can add an option so that  users with slower computers can disable it. For me I'd prefer to be always enabled, primarily as I want to use the total size as a sort of status of the operation: if I see the dir with the new total size updated correctly I know that the cut and paste operation was ok. If I see the wrong size... I have to check manually.

About point (3)... I don't know. For me it often doesn't refresh, but maybe it's some other problem on my PC.

**Comment by tablacus** [comment]
Hello,
(1)
Do you use the add-on of file operations? (Multi thread, Multi process, etc.)
Add-on "Multi process" had a problem.
If you used it, you should update it.
If that's still no good, would you tell me your information?
![info_en](https://cloud.githubusercontent.com/assets/5156977/6688842/d599299c-ccf9-11e4-9c0e-eee47fbffe9b.png)


(2)
I think I will handle this in the next version.

Best regards,

**Comment by jarodsteele** [comment]
Hello,
yes it works with the latest Multi Process plugin!
Thanks!

**Comment by tablacus** [comment]
How wonderful.
And, I handle the automatic update of the total file size in Tablacus Explorer 15.3.18.
Best regards,

**Comment by stefanocaselli** [comment]
Hi,
copy in Windows Explorer and paste in Tablacus doesn't work for me... tested under Windows 7 x64.
I'm using tablacus version 15.5.20

**Comment by tablacus** [comment]
I think that it is UIPI of specifications of Windows.
Don't you execute Tablacus Explorer in administrator privilege?

Best regards,

http://blogs.msdn.com/b/vishalsi/archive/2006/11/30/what-is-user-interface-privilege-isolation-uipi-on-vista.aspx
http://en.wikipedia.org/wiki/User_Interface_Privilege_Isolation

**Comment by stefanocaselli** [comment]
I read what a previous post said about QDir working, so I downloaded QDir
too, and then tried it:
it works correctly.
I also read about Multi Process addon: I too use this addon. I disabled
this addon and copy/paste works!
When I re-enable multi process it doesn't work again.
Then I removed Multi Process and added Multi Thread addon, and it works.
So I suspect it is a bug in Multi Process addon.


2015-05-25 16:52 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
Thank you.
I've adjusted it in Multi process 1.10.

**Comment by Zireael07** [comment]
Win 7 x64, Tablacus intermittently crashes. I suspect it's the folders with many image files... but I'm not sure.

**Comment by stefanocaselli** [comment]
Hi, I tested Multi Process 1.10, but:
1) it works when copy from tablacus and paste into explorer
2) doesn't work the inverse: copy from explorer and paste into tablacus (it
seems to do something, it shows the waiting mouse cursor for a second, but
it doesn't copy the file)


2015-05-26 15:37 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
I've adjusted it in Multi process 1.11.
Thank you.

**Comment by stefanocaselli** [comment]
yes, it works! thank you.


2015-05-28 16:36 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
My pleasure.
