### ISSUE TITLE
TE not showing built-in icons

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#327]
I upgraded to Win 10 Insider Preview Beta. TE is not displaying its icons in the toolbar or in the Add-ons menu. The toolbar is only displaying custom icons.  See enclosed screenshots.

<img width="270" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31006631/92801860-fe3e9100-f383-11ea-8e3a-9c777f4f8a39.png">

<img width="622" alt="Screenshot 2020-09-10 163009" src="https://user-images.githubusercontent.com/31006631/92801918-0a2a5300-f384-11ea-90c3-23fe5bf5c198.png">

**Comment by daVe55w** [comment]
Any solution?

**Comment by tablacus** [comment]
These icons has been deleted from ieframe.dll.

**Comment by daVe55w** [comment]
How do I fix that?
TE just updated to 20.9.17 and now the following error message pops up every minute.

<img width="312" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31006631/93492550-ed88a080-f8d8-11ea-9eab-57267eca57cb.png">

**Comment by duarteframos** [comment]
> These icons has been deleted from ieframe.dll.

I understand the standard icons shown by default on Tablacus toolbar are probably a "safe bet" for being omnipresent and bundled in every supported operating system, from XP to 10, but they are a remnant from other era.
Visually they look really dated, they have this ninties vibe that give Tablacus an aging and "out of date" XP era look.

Would you consider bundling some default icons with the downloaded setup?

Maybe include only a few essential ones to populate the toolbar and pre-installed addons only, to avoid bloating installer size too much.

If you are interested I wouldn't mind designing and contributing a few pictures to include in future releases. Maybe a nice flat style design to better match Windows 10 design.

**Comment by perplexityjeff** [comment]
The general look of the browser is very dated a little fresher look would go a long way. I do love the explorer in features and function tho.

**Comment by tablacus** [comment]
Anyway, if there is no icon, I tried to display the alternative Windows icon.
Please try to install Tablacus Explorer 20.9.18.

![image](https://user-images.githubusercontent.com/5156977/93604499-6a626a00-fa00-11ea-902d-87f7ba0c0638.png)

Regards,

**Comment by tablacus** [comment]
@duarteframos
Thank you for your input.
I think it's a good idea to include a standard icon.
I'm thinking of a way to replace the standard icon with an add-on at once.
I don't have an artistic mind, so this is helpful.
Thank you so much,

**Comment by tablacus** [comment]
@perplexityjeff 
Thank you,

**Comment by daVe55w** [comment]
The update to 20.9.18 did not solve the missing icon problem. Now, the remove icons are completely gone and other icons are missing elsewhere.

<img width="590" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31006631/93655026-01bec180-f9ef-11ea-9bfe-d0a9e9465491.png">


<img width="202" alt="Screenshot_2" src="https://user-images.githubusercontent.com/31006631/93655027-01bec180-f9ef-11ea-8cb0-fbab5cce7253.png">

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Exploer 20.9.19.
The delete icon has been changed to text.
I don't think it's possible to take any further action.
Please contact the Microsoft Feedback Hub to restore the ieframe.dll BITMAP resource (216,214,206,204).

![image](https://user-images.githubusercontent.com/5156977/93668865-85011580-faca-11ea-9647-c5dc2ba9d3e8.png)

Regards,

**Comment by daVe55w** [comment]
Thank you. The icons at the bottom of Add-ons are now appearing as well.  

<img width="618" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31006631/93669524-d8d81400-fa62-11ea-9945-e732f9f5857a.png">

**Comment by daVe55w** [comment]
Can you move the Delete option to the right, either in the middle column or to the right of Enabled? It's too close to the Details link and could be clicked by mistake.
