### ISSUE TITLE
Redesign Generic Settings Screens

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#329]
There seems to be a "generic" settings screen that gets reused a lot in options dialog of Tablacus
![SettingsScreen](https://user-images.githubusercontent.com/8735426/93950765-496d8200-fd3c-11ea-9f77-127c7d9acd2e.png)

The layout is a bit cryptic and it is often not clear what buttons do and especially where they belong to, or what field the actions relate to.

With the recent addition of [icon packs ](https://github.com/tablacus/TablacusExplorerIconPacks) i'd like to propose a new design for this generic settings screen using new icons provided by the pack and to make it easier understand.

The idea is to group buttons so it is clear what field they belong to. Icons make them more compact saving space, and tooltips can make clearer what they do.

![Mockup01](https://user-images.githubusercontent.com/8735426/93995412-e0602b80-fd88-11ea-8b6c-f8548e5c1723.png)

Bottom left buttons all pertain to the list entry management:_Add_, _Remove_, _Save_ (old _Replace_), move up and down, and the _Test_ button.

Fields are reordered for a clearer layout, and the buttons for _Portable_, _Select_, and _Browse_ now clearly show what field they belong to.

These all use icons already in the new default icon packs light and dark.
What do you think @tablacus

**Comment by ccfs** [comment]
- After a user chooses "Type", he/she must enter a relevant "Options". Therefore "Options" should be immediately next to "Type".
- The current design is to let user enter a record, THEN either "Add" it as a new record or "Replace" a currently selected record, THEN (if finished) click "OK" button to SAVE and close the window. Therefore the buttons should be below the list, not at the top.

Regards,

**Comment by duarteframos** [comment]
Hi ccfs hanks for the feedback, I've adjusted the layout. Think it is better?

![Mockup01](https://user-images.githubusercontent.com/8735426/93995345-cc1c2e80-fd88-11ea-91f5-acbac688502e.png)

**Comment by tablacus** [comment]
I'm working on the Tablacus Explorer Blink project.
I want to focus on that for the time being.

https://github.com/tablacus/TablacusExplorerWebView2/issues/1

Regards,

**Comment by duarteframos** [comment]
Fair enough, that sounds like a lot of work on its own.
Feel free to reopen this issue if you ever want to revisit this some time in the future.
Poke me if you need any more icons for this
