### ISSUE TITLE
Remember folder view settings

### ISSUE THREAD

**Issue by Markreif** [tablacus/TablacusExplorer#33]
It doesn't work as expected. Every time I restart the application, I have to "group by" the files again. It does work well with folder size and "sort by", but it cannot remember the "group by" instructions.

**Comment by tablacus** [comment]
I've supported it in Remember 1.17
You should update it now.
Best regards,

**Comment by Markreif** [comment]
It is really better now, but it is strange. Even if I group it in a way that "today" will be the first series and "long time ago", when I restart it, the "today" series will be the last. As to the folders in alphabetical order, they seem to work perfectly to me.

Thanks a lot.

**Comment by tablacus** [comment]
My pleasure.
It seems to be related to a sort.
I will try to check up on that.

**Comment by Markreif** [comment]
Any ETA? I intend to replace Windows Double Explorer by Tablacus.

**Comment by tablacus** [comment]
I will adjust this in the next version of Tablacus Explorer.
Best regards,

**Comment by Markreif** [comment]
The last version is indeed impeccable. 
Tablacus is simply the best explorer available.

Thanks a lot.

**Comment by tablacus** [comment]
My pleasure.
Thank you.

**Comment by Markreif** [comment]
Everything was going fine but suddenly the "remember folder settings" instruction does not work any longer. I even downloaded the program again, in another folder, but the problem remains. Each time I leave that folder, when I return Tablacus does not remember the previously defined settings. Where am I going wrong?

**Comment by tablacus** [comment]
Would you tell me your information?
Would you tell me your using add-ons?
Add-on "Remenber" and "Folder setings" will conflict.
![1](https://cloud.githubusercontent.com/assets/5156977/10411381/42fff51e-6f9e-11e5-8a0d-281e0120121f.png)
Open the option of Remember
![2](https://cloud.githubusercontent.com/assets/5156977/10411382/51e99d96-6f9e-11e5-83ac-d195e01534f9.png)
Would you check the Folders.
![3](https://cloud.githubusercontent.com/assets/5156977/10411383/66616ba0-6f9e-11e5-903c-baaa67626dbf.png)
"Folders" is the number of folders you want to save.


# Location of the Remember settings.
Help -> config
![11](https://cloud.githubusercontent.com/assets/5156977/10411384/7605824e-6f9e-11e5-8ac1-2ef91a5fb50d.png)
Open the remeber.xml
![12](https://cloud.githubusercontent.com/assets/5156977/10411386/82b780be-6f9e-11e5-81df-3d4d8b6f3123.png)
Please confirm whether path is exists.
![13](https://cloud.githubusercontent.com/assets/5156977/10411387/9c6d597a-6f9e-11e5-8eac-f4b176d8388b.png)
# Initialization of the Remember setting
Backup "remember.xml".
And finish Tablacus Explorer, and delete "remember.xml".

Thank you.

**Comment by Markreif** [comment]
Yes! It worked. 
Initially, I "Folder Settings", with no results (It had never caused problems before, anyway).
Then I deleted "remember.xml" and also deactivated "Address Bar" (actually, I don't remember when I installed that add-on, even because I do not use it).

I use Windows 7, in Brazilian Portuguese.
![te01](https://cloud.githubusercontent.com/assets/11520705/10411649/e21585d0-6f42-11e5-8ffa-8bf217655dde.JPG)
![te02](https://cloud.githubusercontent.com/assets/11520705/10411651/ec2f3930-6f42-11e5-9ab8-966e1a0a6f3c.JPG)
![te03](https://cloud.githubusercontent.com/assets/11520705/10411653/f2081d5e-6f42-11e5-9973-6e05347c7a92.JPG)

**Comment by Markreif** [comment]
Thanks a lot.

Sérgio Roberto

**Comment by tablacus** [comment]
It's my pleasure.

**Comment by Markreif** [comment]
I must be doing something wrong. Remember Folder Settings has stopped working a long time ago. I even formatted my PC and reinstalled everything, but the program does NOT remember anything at all.

Right now, my installed add-ons are: Mouse, Key, Address Bar, Filter Bar, Back, Forward, Up,  Tree View, Tool Bar, Main Menu, Title Bar, Tabs, Find Files, Remember Folder Settings, Inner Refresh, Inner Up, Inner Back, Inner Forward, Empty Recycle Bin, Add to Favorites, and Horizontal Favorites. I do not believe the cause is a add-on conflict, anyway. Have you got any idea?

**Comment by tablacus** [comment]
Anyway, check the saved file.
![2](https://cloud.githubusercontent.com/assets/5156977/18608288/51fcde34-7d20-11e6-94f1-09539f33a58a.png)
Help(H)->Config
![3](https://cloud.githubusercontent.com/assets/5156977/18608300/93a48c88-7d20-11e6-81b0-cd788f165499.png)
Saved file is "remember.xml".

**Comment by Markreif** [comment]
I even deleted **remember.xml** and thus the system created a new one. The result remains the same.

**Comment by tablacus** [comment]
Please disable an add-on "Remember folder view settings" and Install an add-on "Take over folder view settings".
Is it working?

**Comment by tablacus** [comment]
Or do you try the following steps.
Remember Folder -> Options -> Path -> Ok
![13](https://cloud.githubusercontent.com/assets/5156977/18615453/66fcff68-7de2-11e6-8d04-f7f6bcd5f8da.png)

**Comment by Markreif** [comment]
No. I tried both suggestions with no success.
My idea was to group the files by date.
It is strange because it used to work, and suddenly…

2016-09-18 8:57 GMT-03:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
I've adjusted it on Remember 1.24.
Please update an add-on.
Best regards,

**Comment by Markreif** [comment]
Great! Thanks a lot.

2016-09-19 10:40 GMT-03:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
My pleasure.
