### ISSUE TITLE
Option to disable click to rename

### ISSUE THREAD

**Issue by char101** [tablacus/TablacusExplorer#330]
Hi,

Is there a way to prevent the rename operation from triggering when clicking on the highlighted/selected file on the list? Personally I never use that function thus it become an annoyance when clicking on the active item triggers the rename input.

**Comment by tablacus** [comment]
How about an add-on "No edit labels"?

Regards,

**Comment by char101** [comment]
Thank you, that's exactly it. With the addon having no description, I don't exactly get what "no edit labels" mean. Maybe "no click rename" or "no slow rename" would express the addon better.

**Comment by duarteframos** [comment]
I tried improving the description at https://github.com/tablacus/TablacusExplorerAddons/pull/203
