### ISSUE TITLE
Script Error on "Open containing folder"

### ISSUE THREAD

**Issue by craigalan** [tablacus/TablacusExplorer#339]
Hello!  Since the last couple of versions, I get a script error when right clicking a file (only from within a tab that was opened from a search done with the Everything Search add-in) and choose "Open the folder that contains this item"

I have attached the error and a screen capture as well.
[Video_2020-10-23_140129.zip](https://github.com/tablacus/TablacusExplorer/files/5431088/Video_2020-10-23_140129.zip)

**Comment by tablacus** [comment]
Please try to install Tablacus Explorer 20.10.23.

https://github.com/tablacus/TablacusExplorer/releases/tag/20.10.23

Regards,

**Comment by craigalan** [comment]
It's been sooo long since I updated with the zip, I usually use the update feature within the program.  Can you remind me how to update without loosing all of my settings?

**Comment by tablacus** [comment]
Recently, I have released Tablacus Explorer in Early access version (Pre-release) once.
Automatic updates are limited to the official release version.
If you have a problem, please check the distribution page.

Regards,

**Comment by craigalan** [comment]
The update resolved the issues.  Thank you.
