### ISSUE TITLE
bug: tab relating to path non available

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#34]
Hi,
found a problem with tabs showing a path that is not existent anymore (like a pendrive that is removed). This can happen when I open a tab on a pendrive, then close tablacus (it saves the tab path) and then I remove the pendrive. Next time I open tablacus there is a tab with the "invalid" path.
In this situation I double clicked on the empty space in the list view of such a tab and got this error:
![errore double click empty area in tab senza path](https://cloud.githubusercontent.com/assets/10347571/6730341/ece53f30-ce3b-11e4-922c-ad956075a1d0.PNG)
I saw this error several times, then all the tabs vanished, but the views were still working. 
Then I tried closing tablacus window and I got this other error:
![2](https://cloud.githubusercontent.com/assets/10347571/6730392/7f3964b0-ce3c-11e4-96ef-e0f1b93583fc.PNG).
Maybe on startup you can automatically close these "invalid" tabs, or perhaps just redirect to the "default" view of tabs,  like as an example to My Computer).
Thanks you.

**Comment by tablacus** [comment]
Hi,
I confirmed a problem too.
I will adjust it in the next version.
Best regards,

**Comment by tablacus** [comment]
I've adjusted this in Tablacus Explorer 15.3.22
Best regards,

**Comment by stefanocaselli** [comment]
thanks!


2015-03-22 15:06 GMT+01:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
My pleasure.
