### ISSUE TITLE
TE Script Error and  64 bit TE Crashes

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#341]
In the latest version of TE, the following error occurs when right-clicking in any tab.

<img width="330" alt="script editor error" src="https://user-images.githubusercontent.com/31006631/97779756-a5ef6880-1b56-11eb-8173-92fdd9523400.png">

Also, TE crashes when running the 64 bit version.

**Comment by tablacus** [comment]
I have not encountered them.
I need more information.
Regards,

**Comment by daVe55w** [comment]
It happens when right-clicking in every tab. 
I have TE32.exe and TE64.exe whitelisted in Webroot SecureAnywhere. I have been using that antivirus programs for years and today is the first time encountering this problem with TE.

TE32 20.10.30 Windows 10 Enterprise 2004 (10.0.20246) Wow64 Admin IE11 en_us 144 System Shield Webroot SecureAnywhere Windows Defender Webroot SecureAnywhere Webroot SecureAnywhere

mouse,key,addressbar,filterbar,back,forward,up,treeview,toolbar,mainmenu,titlebar,tabplus,multithread,undoclosetab,extract,download,thumbplus,tabcolor,autobackup,systemfolders,countbar,addonsupdater,sizestatus,everything,wcx,wfx,controlpanelbutton,forcerefresh,closebutton,properties,restart,refresh,emptyrecyclebin,fastcopy,font,tabname,notepadalternative,maximizebutton,thumbnailengine,mainmenubutton,mixedsort,startup,dragdrop,minimizebutton,paste,delete,newtab,copy,cut,checkbox,autoupdate,fullpathbar,opencpinexp,grabbutton,tabdesign,takeoverfoldersettings,sethome,gohome,tabgroups,previewwindow,runatsetup

**Comment by daVe55w** [comment]
Also, TE64 will not update to 20.10.30 from 20.10.29. TE32 updated successfully.
How can I manually update TE64 without changing settings and add-ons?

**Comment by tablacus** [comment]
What happens in the case of Tablacus Explorer 20.9.3?

https://github.com/tablacus/TablacusExplorer/releases/download/20.9.3/te200903.zip

**Comment by daVe55w** [comment]
How to manually install without affecting settings and add-ins?

**Comment by tablacus** [comment]
Would you try the older version above?

Regards,

**Comment by daVe55w** [comment]
The same issue occurs with TE 20.9.3
With the current version, the scripts error is again popping up often.

**Comment by tablacus** [comment]
The same issue occurs with TE 20.9.3, I think there may be something wrong with your system.

Try last year's version and if it doesn't work, there's nothing I can do about it.

https://github.com/tablacus/TablacusExplorer/releases/download/19.12.22/te191222.zip

Regards,

**Comment by daVe55w** [comment]
I am using Win 10 Pro Insider Edition v2004 (OS Build 20251.1). It's probably that, which likely means TE will have the same problem when that OS is released.

**Comment by tablacus** [comment]
I have not encountered it inTE32 20.11.6 Windows 10 Enterprise 2004 (10.0.20251)

![image](https://user-images.githubusercontent.com/5156977/98440583-e9d90380-213c-11eb-99d9-7a88aa8498c3.png)

Regards,

**Comment by daVe55w** [comment]
So far, after updating to 20.11.6 and using TE64, the problem has not reoccurred.
