### ISSUE TITLE
addon Folder list menu does not work anymore

### ISSUE THREAD

**Issue by herbrot** [tablacus/TablacusExplorer#343]
In version 20.10.30 addon "folder list menu" shows up following error:
![grafik](https://user-images.githubusercontent.com/28577466/98130334-7031e300-1eba-11eb-8704-98fd3c45c0b7.png)

It works in version 10.20.9

**Comment by tablacus** [comment]
I have adjusted it in Folder list menu version 1.12
Please try to install it.

Regards,

**Comment by herbrot** [comment]
Just tested with versions 20.11.3 and 20.10.30 works very well.
Thank you for the quick response and your wonderful work.

Kind Regards
