### ISSUE TITLE
Portuguese language

### ISSUE THREAD

**Issue by Markreif** [tablacus/TablacusExplorer#35]
I am trying a translation into (Brazilian) Portuguese.
There are some words that I would like you to clarify the meaning:
Init
EnumFlags
Expandos
Spring expand

Thanks in advance.

**Comment by tablacus** [comment]
I look forward to that a lot.
I want to distribute your (Brazilian) Portuguese language file in my website.

I will explain simply.

**"Init"**
Initialization

"Init" is an abbreviated form of the initialization.

**"EnumFlags"**
Enumeration Flags

grfEnumFlags in [INameSpaceTreeControl::AppendRoot method](https://msdn.microsoft.com/en-us/library/windows/desktop/bb761620%28v=vs.85%29.aspx)

>Enumerates the qualities of the root and all of its children. One or more of the values of type SHCONTF. These flags can be combined using a bitwise OR.

**"Expandos"**
NSTCS_HAS**EXPANDOS** in [NSTCSTYLE enumeration](https://msdn.microsoft.com/ja-jp/library/windows/apps/xaml/dd378458.aspx)

>The control displays a triangle—known as an expando—on the leftmost edge of those items that have child items. Clicking on the expando expands the item to reveal the children of the item. Has no effect when combined with NSTCS_SHOWTABSBUTTON, NSTCS_SHOWDELETEBUTTON, or NSTCS_SHOWREFRESHBUTTON.

*I think this is "Show buttons".*

**"Spring expand"**

NSTCS_**SPRINGEXPAND** in [NSTCSTYLE enumeration](https://msdn.microsoft.com/ja-jp/library/windows/apps/xaml/dd378458.aspx)

>When one item is selected and expanded and you select a second item, the first selection automatically collapses. 

Best regards,

**Comment by Markreif** [comment]
Thanks for your answer.
It is finished:
http://www.4shared.com/document/fXW5WTykba/ptbr.html

It seems to work well to me.

**Comment by tablacus** [comment]
Thank you so much.
I downloaded it.
May I enclose it to a Tablacus Explorer?
And, would I change the file name to pt.xml?
To use it by default in Portuguese windows.

Best regards,

**Comment by Markreif** [comment]
Certainly. I feel honoured.

[?]
And the file name is no problem at all.

Regards
Sérgio Roberto

2015-03-25 12:57 GMT-03:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
Ok, I've distributed your (Brazilian) Portuguese language file in my website.
I'll enclose it to a next version of Tablacus Explorer.

Thank you.
