### ISSUE TITLE
Breadcrumbs address bar (1.53) & middle click

### ISSUE THREAD

**Issue by janbatist** [tablacus/TablacusExplorer#352]
Hello,

I used to open new tabs by middle clicking folders in the breadcrumbs address bar.
Nowadays, doing so doesn't open a new tab but instead select the full path.

When I click (left click) in the address bar but not on any folder, the full path gets selected as well (perfectly fine) and a click anywhere else than the address bar gets the breadcrumbs back. When using the middle click though, the address bar stays in XP style as long as I don't click again in the address bar and then click anywhere else. I'm just mentioning that in case it helps pinpoint what the problem is.

Help\About:
Tablacus Explorer 20.12.5 Gabu (64 bits)
C:\Program Files (x86)\Tablacus\TE64.exe (20.12.4.0)
C:\Users<user name>\AppData\Roaming\Tablacus\Explorer\config
Information: `TE64 20.12.5 Windows 8.1 (6.3.9600) IE/11 JS/11.0.19699 fr_fr 96 Windows Defender`
Add-ons: `mouse 1.28,key 1.22,addressbar 1.53,mainmenu 1.14,titlebar 1.07,tabs 1.23,sidetreeview 1.22,filterlist 1.04,tabplus 1.70,findfiles 1.15,clipboardhistory 1.04,history 1.14,split 1.16,usercss 1.06,undoclosetab 1.11,tabposition 1.08,foldersettings 1.31,remember 1.39,searchbar 1.06,sizestatus 1.13,shellexecutehook 1.09,addonsupdater 1.06,countbar 1.09,tabgroups 1.35,autoupdate 1.02,autobackup 1.02`

Thanks

P.-S.: I wasn't sure, please tell me if I should have posted this in https://github.com/tablacus/TablacusExplorerAddons/issues instead

**Comment by tablacus** [comment]
I have adjusted it in Address bar 1.54.
Please try to install.

Regards,

**Comment by janbatist** [comment]
Thank you!
