### ISSUE TITLE
Script Error on Drag/Drop with Latest Version

### ISSUE THREAD

**Issue by craigalan** [tablacus/TablacusExplorer#357]
With the latest release, when dragging and dropping,  the follow script error is produced.

Copy/Paste & Cut/Paste seem to work fine, it's just drag/drop

![445](https://user-images.githubusercontent.com/17946784/102785205-911b9e00-436b-11eb-8df2-6cd41d7745ce.jpg)

**Comment by tablacus** [comment]
Please try to install Tablacus Explorer 20.12.21.

https://github.com/tablacus/TablacusExplorer/releases/tag/20.12.21

Regards,

**Comment by craigalan** [comment]
Appears to be resolved. Thank you!

**Comment by craigalan** [comment]
Appears to be resolved. Thank you!
