### ISSUE TITLE
ダブグループの読み込みと保存でスクリプトエラー

### ISSUE THREAD

**Issue by tenteke12** [tablacus/TablacusExplorer#358]
かなり前からなのですが、ダブグループの読み込みと保存でスクリプトエラーが発生します。
現時点での最新バージョン 20.12.21 (64ビット) で表示されたメッセージを添付します。

![読み込み](https://user-images.githubusercontent.com/76507885/102961671-4430f680-4528-11eb-8923-054721fd3a6e.jpg)
![保存](https://user-images.githubusercontent.com/76507885/102961675-45faba00-4528-11eb-86ee-54e53de46749.jpg)

よろしくお願いいたします。

**Comment by tablacus** [comment]
投稿の少し前に更新の「タブグループ 1.36」で調整されていると思います。
試してみてください。

※ここは多くの国の方が使われているので、タイトルだけは英語に変更していただけると幸いです。
本文の方は日本語でOKです。

**Comment by tenteke12** [comment]
ありがとうございます。なおりました。
タイトルの英語表記の件、承知いたしました。
