### ISSUE TITLE
Supprt some form of relative paths in Tab Groups

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#362]
Are any form or relative paths currently supported in Tab Groups addon?

I've been using Tablacus portably on a thumb drive, and I'm trying to set up some pre configured tab groups from common tasks.
Drive letters change so I was trying to use some form of relative path manually in the XML layout files, that would grantee it will work on different computers, regardless of assigned letter.

I've tried the obvious `..\`, `.\` or using variables like `%X-Finder%` or `%Installed%` without success.
Tablacus always seems to point the base path to `C:\Users\Current User\Desktop\` and map relative paths from there like `C:\Users\Current User\Desktop\%X-Finder%` or `C:\Users\Current User\Desktop\%Installed%`.

Are there any workarounds? Would it be possible to allow parsing those from the address bar correctly from `TE64.exe` folder or at least from `%Installed%` ?

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 21.1.24.
Please try to install it.
https://github.com/tablacus/TablacusExplorer/releases/tag/21.1.24

Regards,

**Comment by duarteframos** [comment]
Seems to be working as well with `...\` dot based notation in the linked version. Pretty awesome, many thanks.

Justo one question, are these new versions already WebView2 based yet, or Blink engine reserved exclusively for the other specific repository?

**Comment by tablacus** [comment]
The new version works with Blink engine when used with Tablacus Explorer WebView2.

https://tablacus.github.io/tewv2.html
https://github.com/tablacus/TablacusExplorerWebView2

Regards,

**Comment by duarteframos** [comment]
Ah so it is implemented as an addon then. Quite nice. Wasn't aware of that. Thanks for the info

**Comment by duarteframos** [comment]
@tablacus Is it possible to do the same for the [Label addon](https://github.com/tablacus/TablacusExplorerAddons/wiki/label)?
Can some form of relative path or perhaps instead some form of wildcards be supported in `label.tsv`?
You can right click a file with labels and click _Path_ to adjust the stored path. I tried manually changing it to use `*` for wildcards like say `*:\Users\Documents` but it didn't seem to work.

Would it be possible to support wildcards in `label.tsv`, just like you can for other addons like say [Folder Settings](https://github.com/tablacus/TablacusExplorerAddons/wiki/foldersettings)?
