### ISSUE TITLE
[Feature Request] Sync Browse / Sync Scroll

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#363]
XYPlorer has a feature where you can sync browse/sync scroll two similar folder structures as [described in the forum](https://www.xyplorer.com/xyfc/viewtopic.php?f=3&t=8725).

When you have two panes open simultaneously pointing to two different paths with similar folder structures (say two mirrored drives, or two synced folder structures), it basically tries to keep navigation in sync between the two panes.

If you scroll tab A it scrolls to the folder with the same name in tab B, if you enter a folder named "Documents" in tab B, it tries to do so in tab A as well, if a folder with the same name is found.

Is there any similar feature in Tablacus? Searching through the addons nothing seems to indicate that.
Would this be too much trouble to implement?

### X-Finder Addon Documentation

On another note, an unrelated request: Where can I find documentation about the X-Finder addon?
There doesn't seem to be any entry in the wiki, and I'd like to know more about the features found in the addon menu and what they do.

I'm talking about this list specifically, what does each entry do and how do you use it.
![XFinder](https://user-images.githubusercontent.com/8735426/105985880-075e9f00-6094-11eb-84c7-6bdffa440dc8.jpg)

If you could give a quick rundown on each entry, I'd love to contribute it to the wiki, so everyone else can benefit from it.

**Comment by tablacus** [comment]
I will consider synchro browsing.

X-Finder is a file management software I created earlier.
X-Finder add-on allows you to use the built-in commands of X-Finder.
X-Finder's instructions are in Japanese only. 

https://www.eonet.ne.jp/~gakana/xf.html

Regards,

**Comment by duarteframos** [comment]
> I will consider synchro browsing.

Splendid  looking forward to it, many thanks.

> X-Finder is a file management software I created earlier.
> X-Finder add-on allows you to use the built-in commands of X-Finder.
> X-Finder's instructions are in Japanese only.
> https://www.eonet.ne.jp/~gakana/xf.html

Well I don't know any Japanese, but luckily google does, so with the help of Google Translate I think I can cobble it up to at least create a stub page.

Will work on it as time permits. I can already see some convenient functions there, many thanks for the pointer

**Comment by duarteframos** [comment]
I've created a first draft, feel free to correct me if I add anything incorrect.

https://github.com/tablacus/TablacusExplorerAddons/wiki/xfinder

Will add more later

**Comment by tablacus** [comment]
Thank you for adding wiki!

**Comment by bob362181** [comment]
I have been using XYplorer for a very long time. I discovered Tablacus a few days ago. I like it a lot. I t would be nice  to have the sync browse/sync scroll option.

Thank you very much

**Comment by tablacus** [comment]
Please try to install an add-on "Synchronize browsing".

Regards,

**Comment by duarteframos** [comment]
This works great, fantastic work! Many thanks for the new feature, this will be insanely useful for checking backups.
Only one remark, you misspelled "Synchronize" in the addon name, it reads "Synch**o**ronize".

**Comment by duarteframos** [comment]
In the meantime I have made a few custom icons for several addons I have installed and features I make use of.
I'll share them here if you want to use them or include them in your addons by default; they match with the light theme icon pack I have made earlier.

![Tablacus_Home_48](https://user-images.githubusercontent.com/8735426/109399960-e660c680-793d-11eb-9d3e-590f409c1573.png) - Navigate Home Addon
![Tablacus_FolderView_48](https://user-images.githubusercontent.com/8735426/109399958-e5c83000-793d-11eb-9930-5a206d491f4c.png) - Folder Settings Addon
![Tablacus_Flat_48](https://user-images.githubusercontent.com/8735426/109399956-e5c83000-793d-11eb-9c10-630095292ecf.png) -  Flat View Addon
![Tablacus_SyncBrowse_48](https://user-images.githubusercontent.com/8735426/109399954-e52f9980-793d-11eb-842f-1b40595b4979.png) - Sync Browse Addon
![Tablacus_OpenPane_48](https://user-images.githubusercontent.com/8735426/109399953-e4970300-793d-11eb-8259-05fbab6ed40b.png) - Open in other pane
![Tablacus_Hidden_48](https://user-images.githubusercontent.com/8735426/109399959-e660c680-793d-11eb-8b5e-40f5dcda307b.png) - Toggle Hidden Filter (list filter feature)
![Tablacus_Copy_48](https://user-images.githubusercontent.com/8735426/109399955-e52f9980-793d-11eb-8b44-256f10be2e3a.png) - Generic Copy
![Tablacus_Folders_48](https://user-images.githubusercontent.com/8735426/109399957-e5c83000-793d-11eb-9681-4d2b92218b2f.png) - Generic Folder

If you need them in different sizes or if you want them in .ico format feel free to ask,

This is how they look in my current setup
![20210227_210257](https://user-images.githubusercontent.com/8735426/109400202-3c823980-793f-11eb-95d6-135847c22c09.png)

**Comment by bob362181** [comment]
How do you program your Sync Browse Addon to toggle synchronization?

**Comment by duarteframos** [comment]
> How do you program your "Sync Browse Addon" button to toggle synchronization on/off?

That is the default behavior, after installation there is a new button added to the toolbar that toggles sync browse on or off

**Comment by bob362181** [comment]
Mine did not installed automatically, but I found the button in the plugin folder, so I installed it manualy. Everything work nice now!

Thank you for your help

Bob

**Comment by tablacus** [comment]
@duarteframos  thank you for pointing out typo.

I want you to put those icons in the icon packs.

In Synchronize 1.01, if icons/misc/synchronize.png exists, it will be displayed in preference to synchronize.png in the add-on folder. 

**icons/misc/synchronize.png**

![image](https://user-images.githubusercontent.com/5156977/109421522-0fa35480-7a1b-11eb-8309-56902fd109ab.png)

Regards,

**Comment by tablacus** [comment]
@bob362181 

If you want the synchronization to start on startup, check Tools -> Add-ons -> Synchronization -> Enabled. 

![image](https://user-images.githubusercontent.com/5156977/109421896-93aa0c00-7a1c-11eb-9259-1a0dffa01228.png)

Regards,

**Comment by duarteframos** [comment]
> @duarteframos 
> I want you to put those icons in the icon packs.

I've created a pull request at https://github.com/duarteframos/TablacusExplorerIconPacks/pull/8
If anything is missing let me know.

Thanks again

**Comment by tablacus** [comment]
OK,

**Comment by tablacus** [comment]
OK, please make a pull request here.
https://github.com/tablacus/TablacusExplorerIconPacks/pulls

Regards,

**Comment by duarteframos** [comment]
Ops sorry, done there

**Comment by tablacus** [comment]
Please update config.json.
Regards,

**Comment by duarteframos** [comment]
> Please update config.json.
> Regards,

Updated, also added icons for the dark theme and light theme
