### ISSUE TITLE
Script Error when expanding breadcrumb of "This PC"

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#364]
I've tested this on two different computers at home and work on Tablacus 21.1.24 and it happens on both consistently

I use two panes with inner breadcrumb addon, and whenever I click the little `>` sign to expand the breadcrumb ahead of This Computer I get a Script Error message consistently

![Tablacus_Error](https://user-images.githubusercontent.com/8735426/106013905-d80c5a00-60b4-11eb-81d4-94d30f1ae037.gif)

It only happens once per Tablacus Session, if I click it I get the error, then it becomes disabled until I navigate away or change the breadcrumb address. After navigating it becomes available, and if I close and reopen TE the error happens again.

The error states it is line 633 char 2 but doesn't give much more information. Is there a log somewhere I can get to help you narrow this down?

`TE64 21.1.24 Windows 10 Pro 2004 (10.0.19041) IE/11 JS/11.0.16384 en_us 96 Windows Defender ESET Security ESET Endpoint Antivirus`

`mouse 1.29,key 1.23,titlebar 1.07,mainmenu 1.14,toolbar 1.36,favoritesbar 1.40,foldersettings 1.31,tabplus 1.74,multithread 1.24,undoclosetab 1.12,addonsupdater 1.09,flat 1.16,wildcardselect 1.05,innerbreadcrumbsaddressbar 1.38,innerfilterbar 1.28,switchhiddenfilter 1.01,sizestatus 1.18,switchhidden 1.03,archiveimage 1.04,tabgroups 1.36,tabname 1.07,multiprocess 1.27,sethome 1.02,gohome 1.02,tabposition 1.08,sidetreeview 1.22,clipboardimage 1.01,checkbox 1.12,protecttabs 1.04,innerback 1.11,innerforward 1.13,innerup 1.07,innerrefresh 1.03,tooltippreview 1.19,xfinder 1.28,folderlistmenu 1.14,searchbar 1.07`

**Comment by tablacus** [comment]
I can't encountered it yet.
What happens if I download and unzip the following ZIP and replace it with ui.js in the script folder? 
 
[ui.zip](https://github.com/tablacus/TablacusExplorer/files/5887208/ui.zip)

Regards,

**Comment by duarteframos** [comment]
> What happens if you download and unzip the following ZIP and replace it with ui.js in the script folder?
> [ui.zip](https://github.com/tablacus/TablacusExplorer/files/5887208/ui.zip)

This seems to solve the issue indeed.

Made a copy of the installation so I could test both, with this new ui.js I no longer get the error, while I can consistently recreate with the original.

Thanks for the fix

**Comment by duarteframos** [comment]
By the way.
How can I create a keyboard shortcut to duplicate the current tab to the other pane?

Say I'm navigating `C:\users\Me\My Documents` and I want to create a new tab in the other pane pointing the the same folder `C:\users\Me\My Documents`. What Javascript should I use to achieve this?

**Comment by tablacus** [comment]
Please install an add-on "Switch to next pane" and use the following script. 

Type
`Jscript`

Options
```
Sync.SwitchPane.NextFV().Navigate(GetFolderView(), SBSP_NEWBROWSER);
```

![image](https://user-images.githubusercontent.com/5156977/106145391-d6c45580-61b8-11eb-8833-9153f91c0c5c.png)

Regards,

**Comment by duarteframos** [comment]
> Please install an add-on "Switch to next pane" and use the following script.
> 
> Type
> `Jscript`
> 
> Options
> 
> ```
> Sync.SwitchPane.NextFV().Navigate(GetFolderView(), SBSP_NEWBROWSER);
> ```

That is perfect, works like a charm, awesome. :)
Adding documentation to the Wiki for posterity. Many Tanks
