### ISSUE TITLE
What could cause drag and drop from EssentailPIM to Tablacus to fail?

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#366]
I'm trying to use the email client [Essential PIM](https://www.essentialpim.com) (free version [available for download](https://www.essentialpim.com/get-epim)) to drag and drop an email message in .eml format from the application directly into Tablacus.

It works well for Windows explorer but always fails for TE. The message is temporarily saved into a temp folder under `EssentialPIM\Temp` and then moved to the desired destination.

When I drag into windows explorer I can see the file being created and moved correctly, but when I drag into Tablacu, the file is briefly created as normal, but then prematurely erased before the move process is completed.
I then get an error box saying the file can no longer be found which is actually true).

Is this something that can be fixed on Tablacus end, or is it actually an issue with EssentialPIM?

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 21.1.30.

https://github.com/tablacus/TablacusExplorer/releases/tag/21.1.30

If that doesn't work, Please try to stop the add-ons "Multi thread" and "Multi process".

Regards,

**Comment by duarteframos** [comment]
The 21.1.30 version still showed the same issue, but Disabling the _Multi Thread_ addon did fix the issue.
Too bad we have to disable  _Multi Thread_, but thanks for the solution, seems to be working.

**Comment by tablacus** [comment]
OK, please turn off "Temporary Burn Folder" in "Multi thread".

![image](https://user-images.githubusercontent.com/5156977/106369823-e9e14c00-6397-11eb-81dc-f3362932df7c.png)

Regards,

**Comment by duarteframos** [comment]
> OK, please turn off "Temporary Burn Folder" in "Multi thread".

Sadly doesn't seem to work, I still get the missing file error, only fully disabling the _Multithread_ addon seems  to fix the issue.
Don't worry about it too much, I can live without _Multithread_. Thanks for trying to help


# Unrelated questions

I've been looking at several of your posts around here and trying to adapt the scripts, but my I am not versed enough in Javascript to modify them

## 1 Copy all selected items name to clipboard

I'm trying to change the following code to copy just the names with extensions of all selected items without path
```
var FV = GetFolderView(Ctrl, pt);
var Selected = FV.SelectedItems();
if (Selected) {
	clipboardData.setData("text", Selected.Name);
}

```
Obviously I'm missing some `for` loop here, but I'm not sure how to go about doing it.

## 2 Script to navigate to different drive letters in other pane

I often navigate similar folder structures in different drives. How can I write a script to open a new tab in the other pane for the same folder in some other drive?

Say I'm currently navigating `D:\User\Documents`. What I'd like the script to do is to open a new tab in the other pane for say `F:\User\Documents` or if I'm currently at `G:\Files\Projects` it would open a new tab on the other pane for `X:\Files\Projects`.

The drive letter can be hardcoded in the script, I'll change it as necessary.

## 3 Script to pass single file name to 7Zip, otherwise pass current path.

I already set up a context menu for portable 7Zip to add selected items to a new archive files as [described here](https://stackoverflow.com/questions/21069846)

`%X-Finder%\7Zip\7zG.exe a "%Current%\%FocusedName%" %Selected% -ad`

It works well but I'm trying to improve the passed archive name to replicate the default behavior.
What I'd like to achieve is if only one item is selected pass the selected item name, otherwise if multiple are selected, pass the current folder name instead. Is this possible to achieve without breaking relative paths?

**Comment by tablacus** [comment]
I have downloaded EssentailPIM and install it.
Drag and drop from EssentailPIM to Tablacus Explorer(with add-on Multi-thread) is working without any problems.

**Comment by tablacus** [comment]
1 Copy all selected items name to clipboard

Please install an add-on "X-Finder" and use the following command. 

Type
`X-Finder`

Options
```
ClipPath:12
```
![image](https://user-images.githubusercontent.com/5156977/106383607-5bf27900-640a-11eb-8e1d-c75fd6ffdd86.png)

**Comment by tablacus** [comment]
### 2 Script to navigate to different drive letters(X:) in other pane

Type
`JScript`

Options
```
const FV = GetFolderView();
const path = FV.FolderItem.Path.replace(/^[A-Z]:(.*)/i, "X:$1");
Sync.SwitchPane.NextFV().Navigate(path, SBSP_NEWBROWSER);
```

**Comment by tablacus** [comment]
### 3 Script to pass single file name to 7Zip, otherwise pass current path.

You need to write it in a script.

**Comment by duarteframos** [comment]
> 
> 
> I have downloaded EssentailPIM and install it.
> Drag and drop from EssentailPIM to Tablacus Explorer(with add-on Multi-thread) is working without any problems.

Sadly I couldn't get it to work on my end. I tried with both _MultiProcess_ and _Multithread_ addon, disabling _Temporary Burn Folder_ and it doesn't work as long as any of the addons are enabled. Maybe it is because I'm using the portable version not fully installed, though I'm not sure that would make a difference.

I now tried disabling _Drag and Drop_ from Multi Process addon and it does work that may. Maybe I'll keep it like this, dont worry too much about it.

**Comment by duarteframos** [comment]
> ```
> ClipPath:12
> ```

> const FV = GetFolderView();
> const path = FV.FolderItem.Path.replace(/^[A-Z]:(.*)/i, "X:$1");
> Sync.SwitchPane.NextFV().Navigate(path, SBSP_NEWBROWSER);
> ```

These work great, I have Tablacus almost all set up as I want it.
Many thanks for the patience, in solving these, I'll add them to the wiki as well
