### ISSUE TITLE
Unable to change directory by changing the path

### ISSUE THREAD

**Issue by RedCrafterLP** [tablacus/TablacusExplorer#367]
I tried to navigate using the titlebar. I typed in an adress and the only thing I got was a context menu.
![1](https://user-images.githubusercontent.com/68075054/106384210-039b8700-63ca-11eb-9ebe-fc1924b38bd3.png)
![0](https://user-images.githubusercontent.com/68075054/106384211-04341d80-63ca-11eb-8b11-371cebcd5e8b.png)

**Comment by tablacus** [comment]
I haven't encountered it yet.
Did you customize the key settings?
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

Regards,

**Comment by RedCrafterLP** [comment]
mouse 1.29,key 1.23,addressbar 1.58,back 1.16,forward 1.16,up 1.17,toolbar 1.36,titlebar 1.07,tabplus 1.74,multithread 1.24,remember 1.39,runatsetup 1.01,multiprocess 1.27,everything 1.41,foldericon 1.03,multipleexecutions 1.04,preventduplicatetabs 1.14,addonsupdater 1.09,mainmenubutton 1.13

**Comment by RedCrafterLP** [comment]
TE64 21.1.28 Windows 10 Home 2009 (10.0.19042) IE/11 JS/11.0.16384 de_de 96 Windows Defender

**Comment by RedCrafterLP** [comment]
I pin pointed the error to my menus.xml, but couldn't find the error in it. (I tested with and without the xml config)

[menus.zip](https://github.com/tablacus/TablacusExplorer/files/5905715/menus.zip)

**Comment by RedCrafterLP** [comment]
I am shure is was an config error on my side, I'm closing the Issue now.
