### ISSUE TITLE
Long lag when dragging files/folders over not attached network drives

### ISSUE THREAD

**Issue by RedCrafterLP** [tablacus/TablacusExplorer#368]
When I drag files/folders over network drives on the left sidebar the dragged item gets stuck on the drive and Tablacus Explorer ist not responding for a few seconds. 
Then the dragged Item returns to the cursor. 
I believe that Tablacus Explorer is checking the Network drives availability when dragging over it.
![0](https://user-images.githubusercontent.com/68075054/106384501-7eb16d00-63cb-11eb-8b80-c6c98bfc307e.png)

**Comment by tablacus** [comment]
Let me know more information about add-ons you are using in the side bar.
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

Regards,

**Comment by RedCrafterLP** [comment]
![Unbenannt](https://user-images.githubusercontent.com/68075054/106488030-919f6c80-64b3-11eb-9723-cf81cbf28b5e.PNG)
That are the add-ons i'm using. 
The sidebar/foldertree is provided by the option: show frames

**Comment by RedCrafterLP** [comment]
The source of the bug is the shell itself. It's a Windows bug. It happens in open shell diaologs and explorer , too.
