### ISSUE TITLE
Support Filters or wildcards in labels.tsv

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#369]
Is it possible to support some form of wildcards filters for the [Label addon](https://github.com/tablacus/TablacusExplorerAddons/wiki/label)?
Perhaps some form of relative path or instead some form of wildcards be supported in `label.tsv`?
You can right click a file with labels and click _Path_ to adjust the stored path. I tried manually changing it to use `*` for wildcards like say `*:\Users\Documents` or `*Apps\Media\*` by opening directly in a text editor but it didn't seem to work.

Would it be possible to support wildcards or standard filter format available elsewhere in `label.tsv`, just like you can for other addons like say [Folder Settings](https://github.com/tablacus/TablacusExplorerAddons/wiki/foldersettings)?

**Comment by tablacus** [comment]
When it does, performance suffers. 

Regards,

**Comment by duarteframos** [comment]
> When it does, performance suffers.

Hum I see, it can get heavy with lots of entries.

What about relative paths, something like `..\Some\Path` or perhaps using `%X-Finder%\..\Some\Folder`?
Would those cause performance issues as well?

**Comment by ccfs** [comment]
For what purpose is this?

**Comment by duarteframos** [comment]
I use tablacus portably in my thumb drive, and I'd like to label a few folders in the same USB drive for sorting purposes, regardless of assigned drive letters.

I was hoping do this with either a wildcard for drive letter, a filter, or a relative path to TE64.exe 

If these are not possible I'll alternatively just add a few entries for common drive letters, but I'd like to avoid having to enter multiple entries for the same folders manually for every possible assigned path 

⁣

**Comment by ccfs** [comment]
I suggest to use a fixed drive letter for your thumb drive. There are 2 ways:

1. [Change the assigned drive letter](https://winaero.com/change-drive-letter-windows-10/) before you run TE.

2. Assign one more drive letter and run TE using this [BAT file](https://github.com/tablacus/TablacusExplorer/files/5958597/TE.zip) in your thumb drive:

```
@echo off
subst Z: %~d0\ >nul
start Z:\TE\TE64
```

Z: is the fixed drive letter. Z:\TE is the path of your TE folder.

Regards,

**Comment by tablacus** [comment]
How about Tools -> Add-ons-> Label -> General -> Portable?

![image](https://user-images.githubusercontent.com/5156977/107520007-43e1dd00-6bf4-11eb-88b1-a3ad0daf6d55.png)

Regards,

**Comment by ccfs** [comment]
The "Portable" option is surely the simplest solution.

**Comment by duarteframos** [comment]
> How about Tools -> Add-ons-> Label -> General -> Portable?

I totally missed that setting, that sounds sounds exactly like what I need.
I'll give it a try if labels stick once I get home, it sounds like it pretty much solves the issue.

Thanks for the help

**Comment by duarteframos** [comment]
> ```
> @echo off
> subst Z: %~d0\ >nul
> start Z:\TE\TE64
> ```

I have though about using `subst` before, it would help solve other issues with some applications and libraries that don't natively support portability as well, but I've been trying to avoid relying on it.

**Comment by duarteframos** [comment]
[Wiki documentation](https://github.com/tablacus/TablacusExplorerAddons/wiki/label) about Label addon updated to include info
