### ISSUE TITLE
Multiple Executions not working properly 

### ISSUE THREAD

**Issue by RedCrafterLP** [tablacus/TablacusExplorer#370]
The problem is that when I start Tablacus Explorer a second time it just opens the first opened Window
![1](https://user-images.githubusercontent.com/68075054/107477757-9ed5ee80-6b78-11eb-8aea-4f21fd49bc75.PNG)
After Klicking The link:
![2](https://user-images.githubusercontent.com/68075054/107477793-b3b28200-6b78-11eb-8b27-686b5802ff48.PNG)
The 1. Windows is selected instead of a new Windows started.
But when I drag a folder over the link or start TE with a path in some way it works:
![3](https://user-images.githubusercontent.com/68075054/107478168-50751f80-6b79-11eb-9658-6825637fc373.PNG)

My Information:
TE64 21.1.30 Windows 10 Home 2009 (10.0.19042) IE/11 JS/11.0.16384 de_de 96 Windows Defender
My Addons:
mouse 1.29,key 1.23,addressbar 1.58,back 1.16,forward 1.16,up 1.17,toolbar 1.36,titlebar 1.07,tabplus 1.74,multithread 1.24,multiprocess 1.27,remember 1.39,runatsetup 1.01,everything 1.41,foldericon 1.03,mainmenubutton 1.13,virtualrecyclebin 1.03,multipleexecutions 1.04,shellexecutehook 1.09

I hope you can get some useful Information out of my explanation.
Best regards RedCrafter_LP

**Comment by tablacus** [comment]
Please try to update Multiple executions 1.05.
Check Tools -> Add-ons -> Multiple executions -> always.

![image](https://user-images.githubusercontent.com/5156977/107521592-15650180-6bf6-11eb-99a3-31499febc0b4.png)

Regards,

**Comment by RedCrafterLP** [comment]
Fixed it, thanks ; -)
