### ISSUE TITLE
Redundant quotation mark returned by Browse button

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#371]
The file path returned by the Browse button (Options and Icon) is incorrectly preceded by a quotation mark, when it contains space. Please help to solve this problem. Thanks.

![20210213_094642](https://user-images.githubusercontent.com/34089121/107840847-0bf3b900-6df1-11eb-89ac-ec84049202cb.png)
![20210213_094848](https://user-images.githubusercontent.com/34089121/107840848-0d24e600-6df1-11eb-9113-8f53ac5fa00e.png)
![20210213_094951a](https://user-images.githubusercontent.com/34089121/107840849-0dbd7c80-6df1-11eb-87ce-b69d964cda80.png)
![20210213_095138](https://user-images.githubusercontent.com/34089121/107840850-0dbd7c80-6df1-11eb-929b-7c3af02fa706.png)
![20210213_095200a](https://user-images.githubusercontent.com/34089121/107840851-0e561300-6df1-11eb-8929-b285a17fe4ac.png)

**Comment by tablacus** [comment]
Please try to update Tablacus Explorer 21.2.13.
Regards,

**Comment by ccfs** [comment]
Tested OK. Thanks.
