### ISSUE TITLE
Selected icon in Options not showing

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#372]
Select an icon. It shows on the page.
![1](https://user-images.githubusercontent.com/34089121/107871082-69633500-6ed9-11eb-9433-428cb82117ec.png)
TE works properly.
![2](https://user-images.githubusercontent.com/34089121/107871086-6a946200-6ed9-11eb-89e9-348cd51851cf.png)
When I open the Options page again, it DOES NOT SHOW.
![3](https://user-images.githubusercontent.com/34089121/107871087-6b2cf880-6ed9-11eb-9253-666e87e13cd5.png)

Please help to solve this problem. Thanks.

**Comment by tablacus** [comment]
Please try to update Tablacus Explorer 21.2.14.
Regards,

**Comment by ccfs** [comment]
Tested OK. Thanks.
