### ISSUE TITLE
Scrolling in Inner breadcrumps

### ISSUE THREAD

**Issue by bob362181** [tablacus/TablacusExplorer#373]
Hi, 

 I am learning to work with Tablacus(newbee). I need to know if it is possible to scroll up and/or scroll down in the submenu of the inner breadcrumps address bar? If yes, how? Is there an option?

Thank you

![2021-02-20_161656](https://user-images.githubusercontent.com/79371808/108608896-19341900-7398-11eb-88f1-28c7342e362c.jpg)

**Comment by ccfs** [comment]
Press Up/Down arrow keys or click ▲▼ in the menu

**Comment by bob362181** [comment]
Sorry, I mean with wheel up / wheel down?

**Comment by ccfs** [comment]
Currently this is not supported.

**Comment by bob362181** [comment]
Thank you ccfs.
