### ISSUE TITLE
Send multiples keys

### ISSUE THREAD

**Issue by bob362181** [tablacus/TablacusExplorer#374]
Hi, 

When I press ALT+LMB, I need to send 6 keys:
ALT+D
Ctrl+C
TAB
ALT+D
Ctrl+V
ENTER

Somebody can help me?

Thank you for your help

**Comment by ccfs** [comment]
I think of an alternative. May you state what you want TE to do. Gaku may provide you a piece of JScript (that runs upon mouse gesture A1) to achieve.
Regards,

**Comment by bob362181** [comment]
When I press Alt+Left mouse button on a folder in the list of one pane, I want the same folder to open in the other pane.

Thank you for your help.

Regards

**Comment by tablacus** [comment]
Try the following script.

https://gist.github.com/tablacus/59b4d93cf69e62b6bd564290bbaa6a7f

Tools -> Add-ons -> Mouse -> Options -> List

Mouse
`A1`
Type
`JScript`
Optons
```
const FV = GetFolderView(Ctrl, pt);
NavigateFV(Sync.SwitchPane.NextFV(FV), FV, SBSP_SAMEBROWSER);
```
![image](https://user-images.githubusercontent.com/5156977/108842616-e51d5a00-761c-11eb-9e69-e32b3c1dddf3.png)

Mouse
A; Alt key
1; Left button (Mouse)


Regards,

**Comment by bob362181** [comment]
This work great, but I forgot to say that the Alt+LMB should open the folder I click on in the first pane and then open the same folder in the other pane.

Thank you.

**Comment by tablacus** [comment]
Please try to change `SBSP_SAMEBROWSER` to `SBSP_NEWBROWSER`.
```JavaScript
const FV = GetFolderView(Ctrl, pt);
NavigateFV(Sync.SwitchPane.NextFV(FV), FV, SBSP_NEWBROWSER);
```
Regards,

**Comment by bob362181** [comment]
This does not open the folder on which I Alt click... it open a new tab in the other pane, that's ok but, before i want the folder i have clicked on to open. See the picture below.


![TAB-2](https://user-images.githubusercontent.com/79371808/108856801-6abaee80-75b8-11eb-86a3-39ffad020d42.jpg)

**Comment by tablacus** [comment]
Try the following script.

https://gist.github.com/tablacus/bbad6d9ffb29029ca94f35f51c80f1dc

```js
let FV = GetFolderView(Ctrl, pt);
const Selected = FV.SelectedItems();
if (Selected.Count) {
  FV = Sync.SwitchPane.NextFV(FV);
  for (let i = 0; i < Selected.Count; i++) {
    NavigateFV(FV, Selected.Item(i), SBSP_NEWBROWSER);
  }
}
```

Regards,

**Comment by bob362181** [comment]
Here is the result when I press Alt+LMB on folder "layout" in the right pane:

- Ghost appear in the right panel - This is not correct
- Folder "layout" open in new Tab in the left pane - That's OK
- Window "Confirm Drop" open - This is not correct
- Folder "layout" doesn't open in the "Tablacus" TAB as it should
- The Frame close on the left pane - This is not correct

![TAB-3](https://user-images.githubusercontent.com/79371808/108873719-69de8880-75c9-11eb-81b0-bd976858af28.jpg)

**Comment by bob362181** [comment]
I worked a little bit your suggestion and the solution for my needs is something like this:

> let FV = GetFolderView(Ctrl, pt);
> const Selected = FV.SelectedItems();
> if (Selected.Count) {
>   FV = Sync.SwitchPane.NextFV(FV);
>   for (let i = 0; i < Selected.Count; i++) {
>     NavigateFV(FV, Selected.Item(i), SBSP_NEWBROWSER);
>   }
> }
> if (Selected.Count) {
>   FV = Sync.SwitchPane.NextFV(FV);
>   for (let i = 0; i < Selected.Count; i++) {
>     NavigateFV(FV, Selected.Item(i), SBSP_NEWBROWSER);
>   }
> }

The only thing that I don't understand is why "Confirm drop" comes up? If "Confirm drop" is desactivated, everything is working perfectly.

Thank you very much for your help

p.s. Sorry I don't know how to insert jscript code...
