### ISSUE TITLE
How to center the toolbar

### ISSUE THREAD

**Issue by bob362181** [tablacus/TablacusExplorer#376]
Below is a picture of my setting. Is it possible to place the toolbar in the center and how?

Thank you for your help.

![Barre-Outils](https://user-images.githubusercontent.com/79371808/108846124-36413580-75ac-11eb-9eae-726d26f43157.jpg)

**Comment by tablacus** [comment]
Please try to use an add-on "User style sheet".
```css
#ToolBar1Center {
  text-align: center
}
```

![image](https://user-images.githubusercontent.com/5156977/108855899-d179ef80-762c-11eb-8c59-6a4fb8f78e44.png)

Regards,

**Comment by bob362181** [comment]
Thank you very much, it works perfectly!

**Comment by bob362181** [comment]
Is it possible to change height of the toolbar?
