### ISSUE TITLE
I want to try to ask user opinions.

### ISSUE THREAD

**Issue by tablacus** [tablacus/TablacusExplorer#38]
I am worried about how to implement new functions.

# How to change the color of the font on the list view.
What kind of method do you want to change the color of the font on the list view?

* Attribute (Directory/System/Hidden etc.)
* Extension
* Wildcard and/or regular expression

Will you need character decoration? (bold/italic/etc.)

# Format of size.
What kind of format do you want other than "KB"?

* Byte only   1,404 / 1,778,176
* Auto        1.37 KB / 1.69 MB
* MB fixation 0.00 MB / 1.70 MB
* Other

Best regards,

**Comment by LightTempler** [comment]
Q1) How to change the color of the font on the list view?
By extension fits my needs most. e.g. all VisualStudio .sln files in dark blue to get the solution 's entry point faster.

**Comment by LightTempler** [comment]
Q2) Format of size.
Exact number of Bytes would help me from time to time. Auto is informativ, but harder to read/compare on fast eye flying over the list. 
Great would be a multistate switch button: With every click on it the next format size Display type.

**Comment by tablacus** [comment]
You should use this script.

> var FV = GetFolderView(Ctrl, pt);
> if (FV.SizeFormat == 3) {
> &nbsp;&nbsp;FV.SizeFormat = 2;
> } else {
> &nbsp;&nbsp;FV.SizeFormat = 3;
> }
> api.InvalidateRect(FV.hwndList, null, false);

- FV.SizeFormat
- 0: System default
- 1: KB
- 2: Auto
- 3: Size
- 0x22: MB

Best regards,

![1](https://cloud.githubusercontent.com/assets/5156977/7873316/e16e35a8-05db-11e5-9d24-611b82be11ec.png)
