### ISSUE TITLE
Personalized Dark Mode.

### ISSUE THREAD

**Issue by bob362181** [tablacus/TablacusExplorer#382]
I modified Dark Mode with my own color, for this I changed "style.css" in Darkmode folder. I don't want my version of Dark Mode to be overwrite by future update.

1- So how can replace the original?
2- I want a button in tool bar to toggle bethween Light/Dark mode. Have you a suggestion?

Thank you for your help.

p.s. TE is the best Files Editor I have use until now(for the last 20 years)  ... lot of thanks.

**Comment by tablacus** [comment]
1. Please use add-ons [User style sheet](https://github.com/tablacus/TablacusExplorerAddons/wiki/usercss) and [Color](https://github.com/tablacus/TablacusExplorerAddons/wiki/color) instead  of "Dark mode".

2. Please try to install an add-on [Add-on switcher](https://github.com/tablacus/TablacusExplorerAddons/wiki/addonswitcher).

Regards,

**Comment by bob362181** [comment]
It seem a bit complicated, because each time I need to change "Mode" I need to:

1. Load a file to change the "usercss"
2. Change the parameter of "Color" plugin
3. Change the parametes of "Inactive pane" plugin
4. Change the set of "Icons"
5. Switch "Dark mode" off/on
 This is not very user friendly...!

What about having 2 setups for TE, one Dark and one Light, each one in it's own folder. To change "Mode", one would start another instance of TE using a button to start the app in the required "Mode" (Light or Dark). Do you think it is possible to do something like this?

Regards,

**Comment by bob362181** [comment]
Hi Gaku,

I created 2 versions (One light, one dark) in 2 differents folders. Each version have a toolbar button to start the other mode. Another button to load the layout, if necessary. It is very fast, efficient and satisfy my needs.

Regards,
