### ISSUE TITLE
Submenu font color

### ISSUE THREAD

**Issue by bob362181** [tablacus/TablacusExplorer#388]
Hi, 

As shown in the picture below the "Folder Submenu" font is pretty dark. When "Dark Mode" is activated it is hard to see. How can I change the color of the font specifically for "Dark Mode"?

Thank you for your help.

![Subfolder_Color](https://user-images.githubusercontent.com/79371808/109809616-847eb600-7bf6-11eb-9426-7391bda04d6d.jpg)

**Comment by tablacus** [comment]
Unfortunately I don't know how to change the color there. 

Regards,
