### ISSUE TITLE
Environment variable

### ISSUE THREAD

**Issue by bob362181** [tablacus/TablacusExplorer#389]
Is it possible to have an "Environment variable" for the full path of the installed program "TE.exe", so it would be possible to install a copy on the root folder of a USB drive without changing the references of applications started by right-click or from a toolbar button or even custom icon?

Thank you for your help

**Comment by duarteframos** [comment]
https://github.com/tablacus/TablacusExplorer/issues/153

**Comment by duarteframos** [comment]
https://github.com/tablacus/TablacusExplorerAddons/wiki/xfinder

**Comment by bob362181** [comment]
Thank you Duarte,
 ...but I meant  the parent folder of "Tablacus" because all my portable programs are in the same folder. So, it looks like this:

 C:\Portable_64 

> Folder_Pgm1
    Folder_Pgm2
               .
               .
    Folder_Tablacus
               .




The "Environment Variable" I need should contain "C:\Portable_64" and not "C:\Portable_64\Folder_Tablacus".
