### ISSUE TITLE
open new tab shortcut

### ISSUE THREAD

**Issue by guilhas** [tablacus/TablacusExplorer#39]
Hello,

This is a feature/bug report

In windows explorer when we double click a folder with CTRL pressed it opens a new tab, it's not working in tablacus 15.4.5

Best regards,

**Comment by tablacus** [comment]
That function hasn't been implemented yet.
I'll add it in next version.

Best regards,

**Comment by tablacus** [comment]
I've adjusted it on Tablacus Explorer 15.5.18
Best regards,

**Comment by LightTempler** [comment]
So left ...
 * Doubleclick a folder with Ctrl is same as 'New Tab'.
 * Doubleclick a folder with Shift-Ctrl opens all selected folders in new tabs.
 * Doubleclick a folder/file with Alt opens properties dialog.

Cool! :-)

**Comment by tablacus** [comment]
Thanky you!

**Comment by guilhas** [comment]
nice, thanks.
