### ISSUE TITLE
Selection of items

### ISSUE THREAD

**Issue by bob362181** [tablacus/TablacusExplorer#392]
Hi Gaku,

Do you think it is possible for you to do a plugin doing these type of selection from one pane to the other as illustrated in the picture below:

![Selection](https://user-images.githubusercontent.com/79371808/110385490-fc9d0f80-802c-11eb-8cdb-a6231ac4a534.jpg)

Thank you.

**Comment by tablacus** [comment]
OK, there are some challenges.

1.  What is the name of the add-on?
2. Timestamp 2 seconds off due to file system 
3. Handling folder timestamps 
4. Processing of folders with the same file such as Everything 

Regrads,

**Comment by duarteframos** [comment]
This sounds useful, at especially the part of selecting items on both panes.

Maybe this could be somehow integrated into the recent [Synchronize addon](https://github.com/tablacus/TablacusExplorerAddons/wiki/synchronize).

Otherwise maybe name it something along _Synchronize Selection_, _Sync Select_ or _Select on Both Panes_.

**Comment by bob362181** [comment]
I think **SyncSelect** would be a representative name ... Sorry, Duarte, but I don't think it should be integrated with Synchronize addon which is about navigation between folders. **SyncSelect** is more about "selection of items" in two location with similar content.

**Comment by bob362181** [comment]
Hi Gaku,

It would be interesting to add a few more type of selections like these:

![Selections-2](https://user-images.githubusercontent.com/79371808/110631590-ae932380-8174-11eb-9649-be693ea440fd.jpg)

Regards,

**Comment by tablacus** [comment]
### Select all
Type:`Edit`
Click "Browse" and select "Select all"
![image](https://user-images.githubusercontent.com/5156977/110645700-8d284b00-81f9-11eb-8dd4-d1517de20fd2.png)

### Deselect all
Type:`JScript`
Options
```
const FV = GetFolderView(Ctrl, pt);
FV.SelectItem(null, SVSI_DESELECTOTHERS);
```
![image](https://user-images.githubusercontent.com/5156977/110646926-bd241e00-81fa-11eb-887d-f0ad5a751224.png)

### Invert selection
Type:`Edit`
Click "Browse" and select "Invert selection"
![image](https://user-images.githubusercontent.com/5156977/110647526-3f144700-81fb-11eb-980f-470dbdd3a0e7.png)

### Selection filter
Install an add-on "Wildcard selection"
Type:`Add-ons`
Options:`Wildcard Select...`
![image](https://user-images.githubusercontent.com/5156977/110649148-b0082e80-81fc-11eb-8b5b-19e6ae94c078.png)


Regards,

**Comment by bob362181** [comment]
Thank you so much Gaku  ... I am still a newbie!

**Comment by tablacus** [comment]
I have created an add-on "Sync select".
Please try it out.

Regards,

**Comment by bob362181** [comment]
I have already installed the add-on, I will come back soon with all my comments, but at first glance it seem very promising!

Thank you for your work.

**Comment by bob362181** [comment]
First, let's take a look at the dialog box. The presentation is clear and neat. All statements are simple, easily understandable and doing what they are supposed to do. The way the dialog box is presented make the use of the add-on efficient and flexible. It is possible, at all times, to change our mind without having to restart the add-on. Still, I noted a typographical error with the word "different", there should not have a "r" after the "ff".

In spite of that, if this is possible, it would be nice if the position and the size of the dialog box were remembered, because to use the add-on, one's need to place the box where it doesn't hide useful information. So, the way it works now, it is necessary to reposition and resize the dialog box each time the add-on is started.

The same is true after reducing the window. Actually, the window reduces to the bottom left corner. That's ok, but to come back it needs two clicks, it would be more practical if only one click reposition the dialog box.
Now, let's talk about the tests. I have tested all the "Select types" with folders, with files and extension "on" and with files and extension "off". All the "Select type" work correctly with files. However, "Select newer", Select different", "Select unique and newer" and "Select unique and different" doesn't work correctly with the folders (see picture 1).

Finally, I think that, having "Show only selected" and "Invert selection" at bottom of the dialog box would be very useful.

If you need help for the french translation of the add-on, I will be glad to help.

Thank you.

![Select_Newer](https://user-images.githubusercontent.com/79371808/110993005-c02b2580-8344-11eb-8bda-5d0ac87b6a34.jpg)

**Comment by bob362181** [comment]
Hi Gaku,

I forgot about "Focus", after  "Sync Selecting", focus should immediately given to the panel. Actually, selection is lost when clicking one of the item selected or the background of the pane.

**Comment by tablacus** [comment]
OK, I will think about it 

Translation of add-ons is the same method as the main body.
https://github.com/tablacus/TablacusExplorer/wiki/languages

Example(Japanese)
```ja.xml
<text s="Select matches">他にも存在する項目を選択</text>
<text s="Select all items that are also listed in the other pane.">他のペインにも存在する項目を選択します。</text>
```
Please write in the above way.

Regards,

**Comment by bob362181** [comment]
Translation in French is done. What do you want me to do with the file? Please note that I have changed the word " diff**r**erent" for "different" (4 occurrences), so "dialog.htlm" has to be changed accordingly.

"Invert selection is not necessary because it is already in context menu (right click).

"Show only selected" could also be in the context menu because it would be useful at all time. Please tell me the JScript code.

It would be more practical if "Focus" is immediately given to the panel, but it is ok like it is.

Thank you very much.

**Comment by bob362181** [comment]
Hi Gaku,

I have installed Sync Select 1.01. Everything works perfectly (100% percent). It is a very handy add-on.

Thank you very much, どうもありがとうございました

**Comment by tablacus** [comment]
Would you upload the French translation file here.

Regards,

**Comment by bob362181** [comment]
Here it is.


[fr-RV.txt](https://github.com/tablacus/TablacusExplorer/files/6150070/fr-RV.txt)

**Comment by tablacus** [comment]
Please try to update "Sync select".

To apply the language file, disable the add-on, then enable it and click OK.
![image](https://user-images.githubusercontent.com/5156977/111486148-95910080-877a-11eb-860a-7bc32587d1d6.png)

Thank you.

**Comment by bob362181** [comment]
This is working very well.

Thank you.
