### ISSUE TITLE
icon overlay not visible

### ISSUE THREAD

**Issue by tortino** [tablacus/TablacusExplorer#393]
Hello,
I'm using this version of tablacus (edge):
TE64 21.3.14 Windows 10 Enterprise 1909 (10.0.18363) Edg/89.0.774.54 JS/Chakra en_us 96 Windows Defender
and these plugins:
foldersettings 1.31,multiprocess 1.29,multithread 1.24,mouse 1.29,key 1.24,mainmenu 1.14,titlebar 1.07,tabplus 1.74,statusbar 1.16,innerback 1.11,innerforward 1.13,inneraddressbar 1.34,innerfilterbar 1.29,innerup 1.07,innerrefresh 1.03,innernewfolder 1.03,gridlines 1.04,undoclosetab 1.13,touchex 1.09,findfiles 1.16,delete 1.04,fastlistmode 1.03,favorites 1.05,usercss 1.06,switchhidden 1.04,iconoverlay 1.10,tabgroups 1.37

I have to use Serena Dimensions to access a software repository, and using Tablacus I cannot see the icon overlays.
I can see the overlays from TortoiseGIT and OneDrive but not the ones from Serena.
Please not that oon Windows Explorer the overlays are correctly visible.

Here is a a screenshot:
![image](https://user-images.githubusercontent.com/26486758/111189226-2a96cc80-85b6-11eb-98be-8fb5ed7e0b6c.png)

currently I'm testing the tablacus edge preview release, but the issue is exactly the same on stable tablacus (ie engine)

**Comment by ccfs** [comment]
Try "Icon overlay" add-on. Set “Base” to 0.

**Comment by tortino** [comment]
Hello,
I already using Icon overlay with base = 0.
Enabling or disabling the addon doesn't make a difference.

**Comment by tablacus** [comment]
Please try to check List -> Style -> Explorer browser -> Icon.

![image](https://user-images.githubusercontent.com/5156977/111340042-9adb4600-86bb-11eb-98f9-4974f53ec0fb.png)

Regards,

**Comment by tortino** [comment]
Hello, I've tried your suggestion but it's not working.

**Comment by tablacus** [comment]
It may be for Windows Explorer only.

Thank you,

**Comment by tortino** [comment]
ok thank you.

**Comment by garry-ut99** [comment]
No need to duplicate threads:
- https://github.com/tablacus/TablacusExplorer/issues/140
