### ISSUE TITLE
Top of the list

### ISSUE THREAD

**Issue by bob362181** [tablacus/TablacusExplorer#396]
Hi,

How can I have all selected items on top of the list in the folderview?

Thank you

**Comment by tablacus** [comment]
Unfortunately, there is no such function now.

Regards,

**Comment by tablacus** [comment]
Please try the following script. 
https://gist.github.com/tablacus/449b7f93415c9e2a646b50d75383d5bd

**Comment by bob362181** [comment]
When tested with less than one hundred items it works correctly. I made some test with 750 items in a folder, 320 of which were selected. It took 65 seconds to produce the list. It is common for me to have a few thousands items. The problem seem to come from "CustomSort" command, the information box "Organized by: Selected items" is there all the time. If 25/750 selected, it takes 8 seconds.

Hope this will help.

**Comment by tablacus** [comment]
I've improved a bit.

https://gist.github.com/tablacus/449b7f93415c9e2a646b50d75383d5bd

Regards,

**Comment by bob362181** [comment]
This seem a lot better, but I could not test with more than 250 items because now it doesn't work in "flat mode".

Regards,

**Comment by tablacus** [comment]
I have adjusted this script for flat.
I haven't encountered any zoom level issues.

https://gist.github.com/tablacus/449b7f93415c9e2a646b50d75383d5bd

Regards,

**Comment by bob362181** [comment]
Now it works in flat mode but "Selection is lost", items are no more highlighted whether it is in flat mode or not.

It doesn't work with the result of search made in the search bar.

When a column header filter is used the script works but it still change the zoom level(see picture below)

![Zoom_Level2](https://user-images.githubusercontent.com/79371808/111904725-bbd6ca80-8a1e-11eb-81d5-2a0b72e45b54.jpg)


Regards

**Comment by tablacus** [comment]
I have adjusted this script.
This script requires Tablacus Explorer 21.3.19 or later. 
I feel that there is no way to sort the items in any order in the search results.

https://gist.github.com/tablacus/449b7f93415c9e2a646b50d75383d5bd

Regards,

**Comment by bob362181** [comment]
Thank you Gaku,

The zoom problem and selection problem are now solved.

**Comment by ccfs** [comment]
@tablacus,
I suggest to make this script a new add-on, so that this handy feature can be easily used through a command button, a hot key, etc.
Regards,

**Comment by tablacus** [comment]
What is the proper name for this add-on?

Thank you,

**Comment by bob362181** [comment]
May be "Select last item used"  or  "Remember last item".

Regards,




________________________________
De : Gaku ***@***.******@***.***>>
Envoyé : 24 mars 2021 09:28
À : tablacus/TablacusExplorer ***@***.******@***.***>>
Cc : bob362181 ***@***.******@***.***>>; Author ***@***.******@***.***>>
Objet : Re: [tablacus/TablacusExplorer] Top of the list (#396)


What is the proper name for this add-on?

Thank you,
