### ISSUE TITLE
Remember last item.

### ISSUE THREAD

**Issue by bob362181** [tablacus/TablacusExplorer#399]
Is it possible to add a new option to "Remember folder view settings" add-on. With this option "on" folders could reopen pointing on the last item selected before closing. 

Thank you.

**Comment by tablacus** [comment]
Maybe it's heavy. 
I think it's better to create another add-on that remembers the selection of items in any folder. 

Thank you,

**Comment by bob362181** [comment]
It's OK for me.

Thank you.

**Comment by bob362181** [comment]
Do you have an idea of when the add-on remembering last folder will be ready?

Thank you

**Comment by tablacus** [comment]
I'm currently adjusting some unreleased add-ons so I'll think about it once it's settled down.

Regards,

**Comment by bob362181** [comment]
Thank you for your attention to my request .

Regards,

**Comment by tablacus** [comment]
I have created an add-on "Save selected items" to save and restore the selections. 
Please give it try.

Regards,

**Comment by bob362181** [comment]
I am sorry but I can't get it to work. I have installed the add-on, I made a button but nothing happen?

**Comment by tablacus** [comment]
1. Select the item you want to save and click the icon. 
2. Select Save menu. 
![image](https://user-images.githubusercontent.com/5156977/114180924-d9db7f00-997b-11eb-98f1-40015a91b418.png)
3. Deselect it. 
![image](https://user-images.githubusercontent.com/5156977/114181301-4f474f80-997c-11eb-8e0f-330fd6ec3839.png)
4. Click the icon.
![image](https://user-images.githubusercontent.com/5156977/114181716-ce3c8800-997c-11eb-9deb-8db632a55d06.png)
5. Select Select menu to restore selected items.
![image](https://user-images.githubusercontent.com/5156977/114181829-f330fb00-997c-11eb-9c3e-29581d45f965.png)

Regards,

**Comment by bob362181** [comment]
I am sorry but we misunderstood about the idea I suggested! Let me explain...

Let's suppose that I go in "addons" folder by double-clicking, then I enter in"color" folder and then I open "script.js". I need to remember the folder and/or filename that were use, so the next time I open, let's say "color" folder "script.js" will automatically focused and selected or if I open "addons" folder "color" folder will be selectded and so on.

Am I clear enough? If not tell me and I will try to be clearer.

Regards,

**Comment by tablacus** [comment]
I have created a new add-on "Remember selection".
Please give it try.

Regards,

**Comment by bob362181** [comment]
I made some test and everything seems to work nicely. Indeed, no matter if we use back button, up button, backspace key or even inner address bar segment to change folder, the addon always remembers the last item selected correctly. The only exception I met  is when using double clicking in the empty space of the list to go up one level, the addon seems to lose track of the selected items. It would make sense for the addon to also remember the last selected item in this case too, but I don't know if this is possible for you to do it.

Anyway, this is very nice feature to have and it is a real time saver.

Thank you very much for your patience.

Regards,

**Comment by bob362181** [comment]
I have tested "Remember selection 1.01" and the problem when using double clicking in a empty space is gone. So, I think the addon works properly in all cases. I consider this addon to be very useful, therefore I highly recommend it to all users of  TE.

Thank you very much Gaku.

Regards,
