### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by guilhas** [tablacus/TablacusExplorer#40]
Hello,

When opening a path Network share or Local that we do not have permissions or the path does not exist, there is no error box or popup warning. We stay in same folder and it does nothing.

v15.4.5

Best regards,
Guilherme Lino

**Comment by tablacus** [comment]
Hello,
I will try to consider it.
Thank you,

**Comment by tablacus** [comment]
I've adjusted it on Tablacus Explorer 15.5.18
Best regards,

**Comment by guilhas** [comment]
Thanks
