### ISSUE TITLE
TE crashes if a folder path is entered into the Run dialog box

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#400]
Please help to solve this problem. Thanks.

![20210323_171948](https://user-images.githubusercontent.com/34089121/112129673-9d312900-8c02-11eb-8f77-6e808218d5ea.png)
Press F10 to open the Run dialog box.
Enter a folder path. TE should go to the folder.
![20210323_172012](https://user-images.githubusercontent.com/34089121/112129677-9e625600-8c02-11eb-9dcd-ddd16efb0302.png)
But TE crashes.
![20210323_172032](https://user-images.githubusercontent.com/34089121/112129680-9efaec80-8c02-11eb-811c-fc9ac53df6c8.png)

**Comment by ccfs** [comment]
This problem is quite awful. Is there any cure?

**Comment by tablacus** [comment]
I haven't encountered it.
The following is a workaround.

Type
```
JScript
```
Options
```
sha.FileRun();
```

![image](https://user-images.githubusercontent.com/5156977/112612974-ec759480-8e62-11eb-8baa-c0d69362c169.png)

Regards,

**Comment by ccfs** [comment]
The problem may not occur if TE has started for a while, or has some additional add-ons enabled.
The problem probably occurs if you unzip te210326.zip into a folder, run TE64 and then press F10.

Regards,

**Comment by tablacus** [comment]
I haven't encountered it, so I think it's difficult to fix without more information.

https://github.com/tablacus/TablacusExplorer/wiki/report-problem

Regards,

**Comment by tablacus** [comment]
I have adjusted Tablacus Explorer 21.3.28 by analogy with #248.
Please give it try.

https://github.com/tablacus/TablacusExplorer/releases/tag/21.3.28

Regards,

**Comment by ccfs** [comment]
Sorry the problem still remains in TE 21.3.28.

Here is something copied from Event Viewer:
失敗的應用程式名稱: TE64.exe，**版本: 21.3.28.0**，時間戳記: 0x6060852b
失敗的模組名稱: SHELL32.dll，版本: 6.1.7601.24468，時間戳記: 0x5ce88682
例外狀況碼: 0xc0000005
錯誤位移: 0x000000000009b668
失敗的處理程序識別碼: 0xd28
失敗的應用程式開始時間: 0x01d72449a1cee93f
失敗的應用程式路徑: M:\te210328\TE64.exe
失敗的模組路徑: C:\Windows\system32\SHELL32.dll

I believe that the problem has been there for a long time, because it occurs also in TE 20.9.3 which is before the Blink project.
失敗的應用程式名稱: TE64.exe，**版本: 20.9.3.0**，時間戳記: 0x5f50f375
失敗的模組名稱: SHELL32.dll，版本: 6.1.7601.24468，時間戳記: 0x5ce88682
例外狀況碼: 0xc0000005
錯誤位移: 0x000000000009b668
失敗的處理程序識別碼: 0xadc
失敗的應用程式開始時間: 0x01d722cfc5e68f27
失敗的應用程式路徑: M:\te200903\TE64.exe
失敗的模組路徑: C:\Windows\system32\SHELL32.dll

But the problem does NOT occur in my another copy of TE with many additional add-ons enabled. Therefore I think that this is because of the existence of an add-on that uses SHELL32.dll.

This is a proof:

TE64 21.3.28 Windows 7 Home Premium (6.1.7601) IE/11 JS/11.0.19597 zh_hk 96 Avast Antivirus
mouse 1.29,key 1.24,addressbar 1.61,filterbar 1.34,back 1.17,forward 1.17,up 1.19,treeview 1.38,toolbar 1.38,mainmenu 1.15,titlebar 1.08,tabplus 1.74,multithread 1.24,remember 1.39,undoclosetab 1.13,history 1.15

I enabled "History" add-on.
![20210329_122040](https://user-images.githubusercontent.com/34089121/112787672-a2bbc280-908b-11eb-8b41-379d71aa61b5.png)
Try the case.
![20210329_122120](https://user-images.githubusercontent.com/34089121/112787675-a3ecef80-908b-11eb-8a7a-1a91ccc7aace.png)
NO PROBLEM OCCURS.
![20210329_122142](https://user-images.githubusercontent.com/34089121/112787676-a4858600-908b-11eb-92ac-681ffb314963.png)

My conclusion is that there is something wrong in TE in handling SHELL32.dll

**Comment by ccfs** [comment]
Actually if then I click the X button to close TE, TE still crashes but due to mshtml.dll.
失敗的應用程式名稱: TE64.exe，版本: 21.3.28.0，時間戳記: 0x6060852b
失敗的模組名稱: mshtml.dll，版本: 11.0.9600.19597，時間戳記: 0x5df83e4a
例外狀況碼: 0xc0000005
錯誤位移: 0x00000000002d5653
失敗的處理程序識別碼: 0x630
失敗的應用程式開始時間: 0x01d724662560cc5b
失敗的應用程式路徑: M:\te210328\TE64.exe
失敗的模組路徑: C:\Windows\System32\mshtml.dll

If I click a folder to go there before clicking the X button, TE does not crash.

**Comment by tablacus** [comment]
What about older versions? 

https://github.com/tablacus/TablacusExplorer/releases/tag/17.5.24

Regards,

**Comment by ccfs** [comment]
Results:

TE 21.3.29 crashed after entering a folder path into the Run dialog box. It failed at SHELL32.dll
失敗的應用程式名稱: TE64.exe，版本: 21.3.29.0，時間戳記: 0x6061d148
失敗的模組名稱: SHELL32.dll，版本: 6.1.7601.24468，時間戳記: 0x5ce88682
例外狀況碼: 0xc0000005
錯誤位移: 0x000000000009b668
失敗的處理程序識別碼: 0x138c
失敗的應用程式開始時間: 0x01d724aeff9d4cb7
失敗的應用程式路徑: M:\te210329\TE64.exe
失敗的模組路徑: C:\Windows\system32\SHELL32.dll

TE 21.3.29 with "History" enabled crashed after entering a folder path into the Run dialog box and then clicking the X button to close TE. It failed at jscript9.dll
失敗的應用程式名稱: TE64.exe，版本: 21.3.29.0，時間戳記: 0x6061d148
失敗的模組名稱: jscript9.dll，版本: 11.0.9600.19597，時間戳記: 0x5df826d6
例外狀況碼: 0xc0000005
錯誤位移: 0x00000000000dee23
失敗的處理程序識別碼: 0x564
失敗的應用程式開始時間: 0x01d724aec470ba67
失敗的應用程式路徑: M:\te210329\TE64.exe
失敗的模組路徑: C:\Windows\System32\jscript9.dll

TE 17.5.24 crashed after entering a folder path into the Run dialog box and then clicking the X button to close TE. It failed at jscript9.dll
失敗的應用程式名稱: TE64.exe，版本: 17.5.24.0，時間戳記: 0x59257928
失敗的模組名稱: jscript9.dll，版本: 11.0.9600.19597，時間戳記: 0x5df826d6
例外狀況碼: 0xc0000005
錯誤位移: 0x00000000000dee23
失敗的處理程序識別碼: 0xa28
失敗的應用程式開始時間: 0x01d724ae5c072435
失敗的應用程式路徑: M:\te170524\TE64.exe
失敗的模組路徑: C:\Windows\System32\jscript9.dll

I have a second thought. Maybe the problem is not in the way TE handles SHELL32.dll. The function itself may be the problem.

When a folder path is entered into the Run dialog box, Windows opens the folder in Explorer. However TE interferes with this process and makes the folder be opened in TE instead.

Generally if a user wants to open a folder in TE by entering a path, he/she can use the address bar. Using the Run dialog box to do this is just a "nice to have" feature. Therefore my suggestion is to REMOVE this feature if the problem is difficult to solve. Simply let the Run dialog box do what it normally does (open the folder in Explorer).

Alternatively you just tell any user getting the problem to use the above "sha.FileRun();" workaround.

Regards,

**Comment by tablacus** [comment]
I have fixed it in Tablacus Explorer 21.3.30.
Please give it try.

https://github.com/tablacus/TablacusExplorer/releases/tag/21.3.30

**Comment by tablacus** [comment]
Thank you for your cooperation.
Many reports have been very helpful in fixing the problem.

Thanks a lot.
