### ISSUE TITLE
right mouse click menu missing TortoiseGit/TortoiseSVN

### ISSUE THREAD

**Issue by Xyrio** [tablacus/TablacusExplorer#401]
right mouse click menu on folder or empty space inside a folder is missing TortoiseGit/TortoiseSVN that appear in normal explorer, TortoiseHg is visible

i ran TE as administrator too but no difference.

i looked in 
HKCR\Drive
HKCR\Directory 
HKCR\Folder
HKCR\LibraryFolder
but couldnt find TortoiseHg only entries (rather the opposite). so i have no clue why.

one difference in HKCU\Tortoise* is that Hg has the path set for the (Default) key while others dont.

TortoiseGit points to: C:\Program Files\TortoiseGit\bin\TortoiseGitStub32.dll
TortoiseSVN points to: C:\Program Files\TortoiseSVN\bin\TortoiseStub32.dll
TortoiseHG points to: C:\Program Files\TortoiseHg\ThgShellx64.dll

tried TE32 too but here the 2 above are still missing but now also TortoiseHg is missing and additionally also an entry from Dropbox is gone.

stuff always visible is: 7-Zip and KDiff3

info:
all 3 Tortoise* are 64bit (no *32 in task manager)

TE64 21.3.22 Windows 7 Professional (6.1.7601) IE/11 JS/11.0.19597 de_de 96
mouse 1.29,key 1.24,addressbar 1.61,filterbar 1.34,back 1.16,forward 1.16,up 1.18,treeview 1.37,toolbar 1.38,mainmenu 1.14,titlebar 1.07,tabs 1.20,addtabs2fav 1.01,tabgroups 1.20,flat 1.04,branchbar 1.00,split6 1.00,split 1.04,hotkey 1.00,favoritesnewtab 1.00

**Comment by tablacus** [comment]
I haven't encountered it.
![image](https://user-images.githubusercontent.com/5156977/112470642-3d778100-8dae-11eb-9ef1-849bcd5c4c41.png)

Please try to install TortoiseGit/TortoiseSVN 64-bit.

Regards,

**Comment by Xyrio** [comment]
all 3 Tortoise* are 64bit (no *32 in task manager)

**Comment by tablacus** [comment]
Please try to check the TortoiseGit/SVN settings.

Uncheck Settings-> Icon Overlays -> Show overlays and context menu only in explorer

![image](https://user-images.githubusercontent.com/5156977/112611396-19c14300-8e61-11eb-9dd8-4c7f4f3044d3.png)

Regards,

**Comment by Xyrio** [comment]
yea thats it, was activated.
