### ISSUE TITLE
[Feature requests] Drag the breadcrumb-list address bar item to create a shortcut link.

### ISSUE THREAD

**Issue by yuru7** [tablacus/TablacusExplorer#405]
TE開発お疲れさまです。1つ要望を挙げさせてください。

アドレスバー、及び Inner パンくずリストアドレスバーに表示される各階層のフォルダ名をドラッグして、ショートカットを作成する機能をご検討いただけないでしょうか？

Win 10のエクスプローラのアドレスバーと同じ動作を想像しています。

![image](https://user-images.githubusercontent.com/13458509/114484020-6c15a880-9c44-11eb-98ac-ccdc9f20bb5a.png)

**Comment by yuru7** [comment]
Inner パンくずリストアドレスバー 1.46 にて搭載されたことを確認しました。
とても便利で助かります！ありがとうございました！

**Comment by yuru7** [comment]
本件実装に関して、大変ありがとうございました。とっても便利で、活用の幅が広がったことを早速実感しています。

特定の操作で上手くドラッグができないケースが見受けられたので、ご報告いたします。

### 環境

- TE64 21.4.23 Microsoft Windows 10 Home 64 ビット 20H2 (10.0.19042) Dark IE/11 JS/11.0.16384 ja_jp 125 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz Windows Defender カスペルスキー インターネット セキュリティ カスペルスキー インターネット セキュリティ
- usercss 1.06,mouse 1.29,key 1.24,addressbar 1.66,mainmenubutton 1.14,titlebar 1.08,tabs 1.24,favoritesbar 1.42,hotkey 1.01,undoclosetab 1.14,tasktray 1.11,treeview 1.38,importexplorer 1.07,split 1.20,statusbar 1.17,tabplus 1.80,tabgroups 1.41,tablist 1.03,innerbreadcrumbsaddressbar 1.46,innerfilterbar 1.31,innerback 1.12,innerforward 1.14,innerup 1.08,lockedtabstop 1.08,multithread 1.25,replaceslowcolumns 1.03,autodisableime 1.03,remember 1.39,darkmode 1.08,recentlyusedtabs 1.02,innerrefresh 1.04,tabcolorplus 1.04,flat 1.19
- Inner パンくずリストアドレスバー 1.46

### 操作

1. ファイル一覧ペインをアクティブにする
2. Inner パンくずリストアドレスバーの項目を、下 (ファイル一覧ペイン方向) に向かってドラッグする

手順2でショートカットリンク配置のドラッグ操作になるのが期待の動作ですが、下記キャプチャにあるように、ドラッグ箇所のパンくず項目がハイライトしたままになり、ドラッグでの配置がされません。

ドラッグ方向を一旦、上 (タブバー方向) に向かってドラッグした場合や、ファイル一覧ペインを越えてステータスバーまでドラッグした場合には、期待通りにショートカットリンクのドラッグ操作ができるようです。

![20210425_210234](https://user-images.githubusercontent.com/13458509/115992668-caaa3180-a609-11eb-85e3-58fbdd50830b.gif)

**Comment by yuru7** [comment]
おそらく Inner パンくずリストアドレスバー 1.47 にて [上記](https://github.com/tablacus/TablacusExplorer/issues/405#issuecomment-826314314) の修正が入っているのであろうと思っています。本当にありがとうございます。

アップデート後の状況ですが、発生しづらくなったと感じています。しかし、全く発生しないわけではないようです。報告していた操作を行うと、数回に1度は同じ事象が起きます。

**Comment by tablacus** [comment]
こちらの環境では1.46でも問題出ないんです。
script.js を以下の物に差し替えた場合はどうなりますか？

[script.zip](https://github.com/tablacus/TablacusExplorer/files/6411303/script.zip)

**Comment by yuru7** [comment]
script.js を差し替えてみましたが、状況は変わりませんでした。

> こちらの環境では1.46でも問題出ないんです。

環境によって変わるのかもと思い、いくつかの環境で確認してみたところ、マウスによって起きたり起こらなかったりする状況が見えてきました。

|機種|再現|
|:---:|:---:|
|ThinkPad付属トラックポイント (キーボード真ん中の赤ポチ)|再現しやすい|
|ThinkPad付属タッチパッド|再現しやすい|
|トラックボールマウス (Logicool MX ERGO)|再現しやすい|
|トラックボールマウス (Logicool M570)|やや再現しやすい|
|マウス (Logicool G502)|再現しない|

機種の違いで微妙な操作の違いに繋がらないよう、クリックタイミングやドラッグの方向などの操作はそれぞれのマウスでできるだけ合わせるようにしたのですが、上記のような再現度の違いがありました。

**Comment by yuru7** [comment]
[innerbreadcrumbsaddressbar](https://github.com/tablacus/TablacusExplorerAddons/blob/master/innerbreadcrumbsaddressbar/script.js) のコミット履歴から、181L `Out1` プロパティがショートカットリンク作成に関する処理なのだろうと推測して、 `alert` を差し込んで処理に入っているかを観察してみました。

```js
		Out1: async function (ev, el) {
			alert('hoge');
			MouseOut();
			const ev1 = Addons.InnerBreadcrumbsAddressBar.ev;
...
```

その結果、 以下のことが分かりました。

- [当該事象](https://github.com/tablacus/TablacusExplorer/issues/405#issuecomment-826314314) が発生するとき、 `Out1` の処理の中に入っていない
- `Out1` の処理に入るかどうかは、ドラッグのスピードによる (以下キャプチャ参照)

![20210503_135326](https://user-images.githubusercontent.com/13458509/116842300-0c913400-ac17-11eb-9bfe-b9bd75473b49.gif)

正常に動作しないケースのように、素早くドラッグすると何故か `onmouseout` イベントが発火しないのかもしれません。

**Comment by yuru7** [comment]
Inner パンくずリストアドレスバー 1.48 を試してみました。少し試してみたところ、件の問題は解消されたように見えます。ありがとうございます！

ちなみに不具合というほどではないので迷ったのですが、一応ご報告いたします。
ドロップした後もアドレスバー上の対象パンくず項目がハイライトされたままになるようです。再度アドレスバーにマウスオーバーしたり、階層移動をするとハイライトは解除されます。

![20210504_112704](https://user-images.githubusercontent.com/13458509/116954836-fdb88900-accb-11eb-88db-bcc9a6d1c343.gif)

**Comment by yuru7** [comment]
> ドロップした後もアドレスバー上の対象パンくず項目がハイライトされたままになるようです。再度アドレスバーにマウスオーバーしたり、階層移動をするとハイライトは解除されます。

上記の問題は解消されたことを確認しました。ありがとうございます。

ただ、inner パンくずリストアドレスバー 1.49 にて、パンくずリスト項目のドラッグでのリンク作成が、タブ間を越えられなくなるケースがあるようです。通常、タブ間を越えてドロップできることはできるのですが、何かの拍子に以下キャプチャのように、タブが切り替わったタイミングで、ドラッグ中状態を示すマウスカーソル右下の四角形が消え、ドロップしてもショートカットリンクが貼られなくなることがあります。
数回に1回は再現するものの、明確な再現手順は不明です。何か気付くことがあったら追ってご報告いたします。
![20210509_080033](https://user-images.githubusercontent.com/13458509/117555715-a421d700-b09c-11eb-84f2-fee24f0773d8.gif)

**Comment by yuru7** [comment]
> ただ、inner パンくずリストアドレスバー 1.49 にて、パンくずリスト項目のドラッグでのリンク作成が、タブ間を越えられなくなるケースがあるようです。

上記について、リリースノートの内容から TE 21.5.9 で対策を入れていただいたのではないかと思うのですが、相変わらず発生します（タブが切替わった瞬間にリンクのドラッグ状態が解除される）
![20210511_060332](https://user-images.githubusercontent.com/13458509/117724392-a57b0d00-b21e-11eb-83a9-996da4c94339.gif)

**Comment by yuru7** [comment]
いえ、問題はそこではありません。
問題は、タブが切り替わった瞬間に、ショートカットリンクのドラッグ状態が解除される点です。

---

Thanks for the reply. No, that's not the problem.
The drag state of the shortcut link is broken when the tab is switched.

![20210511_180819](https://user-images.githubusercontent.com/13458509/117790000-e1948900-b283-11eb-8c82-bf30be4f7b0f.gif)

**Comment by yuru7** [comment]
> 問題は、タブが切り替わった瞬間に、ショートカットリンクのドラッグ状態が解除される点です。

TE 21.5.11 にて、解消されたことを確認しました。ありがとうございました。数日様子を見てみたいと思います。
