### ISSUE TITLE
inner new folder button ?

### ISSUE THREAD

**Issue by jarodsteele** [tablacus/TablacusExplorer#41]
Hi,
what about creating a new addon: inner create new folder ?
I use a 4 view layout, and for each view I use all the inner buttons, like forward, backward, up, refresh.
I really like to have an inner "new folder" button too!
Thanks!!!!!!

**Comment by tablacus** [comment]
Hi,
That's great.
I created a new add-on "Inner New folder".
http://www.eonet.ne.jp/~gakana/tablacus/addons/?q=inner%20new%20folder
Thank you!

**Comment by jarodsteele** [comment]
Thanks! Works perfectly!


2015-05-16 14:54 GMT+02:00 Gaku <notifications@github.com>:
