### ISSUE TITLE
"No header" captions are incorrectly swapped

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#417]
Please help to solve this problem. Thanks.

Under "Tools > Options > List > Style > Advanced"

Enable "No header in all views"
![20210429_144138](https://user-images.githubusercontent.com/34089121/116513670-8914d180-a8fc-11eb-9b79-cef70c641230.png)
A column heading still shows in Details view.
![20210429_144201](https://user-images.githubusercontent.com/34089121/116513679-8a45fe80-a8fc-11eb-8dc1-5fa860e96785.png)

Enable "No column header"
![20210429_144023](https://user-images.githubusercontent.com/34089121/116513758-a5b10980-a8fc-11eb-9941-2b4dd5417ae6.png)
There is not any column heading in Details view (and other views).
![20210429_144109](https://user-images.githubusercontent.com/34089121/116513763-a6e23680-a8fc-11eb-8f16-2aa2bf0e5f56.png)

My conclusion is that the captions are incorrectly swapped.

**Comment by tablacus** [comment]
See here.
https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-folderflags

**No header in all views**

> FWF_NOHEADERINALLVIEWS | 0x01000000. Windows Vista and later. Only show the column header in details view mode.

**No column header**

> FWF_NOCOLUMNHEADER | 0x00800000. Windows Vista and later. Do not display a column header in the view in any view mode.

Regards,

**Comment by ccfs** [comment]
The amended caption in TE 21.4.29 makes sense now. Thanks.
