### ISSUE TITLE
Open only one folder (switch?)

### ISSUE THREAD

**Issue by DarkLite1** [tablacus/TablacusExplorer#42]
This is probably already possible, but I can't find it in the documentation. How can I open only one folder location without seeing the previously opened folders (the history)? To do this I use PowerShell to open just one folder like this:

Start-Process 'S:\Tools\TablacusExplorer\TE64.exe' -ArgumentList 'S:\My folder'

After executing this line it does open the folder 'S:\My folder' but also some other folders from the history. How is it possible to have it only open this 1 folder and nothing else?

I'm also trying to find the switches that are possible by typing 'TE64.exe /?', but this doesn't work. It works for other applications like this 'Robocopy.exe /?'.

Thank you for your help.

**Comment by LightTempler** [comment]
Afaik there are now command line switches yet.
But u can open as many tabs (= Locations) as u want to with paths behind call:

"C:\Program Files\Tablacus\TE64.exe" C:\Temp C:\Windows C:\Programme C:\My\Very\Special\Folder

**Comment by DarkLite1** [comment]
Thank you for the help. I tried to install the 'Startup settings' Add-on as you suggested. Then I clicked on 'Options > Tabs > Close tabs on the left > Ok' and it spits out an error. I am using the portable version, so I don't know if this makes a difference or not.

Error message: An error has occurred in the script on this page.Line 1918, Char 6, Object expected.

This option doesn't close all the other tabs but leaves 2 open. Can you tell me what the best way would be to have it only open one tab? The requested tab from the prompt that is...

**Comment by tablacus** [comment]
I've adjusted it in Tablacus Explorer 15.5.28

- Open only one folder (C:\Program Files) with PowerShell

> Start-Process 'S:\Tools\TablacusExplorer\TE64.exe' -ArgumentList '"Tabs,Close other tabs" "Open,C:\Program Files"'

Best regards,

**Comment by DarkLite1** [comment]
Thank you very much tablacus, works like a dream! Perfect! :)

**Comment by tablacus** [comment]
My pleasure.
