### ISSUE TITLE
False alarm of "File is in operation" upon "Check for updates" when "Multi process" is used

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#429]
Please help to solve this problem. Thanks.

After I replied OK to proceed program update
![UPD](https://user-images.githubusercontent.com/34089121/117743704-dfa5d800-b239-11eb-8725-09c3b6061a7a.png)
A progress window flashed. Then the following false alarm showed up.
![FILE OP](https://user-images.githubusercontent.com/34089121/117743796-14199400-b23a-11eb-9460-84c9b5695c43.png)
After I clicked "Retry", TE was frozen.

The problem does not occur if "Multi thread" is used instead.

TE64 21.5.7 Microsoft Windows 7 家用進階版  64-bit (6.1.7601) IE/11 JS/11.0.19597 zh_hk 96 Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz Avast Antivirus
mouse 1.30,key 1.24,addressbar 1.67,back 1.17,forward 1.17,up 1.19,mainmenu 1.15,titlebar 1.08,tabplus 1.85,remember 1.39,addonsupdater 1.09,multiprocess 1.30

**Comment by ccfs** [comment]
I tried TE 21.5.11 with "Multi process" add-on:

1. I clicked X button on title bar when a file copy operation was in progress.
2. TE window was unexpectedly closed. "File is in operation" prompt did not appear. But the operation continued.
3. When the operation finished, an error message showed.
![20210512_154641](https://user-images.githubusercontent.com/34089121/117942707-f2093a00-b33d-11eb-8a85-b3f72dd7f47c.png)

**Comment by ccfs** [comment]
I tried the new version 1.31 of "Multi process" add-on. It solves the above missing "File is in operation" prompt problem.
However it has another problem: After a file operation completes and the progress window is closed, the process still stays in Windows for about 1 minute, even if I close TE normally.
![20210513_110712](https://user-images.githubusercontent.com/34089121/118093658-57bdfa80-b400-11eb-9538-876468776a20.png)

**Comment by ccfs** [comment]
The false alarm problem is solved. I have succeed updating TE 21.5.11 to 21.5.14, with "Multi process" or "Multi thread" (and without both).

The staying process problem of "Multi process" is still here. It may cause a memory shortage if the user does a lot of file operations, since each process occupies about 1 MB memory for about 1 minute.

Regards,

**Comment by tablacus** [comment]
I think it is safety margins.

Regards,

**Comment by ccfs** [comment]
Is it possible to shorten this safety margin to a few seconds? 1 minute is too long. The file operation has already completed, and I don't know why the process still stays there.

Regards,

**Comment by tablacus** [comment]
Would you like to cooperate with the test?
Please overwrite worker.js in the multi-process folder.

[multiprocess_worker.zip](https://github.com/tablacus/TablacusExplorer/files/6494648/multiprocess_worker.zip)

Regards,

**Comment by ccfs** [comment]
The stay time is significantly shortened and is acceptable.
However, audio playback is incorrectly delayed until the process disappears in Windows Task Manager.

Regards,

**Comment by tablacus** [comment]
How about this?

[multiprocess_worker_210518.zip](https://github.com/tablacus/TablacusExplorer/files/6501738/multiprocess_worker_210518.zip)

Regards,

**Comment by ccfs** [comment]
This one is good. No problem is found.

Regards,
