### ISSUE TITLE
Unable to upgrade to Version 21.5.11

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#430]
I am unable to upgrade from v 21.5.9 to 21.5.11. Error message enclosed. Selecting Retry does not work.
If I download 21.5.11 and unzip the contents to the TE directory, will I lose all customizations and add-ons? If so, is there another way to manually update TE?

<img width="212" alt="Screenshot_1" src="https://user-images.githubusercontent.com/31006631/118013024-af386980-b31f-11eb-9a86-2420b8685abd.png">

**Comment by InvisibleManX** [comment]
1. Make a backup copy of your old TE directory. 
2. Unzip the downloaded new version of TE. 
3. Then copy and paste every single folder (with their contents) from the old backup directory to a new version's directory. But do not copy those old exe files. This will get all your settings and addons back. 
4. Run the new version of TE, and manually update all addons it suggests you to update in the program's settings.

**Comment by tablacus** [comment]
Please select "Ignore" in "File is in operation" dialog on update Tablacus Explorer.

Regrds,
