### ISSUE TITLE
Incorrect search result for name* and *name*

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#435]
Please help to solve this problem. Thanks.

When `name*` or `*name*` is searched for, TE shows an incorrect result, compared with Windows Explorer.

Case: `name*`
![1e](https://user-images.githubusercontent.com/34089121/120256616-1911b680-c2c1-11eb-986c-6c2754ae9e57.png)
![1t](https://user-images.githubusercontent.com/34089121/120256618-1a42e380-c2c1-11eb-8b74-d020397b13f1.png)

Case: `*name*`
![2e](https://user-images.githubusercontent.com/34089121/120256619-1adb7a00-c2c1-11eb-8494-305aae4e8ea1.png)
![2t](https://user-images.githubusercontent.com/34089121/120256623-1b741080-c2c1-11eb-8195-2f4f72084b6a.png)

**Comment by ccfs** [comment]
Version 21.6.1 solves the above case, but `*name` case now gets the above problem.

I tried to upload 2 screen shots showing the problem. However the upload failed for an unknown reason. Please test it at your side. The case I tested was `*k`. Windows Explorer showed 3 items, but TE showed 6.

Regards,

**Comment by tablacus** [comment]
It's the same as Windows 10 Explorer. 

![image](https://user-images.githubusercontent.com/5156977/120468402-240d3980-c3dc-11eb-9e47-b8ae50639d4a.png)

Regards,

**Comment by ccfs** [comment]
I think the difference is not due to Windows version. It is probably due to the "**Partial match**" option on "Search" tab of "Folder Options" of Windows Control Panel.

The option is ticked by default. Both Explorer and TE produce the same results. However if the option is **cleared**, Explorer and TE produce different results, if the search string is not ended with *. It seems that **TE does not comply to the option**.

I tried 4 cases:
1. `*k*`: Both Explorer and TE produce the same result.
2. `*k`: Explorer and TE produce different results (The result of TE is the same as 1).
3. `k*`: Both Explorer and TE produce the same results.
4. `k`: Explorer and TE produce different results (The result of TE is the same as 3).

![F](https://user-images.githubusercontent.com/34089121/121162283-60c7ad80-c880-11eb-82a6-e7f84b345112.png)
1. `*k*`
![F1E](https://user-images.githubusercontent.com/34089121/121162462-83f25d00-c880-11eb-9ab1-2049e49a9e6a.png)
![F1T](https://user-images.githubusercontent.com/34089121/121162468-85238a00-c880-11eb-9ceb-e599455abe53.png)
2. `*k`
![F2E](https://user-images.githubusercontent.com/34089121/121162470-85bc2080-c880-11eb-90c2-a737ec538220.png)
![F2T](https://user-images.githubusercontent.com/34089121/121162474-85bc2080-c880-11eb-91d3-f833cc44d72d.png)
3. `k*`
![F3E](https://user-images.githubusercontent.com/34089121/121162477-8654b700-c880-11eb-8ea4-237690de6a1e.png)
![F3T](https://user-images.githubusercontent.com/34089121/121162480-86ed4d80-c880-11eb-986e-930a94fee4e4.png)
4. `k` 
![F4E](https://user-images.githubusercontent.com/34089121/121162488-86ed4d80-c880-11eb-9696-c82e02ef9b7f.png)
![F4T](https://user-images.githubusercontent.com/34089121/121162490-8785e400-c880-11eb-82fe-624f4ba26c4c.png)

Regards,

**Comment by ccfs** [comment]
The situation gets worse with TE 21.6.8.
TE 21.6.7 works as if the option were always opted for (always partial match).
TE 21.6.8 gets a problem regardless of the option:

"Full match" case 4 (`k`)
![F](https://user-images.githubusercontent.com/34089121/121283247-63bcaf80-c90d-11eb-910c-8e89826f66be.png)
![F4E](https://user-images.githubusercontent.com/34089121/121283256-65867300-c90d-11eb-8671-30e708beb435.png)
![F4T](https://user-images.githubusercontent.com/34089121/121283259-65867300-c90d-11eb-89e3-f5622e80f61e.png)

"Partial match" case 2 (`*k`)
![P](https://user-images.githubusercontent.com/34089121/121283264-68816380-c90d-11eb-8971-c6cf18f11944.png)
![P2E](https://user-images.githubusercontent.com/34089121/121283265-6919fa00-c90d-11eb-8b8c-441a69de0bed.png)
![P2T](https://user-images.githubusercontent.com/34089121/121283267-6919fa00-c90d-11eb-9497-8a8441123a23.png)

**Comment by tablacus** [comment]
The "Partial Match" option is no longer available in Windows 10. 
![image](https://user-images.githubusercontent.com/5156977/121286702-2d862c80-c91b-11eb-8bb3-da374195c482.png)

Regards,

**Comment by ccfs** [comment]
Please revert to version 21.6.7 which gives consistent results (partial match regardless of the option and Windows version). For a full match users have to put the search string in "quotes".

Regards,

**Comment by ccfs** [comment]
The problems are solved in version 21.6.9. It can produce the same results as Explorer when "full match" or "partial match" are set. Thanks.
