### ISSUE TITLE
Show/Hide Hidden files no longer working

### ISSUE THREAD

**Issue by craigalan** [tablacus/TablacusExplorer#438]
I have an icon to show/hide hidden files.  For some reason it has stopped working.  This is the jscript that you once provided for me:

var FV = GetFolderView(Ctrl, pt);
FV.ViewFlags ^= 1;
FV.Refresh();

Can you help me to get this work again?

Thanks!

**Comment by tablacus** [comment]
I have not encountered it.
Let me know your environment.
Anyway, please try to update Tablacus Explorer.

Regards.

**Comment by ccfs** [comment]
use "Switch hidden items" add-on


	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.1.2.2 (Windows)">
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"微軟正黑體"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	




Switch hidden items
--

**Comment by craigalan** [comment]
When I sent the first issue, I was on the latest update at that time, which was 21.6.5.  I just updated now to 21.6.7 and my original icon is now working.  Should I change over to the "Switch Hidden Items" Add-on or can I continue to use it the way it is?

Also, this is a bit off topic, but does having multiple add-ons added slow down or put a hit on performance of the app in anyway?

As always thank you so much for the quick reply and for all the hard work you put into this fantastic explorer replacement!

**Comment by tablacus** [comment]
Either's fine.

I think some add-ons slow things down and some don't.

Regards,

**Comment by craigalan** [comment]
Thank you!
