### ISSUE TITLE
problem with "folder settings" and "remember folder view settings"

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#44]
Hi, I'm using the two addons:
1) "folder settings" addon, to set "default" layouts for details columns for various folders/devices (ie c:\, MTP devices, etc). The default columns I chose is: name, date modified, total file size, order by name.
2) "remember folder view settings" addon, to occasionally set exceptions to the default layout from "folder settings" addon (es sort by desc date for Downloads folder only)
It almost works, but sometimes I get the default column layout of windows, not the "default" I chose in addon 1.  When this happens I have to manually adjust columns, and it's really annoying.
Can you fix this?
Thank you.

**Comment by tablacus** [comment]
Hello,
If two add-ons are older, please update them.

These two add-ons are conflicts.
Please try to change their order.

Best regards,

**Comment by stefanocaselli** [comment]
OK I'll try and then report here how it gone.
Thanks
 Il 06/giu/2015 16:13, "Gaku" <notifications@github.com> ha scritto:

**Comment by stefanocaselli** [comment]
Hello,
no good news from my tests. I have updated the addons and tried changing the order.
The result:
1) at the top "remember folder view settings"  and after that "folder settings": first addon isn't working at all: as an example I change the sort order from name to date modified, then close and re-open same folder, but it always get the default from "folder settings" (sort by name)
2) fist "folder settings" and then "remember folder view settings": almost work. but sometimes it get the windows default column layout, not the one set in "folder settings".
Do you have suggestions about which test I could do to help you fixing this issue?
thanks.

**Comment by tablacus** [comment]
Hello,
I also did the test, I found a problem in add-on "Remember".
I've adjusted it in Remember 1.20
Thank you,

**Comment by tablacus** [comment]
Hello,
If it does not work well, you can adjust the columns at tool bar buttons etc.

This is "Folder settings"
![1](https://cloud.githubusercontent.com/assets/5156977/8063224/8389211e-0f0e-11e5-8c33-e0d40fba0cfd.png)

Add this to the top of the options in tool bar button etc.
> Ctrl = GetFolderView(Ctrl, pt);

This is "Tool bar"
![2](https://cloud.githubusercontent.com/assets/5156977/8063244/9ffe0eea-0f0e-11e5-8b98-c1a4efccebfb.png)

**Comment by stefanocaselli** [comment]
Hi,
I'm testing latest versions, I'll let you know if it's working (it seems ok for now)
Thank you.

**Comment by tablacus** [comment]
My pleasure.

**Comment by tablacus** [comment]
I've adjusted it in Total file size sort 1.02
You can choose the inner bar.
![1](https://cloud.githubusercontent.com/assets/5156977/8458317/668c68b0-2051-11e5-9c1f-e8ede5d3c8dd.png)
Thank you.

**Comment by stefanocaselli** [comment]
yes, it works. thank you.

by the way, I think the italian translation can be enhanced a little: in
the screenshot the "Location" is not translated, and should be "Posizione".
And I think the "Key" is wrong: it should be "Tasto", not "Chiave".


2015-07-01 17:29 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
"Posizione" It has already been used in the translation "Position".
The same words are not usable.
Are there any good words?

I understood it about "Tasto".

Thank you.

**Comment by stefanocaselli** [comment]
To me the words "Location" and "Position" have more or less the same
meaning.
Where is used "Position" ?

2015-07-02 14:26 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
Here it is.
![4](https://cloud.githubusercontent.com/assets/5156977/8508495/0981df92-22ae-11e5-9cf4-d27e0b5e7898.png)
Thank you for the information.

**Comment by stefanocaselli** [comment]
I'm sorry but I'm still thinking that Location and Position are equivalent.
Can you kindly explain to me the intended meaning of the two different words in the context of Tablacus?
Thank you.

**Comment by tablacus** [comment]
All right.
I use "Position" without using "Location".
Thank you.

**Comment by stefanocaselli** [comment]
ok, seems reasonable.
thank you.
