### ISSUE TITLE
Keystroke to cycle between tree pane / list pane / inner address bar ?

### ISSUE THREAD

**Issue by sdrubble** [tablacus/TablacusExplorer#440]
Hello ... many thx for the amazing Tablacus tool !

I've been experimenting with the 'Key' addon, but was unable to figure out how to set up some key (let's say the TAB key) to cycle between the panes mentioned in the title.

The idea here is to somehow mimic a method I've been using for years with Explorer++ (and in a lesser scale, also with Windows Explorer itself), aiming to mostly use the keyboard and avoid as many mouse clicks as possible.

I'm under the impression that the 'Key' addon is most useful when defining functions WITHIN a particular pane, so I'm unsure that my intent of traversing multiple panes would be possible.

Is there a way to perform this pane-cycling within Tablacus with the keyboard only ?

Thanks !

**Comment by tablacus** [comment]
How to switch the split pane with the keyboard.

1. Install an add-on "Switch to next pane".

![image](https://user-images.githubusercontent.com/5156977/122635594-d0128c80-d11f-11eb-85ab-954f62b4f67b.png)

2. Open the option for the add-on "Key".
3. Change the location to "List".
4. Click "Input" and select the key.
5. Change the type to "Add-ons".
6. Click "Browse..." and select "Switch to next pane".
7. Click "Add" and "OK". 

![image](https://user-images.githubusercontent.com/5156977/122635705-6f378400-d120-11eb-9a7d-6ae9521b91b8.png)

Regards,

**Comment by tablacus** [comment]
### Focus Inner address bar from List view.
1. Open the option for the add-on "Key".
2. Change the location to "List".
3. Click Enter and select the key.
4. Change the type to "Add-ons".
5. Click Browse ... and select "Inner address bar".
6. Click Add and OK. 

![image](https://user-images.githubusercontent.com/5156977/122637334-0d2f4c80-d129-11eb-972f-933c26b20e67.png)

### Focus Tree view from Inner address bar
1. Install an add-on "Run at setup".
2. Open the option for the add-on "Run at setup".
3. Change the type to "JavaScript".
4. Enter the following script in Options. 
```js
window.addEventListener("keydown", function (ev) {
  if (ev.keyCode == VK_TAB) {
    if (/inneraddressbar/i.test((ev.target || ev.srcElement).id)) {
      setTimeout(async function () {
        const FV = await GetFolderView();
        FV.TreeView.Focus();
      }, 99);
    }
  }
});
```
![image](https://user-images.githubusercontent.com/5156977/122637264-9abe6c80-d128-11eb-9937-fe17187bb9cb.png)


https://gist.github.com/tablacus/1cf14bbf97c9744bfc58865127a7a744

Regards,

**Comment by sdrubble** [comment]
Thx for your input ! :) However...

My fault: I should have stated previously that I was ALSO using a 4-panel layout. Screenshot [here](https://i.imgur.com/MxXGxVK.png) .

So what happens is: when I press TAB, the focus cycles among each of the 'Inner Address Bar' elements from each panel, plus 2 or 3 'invisible' spots, before repeating the cycle. None of the 'Tree' elements is ever touched.

The desired behavior, in this case, should be that the focus would only cycle inside one given panel. I would use the mouse in case I wished to select any one of the other panels, after which the cycle would perform only inside the newly mouse-selected panel.

**Comment by tablacus** [comment]
Please replace the script. 

```js
window.addEventListener("keydown", function (ev) {
  if (ev.keyCode == VK_TAB) {
    const res = /inneraddressbar_(\d+)/i.exec((ev.target || ev.srcElement).id);
    if (res) {
      setTimeout(async function () {
        const FV = te.Ctrl(CTRL_TC, res[1]).Selected;
        FV.Focus();
        FV.TreeView.Focus();
      }, 99);
      if (ev.preventDefault) {
        ev.preventDefault();
      } else {
        ev.returnValue = false;
      }
      return false;
    }
  }
});
```

![image](https://user-images.githubusercontent.com/5156977/122659129-5f1ab580-d1af-11eb-86e9-a5b1805715eb.png)

https://gist.github.com/tablacus/1cf14bbf97c9744bfc58865127a7a744

Regards,

**Comment by sdrubble** [comment]
1. Thx. I replaced the script.

2. I tested the new script and results remained the same (only the SEQUENCE of cycling panels changed - like 1-2-3-4 to 4-3-2-1).

3. Made multiple tests as to enabling / disabling some addons and to re-ordering addons around in the Addon panel. Still no change, except another change in the sequence of cycling panels (1-4-3-2).

4. Then it occurred to me that, in the 2nd post in this thread, you provided 2 recipes. Shouldn't it have been _THREE recipes in order to close the cycling sequence ?_ See:

4a. Focus Inner address bar from List view - provided.
4b. Focus Tree view from Inner address bar - provided.
4c. _Focus  List view from Tree view - MISSING ?_

Cheers

**Comment by tablacus** [comment]
> 4c. Focus List view from Tree view - MISSING ?

This is included in the add-on "Tree view".

Regards,

**Comment by sdrubble** [comment]
> This is included in the add-on "Tree view".

Well, I tried [this](https://imgur.com/5wVX9a3).
But there was no change in behavior, as in (quoting myself from a previous post):
> when I press TAB, the focus cycles among each of the 'Inner Address Bar' elements from each of the 4 panels, plus 2 or 3 'invisible' spots, before repeating the cycle. 

Thank you once again :)

**Comment by tablacus** [comment]
![image](https://user-images.githubusercontent.com/5156977/123090240-e479c080-d462-11eb-8265-60358c69473f.png)

Which tree view are you using?

1. Blue - Side tree view
2. Red - Tree view
3. Green - Frame tree view

Regards,

**Comment by sdrubble** [comment]
> 2\. Red - Tree view

This one.

**Comment by tablacus** [comment]
If that's the case, then you shouldn't have to do anything.
Please read this and let me know your environment.
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

Regards,

**Comment by sdrubble** [comment]
Thx Gaku. 

I've been for a while preparing a migration to Windows 10 (I'm still on Windows 7) and setting up a Win10 VM to test stuff before I migrate my main system.

So yesterday I finally got to the point where I could copy my original Tablacus' folder on Win7 over to the Win10 VM.

I'm happy to report that, while the misbehavior remains under Win7, the exact same Tablacus folder under Win10 is working correctly, wrt to cycling among UI elements with 'Tab'. I had been suspecting for a while that that might be the case, for under Win7 I was getting frequent scripting errors when fiddling with settings within 'Options' and 'Addons'.

Here are the environment info you requested, for both Win7 and Win10.

**_Win7 - Information_**
`TE64 21.6.17 Microsoft Windows 7 Enterprise  64-bit (6.1.7601) IE/8 JS/5.8.17514 en_us 96 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz ESET Security`

**_Win7 - Add-ons_**
`multipleexecutions 1.09,multithread 1.25,mainmenu 1.15,back 1.17,forward 1.17,up 1.19,filterbar 1.36,toolbar 1.41,drivebar 1.17,restart 1.08,treeview 1.38,favorites 1.06,mouse 1.30,inneraddressbar 1.35,key 1.24,runatsetup 1.02,titlebar 1.08,tabplus 1.86,remember 1.39,undoclosetab 1.14,aboutblank 1.00,favoritesbar 1.42,innernewfolder 1.04,gridlines 1.05,attributescolor 1.06,download 1.05`

**_Win10 - Information_**
`TE64 21.6.17 Microsoft Windows 10 Enterprise 64-bit 21H1 (10.0.19043) Dark IE/11 JS/11.0.16384 en_us 96 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz Windows Defender`

**_Win10 - Add-ons_**
`multipleexecutions 1.09,multithread 1.25,mainmenu 1.15,back 1.17,forward 1.17,up 1.19,filterbar 1.36,toolbar 1.41,drivebar 1.17,restart 1.08,treeview 1.38,favorites 1.06,mouse 1.30,inneraddressbar 1.35,key 1.24,runatsetup 1.02,titlebar 1.08,tabplus 1.86,remember 1.39,undoclosetab 1.14,aboutblank 1.00,favoritesbar 1.42,innernewfolder 1.04,gridlines 1.05,attributescolor 1.06,download 1.05`

Looking at this reports attentively, it seems more or less obvious to me now that the striking difference between JavaScript versions might be the reason behind my original 'Tab cycling' issue, as well as the various scripting errors I have been seeing.

I suppose this issue could be closed by now. And again, many thx for your investment in time and effort regarding the creation and dedicated maintenance of Tablacus.

Cheers ! :))
