### ISSUE TITLE
[Feature Request] Addon: Inner Favorites

### ISSUE THREAD

**Issue by acambule** [tablacus/TablacusExplorer#443]
Hi there,

I use the favorite addon to have a favorites bar on the top and that works great.
My standard configuration ist to use a split of 2x1.

There are some important folders that i have pinned on both sides.
But sometimes it's very uncomfortable to work with, when other folder are needed. 

So i have started to put some of them into the favorites bar to keep the tabs cleaner.

While doing that i noticed that it would be much cooler to have splitted favourites,
directly inside the tab splits. So for every split i could have it's own favourites.
When opening a favourite it also would open in it's appropriate split side.

Tha's my request, splitted favourite bars for every split part.

Thanks and regards
Antonio

**Comment by tablacus** [comment]
Please try setting the position of the add-on "Favorites" to the inner bar.

![image](https://user-images.githubusercontent.com/5156977/123252942-ce820380-d527-11eb-9d7a-21094595b67c.png)

Regards,

**Comment by acambule** [comment]
Thanks for the quick answer. 
The main part was to have separated favourites, per split.

I found another solution using Groups instead, thats ok too. Having my workspace with open tabs and then another when i have to switch for something else.

Regards
