### ISSUE TITLE
[feature request] Deselect with space bar

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#444]
Currently TE (and Windows Explorer) allows users to move the focus in a file list (by Ctrl+Arrow keys) and then press space bar to select a focused item. However pressing space bar cannot deselect. Please help to find a way to do so, e.g. by setting up the space bar in Key add-on. Thanks.
![sp](https://user-images.githubusercontent.com/34089121/123510507-9c4ede00-d6ae-11eb-8f63-b7840a080614.png)

**Comment by tablacus** [comment]
In this cases, I usually hold down Ctrl and press Space bar.
e.g. Ctrl+Down Ctrl+Space Ctrl+Down Ctrl+Space. (Hold down Ctrl and press any other key. )

Regards,

**Comment by ccfs** [comment]
Ctrl+Space works, after I have disabled in IME (Windows language bar). Thanks.
