### ISSUE TITLE
selection in tree 

### ISSUE THREAD

**Issue by jiewangjs** [tablacus/TablacusExplorer#445]
Great app. 
When show files in the tree, is there anyway to just select the file rather than automatically open the file, popping out a dialog ?

**Comment by tablacus** [comment]
Please uncheck Tools -> Add-ons -> Tree view -> Options -> General -> Expanded and List.

![image](https://user-images.githubusercontent.com/5156977/123546423-65a0c280-d797-11eb-9a08-6391ad85c0b7.png)

Regards,

**Comment by jiewangjs** [comment]
> Please uncheck Tools -> Add-ons -> Tree view -> Options -> General -> Expanded and List.
> 
> ![image](https://user-images.githubusercontent.com/5156977/123546423-65a0c280-d797-11eb-9a08-6391ad85c0b7.png)
> 
> Regards,

May I say it doesn't seem to take effect.

**Comment by tablacus** [comment]
Please try to update the add-on "Tree view" 1.39 (or "Side tree view" 1.23).

Regards,

**Comment by jiewangjs** [comment]
Superb. Thanks
