### ISSUE TITLE
Some menus visible in Explorer are not visible.

### ISSUE THREAD

**Issue by AoiKagase** [tablacus/TablacusExplorer#446]
I can't see the standard OS menus such as "Pin to Taskbar" and "Restore Previous Versions" or the menus added by software.
OS標準のメニューや、ロケールエミュレータと言った後から追加されたメニューの一部が表されません。
EXEを右クリックした際にロケールエミュレータが表示できないのは仕様でしょうか。
Left：Tablacus / Right：Explorer
![image](https://user-images.githubusercontent.com/26139931/123543644-8adb0400-d78a-11eb-8e48-2f51b1c8bd92.png)

**Comment by tablacus** [comment]
プレリリース版のTablacus Explorer 18.6.28で調整しました。
アップデートしてみてください。

https://github.com/tablacus/TablacusExplorer/releases/tag/21.6.28

**Comment by AoiKagase** [comment]
確認しました。
お早い対応ありがとうございました。
