### ISSUE TITLE
Startup issues: Script error when right clicking group tab and Stray tab leading to TE64.exe

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#449]
I've been getting these two issues  consistently for a while now

# Issue 1 - Script error when right clicking group tab right after a fresh startup.

If I right click on a group tab, or try to close it right away after opening a fresh instance of TE I get a script error message. I am unable to close it or operate the group tabs until I manually click on one and switch tabs. If I manually click on a group tab and switch to it, after that right clicking resumes working properly.

![20210630_094753](https://user-images.githubusercontent.com/8735426/123937425-0f49a480-d98e-11eb-9d0f-f6acd8e37276.png)

# Issue 2 - Stray tab pointing to TE64.exe when launched from QAP

I've been using [QAP Quick Access Popup](https://www.quickaccesspopup.com) to launch my apps for a while now, including Tablacus. Since a few versions ago, for about maybe two or three months (cant quite precise when exactly), whenever I use it to open Tablacus a new unwanted stray tab pointing to TE.exe is created.

This only happens when launching from QAP, there are no parameters or command line arguments given, only directly pointing to TE64.exe. Happens both with absolute or relative paths, launching form a menu or hotkey. Even if tablacus is already running a new tab pointing to TE64.exe is created.

Is this a Tablacus issue, or a QAP one? Did anything change in the code at some point that could be causing this?

TE64 21.6.25 Microsoft Windows 10 Pro 64-bit (10.0.19041) IE/11 JS/11.0.16384 en_us 96 Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz Windows Defender ESET Security ESET Endpoint Antivirus

mouse 1.30,key 1.24,foldersettings 1.34,tabplus 1.87,tabgroups 1.43,filtericon 1.11,usercss 1.06,tabs 1.25,mainmenu 1.15,toolbar 1.41,inactivepane 1.10,undoclosetab 1.14,searchbar 1.10,favoritesbar 1.42,flat 1.20,extract 1.13,folderlistmenu 1.14,innerbreadcrumbsaddressbar 1.49,innerfilterbar 1.32,multiprocess 1.33,totalfilesizesort 1.12,countbar 1.11,tabname 1.07,statusbar 1.17,sethome 1.02,gohome 1.02,checkbox 1.13,protecttabs 1.05,innerback 1.12,innerup 1.08,tooltippreview 1.19,label 1.41,aboutremember 1.05,sidetreeview 1.22,innerforward 1.14,titlebar 1.08,switchpane 1.04,addonsupdater 1.09,quickmenu 1.14,xfinder 1.31,dragtop 1.03,clipboardimage 1.01,synchronize 1.05,lockedtabstop 1.08,switchhiddenfilter 1.02

**Comment by tablacus** [comment]
### Issue 1
I have adjusted it in Tab groups 1.44.
Please try to update it.

### Issue 2
I have adjusted it in Tablacus Explorer 21.6.30.
Please give it try.

https://github.com/tablacus/TablacusExplorer/releases/tag/21.6.30

Regards,

**Comment by duarteframos** [comment]
Both issues solved with the latest versions, many thanks!

One unrelated question. Is it possible in any way to have Group Tabs behave more like regular folder tabs.
By that I mean display the X to close, or have customizable mouse click options.

With _Mouse Addon_  you can customize mouse actions for _Tab_ and _Tab Background_ contexts, would it be possible to do the same for _Group_ and _Group Background_?
