### ISSUE TITLE
inner icon for Total File Size Sort

### ISSUE THREAD

**Issue by jarodsteele** [tablacus/TablacusExplorer#45]
Hi,
I have tried the newest addon Total File Size Sort. It's good, but I don't use a single toolbar at the top (I use 4 separate views with inner buttons) so having a single button to activate this size sort is ugly, and uses precious vertical space (especially on laptops with 16:9 screens).
I suggest you add an optional inner button for size sort, and also a menu item. Maybe you could add a new menu for addons, like "Utilies" or similar, and put there the option to size sort (and others).
Thanks!

**Comment by tablacus** [comment]
Hi,
I understand.
Anyway, Set Location of "Total folder size"' to "None"
![1](https://cloud.githubusercontent.com/assets/5156977/8232287/66189c2a-1609-11e5-880c-e65f6b5f4d92.png)
You can add "Total folder size" to menu.
![2](https://cloud.githubusercontent.com/assets/5156977/8232294/7ae280b2-1609-11e5-87b9-aa27f310fc83.png)
Like this
![3](https://cloud.githubusercontent.com/assets/5156977/8232506/53e40e66-160b-11e5-9a00-404b722c2e7f.png)
And you can click on the column of "Total folder size"  to sort by total folder size.
Also, you can shift-click on the column of "Size" to sort by total folder size.
![4](https://cloud.githubusercontent.com/assets/5156977/8232665/6210a264-160c-11e5-9077-2f02fc011ff7.png)
Best regards,

**Comment by jarodsteele** [comment]
Tablacus is really incredibly customizable! I will try your suggestion.
Thanks!


2015-06-18 15:58 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
My pleasure.
