### ISSUE TITLE
[Feature Request] Reorder UI elements from 'Inner' add-ons

### ISSUE THREAD

**Issue by IGP** [tablacus/TablacusExplorer#453]
Currently there does not seem to be a way to change the order that UI elements from 'Inner' add-ons are displayed in.

For example I would like to be able to display the 'Inner Refresh' button after the 'Inner breadcrumbs address bar'.

**Comment by duarteframos** [comment]
Toolbar order is determined by addon load order which is defined by the addon order in the list. To reorder the buttons place the inner addons in the desired order in the list by picking the radio button to the left, then dragging it up or down

**Comment by IGP** [comment]
> Toolbar order is determined by addon load order, which in turn is defined by the addon order in the installed addons list list.

This does not seem to apply for the inner buttons. Please see the attached images.

![1](https://user-images.githubusercontent.com/920452/124825287-6e388c00-df41-11eb-8d09-0e611da01def.png)
![2](https://user-images.githubusercontent.com/920452/124825298-70024f80-df41-11eb-8677-3fc820d6bfe7.png)

**Comment by duarteframos** [comment]
Breadcrumbs, filter and address bar seem to have fixed positions, other buttons are ordered correctly on my ends

**Comment by IGP** [comment]
> Breadcrumbs, filter and address bar seem to have fixed positions, other buttons are ordered correctly on my ends

Fair. Looking for them to not have fixed positions in that case.

**Comment by tablacus** [comment]
Please try to update an add-on "Inner Refresh".
Check Add-ons -> Inner Refresh -> General -> Position -> Right.

![image](https://user-images.githubusercontent.com/5156977/125088230-32035800-e108-11eb-947b-d7bb8afd33f0.png)

Regards,

**Comment by IGP** [comment]
> Please try to update an add-on "Inner Refresh".
> Check Add-ons -> Inner Refresh -> General -> Position -> Right.

This works. Thanks!
