### ISSUE TITLE
TE not auto refreshing folders again

### ISSUE THREAD

**Issue by daVe55w** [tablacus/TablacusExplorer#458]
We discussed this issue in April 2020 and the "fix" was described in this post. https://github.com/tablacus/TablacusExplorer/issues/280

I just installed TE on a new Win 10 Pro PC and auto-refresh is not working again, even after placing the wild card * in the Filter of 
Force Refresh add-on.

![TE Force Refresh setting](https://user-images.githubusercontent.com/31006631/126049317-aa156fc6-3658-4d9b-8cff-382cbbda8621.png)

**Comment by tablacus** [comment]
I have not encountered it.
Let me know more details.
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

Regards,

**Comment by daVe55w** [comment]
Information
TE64 21.7.16 Microsoft Windows 10 Pro 64-bit 21H1 (10.0.19043) IE/11 JS/11.0.16384 en_us 96 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz System Shield Windows Defender McAfee VirusScan

mouse 1.30,key 1.24,addressbar 1.67,filterbar 1.36,back 1.17,forward 1.17,up 1.19,treeview 1.39,toolbar 1.41,mainmenu 1.15,titlebar 1.08,tabplus 1.87,multithread 1.25,undoclosetab 1.14,extract 1.13,download 1.05,thumbplus 1.19,tabcolor 1.07,autobackup 1.03,systemfolders 1.11,countbar 1.11,addonsupdater 1.09,sizestatus 1.19,everything 1.44,wcx 1.15,wfx 1.26,controlpanelbutton 1.09,forcerefresh 1.07,closebutton 1.06,properties 1.06,restart 1.08,refresh 1.09,emptyrecyclebin 1.05,fastcopy 1.20,font 1.19,tabname 1.07,notepadalternative 1.02,maximizebutton 1.09,thumbnailengine 1.08,mainmenubutton 1.15,mixedsort 1.13,startup 1.09,dragdrop 1.03,minimizebutton 1.08,paste 1.06,delete 1.06,newtab 1.07,copy 1.04,cut 1.04,checkbox 1.13,autoupdate 1.03,fullpathbar 1.06,opencpinexp 1.02,grabbutton 1.10,tabdesign 1.13,takeoverfoldersettings 1.08,sethome 1.02,gohome 1.02,tabgroups 1.44,previewwindow 1.24,runatsetup 1.02

**Comment by daVe55w** [comment]
The problem is McAfee LiveSafe antivirus. I added TE32.exe and TE64.exe to the exclusion list and immediately TE is auto refreshing.
For anyone else experiencing this problem, open McAfee LiveSafe. Click Settings (gear icon). In the PC Settings section (scroll down) select Real-time Scan. In the Excluded Files section, click Add file and browse to the TE folder. Select TE32.exe. Repeat for TE64.exe.
