### ISSUE TITLE
windows share  ad authentication

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#46]
Hi,
cannot load windows share (like \\servername\foldername) that requires authentication.
I have to authenticate using windows explorer, then accessing with Tablacus works correctly.
I think Tablacus should ask for password directly.
Thanks.

**Comment by tablacus** [comment]
Thank you for the report.
I think that the problem is time-out-related processing.
I'll try to adjust it.

Best regards,

**Comment by stefanocaselli** [comment]
Hi, this is the error I get:

![talend network share error](https://cloud.githubusercontent.com/assets/10347571/9150007/d32775f6-3dc4-11e5-9729-63cf65a1ae00.png)

**Comment by tablacus** [comment]
I've tried to adjust it in Tablacus Explorer 15.8.9.
Thank you.

**Comment by stefanocaselli** [comment]
Hi,
unfortunately it doesnt' work. I still have to log in using windows
explorer. Tablacus just not asks for credentials.
However I see that now on startup it automatically loads all tabs beloging
to a network share (good).



2015-08-09 16:16 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
Would you change the timeout into "0"?
![2](https://cloud.githubusercontent.com/assets/5156977/9172578/8e869fac-3faf-11e5-9205-3704af66faa6.png)
 Best regards,

**Comment by stefanocaselli** [comment]
Ok, I tried setting 0 but doesnt' work.


2015-08-10 15:35 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
I've tried to adjust it again in Tablacus Explorer 15.8.14.
Thank you.

**Comment by stefanocaselli** [comment]
Hello,
it works: now it asks the login and password!

However there is still a problem: I have multiple tabs opened showing
different subfolders of the network share: at startup Tablacus opens
multiple login/passwords dialogs! I think it should open only a single
dialog, and reuse the first login/password for other tabs. I don't want to
enter the same login/password multiple times.


2015-08-14 16:26 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
I think that it is a difficult problem.
But, I will try and think about that matter.

Thank you,

**Comment by stefanocaselli** [comment]
Hi, 
I just tried version 15.8.30, but I get 3 password dialogs and a 4th error dialog:
![error](https://cloud.githubusercontent.com/assets/10347571/9582481/e2150a76-5005-11e5-846a-1b003bcbee87.PNG)

**Comment by tablacus** [comment]
I think that this is the network issue or specifications of Windows because I have not made this dialog box.
Anyway, please try the command "net use".

net use \\\\*SERVERNAME* /user:*USERNAME* *PASSWORD*
![1](https://cloud.githubusercontent.com/assets/5156977/9657692/4e61616e-527e-11e5-992f-f6217078b71d.png)

**Comment by stefanocaselli** [comment]
Hi,
After "net use" I'm authenticated, so tablacus doesn't need to ask me the
login and password.This way I don't get all that dialogs.
Thanks.


2015-09-03 13:59 GMT+02:00 Gaku <notifications@github.com>:

**Comment by tablacus** [comment]
Hello,
I am happy to hear it went very well.
Thank you,
