### ISSUE TITLE
tab with about:blank

### ISSUE THREAD

**Issue by tortino** [tablacus/TablacusExplorer#460]
Hello,
I'm using this tablacus version:
TE64 21.7.16 Microsoft Windows 10 Pro 64 bit 20H2 (10.0.19042) IE/11 JS/11.0.16384 it_it 96 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz Windows Defender
with these addons:
foldersettings 1.34,multithread 1.25,multiprocess 1.33,mouse 1.30,key 1.24,mainmenu 1.15,titlebar 1.08,tabs 1.25,tabplus 1.87,undoclosetab 1.14,innerback 1.12,innerforward 1.14,inneraddressbar 1.35,innerfilterbar 1.32,innerup 1.08,innernewfolder 1.04,split 1.22,statusbar 1.17,gridlines 1.05,touchex 1.09,findfiles 1.19,noinfotip 1.02,delete 1.06,totalfilesizesort 1.12,innerrefresh 1.05,favorites 1.06,usercss 1.06,switchhidden 1.05,tabgroups 1.44,tabposition 1.09,sethome 1.02,gohome 1.02

there's an issue when I close all tabs: tablacus opens an empty tab with about:blank
however I'd like to set this empty tab to "This PC" instead.

![image](https://user-images.githubusercontent.com/26486758/126062820-878c5fb0-f7dc-4a32-89e6-518c4a5685a1.png)

**Comment by tablacus** [comment]
Basically, a blank page has a meaning and cannot be replaced by another path.
Please try to install the add-on "blank page".

Regards,

**Comment by tortino** [comment]
the "blank page" addon helps, but I cannot see the devices, like in "This PC" (C:, D: etc)

**Comment by tortino** [comment]
if about:blank cannot be replaced by another path then tablacus must not create the about:blank at all.
is it possible to detect when the last tab is closed? in this case you just create a new default tab, user defined, like This PC, instead of the about:blank page. this would be the best solution.
in any case I don't understand the purpose of about:blank. why it's needed?
thanks.

**Comment by tablacus** [comment]
Please try to update an add-on "Blank page" 1.01.

Regards,

**Comment by tortino** [comment]
new version is better.
thank you.
