### ISSUE TITLE
Tablacus not opening correct location when using switches

### ISSUE THREAD

**Issue by DarkLite1** [tablacus/TablacusExplorer#47]
I really love this little app and have been using it for quite some time now. However, there's a small annoyance that is still there in the newest version I just downloaded from the website.

The first time you open a path it opens correctly. The second time, when you change the path name it opens the previous path. When running the command again for a second time on the new path it does open it correctly. 

It seems like something is wrong with the switches, as it doesn't work correctly from the first time. In the PowerShell ISE you can try the following the see what I mean:

```
# Path 1 opens correctly
$linklabelHomeFolder = '\\domain.net\path1'
Start-Process 'S:\Test\Brecht\te150804\TE64.exe' -ArgumentList """Tabs,Close other tabs"" ""Open,$($linklabelHomeFolder)"""
```

Then close Tablacus and run this:

```
# Path 1 still opens instead of Path 2
$linklabelHomeFolder = '\\domain.net\path2'
Start-Process 'S:\Test\Brecht\te150804\TE64.exe' -ArgumentList """Tabs,Close other tabs"" ""Open,$($linklabelHomeFolder)"""
```

Then close Tablacus and run this again:

```
# Path 2 now opens correctly
$linklabelHomeFolder = '\\domain.net\path2'
Start-Process 'S:\Test\Brecht\te150804\TE64.exe' -ArgumentList """Tabs,Close other tabs"" ""Open,$($linklabelHomeFolder)"""
```

**Comment by tablacus** [comment]
Thank you for the report.
I'll try again look at the process of start-up.

Best regards,

**Comment by tablacus** [comment]
I've adjusted the process of start-up in Tablacus Explorer 15.8.9.
Thank you.
