### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by HyperCriSiS** [tablacus/TablacusExplorer#470]
Hi,

I am suddenly getting Script errors:
![grafik](https://user-images.githubusercontent.com/11708192/131232029-8244a67f-3206-4c07-b4e5-e99927030a5b.png)

Any idea whats the issue here?
Btw thanks for this awesome file explorer, it is simply the best. Loving this concept!

Thanks,
Hyper

**Comment by tablacus** [comment]
If you are using the add-on "Items count", please update it to the latest version.

Let me know more details.
What add-ons do you use?
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

Regards,
