### ISSUE TITLE
Issue refresh after creating new file/folder

### ISSUE THREAD

**Issue by char101** [tablacus/TablacusExplorer#471]
Hi,

Is is possible to issue a refresh after creating a new file or folder via the context menu option (New File/New Folder). This is required when browsing smb mount that does not support change notification (https://github.com/cifsd-team/ksmbd).

Action: Create new file or folder using the context menu
Result: The new file or folder is created but not visible unless the directory content is refreshed
Expect: The new file or folder to be visible automatically
Problem: The directory is a smb mount that does not support directory change notification.

Thanks.

**Comment by duarteframos** [comment]
Doesn't Force Refresh solve this issue?
https://github.com/tablacus/TablacusExplorerAddons/tree/master/forcerefresh

**Comment by tablacus** [comment]
Are you talking about in this dialog?

![image](https://user-images.githubusercontent.com/5156977/132112774-c7581e5b-b7f1-4541-b7cd-41a951be2dcb.png)

Regards,

**Comment by char101** [comment]
Yes, sorry I thought it was the default setting. I added it via Menus 🡒 Background 🡒 New File/Folder 🡒 Tools 🡒 New file/folder.

Currently I am using an external autoit script to replace the new file/folder functionality:

```autoit
#NoTrayIcon
#pragma compile(inputboxres, true)

const $Hwnd = WinGetHandle("")

FileChangeDir($CmdLine[2])

if $CmdLine[1] == "file" then
  local $Name = InputBox("File name:", "File name:", "New File.txt", "", -1, 130, Default, Default, 0, $Hwnd)
  $Name = StringStripWS($Name, 3)
  if $Name then
    if FileExists($Name) then
      MsgBox(0, @ScriptName, "File exists")
    else
      $Fh = FileOpen($Name, 1)
      FileClose($Fh)
      ControlSend($Hwnd, "", "SysListView321", "{F5}")
    endif
  endif
elseif $CmdLine[1] == "folder" then
  local $Name = InputBox("Folder name:", "Folder name:", "New Folder", "", -1, 130, Default, Default, 0, $Hwnd)
  $Name = StringStripWS($Name, 3)
  if $Name then
    if FileExists($Name) then
      MsgBox(0, @ScriptName, "File exists")
    else
      DirCreate($Name)
      ControlSend($Hwnd, "", "SysListView321", "{F5}")
    endif
  endif
else
  MsgBox(0, @ScriptName, "Invalid type")
endif
```

@duarteframos Isn't _force refresh_ only do refresh when switching tabs? It might work if _force refresh_ could trigger refresh when the list view gain focus.

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 21.9.5.
Please try to download and update.

https://github.com/tablacus/TablacusExplorer/releases/tag/21.9.5

Regards,

**Comment by char101** [comment]
Thanks, the new file/folder are visible now after creation.
