### ISSUE TITLE
Easily override/toggle portable file associations.

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#475]
I use TE portably both at home and work. I have all my file associations set up trough _Tools > Options > Menus > Default_, and it works quite well, no issues there. Some times when I move computers, I prefer to momentarily use an installed app rather than the portable one.

Currently I just go to the menu and replace whatever file extension filter with something like `-----`, but this is cumbersome and destructive, and one has to manually revert it later.

Is there an easy way to disable, toggle off or override a file association set up through the method above without totally removing it?
Maybe through javascript set up a file association with some `if` clause? Maybe make it machine name dependent, or perhaps check the existence of an exe file. Say something along the lines of pseudocode:

 `if computer.name='WORK_COMPUTER' c:/program Files/Company/Application.exe else ..\Portable\App.exe`

or

 `if file.exists'C:/program Files/Company/Application.exe' else ..\Portable\App.exe`

**Comment by tablacus** [comment]
Using VBScript, it looks like the following.

Type
```
VBScript
```
Options
```VBScript
pg = "C:\Program Files\paint.net\PaintDotNet.exe"
if fso.FileExists(pg) then
  wsh.Run PathQuoteSpaces(pg) + ExtractMacro(te, " %Selected%")
else
  wsh.Run PathQuoteSpaces(BuildPath(GetParentFolderName(te.Data.Installed), "Portable\PaintDotNet.exe")) + ExtractMacro(te, " %Selected%")
end if
```
![image](https://user-images.githubusercontent.com/5156977/135458815-b33f385f-c202-4dd0-a979-7be9264d3927.png)

Regards,

**Comment by duarteframos** [comment]
Works like a charm, excellent, this will save some daily maintenance work.

Added to [documentation about default menus](https://github.com/tablacus/TablacusExplorer/wiki/Options-Menus-Default), also took the opportunity to add some base explanation about the menu.

Feel free to point any mistakes or improvements

Thanks
