### ISSUE TITLE
When mouse over file list tooltip, the tooltip doesn't disappear on Windows 11

### ISSUE THREAD

**Issue by yuru7** [tablacus/TablacusExplorer#480]
# 不具合報告

ファイルリスト上で表示したツールチップにマウスオーバーした際、ツールチップが消えない。またツールチップが消えないことで、ツールチップが被さっている部分のリストアイテムのホバー時ハイライトが行われない。

Windows 11の端末の場合に発生。Windows 10端末では下記と同様の操作を行った場合、ツールチップ上にマウスオーバーすると即消える。

## 環境情報

```
TE64 21.11.1 Microsoft Windows 11 Pro 64 ビット 21H2 (10.0.22000) Dark IE/11 JS/11.0.16384 ja_jp 96 AMD Ryzen 5 3600 6-Core Processor               Windows Defender カスペルスキー インターネット セキュリティ カスペルスキー インターネット セキュリティ
tabcolorplus 1.04,usercss 1.06,mouse 1.31,key 1.25,toolbar 1.41,importexplorer 1.07,split 1.23,treeview 1.41,mainmenubutton 1.15,titlebar 1.09,tabs 1.25,favoritesbar 1.42,hotkey 1.01,undoclosetab 1.15,tasktray 1.15,statusbar 1.17,tabplus 1.89,tabgroups 1.44,tablist 1.03,innerbreadcrumbsaddressbar 1.49,innerfilterbar 1.32,innerback 1.13,innerforward 1.15,innerup 1.09,innerrefresh 1.06,flat 1.20,lockedtabstop 1.08,multithread 1.26,replaceslowcolumns 1.03,autodisableime 1.03,remember 1.40,clipboardimage 1.01,recentlyusedtabs 1.02,darkmode 1.09,tabname 1.07,switchpane 1.04,switchprevpane 1.02,segoeicons 1.02
```

## 再現方法

1. 適当なリストアイテムにホバーして、ツールチップを表示する
2. ツールチップにマウスオーバーする

![20211103_205937](https://user-images.githubusercontent.com/13458509/140057622-7559641d-99d2-4c2c-bad9-0b7d280d2e6d.gif)

**Comment by tablacus** [comment]
多分、Windows 11のバグだと思いますが、Windows 11のバグ対策 1.01で回避するようにしてみました。
アドオンの「Windows 11のバグ対策 1.01」をインストールしてみてください。

**Comment by yuru7** [comment]
ご対応ありがとうございます。

Windows11のバグ対策 1.01 をインストールしてみたものの、状況に変化ありませんでした…。

![image](https://user-images.githubusercontent.com/13458509/140324946-edb0bc48-18d1-4a93-ad13-a8b6899688b0.png)

![20211104_225619](https://user-images.githubusercontent.com/13458509/140326599-25f817ee-c4d3-4a21-92de-2f40d0a1ee09.gif)

**Comment by tablacus** [comment]
アドオンの「Windows 11のバグ対策 1.01」に不具合がありました。
調整したアドオンの「Windows 11のバグ対策 1.02」をインストールしてみてください。

**Comment by yuru7** [comment]
ツールチップが期待通りに消えるようになりました！
鼻につく挙動が無くなり、改めて快適になりました。大変素晴らしいです。いつもありがとうございます。
