### ISSUE TITLE
TE window does not show at the first run

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#488]
At the first run (config folder does not exist), TE window does not show up. I have to click the app again to show it. Please help to solve this problem which happens in recent versions. Thanks.

Example:

Click TE64.exe
![20211118_110044](https://user-images.githubusercontent.com/34089121/142374776-54de1f2d-7428-4daa-b512-9ae63220d313.png)
config folder appeared
![20211118_110110](https://user-images.githubusercontent.com/34089121/142374783-9bb87ce0-f548-475e-9f7e-80240b502313.png)
TE was running but it did not show up.
![20211118_110143](https://user-images.githubusercontent.com/34089121/142374784-ebbc63ce-42fb-437d-ba59-02f525863d37.png)
I have to click TE64.exe again to show it up.
![20211118_110232](https://user-images.githubusercontent.com/34089121/142374786-9f9f4b83-1c1a-46cc-8fb2-2b5174f3b3cc.png)

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 21.11.18.
https://github.com/tablacus/TablacusExplorer/releases/tag/21.11.18

Thank you as always,

**Comment by ccfs** [comment]
The problem is solved. Thanks.
