### ISSUE TITLE
script error with add-on "preview" after version 21.11.19

### ISSUE THREAD

**Issue by MasouShizuka** [tablacus/TablacusExplorer#490]
After updating to version 21.11.19, te shows the script error when the `preview` add-on is enabled, like this:
![image](https://user-images.githubusercontent.com/44764707/142745819-2ece9c44-dc56-4ae8-ab0a-4d3596ffafa9.png)

If `preview` is disabled, there will be no script error.

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 21.11.21.
Please give it try.

https://github.com/tablacus/TablacusExplorer/releases/tag/21.11.21

Regards,

**Comment by MasouShizuka** [comment]
There are no more script errors about `preview` add-on after the update.
