### ISSUE TITLE
[Feature request] treeview auto collapse after returning to the parent folder

### ISSUE THREAD

**Issue by MasouShizuka** [tablacus/TablacusExplorer#491]
Assuming that te is currently in path `D:\Test`, treeview is like this:
![image](https://user-images.githubusercontent.com/44764707/142746380-205167a7-2ed0-4d0b-8c45-132519e23f18.png)

After entering its subdirectories like `D:\Test\folder1`, treeview is like this:
![image](https://user-images.githubusercontent.com/44764707/142746402-c36b31a4-7a25-41f5-8b47-29dd16831ebb.png)

But when I return to `D:\Test` or maybe `D:\`, treeview won't collapse the list:
- return to `D:\Test`
![image](https://user-images.githubusercontent.com/44764707/142746426-8196341f-491f-471e-bc5a-f20c7b6d6afe.png)
- return to `D:\`
![image](https://user-images.githubusercontent.com/44764707/142746433-bd30e97b-e29a-4d1d-8537-2289b9340cb7.png)

I hope there is an option that allow to auto collapse the list after returning to `D:\Test` like this:
![image](https://user-images.githubusercontent.com/44764707/142746490-03dad554-bd68-4c45-ae99-4fc0e4849300.png)

I remember that `XYplorer` has a similar function like this.

**Comment by tablacus** [comment]
Please update an-add-on "Tree view" or "Side tree view".

# Tree view
Check Tools -> Add-ons -> Tree view -> General -> Collapse Folders (Auto).

![image](https://user-images.githubusercontent.com/5156977/142764751-6dc19738-50fd-4c9b-8889-06f50d542433.png)

# Side tree view
Check Tools -> Add-ons -> Side tree view -> Collapse Folders (Auto).

![image](https://user-images.githubusercontent.com/5156977/142764774-4059d9cd-9cc8-4114-9ef8-57fd3b1271c2.png)

Regards,

**Comment by MasouShizuka** [comment]
It works, thank you.
