### ISSUE TITLE
(Inner) Search crash when accentuated keyword

### ISSUE THREAD

**Issue by Lidgeu** [tablacus/TablacusExplorer#492]
**Win7 64bit Home - TE 64 - French localization** 

When you enter search argument with accentuated character(s) (frequent in French), the function crash with this error message : 
![InnerSearchProblem](https://user-images.githubusercontent.com/88983709/143315011-38dea53e-49c2-4ca2-95a4-1b224d7c8e30.jpg)

Any suggestion to fix ? ;o)

**Comment by tablacus** [comment]
I have adjusted it in Tablcus Explorer 21.11.25 and some add-ons.

Please give it try.

https://github.com/tablacus/TablacusExplorer/releases/tag/21.11.25

Regards,

**Comment by Lidgeu** [comment]
I tested.
Unfortunately not fixed :
![InnerSearchProblem_TE211125](https://user-images.githubusercontent.com/88983709/143474168-378438fc-5f18-42d4-9367-8534f74b01f4.jpg)

**Comment by tablacus** [comment]
Have you updated the Inner search bar?

**Comment by Lidgeu** [comment]
Shame on me : I did not ;o)
Update all my adds on right now and IT WORKED !!
Thanks Gaku :o))

So, I'm closing this issue as resolved.
