### ISSUE TITLE
Recent versions can no longer be launched from Quick Access Popup

### ISSUE THREAD

**Issue by duarteframos** [tablacus/TablacusExplorer#494]
Hi

Since about a couple of versions ago launching Tablcus Explorer from [QAP Quick Access Popup](https://www.quickaccesspopup.com) stopped working.

If I fully close Tablacus and try to launch it from QAP I get a spinning wheel for a few seconds but the app never opens, neither from a hotkey nor from a direct menu entry. QAP works normally once TE is open , launching from the EXE or any other app also works fine

I have an older zipper setup of version 21.10.27 lying around that still works as usual, but if I update to any more recent versions the issue manifests. Did something change recently that could have broken this?

It happens on either my work computer and home computer both running Windows 10 46bits

`TE64 21.11.26 Microsoft Windows 10 Pro 64-bit (10.0.19041) IE/11 JS/11.0.16384 en_us 96 Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz Windows Defender ESET Security ESET Endpoint Antivirus`

`mouse 1.31,key 1.25,foldersettings 1.34,tabplus 1.89,tabgroups 1.44,usercss 1.06,filtericon 1.11,tabs 1.25,mainmenu 1.16,toolbar 1.42,inactivepane 1.10,undoclosetab 1.15,searchbar 1.11,favoritesbar 1.42,flat 1.20,extract 1.14,folderlistmenu 1.15,innerbreadcrumbsaddressbar 1.49,innerfilterbar 1.33,innerback 1.13,innerup 1.09,multiprocess 1.34,innerforward 1.15,totalfilesizesort 1.12,countbar 1.11,tabname 1.07,statusbar 1.17,sethome 1.02,gohome 1.02,checkbox 1.13,protecttabs 1.05,tooltippreview 1.20,label 1.42,aboutremember 1.05,sidetreeview 1.26,titlebar 1.09,switchpane 1.04,addonsupdater 1.09,quickmenu 1.14,xfinder 1.31,dragtop 1.03,clipboardimage 1.01,synchronize 1.05,lockedtabstop 1.08,switchhiddenfilter 1.02,forcerefresh 1.07,preview 1.36`

**Comment by tablacus** [comment]
I'm not sure, but for now, run Tablacus Explorer via rundll32.exe.

Quick Access Popup
Basic Settings
Application (path and filename) *
`C:\Windows\System32\rundll32.exe`
![image](https://user-images.githubusercontent.com/5156977/144177960-72e52c4c-d3d4-46a5-9e29-ee6aa78eda5b.png)

Advanced Settings
Parameters
`shell32.dll,ShellExec_RunDLL "C:\bin\tablacus\explorer\TE64.exe"`
The path to Tablacus Explorer should be written in double quotes.
![image](https://user-images.githubusercontent.com/5156977/144178099-cd9e7d97-6d8f-498b-bd56-d30994a28386.png)

Regards

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 21.12.1. (Pre-release  version)

https://github.com/tablacus/TablacusExplorer/releases/tag/21.12.1

Please give it try.

Regards,

**Comment by duarteframos** [comment]
Couldn't get the runddll workaround to work, but the new version fixes the issue.
Thanks for the fix
