### ISSUE TITLE
Get Icon... Script Error (Add-ons)

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#495]
Dear Gaku, 

Please checkup... something is wrong with the script [Add-ons -> Get Icon]
It looks like some script errors - te211203 (initial folder)

![ScriptError-Icons](https://user-images.githubusercontent.com/60333254/144676980-3e84188e-c9d7-4d79-a7bd-9e715eba593f.jpg)

**Comment by tablacus** [comment]
Thank you for your report. 

I have adjusted it in Tablacus Explorer 21.12.4.

https://github.com/tablacus/TablacusExplorer/releases/tag/21.12.4

Regards,

**Comment by JoxCoswit** [comment]
Gaku, 

It's working like a charm! 😄

_I am closing this issue._ 

Best regards,
Jox.
