### ISSUE TITLE
Some strange selection situation in Jscript

### ISSUE THREAD

**Issue by MasouShizuka** [tablacus/TablacusExplorer#496]
In the add-on `key`, if the type is key, it will press the keys of each letter.
For example, I want to map `j` to `down` like vim, but it just presses the `d`, `o`, `w`, `n`, not the `down` key.

***So if it can map the keys like `down`, `delete`, could you tell me how to do it.***

And I write the related Jscript to achieve the function to use `j` to simulate `down`.
Here is my code:
```
let nIndex = FV.GetFocusedItem;
if (!api.SendMessage(Ctrl.hwndList, LVM_GETITEMSTATE, nIndex, LVIS_SELECTED)) {
	FV.SelectItem(nIndex, SVSI_SELECT);
} else {
	FV.SelectItem(nIndex, SVSI_DESELECT);
	nIndex = nIndex + 1;
	if (nIndex >= FV.ItemCount(SVGIO_ALLVIEW)) {
		nIndex = 0;
	}
	FV.SelectItem(nIndex, SVSI_SELECT | SVSI_ENSUREVISIBLE | SVSI_FOCUSED);
}
```
 
It works good, but recently I found a strange situations about the selection after deleting a file.
For example:
- First, selection is like this:
![image](https://user-images.githubusercontent.com/44764707/144698049-864c237c-a7c4-4f19-81bd-d59f2f47acc4.png)
- Then, I press `j` two times to move to the `新建文本文档.txt`
![image](https://user-images.githubusercontent.com/44764707/144698072-a0ca4514-e662-4203-8a11-929820b9610d.png)
- So far, it's normal. But if I delete the `新建文本文档.txt`, the selection is like this:
![image](https://user-images.githubusercontent.com/44764707/144698107-d46fda24-3926-4c0d-a216-2e82f579e562.png)
- But if I use the `down` key to do like above, the final situation is this:
![image](https://user-images.githubusercontent.com/44764707/144698181-acbaaf9f-61fc-4d26-8696-0afa638e6d7a.png)

To be honest, I don’t know much about Jscript and TablacusExplorer script api.
***Is there any problem with my code? If so, I hope you can tell me how to correct it.***
Thank you.

**Comment by tablacus** [comment]
There is no problem with your script. 
I have adjusted the workaround for it in Tablacus Explorer 21.12.4.
Please give it try.
https://github.com/tablacus/TablacusExplorer/releases/tag/21.12.4

Regards,

**Comment by MasouShizuka** [comment]
Yes, there is no strange selection like before.

By the way, in the add-on `key`, with the type of `key`, can it only can send each single char, but not some keys like `down`, `delete`?
In the `key.xml`, if I map `down` to do something, I see its key is `$150`.
So I tried to write `$150` in the textarea, but it doesn't work, `down` key is not sent.

**Comment by tablacus** [comment]
key is [SendKeys](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/sendkeys-statement) compatible.

down is `{DOWN}` 
delete is `{DELETE} or {DEL}`

You can line up more than one.
Press down twice 
`{DOWN}{DOWN}`
![image](https://user-images.githubusercontent.com/5156977/144712550-069df90a-a1cb-401e-9018-95d70213de0e.png)

If you use a script, do the following: 
```JavaScript
wsh.SendKeys("{F2}");
```

Regards,

**Comment by MasouShizuka** [comment]
I don't know the related expression before.
Thank you. Now I can do more things with TablacusExplorer.

**Comment by MasouShizuka** [comment]
Although there is no strange selection after deleting in `normal folder`,
I found the same strange selection situations in `recycle bin`:
- First
![image](https://user-images.githubusercontent.com/44764707/146130993-dea24288-b9a4-4f12-ac80-189629af77c3.png)
- Press `j` two times
![image](https://user-images.githubusercontent.com/44764707/146131030-5ad0154c-40b9-46da-8758-d6c409c53f96.png)
- Delete the `新建文本文档 - 副本 (4)`
- ![image](https://user-images.githubusercontent.com/44764707/146131064-0480d18b-04ad-429a-9db4-45080f51d3e0.png)
---

Besides, the strange selection is not only related to deletion, but also related to `other operations`.
For example:
- First
![image](https://user-images.githubusercontent.com/44764707/146131793-001a4cb9-9c08-442d-a79e-0ed31502a825.png)
- Press `j` two times
![image](https://user-images.githubusercontent.com/44764707/146131846-efc72dc6-115f-4b5e-b691-033565292924.png)
- `Shift + LeftClick` the `新建文本文档 - 副本 (6)`
![image](https://user-images.githubusercontent.com/44764707/146131923-f7be78be-3403-43a3-b651-e20def314138.png)

The above situation will appear in both `normal folder` and `recycle bin`

**Comment by tablacus** [comment]
I have adjusted the mitigation for the first Recycle Bin issue with Tablacus explorer 21.12.15.
https://github.com/tablacus/TablacusExplorer/releases/tag/21.12.15

I think the add-on Fix Selection might work well.
https://github.com/tablacus/TablacusExplorerAddons/wiki/fixselection

When I repeat SVSI_SELECT and SVSI_DESELECT, I feel that something has accumulated and is causing a problem.
It's a good idea to reset it with SVSI_DESELECTOTHERS.

```js
let nIndex = FV.GetFocusedItem;
if (!api.SendMessage(Ctrl.hwndList, LVM_GETITEMSTATE, nIndex, LVIS_SELECTED)) {
	FV.SelectItem(nIndex, SVSI_SELECT);
} else {
	nIndex = nIndex + 1;
	if (nIndex >= FV.ItemCount(SVGIO_ALLVIEW)) {
		nIndex = 0;
	}
	FV.SelectItem(nIndex, SVSI_SELECT | SVSI_ENSUREVISIBLE | SVSI_FOCUSED | SVSI_DESELECTOTHERS);
}
```

The Shift + Click issue didn't occur in my environment. 

Regards,

**Comment by MasouShizuka** [comment]
I have changed the related script with your code and installed the add-on `Fix selection on sort and update dir`.

Strange selection situations after deleting or restoring in `recycle bin` is fixed.
But in `recycle bin`, after deleting or restoring a file, the last selection disappeared (not remembered).

- In `recycle bin`:
![image](https://user-images.githubusercontent.com/44764707/146204034-3a7c270d-0092-41c5-957f-6d84048f58e4.png)
- `delete or restore`
![image](https://user-images.githubusercontent.com/44764707/146204290-ccf51a02-597f-4b9a-a00c-41187c110938.png)
- Then even if I press the `j` key, it does not respond
- If I press the `down` key, it returns to the first file:
![image](https://user-images.githubusercontent.com/44764707/146204835-fd8d7a32-a7dd-4339-b083-fb0774c3dab2.png)

---

- In `normal folder`,:
![image](https://user-images.githubusercontent.com/44764707/146205507-a9878460-576a-4f22-afa8-3d482aaecfeb.png)
- delete
![image](https://user-images.githubusercontent.com/44764707/146205570-83b15ac5-6d9d-4dd5-b9ea-c697802944e9.png)
- press the `j` key
![image](https://user-images.githubusercontent.com/44764707/146205626-52ab9372-7dee-4833-b42d-0cc012727be4.png)

So, it remembered the last selection in `normal folder`, but not in the recycle bin

**Comment by MasouShizuka** [comment]
Beside, it will lose the selection after deleting more than 3 files at the same time.

- select 3 files
![image](https://user-images.githubusercontent.com/44764707/146209356-d3e6f1f7-5f55-431d-95fb-0b5f3763cb64.png)
- delete
![image](https://user-images.githubusercontent.com/44764707/146209411-126fd0bb-40eb-42d0-862d-01739311c808.png)
- If I press the `j`, it doesn't respond
- If I press the `down` key, it returns to the first file
![image](https://user-images.githubusercontent.com/44764707/146209953-a56afb95-6944-428b-802f-7016f233569c.png)


---

Compared with 2 files:

- select 2 files
![image](https://user-images.githubusercontent.com/44764707/146209542-6874d06c-a3bf-44da-8ab7-03f3d5084802.png)
- delete
![image](https://user-images.githubusercontent.com/44764707/146210153-e8ebe5e6-f663-457e-8b7f-c7e4366cf271.png)
- press `j`
![image](https://user-images.githubusercontent.com/44764707/146210195-edb2b6ea-1318-498e-8637-cfe9e6fa0833.png)

**Comment by MasouShizuka** [comment]
By the way, I use the follow script to select multiple files:

```
let nIndex = FV.GetFocusedItem;
if (!api.SendMessage(Ctrl.hwndList, LVM_GETITEMSTATE, nIndex, LVIS_SELECTED)) {
	FV.SelectItem(nIndex, SVSI_SELECT);
} else {
	nIndex = nIndex + 1;
	if (nIndex < FV.ItemCount(SVGIO_ALLVIEW)) {
		FV.SelectItem(nIndex, SVSI_SELECT | SVSI_ENSUREVISIBLE | SVSI_FOCUSED);
	}
}
```

**Comment by tablacus** [comment]
You won't be able to use various extensions, but try to check Tools -> Options -> List -> Style -> Explorer browser.

![image](https://user-images.githubusercontent.com/5156977/146276928-0df3b06c-2ca3-46ee-ad62-ad3e2277c950.png)

Regards,

**Comment by MasouShizuka** [comment]
I found that if deleting multiple files, the focus will change to the file below the selection area.
Then because of deleting, file list will refresh, and the focus will disappear.

Is there a way to get the index above the selection area?
![image](https://user-images.githubusercontent.com/44764707/146297864-da4774c2-5014-43f3-ae13-fd7b8588d5e0.png)

I try to use the follow script to get the index:
```
FV.SelectItem(Items.Item(0), SVSI_SELECT | SVSI_FOCUSED);
let nIndex = FV.GetFocusedItem - 1;
```

If I select multiple files from bottom to top, it works correctly.
But if I select multiple files from top to bottom, `Items.Item(0)` is the bottom file, so `nIndex` is the second-to-last file index.

If I can get the correct index above the selection area, I can use the follow script to delete file with saving focus:
```
const Items = FV.SelectedItems();
const Count = Items.Count
if (Items && Count) {
	const hMenu = await api.CreatePopupMenu();
	const ContextMenu = await api.ContextMenu(Items, FV);
	if (ContextMenu) {
		await ContextMenu.QueryContextMenu(hMenu, 0, 1, 0x7FFF, CMF_DEFAULTONLY);
		await ContextMenu.InvokeCommand(0, ui_.hwnd, CommandID_DELETE - 1, null, null, SW_SHOWNORMAL, 0, 0);
	}
	api.DestroyMenu(hMenu);

        // nIndex is the index above the selection area
	FV.SelectItem(nIndex, SVSI_FOCUSED);
}
return S_OK;
```

**Comment by MasouShizuka** [comment]
After some attempts, I use the script below to delete file and restore the focus to above the selection area:
```
FV.SelectItem(-1, SVSI_FOCUSED);
const Items = await FV.SelectedItems();
const Count = Items.Count
if (Items && Count) {
	FV.SelectItem(Items.Item(0), SVSI_SELECT | SVSI_FOCUSED);
	let nIndex = FV.GetFocusedItem - 1;
	if (nIndex < 0) {
		nIndex = 0;
	}

	const hMenu = await api.CreatePopupMenu();
	const ContextMenu = await api.ContextMenu(Items, FV);
	if (ContextMenu) {
		await ContextMenu.QueryContextMenu(hMenu, 0, 1, 0x7FFF, CMF_DEFAULTONLY);
		await ContextMenu.InvokeCommand(0, ui_.hwnd, CommandID_DELETE - 1, null, null, SW_SHOWNORMAL, 0, 0);
	}
	api.DestroyMenu(hMenu);

	FV.SelectItem(nIndex, SVSI_FOCUSED);
}
```

**Comment by tablacus** [comment]
You can retrieve items in view order by using `Items(SVGIO_SELECTION | SVGIO_FLAG_VIEWORDER)` instead of `SelectedItems()`. 

```js
const Items = FV.Items(SVGIO_SELECTION | SVGIO_FLAG_VIEWORDER);
const Count = Items.Count
if (Items && Count) {
	const hMenu = await api.CreatePopupMenu();
	const ContextMenu = await api.ContextMenu(Items, FV);
	if (ContextMenu) {
		await ContextMenu.QueryContextMenu(hMenu, 0, 1, 0x7FFF, CMF_DEFAULTONLY);
		await ContextMenu.InvokeCommand(0, ui_.hwnd, CommandID_DELETE - 1, null, null, SW_SHOWNORMAL, 0, 0);
	}
	api.DestroyMenu(hMenu);

    // nIndex is the index above the selection area
	FV.SelectItem(nIndex, SVSI_FOCUSED);
}
return S_OK;
```

Regards,

**Comment by MasouShizuka** [comment]
I changed the script as below to get the index above the first selection:
```Javascript
const Items = FV.Items(SVGIO_SELECTION | SVGIO_FLAG_VIEWORDER);
const Count = Items.Count;
if (Items && Count) {
	FV.SelectItem(Items.Item(0), SVSI_SELECT | SVSI_FOCUSED);
	let nIndex = FV.GetFocusedItem - 1;
	if (nIndex < 0) {
		nIndex = 0;
	}

	const hMenu = await api.CreatePopupMenu();
	const ContextMenu = await api.ContextMenu(Items, FV);
	if (ContextMenu) {
		await ContextMenu.QueryContextMenu(hMenu, 0, 1, 0x7FFF, CMF_DEFAULTONLY);
		await ContextMenu.InvokeCommand(0, ui_.hwnd, CommandID_DELETE - 1, null, null, SW_SHOWNORMAL, 0, 0);
	}
	api.DestroyMenu(hMenu);

	FV.SelectItem(nIndex, SVSI_FOCUSED);
}
```

But to be honest, it feels a little inefficient.
I don't know how to get the `index` directly from the `item`, so I tried to use `FV.SelectItem(Items.Item(0), SVSI_SELECT | SVSI_FOCUSED)` to focus the first `item`, then get the `index` of first `item`.

Is there a way to get the `index` from the `item`?

**Comment by tablacus** [comment]
I don't know how to get the index directly from the item. 
There is a way to get the Index of the top selected item.
```js
const Items = FV.Items(SVGIO_SELECTION | SVGIO_FLAG_VIEWORDER);
const Count = Items.Count;
if (Count) {
	const nIndex = Math.max(api.SendMessage(FV.hwndList, LVM_GETNEXTITEM, -1, LVIS_SELECTED), 0);
	const hMenu = await api.CreatePopupMenu();
	const ContextMenu = await api.ContextMenu(Items, FV);
	if (ContextMenu) {
		await ContextMenu.QueryContextMenu(hMenu, 0, 1, 0x7FFF, CMF_DEFAULTONLY);
		await ContextMenu.InvokeCommand(0, ui_.hwnd, CommandID_DELETE - 1, null, null, SW_SHOWNORMAL, 0, 0);
	}
	api.DestroyMenu(hMenu);

	FV.SelectItem(nIndex, SVSI_FOCUSED);
}
```

**Comment by MasouShizuka** [comment]
Your script looks more straightforward, without additional operations.
Thank you.
