### ISSUE TITLE
Wrong column size with auto column size in some folder

### ISSUE THREAD

**Issue by MasouShizuka** [tablacus/TablacusExplorer#497]
I use the auto column size script with add-on  `folder settings`:
```
FV.SetViewMode(4,16);
FV.Columns ='"System.ItemNameDisplay" -2 "System.DateModified" -2 "System.Size" -2 "System.ItemTypeText" -2';
FV.GroupBy='System.Null';
FV.SortColumn='System.ItemTypeText';
```

It works good, but if I set the date format like this:`yyyy-MM-dd HH:mm`
- In ***some folders***, the column of date is like this:
![image](https://user-images.githubusercontent.com/44764707/144729502-f14aa20a-e666-4624-bfe0-e7cc63fc5c6b.png)
- Strangely, it is ***normal*** in ***other folders***:
![image](https://user-images.githubusercontent.com/44764707/144729601-39013885-64c5-4857-ad08-be16bbc3503c.png)
- If I delete the date setting, it is normal:
![image](https://user-images.githubusercontent.com/44764707/144729661-40a5625d-6f51-4405-9407-83b1bc446ac1.png)

To be honest, I don't know the difference between the two kinds folders.

---

There is another problem.
The minimal column size is `113 x 26`:
![image](https://user-images.githubusercontent.com/44764707/144729756-99665a24-760c-4378-97ff-45b858f4c7db.png)
It causes the columns of size and type can't be reduced to the actual maximum column size of all sizes and types of all files.

I wish it can fit like this:
![image](https://user-images.githubusercontent.com/44764707/144729944-cbf3b55e-9773-4012-aad8-a3ca1eed1eb7.png)

**Comment by tablacus** [comment]
The following script contains a workaround.
* Tablacus Explorer 21.12.5 is required.
https://github.com/tablacus/TablacusExplorer/releases/tag/21.12.5
```javascript
FV.SetViewMode(4,16);
FV.Columns='"System.ItemNameDisplay" -2 "System.DateModified" -2 "System.Size" -2 "System.ItemTypeText" -2';
FV.GroupBy='System.Null';
FV.SortColumn='System.ItemTypeText';
setTimeout(function () {
  api.SendMessage(FV.hwndList, LVM_SETCOLUMNWIDTH, 1, -1);
  const col = api.Memory("LVCOLUMN");
  col.mask = 0x40;
  col.cxMin = 0;
  api.SendMessage(FV.hwndList, LVM_SETCOLUMN, 2, col);
  api.SendMessage(FV.hwndList, LVM_SETCOLUMNWIDTH, 2, -1);
 });
```
![image](https://user-images.githubusercontent.com/5156977/144750707-260e2507-13e7-4120-8689-e06d1bf0661e.png)

MS does not want to change the minimum width of the column, so the minimum width will be restored immediately.

Regards,

**Comment by MasouShizuka** [comment]
Date column is normal now.

I have seen that after I resize the column over 113, the minimal size is still 113 and can't be adjusted below 113.
But that’s not a problem, after all, I won’t manually adjust the column size, with auto column size script.

Thank you.
