### ISSUE TITLE
Script Error on opening, Unable to get property 'ToLowerCase'.

### ISSUE THREAD

**Issue by EDGE-ELITE** [tablacus/TablacusExplorer#498]
Hi there,

Upon opening Tablacus Explorer, I receive an error which states the following:

![TE64_andWVpBCEu](https://user-images.githubusercontent.com/25804147/144755578-d2f0e0e9-92f5-4fdf-877d-b8ccb171fc6b.png)
:

Clicking yes will allow the program to open, and it does appear to run normally, albeit, with graphical refresh issues and occasionally similar error messages reappearing.

EDIT:
To clarify, I'm running Windows 10 Pro (64-bit).

**Comment by tablacus** [comment]
Let me know more details.
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

Regards,

**Comment by EDGE-ELITE** [comment]
> Let me know more details. https://github.com/tablacus/TablacusExplorer/wiki/report-problem
> 
> Regards,

Apologies, yes of course:

Information:
`TE64 21.12.2 Microsoft Windows 10 Pro 64-bit 21H2 (10.0.19044) Dark IE/11 JS/11.0.16384 en_gb 96 AMD Ryzen 5 2600X Six-Core Processor            Windows Defender`

Add-ons
`mouse 1.32,key 1.26,addressbar 1.68,back 1.18,forward 1.18,up 1.20,toolbar 1.42,mainmenu 1.16,titlebar 1.09,tabplus 1.89,multithread 1.27,remember 1.40,undoclosetab 1.15,tabgroups 1.44,tabcolorplus 1.04,darkmode 1.12,tabname 1.07,tabcolor 1.08,addonsupdater 1.09,tabgroupsbutton 1.02,countbar 1.11,sizestatus 1.19,statusbar 1.17,sorttabs 1.04,tasktray 1.15,tabs 1.25,segmdl2 1.01,clipboardimage 1.01,tooltippreview 1.20,autoupdate 1.03,font 1.20,framepane 1.02,everything 1.44,split 1.23,totalfilesizesort 1.12,duplicatecopy 1.11`

I have the installation location set to:
`C:\Users\USERNAME\Documents\Tablacus\`

I hope that helps.
- Kind regards.

**Comment by tablacus** [comment]
Thank you for information.
I have adjusted it in Tool bar 1.43.
Please try to update an add-on "Tool bar".

Regards,

**Comment by EDGE-ELITE** [comment]
> Thank you for information. I have adjusted it in Tool bar 1.43. Please try to update an add-on "Tool bar".
> 
> Regards,

Yes, that's solved it!

Thank you very much Gaku.
