### ISSUE TITLE
Script error upon "Get language"

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#499]
Please help to solve this problem. Thanks.
![20211207_112808](https://user-images.githubusercontent.com/34089121/144961030-eec2784f-7bd8-4ccc-8ad7-b2b267f97f2d.png)
![20211207_112749](https://user-images.githubusercontent.com/34089121/144961039-f89591d8-a994-4534-bc1f-141ebb2113b2.png)

**Comment by tablacus** [comment]
JSON was broken.
I've fixed it so please give it a try. 

Regards,

**Comment by ccfs** [comment]
The problem is solved. Thanks.
