### ISSUE TITLE
French language

### ISSUE THREAD

**Issue by Cromagnon31** [tablacus/TablacusExplorer#50]
Dear gaku,

I translate Tablacus Exporler to french.language.
But I don't know how to upload xml or zip file then I put the xml file in a docx container.
[tablacus_fr.docx](https://github.com/tablacus/TablacusExplorer/files/44373/tablacus_fr.docx)

Send me an email in case of problem.

"systray" markup in english language is erroneous -> "sysray"

Some markers are not explicit for me :
"Hot track"
"Single selection"
"No client edge"
"Run Dialog"
"Shell Browser"
"Explorer Browser"

Best regards,

Olivier Wuillemin

**Comment by Cromagnon31** [comment]
Header corrected...
[tablacus_fr.docx](https://github.com/tablacus/TablacusExplorer/files/44385/tablacus_fr.docx)

**Comment by tablacus** [comment]
I'm very glad for you.

I have received French language file without any problem.
I will probably explain these words later because I will go the work soon.

Thank you.

**Comment by tablacus** [comment]
# "Hot track"
Items under the pointer are automatically highlighted.

 TCS_HOTTRACK
 https://msdn.microsoft.com/fr-fr/library/windows/desktop/bb760549(v=vs.85).aspx

# "Single selection"
Do not allow more than a single item to be selected.

 FWF_SINGLESEL
 https://msdn.microsoft.com/fr-fr/library/office/bb762508.aspx

# "No client egde"
The window has not a border with a sunken edge.

 FWF_SINGLESEL
 https://msdn.microsoft.com/fr-fr/library/office/bb762508.aspx
 WS_EX_CLIENTEDGE
 https://msdn.microsoft.com/fr-fr/library/windows/desktop/ff700543%28v=vs.85%29.aspx

# "Run Dialog"
Display the RUN Dialog box.
#unnamed function "SHRunDialog"

# "Shell Browser"
Classic Explorer (Windows Vista and lower)

# "Explorer Browser"
Modern Explorer (Windows 7 or higher)

Merci.

**Comment by Cromagnon31** [comment]
Thank you for the explanations.

The latest version with minor changes.
[tablacus_fr.docx](https://github.com/tablacus/TablacusExplorer/files/45197/tablacus_fr.docx)

Thank you  too !

**Comment by tablacus** [comment]
I've updated Tablacus Explorer 15.11.27 with this change.

Thank you.
