### ISSUE TITLE
Typo in index.js

### ISSUE THREAD

**Issue by KZIII** [tablacus/TablacusExplorer#500]
Hi.
I think there's a typo in index.js

line 447 (ver 21.12.4)

document.addEventListener("FullscreenChange", function () {
	FullscreenChanged(document.fullscreenElement != null);
});

wrong: "FullscreenChange"
right: "fullscreenchange"

How about?

Thank you and regards,

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 21.12.7.
https://github.com/tablacus/TablacusExplorer/releases/tag/21.12.7
Thank you,

**Comment by duarteframos** [comment]
@KZIII Is it solved for you? If so could you close the issue?

**Comment by KZIII** [comment]
Oh, sorry.
This issue is solved.

Thank you, Gaku san.
