### ISSUE TITLE
Status bar 1.18 - Internal Bottom Bar vs. Bottom Bar (different behavior on different positions)

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#506]
I would ask for a little checking:

- When "**Status bar 1.18**" is located in "**Internal Bottom Bar**"  and **something is selected** - the **date is displayed**
- When "**Status bar 1.18**" is located in "**Bottom Bar**"  and **something is selected** - **selected items is displayed**

So, the same version - if located in different  locations, shows different values.

_Explanation of how the images of examples are sorted_ 
1. VER OF STATUS BAR  
2. POSITIONS
3. SELECTED ITEMS 
4. RESULT

**Example1**: Internal Bottom Bar - display DATE   
![EXAMPL1](https://user-images.githubusercontent.com/60333254/145698178-9d7c8c18-bfd9-49e0-be9f-f4407e46fc4b.jpg)

**Example2**: Bottom Bar - display SELECTED ITEMS
![EXAMPL2](https://user-images.githubusercontent.com/60333254/145698183-4d688511-7e2e-4062-ae3a-5f546e55feac.jpg)

Regards,

**Comment by tablacus** [comment]
I have adjusted it in Status bar 1.19.
Please give it try.

Regards,

**Comment by JoxCoswit** [comment]
Yes, now is working how it should. Thanks! 😉

Speaking of that.... can you please check what I noticed earlier about delete icon size? Is it, perhaps, related somehow?
As I commented before it is strange to me that the delete icon shrinks when it is in another position (normal size, without manual changing value) but when I place to internal bottom bar its shrinks, and its must be put default size number.

So far, I haven't noticed anything strange, but if not trouble, to check also the "Size Status Bar".
To be sure is anything else needs to modify. As I said, when he is put in another position, it starts behaving quite differently!?


**Example 1:** - **INTERNAL BOTTOM BAR**
![Example1](https://user-images.githubusercontent.com/60333254/145714903-d55b9cb0-ae74-4574-a99d-12d4eb3377cc.jpg)

**Example 2:** - **BOTTOM BAR**
![Example2](https://user-images.githubusercontent.com/60333254/145714916-e8971c59-73e1-4731-b206-cd40a269b502.jpg)


Regards,

**Comment by JoxCoswit** [comment]
**Additional comment:**

It is not a problem to enter value but if someone will use the same thing it will be defenitly confused like me because it did not behave as expected, or like before. In my opinion it doesn’t matter, where it place, or is in which position be place - it is important that the same functionally, works every equally. 

**Except**: If not it is intended to behave differently on diffent position or there are some other limitations which is not allowed to be different (_for example: to keep the same size_) or cannot maintain everywhere the same behavior as its used before that.


Regards.

**Comment by JoxCoswit** [comment]
I saw in today's version that it was added "Internal Tool Bar Icon", under "General tab".
That would be now applies generally to all the Add-ons which contained that part-that's okay.
I also updated the latest Add-ons, and adjusted the layout at the bottom bar.

I tried all of that and it works properly now. Thank you! 😊

_I am closing this issue._

Regards,
Jox.
