### ISSUE TITLE
Is there a setting about returning to the left tab after closing the tab?

### ISSUE THREAD

**Issue by MasouShizuka** [tablacus/TablacusExplorer#510]
TE returns to the right tab after closing the tab by default, like this:
- before:
    - ![image](https://user-images.githubusercontent.com/44764707/146111814-12dc3aaa-8197-4be3-86a7-0c6d6e67ef6c.png)
- after:
    - ![image](https://user-images.githubusercontent.com/44764707/146111899-a18ab3d8-6c31-411d-9bd3-c9f133b85e7e.png)

Can it return to the left tab after closing the tab?
- after:
    - ![image](https://user-images.githubusercontent.com/44764707/146112015-ee96ca28-31ec-43cc-a979-68db5e2a800a.png)

**Comment by tablacus** [comment]
Please try to install an add-on "Tab position".

https://github.com/tablacus/TablacusExplorerAddons/wiki/tabposition

Regards,

**Comment by MasouShizuka** [comment]
OK. Maybe I should look for the plugin more carefully first.
Thank you.
