### ISSUE TITLE
2 problems of TE 21.12.14

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#511]
Please help to solve the problems. Thanks.

1. After a certain button is clicked, a menu shows but sometimes at a wrong position.
![test](https://user-images.githubusercontent.com/34089121/146116132-175895be-660d-4031-b0c4-82370846d2ac.png)
![remove](https://user-images.githubusercontent.com/34089121/146116139-9d854a46-d29e-4e6a-b5f0-f9701274f6b0.png)

2. It is now LESS convenient to choose a second level item of Options tree.
![20211215_104456](https://user-images.githubusercontent.com/34089121/146116277-3204ada9-491a-4037-8513-82d4ebab0afb.png)
![20211215_104522](https://user-images.githubusercontent.com/34089121/146116283-e96abb0e-c901-44b2-ab06-c52bbf385c72.png)

**Comment by tablacus** [comment]
I have adjusted them with Tablacus Explorer 21.12.15.

https://github.com/tablacus/TablacusExplorer/releases/tag/21.12.15

Thanks always,

**Comment by ccfs** [comment]
The problems are solved in the new version. Thanks.
