### ISSUE TITLE
FTP problems

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#518]
Please help to solve 4 problems about FTP. Thanks.

**1. Incorrect Back page if no ending slash is specifed**

Open an ftp in a NEW TAB
![1](https://user-images.githubusercontent.com/34089121/147027456-d78f5f49-9c0c-491e-8208-3b5221f27343.png)
There is an incorrect Back page with the port number.
![2](https://user-images.githubusercontent.com/34089121/147027462-4e589a5b-47b8-476a-a629-347c997382e2.png)

Open an ftp in a NEW TAB but with ending slash specified
![1](https://user-images.githubusercontent.com/34089121/147028110-664efcdb-f69c-4ef0-91c8-b70ced987cec.png)
No problem
![2](https://user-images.githubusercontent.com/34089121/147028113-67bf0932-fe55-4823-854d-0a32a880f785.png)

Open an ftp in CURRENT TAB
![1](https://user-images.githubusercontent.com/34089121/147027969-73fb6acc-8b80-4f3e-9b90-49a1491f0644.png)
No problem
![2](https://user-images.githubusercontent.com/34089121/147027974-c0ccb81a-1061-4924-9b6b-cf32ce6b132a.png)

**2. Better to use the same icon as folder tree**

![20211222_103341](https://user-images.githubusercontent.com/34089121/147028465-02b67946-8a69-430d-a552-9fc08672c493.png)

**3. A file is incorrectly regarded as a folder in address bar.**

![20211222_100734](https://user-images.githubusercontent.com/34089121/147028635-3f31e234-31dc-4fe3-b6f9-5bbb6e58a8b1.png)

**4. An error occurs if "Remember folder view settings" add-on is ENABLED.**

![0](https://user-images.githubusercontent.com/34089121/147029314-1e8d7e04-3b4c-48d4-9f52-20b10fb0ee87.png)
![1](https://user-images.githubusercontent.com/34089121/147029043-67a22eee-dd7c-458c-9f72-85e797a3bbd4.png)
![2](https://user-images.githubusercontent.com/34089121/147029046-4f245ee9-6b31-4e20-bb23-c6475a11306a.png)
Note that TE incorrectly treated ftp as a result list, but the "Folder path" column is not available.
![3](https://user-images.githubusercontent.com/34089121/147029047-bc3646cc-b697-4966-a0b9-2d406c04932a.png)

**Comment by tablacus** [comment]
MS FTP does not have a "folder path". 
![image](https://user-images.githubusercontent.com/5156977/147099978-95965ee0-8f9f-48a2-9a81-970d9fd2eeb2.png)

Regards,

**Comment by ccfs** [comment]
I have tried TE 21.12.22. Problem 2 (icon) and 3 (file/folder) are solved.

Problem 4 (error in "remember") is solved partially. It does not happen if ftp is opened in current tab. However, it still happens in NEW TAB.
![20211223_170818](https://user-images.githubusercontent.com/34089121/147218165-65949767-4efd-4e1d-b3c1-8ef48fecf2d0.png)
![20211223_170841](https://user-images.githubusercontent.com/34089121/147218170-2e2b62bc-a193-4aa1-8241-7ff2a2f024c4.png)

Problem 1 still happens. I suspect that it is due to the ENDING SLASH.

Windows Explorer shows that the ftp address has an ending slash, even when I have not entered any.
![20211223_165021](https://user-images.githubusercontent.com/34089121/147219621-c1d35fb3-61d5-47f3-a1c2-8b72133c3345.png)

I think that TE may need to do the same: Automatically append a slash if the user have not entered any.

Regards,

**Comment by ccfs** [comment]
I have tried TE 21.12.23. Problem 1 (incorrect back page) is solved.

Problem 4 ("remember" error) is still solved partially. If ftp is opend in a NEW TAB and there is not any "remember" record for the item, TE incorrectly shows the "Folder path" column, though no error messge shows.
![20211224_113036](https://user-images.githubusercontent.com/34089121/147313278-be751013-27e9-46bc-9844-041b21144d72.png)

Wish you a merry Christmas!

**Comment by ccfs** [comment]
The problems are solved in TE 21.12.24. Thanks.
