### ISSUE TITLE
Please how to identify corrupted/damaged files?

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#526]
**Corrupted/damaged files?**

- Can you explain to us how we could notice-spot the corrupted/damaged file?
- What are the indication, and how to recognize what it is happens... if something like that might occur?
- What do you expect to happen in that case?
- Can you give some examples - how this could be manifested on daily working progress?
- How to distinguish something like that from a regular error/bugs?

As I said last time I will report every thing that is strange or odd to me.
In this case I see you are expecting something but unfortunately I don't know what exactly you expected.
So I would like to know approximately becasue I will pay more attention what is going on with BETA version according to your instructions.

_Thank you for your help and support as always!_

**Comment by tablacus** [comment]
I created an additional one that uses DOMParser to read the XML and XMLSerializer to write it in Tablacus Explorer 21.12.30.
This is intended to speed up the Blink version.
Pay attention to the settings stored in XML. 

Regards,

**Comment by JoxCoswit** [comment]
Okay I'll pay attention if there are any unwanted changes or I find anything that is suspicious/different.
As far as I understood this could affect on settings and they would not be as before and there would be unwanted or unexpected differences.

Regards, 
Jox.
