### ISSUE TITLE
Suggestion for the "tabgroup" add-on

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#530]
Hello. I know that tab groups can be saved and loaded, but my suggestion is that clicking the button or tab for a given tab group opens the original tabs of that group, thus closing all other tabs that were have opened and are not part of the original group. This saves the trouble of having to load the saved group of tabs. Thank you.

**Comment by dieg467** [comment]
Hello Gaku. Is there a procedure so that clicking on a tab in a "Tab Group" will load the original saved tab set? Thanks a lot.

**Comment by tablacus** [comment]
You can load the saved tab layout by placing the "Load layout" button on the toolbar.

![image](https://user-images.githubusercontent.com/5156977/151176735-ac1ddfb3-7846-4102-82ef-a0457f46236b.png)

Regards,

**Comment by duarteframos** [comment]
Hey this is pretty interesting.
Can I make it load as a new tab so that it opens a new layout without closing currently open ones?

Can I make a menu entry in _Folder List Menu_ addon that does this same task of loading a new layout?

**Comment by dieg467** [comment]
Great Gaku, that was exactly what I needed. With a button on the toolbar, I access my saved "group of tabs". And if I have multiple groups of tabs, I make a button for each group. Thanks!

**Comment by dieg467** [comment]
> Oye, esto es bastante interesante. ¿Puedo hacer que se cargue como una nueva pestaña para que abra un nuevo diseño sin cerrar los abiertos actualmente?
> 
> ¿Puedo hacer una entrada de menú en el complemento _Menú de lista de carpetas_ que haga la misma tarea de cargar un nuevo diseño?

Hello duarteframos. Something similar to what you are asking for would be to create an entry in the horizontal favorites bar (you must have the “horizontal favorites bar” add-on installed), where a submenu made up of all the saved designs is placed. Instead of having buttons in the toolbar, you will have a submenu in the favorites bar.
The steps to follow are:
1) Create a design and save it, going to Tools --> Save design.
2) Favorites --> Edit. See how to create a file/subfolder submenu in the favorites bar here: https://github.com/tablacus/TablacusExplorer/issues/271
3) Load the design in the submenu in the same way that Gaku explains here, in this query.
4) Repeat the previous step for each of the saved designs.

A similar procedure can be done with the “link bar” add-on. It's not exactly what you ask for, but I hope it can help you. Greetings.

**Comment by ccfs** [comment]
I suggest a more convenient way: Add a RELOAD option to Tab Group menu. If a group has been loaded/saved from/to an XML file, the option will be enabled. When chosen, the group will be wiped out and be replaced from the XML file.

Regards,

**Comment by ccfs** [comment]
The "Load layout" method suggested by @tablacus will replace the WHOLE TE SESSION, not only a group.

Regards,

**Comment by duarteframos** [comment]
Yes, that as @ccfs  mentions the issue is it replaces all currently loaded layouts, rather than open a new tab.
I suspect it might be possible to do with scripting. Probably the equivalent of the option _Load Layout_ when right clicking a group tab, but I have no idea how.

**Comment by dieg467** [comment]
> Sugiero una forma más conveniente: agregue una opción RECARGAR al menú Grupo de pestañas. Si un grupo ha sido cargado/guardado desde/a un archivo XML, la opción estará habilitada. Cuando se elige, el grupo se borrará y se reemplazará del archivo XML.
> 
> Saludos,

Hello ccf. Using the tabgroup add-on I can create a bar with layout tabs, each tab is a layout. What I was looking for is that clicking on each tab would reload the original layout. I don't know how to add the "RELOAD" option.

**Comment by dieg467** [comment]
> Sí, como menciona @ccfs , el problema es que cuando se carga desde un menú, reemplaza todos los diseños cargados actualmente, en lugar de abrir una nueva pestaña. Sospecho que podría ser posible codificar una entrada de menú con secuencias de comandos que cargarán una pestaña adicional. Probablemente el equivalente a la opción _Cargar diseño_ al hacer clic derecho en una pestaña de grupo, pero no tengo idea de cómo.

Hello, for that you have to use the "tabgroup" add-on. With this plugin you can create a layout bar, where each layout can be opened from its tab (or button). Also, each design can be saved for reloading.

**Comment by ccfs** [comment]
The RELOAD option is my suggested enhancement, which does not exist yet.

**Comment by dieg467** [comment]
> La opción RECARGAR es mi mejora sugerida, que aún no existe.

Ok, that's a good idea to add to the "tab group" context menu.

**Comment by dieg467** [comment]
> Oye, esto es bastante interesante. ¿Puedo hacer que se cargue como una nueva pestaña para que abra un nuevo diseño sin cerrar los abiertos actualmente?
> 
> ¿Puedo hacer una entrada de menú en el complemento _Menú de lista de carpetas_ que haga la misma tarea de cargar un nuevo diseño?

Using the "Tab group" add-on several tab layouts can be created and saved. Once the add-on is installed, follow these steps:
1st) Select the tabs of the design you want to create.
2º) Right click on the button/tab "Group 1" to change the name of the group and to save it.
3º) Repeat the previous steps to create new designs, each one from a new button/tab (group 2, group 3, etc) in the tabgroup bar.
In this way, several designs can be used at the same time.
If other tabs were opened in a design that are not part of the original design, to recover the original design, right-click on the corresponding design button/tab and load it.

**Comment by ccfs** [comment]
The Reload function has been added to the [patch version](https://github.com/tablacus/TablacusExplorer/issues/692).

**Comment by dieg467** [comment]
Excellent CCFS. Thank you so much for adding this requested option!
