### ISSUE TITLE
Correct way to add a button that opens a CMD window in the current folder

### ISSUE THREAD

**Issue by kettenfett** [tablacus/TablacusExplorer#531]
Hi,
In Tablacus, what is the correct way to add a button that opens a CMD window in the currently opened folder of the active/focussed tab?
I need this functionality very often, multiple times a day. How can it be done?`

I have the toolbar addon installed. but I don't know how to do it.

Thank you.

**Comment by tablacus** [comment]
1. Click "+"(Add) button
![image](https://user-images.githubusercontent.com/5156977/148685331-0b620cf1-9dd7-4a74-bac9-3d2db1854350.png)

2. Enter `CMD` to Name.
3. Choose `Exec` in Type.
4. Enter `cmd /k cd /d %Current%` to Options
5. Click Save and OK.
![image](https://user-images.githubusercontent.com/5156977/148685811-971537dc-f54d-456b-98bd-9c818ce7a499.png)

Regards,

**Comment by kettenfett** [comment]
Works like a charm.

Thank you.

**Comment by kettenfett** [comment]
Closing this.

**Comment by tablacus** [comment]
Another way

1. Enter `CMD` to Name.
2. Choose `Backgound` in Type.
3. Enter `cmd` to Options
4. Click Save and OK.

![image](https://user-images.githubusercontent.com/5156977/148759647-5d13b1f6-5b07-4f94-aed9-0519983b9941.png)

**Comment by kettenfett** [comment]
For reference: 
I just noticed, there's also a neat way to get a powershell window instead of a Cmd-Window. For this, just enter "powershell".

![grafik](https://user-images.githubusercontent.com/23098362/148776298-9168aeb4-d970-4b89-97bd-c7b2405eaf8c.png)

**Comment by yuraloginoff** [comment]
In case of **PowerShell 7**:

Type: `Exec`
Options: `pwsh -NoExit -Command "cd %CURRENT%"`
