### ISSUE TITLE
2 problems about "Discovering items..." in a sub-menu

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#533]
Please help to solve 2 problems. Thanks.

**Problem 1: Parent menu disappears or flashes**

Go to a menu with a sub-menu showing a "Discovering items..." message
![1](https://user-images.githubusercontent.com/34089121/148709285-48d019b3-4e22-45bb-935f-e781cc962500.png)
Move to another menu item BEFORE the discovery completes
![2](https://user-images.githubusercontent.com/34089121/148709288-f3d9814f-a711-468b-9d44-3b84111ffdb3.png)
The menu unexpectedly disappears (sometimes it re-appears).
![3](https://user-images.githubusercontent.com/34089121/148709290-609f5991-0ba9-440e-8d9e-9912274d2963.png)

**Problem 2: Incorrect "Discovering items..."**

The main menu incorrectly shows some "Discovering items..." when "Main menu button" add-on is used
![1](https://user-images.githubusercontent.com/34089121/148709643-758c52dc-a7f4-4081-a983-db0f98792115.png)
![2](https://user-images.githubusercontent.com/34089121/148709645-1e9c13d1-2285-40da-b3ee-005031273e1d.png)
![3](https://user-images.githubusercontent.com/34089121/148709646-937b5fca-3787-4b3c-99c2-9869f7d5b3e5.png)
![4](https://user-images.githubusercontent.com/34089121/148709647-52b8a520-ad1c-4f7a-97e9-8ec5469a66bf.png)

**Comment by kettenfett** [comment]
I was able to reproduce Problem 1, as described above.

**Comment by ccfs** [comment]
The problems are solved in TE 22.1.10 and "Main menu button" 1.16. Thanks.

**Comment by ccfs** [comment]
"Discovering items..." problem is found in another 2 add-ons:
- Label
- Menu image plus
 
![label](https://user-images.githubusercontent.com/34089121/150236264-af785d79-3cb9-4f65-bcf7-3ad622953e04.png)
![menuimageplus](https://user-images.githubusercontent.com/34089121/150236267-2e3eb826-0547-453f-bb16-568efd7b2b45.png)

**Comment by ccfs** [comment]
The problem are solved in the new versions. Thanks.
