### ISSUE TITLE
Something is wrong with keyboard input?

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#534]
Please can you check... I can't use keyboard with 22.1.10 (10.1.2022)
I try on my PC and on my LAPTOP. The problem is identical! Thanks.

**For example:** 

- Tools -> Options -> Try to insert value into box "**Left bar Width**"

or 

- Try to create "**New folder**" and insert something with keyboard.

Regards, 
Jox.

**Comment by ccfs** [comment]
I have the same big problem. ALL TEXT BOXES are dead.

**Comment by JoxCoswit** [comment]
Now is working again! 😊
Checked with today's newest version - 22.1.11 (11.1.2022)

_This issue will be closed._

Regards, 
Jox.
