### ISSUE TITLE
Auto-Update not working

### ISSUE THREAD

**Issue by kettenfett** [tablacus/TablacusExplorer#539]
I get this when trying to auto-update from 22.1.7.

This process seems to work
![grafik](https://user-images.githubusercontent.com/23098362/149660386-eda4bcf2-5b36-4992-a99f-9c0f589a05f5.png)

but after this, I get:
![grafik](https://user-images.githubusercontent.com/23098362/149660388-50545d95-b3d5-4102-b5bf-82e2728d1283.png)

"There is no script module for the js extension"

**Comment by tablacus** [comment]
I have not encountered it.
Are not the files quarantined by security software?

Regards,

**Comment by kettenfett** [comment]
I don't use any virus program or firewall other than windows defender.

**Comment by kettenfett** [comment]
It worked.
I just had to enter assoc .js=JSFile into an elevated command prompt.

Thx for providing the solution.
