### ISSUE TITLE
Enhancement - Address and type columns regarding network

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#540]
If a network path is entered for navigation, some address and type columns will be empty for
- network computer
- network share
- FTP site
- FTP folder

Please enhance TE so that these columns are available for sorting and column filtering (blue text below), especially in result lists. Thanks.
![history](https://user-images.githubusercontent.com/34089121/149854111-1d5ffcf0-ef8e-45f0-94c3-bcf9dbc48f9c.png)

Please note that if the same path is navigated through a "Network Shortcut", the columns will be available and can be retained.
![computer](https://user-images.githubusercontent.com/34089121/149855011-87ba741b-f6f4-4961-810a-08a142048b78.png)

**Comment by tablacus** [comment]
1.
I have created an add-on "Path column".
Please give it try.

2. Check Link target / Network location
![image](https://user-images.githubusercontent.com/5156977/149952746-51547c04-faaa-45d9-9262-debb20a213a8.png)

Regards,

**Comment by ccfs** [comment]
I have tried the add-on but it is far from enough.
"Type", "Folder path", "Folder name" and "File name" are still missing.
![history](https://user-images.githubusercontent.com/34089121/150079954-e84d4f32-a54a-48a1-b680-a5f43d83b197.png)
Sorting and column filtering do not work.
![filter](https://user-images.githubusercontent.com/34089121/150079960-b6f015ac-0d55-4008-8f62-c9a7cbcaf8a5.png)

**Comment by ccfs** [comment]
I have tried TE 22.1.19 with "Path column" 1.01. They are better but still not good enough.
- "Type", "Folder path" and "Folder name" are still missing.
- Column filtering is OK, but sorting does not work correctly.

![report](https://user-images.githubusercontent.com/34089121/150263907-a3d73f1b-bb86-4afc-aaab-aba70f815695.png)

**Comment by tablacus** [comment]
Script for Type

Add-on: Run at Setup

Type
`JScript`

Options
```js
ColumnsReplace(te, "{B725F130-47EF-101A-A5F1-02608C9EEBAC} 4", HDF_LEFT, function (FV, pid, s) {
	if (!s) {
		const path = pid.Path;
		if (/^ftp:/i.test(path)) {
			return GetTextR("@msieftp.dll,-287");
		}
		if (/^\\\\\w/i.test(path)) {
			return GetTextR("@utildll.dll,-201");
		}
	}
});
```

![image](https://user-images.githubusercontent.com/5156977/150339873-e8378ad2-8607-4a1b-afda-8df47e0f1750.png)

Regards,

**Comment by ccfs** [comment]
I tried your script and filtered for "Network" and "FTP". It was very interesting that network share, network folders and FTP folders were also found, although their types appeared original.
![script org](https://user-images.githubusercontent.com/34089121/150470717-348da851-35a2-45ec-83c0-f18389c5b9ca.png)

So I tried the following modified script and succeeded to correct the types:
```
ColumnsReplace(te, "{B725F130-47EF-101A-A5F1-02608C9EEBAC} 4", HDF_LEFT, function (FV, pid, s) {
//	if (!s) {
		const path = pid.Path;
		if (/^ftp:/i.test(path)) {
			return GetTextR("@msieftp.dll,-287");
		}
		if (/^\\\\\w/i.test(path)) {
			return GetTextR("@utildll.dll,-201");
		}
//	}
});
```
![script mod](https://user-images.githubusercontent.com/34089121/150470813-eae0426e-154d-499d-b820-32fd96b89004.png)

Nevertheless sorting by type is also not working correctly.

Besides, I right-clicked a "FTP server" item or a "Windows Search" item but TE incorrectly showed the context menu of file list background, not that of the item.
![context](https://user-images.githubusercontent.com/34089121/150471981-9fe30948-31c3-4bb8-885e-0b11d3e7ecb4.png)

**Comment by tablacus** [comment]
I have added the ability to sort into scripts.

```js
$ExtendedTypeProperty = function (FV, pid, s) {
  const path = pid.Path;
  if (/^ftp:/i.test(path)) {
    return GetTextR("@msieftp.dll,-287");
  }
  if (/^\\\\[^\\]+$|^\\\\[^\\]+\\[^\\]+$/i.test(path)) {
    return GetTextR("@utildll.dll,-201");
  }
}

ColumnsReplace(te, "{B725F130-47EF-101A-A5F1-02608C9EEBAC} 4", HDF_LEFT, $ExtendedTypeProperty);

AddEvent("ColumnClick", function (Ctrl, iItem) {
  const cColumns = api.CommandLineToArgv(Ctrl.Columns(2));
  if (cColumns[iItem * 2] == "{B725F130-47EF-101A-A5F1-02608C9EEBAC} 4") {
    Ctrl.SortColumn = Ctrl.GetSortColumn(1) == "System.ItemTypeText" ? "-System.ItemTypeText" : "System.ItemTypeText";
    return S_OK;
  }
});

AddEvent("Sorting", function (Ctrl, Name) {
  if (/^\-?System\.ItemTypeText$/i.test(Name) && api.ILIsEqual(FV.FolderItem.Alt, ssfRESULTSFOLDER)) {
    CustomSort(Ctrl, 'System.ItemTypeText', /^\-/.test(Name),
      function (pid, FV) {
        return pid.ExtendedProperty("{B725F130-47EF-101A-A5F1-02608C9EEBAC} 4") || $ExtendedTypeProperty(FV, pid) || "";
      },
      function (a, b) {
        return api.StrCmpLogical(b[1], a[1]);
      }
    );
    return true;
  }
});
```

Regards,

**Comment by ccfs** [comment]
I have tried TE 22.1.21, the context menu problem is solved.

I tried the above script but sorting did not work correctly, due to the type override. I amended the function to make it work:
```
$ExtendedTypeProperty = function (FV, pid, s) {
	if (!s) {
		const path = pid.Path;
		if (/^ftp:\/\/[^\/]+\/$/i.test(path)) {
			return GetTextR("@msieftp.dll,-287");
		}
		if (/^\\\\[^\\]+$/i.test(path)) {
			return GetTextR("@shell32.dll,-9216");
		}
	}
}
```

**Comment by ccfs** [comment]
I have tried "Path column" add-on focusing on 5 useful columns. This is a summary of the test results:
![table](https://user-images.githubusercontent.com/34089121/151695921-fec201c0-9d92-438e-b53d-7b4b4d44cf5a.png)

"Path column" 1.02 has some problems in "Type" column. Besides, "Folder path" column should be "System.ItemFolderPathDisplay", NOT "System.ItemFolderPathDisplayNarrow".
![102](https://user-images.githubusercontent.com/34089121/151696085-f5fda4be-c5cc-4e68-a651-430db1e256fc.png)

This is the result of my [patched](https://github.com/tablacus/TablacusExplorer/files/7965702/pathcolumn.zip) version of "Path column" 1.02. "Type" column is now correct.
![patch](https://user-images.githubusercontent.com/34089121/151696190-76826e28-e0e3-448f-a991-615daeb539d5.png)

Please help to update "Path column" add-on based on my patch.
- "Folder path" column should always be blank for query items. It should be corrected for FTP items.
- "Location" column is my suggested enhancement for sorting and filtering network items.
- Sorting "Name" column is incorrect for query items. I think the add-on can include a fix.

Regards,
