### ISSUE TITLE
How to add bookmarks? 

### ISSUE THREAD

**Issue by LeiK34F** [tablacus/TablacusExplorer#542]
Can someone help me with this plsssss, how can I add bookmarks?  or do I need to use this addon NETSCAPE Bookmarks?

**Comment by LeiK34F** [comment]
Nevermind, you can add "bookmarks" by going to the tool bar Name:Whatever Type: Open in a new tab then go to options *...* select the folder you want to add as a "bookmark" and lastly just add it with the + button at the bottom

**Comment by dieg467** [comment]
To add bookmarks, you have to install the "Horizontal favorites bar" add-on. In this way, you have a horizontal favorites bar like in Google Chrome. To create subfolders within each favorite, see https://github.com/tablacus/TablacusExplorer/issues/271.
If you want to have a vertical favorites panel, you need to install another add-on called "Favorites bar".
