### ISSUE TITLE
How to hold the position of main folder when enter to sub-folder?

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#544]
Dear Gaku, 

I need help with configuration I don't know how to explane what I want because of that I made video examples to help for You.  

When I return to the previous folder I would like the position 'how I left' to remain in state - ie. "holding of that positon....". 

Everytime it return to the beginning of folder so I have to re-position again to location I want to be or where are folder is located.

So, when I enter of the subfolder, and than return back, it automatically change the position, and always go back to the top of the main folder but I would like to keep that position because I had to review/see other maps as well who are located on similar position.  In this way I have to position myself every time to a location I’ve been before and when I enter again it return me again and again to the beginning state of the main folder.

_As can be seen, the options are turned off:_ 

_1. **Auto arrange icons**_
_2. **Auto arrange (Refresh)**_

![AutoRef](https://user-images.githubusercontent.com/60333254/150652967-7c5cc1a1-048f-4369-ba61-57a3f66f77cc.jpg)

**Detail of environment:**
--
- TA ver: **te220121.zip** (22.1.21)  ->  2022-01-21
  _Initial folder without any user configuration files_ ['clean' te220121.zip]
- OS: Windows 10, 20H2.

**What can I do else...???**
My question is: **How to keep the position of main-folder, when it comes out of the sub-folder?**

 >  I don't know if it should be like that or is it a error/fault?
 >  Does this happen on your working environment...?

Thank you for your answer.

**PS.**
I don't know maybe there are users who like something like that; "_Starting from beginning folder, when exit from sub-folder_"
For me, something like that is frustrating because I have a feeling that I have to position myself again in the place I was recently.

Maybe I had learned (I got used to it) on that 'old fashioned' way-so now this is something unusual for me. I really don't know!
I prefer to control what I work on rather than something happening without my supervision or overseeing things by themself.

If I like something like that, I'd rather put an auto-refresh, although, I prefer when (I'm done) to refrash "_manual_" with key F5. 
Even that doesn’t bring me back (_which is good_) to the very beginning of 'main' folder.  It makes only a simply refreshment of structure folder(s) itself but the structure remains as it was without being moved from that position - "top" or "bottom".

Best regards, 
Jox.

- **Tablacus Explorer**
  _It return of beginning and starting from the top position of the main folder_

https://user-images.githubusercontent.com/60333254/150652846-c11c31db-8630-4590-86fd-a829e55baaff.mp4

- **Windows Explorer**
 _Holding the position of the folder on which selection is located_

https://user-images.githubusercontent.com/60333254/150652864-f309e76c-c9a2-4526-b667-29e5a8211841.mp4

**Comment by kettenfett** [comment]
I second this.

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 22.1.23.
Please give it try.

https://github.com/tablacus/TablacusExplorer/releases/tag/22.1.23

Regards,

**Comment by JoxCoswit** [comment]
Gaku, 

Yes, that would be it! 😊
![Thank you2](https://user-images.githubusercontent.com/60333254/150687017-1086f9a1-65e7-48a1-b0b2-98cfc14490b4.png)





Regards,
Jox.

**Comment by kettenfett** [comment]
It seems to worl quite well. Thank you, Gaku.
