### ISSUE TITLE
Suggestion and notification by the below INFO message FOLDERS action COPY/MOVE.

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#545]
Dear Gaku, 

I would kindly ask you to solve another problem which is also important as the previous one and for a while I wanted to ask you to check it out. I also prepared video examples in which I tried to demonstrate how this problem works.

Namely, the problem occurs when I want to copy or move a folder/folders. It says (**below info message**) that it will be copy/moved to the main folder but actually it will not be copy/moved to main folder instead of that it will be drop to below selected sub-folder if wishing content located above it folder _(ie. it will not be copy or moved, as it say/write on the message... suggests)_

**Sometimes, it will be fine!** (This is also seen, in the video example). 
So it was not clear to me... what was the really problem!?
Am I doing something wrong, or do I have to be careful, how I am doing it - maybe I move to fast (!)

When it has a few folders, that is not a problem for me, because I always try to put on the blank field/spot/space.
This problem is noticeable when there are a lot of folders so I can not always able to find blank space/spot or trust to message what it will be done - written on the message. I must always be careful when copying or moving folders... ie. to put on the blank field, because it will not be done as it says, or suggestion by the info message.

I don’t know if it says on the info message one why is it moving to the folder below when it located between folders?

**In this case, my wish would be to be sure, when it says where will be set, then when I drop-to be place there exactly.**

**NOTE:**  
There was never a problem when I wanted to copy or move content to the folder which was selected as message are suggest.
_For example:_ When I wanted to copy/move content to somewhere else in other, or another selected folders.... all that works fine!

---
- **VIDEO 1 (NOT):  The message says "main folder" (TEMPO) but it will be move to "sub-folder" (FOLDER2)**
   I don't know for sure I think it has been dropped into Folder2 (I hope I wrote well) 

https://user-images.githubusercontent.com/60333254/150698143-fff00e85-5a61-4141-be95-040a1539ccc4.mp4

- **VIDEO 2 (OK):  The message says "main folder" (TEMPO) and it will be move to "main folder" (TEMPO)**

https://user-images.githubusercontent.com/60333254/150694204-553d1680-106a-4ba2-b860-ef778c75d98b.mp4

**- FULL-TEST:  Complete testing.... etc.**

1. Target: **Copy/Move** to **MAIN folder "TEMPO"** [as action suggestion, by the below message] -> **drop to SUB-folder (FOLDER1)**
2. Target: **Copy/Move** to **MAIN folder "TEMPO"** [as action suggestion, by the below message] -> **drop to MAIN-folder (TEMPO)**

**On the last example:**
* I tried not to select any folder, but unfortunately it didn't work (that is example from VIDEO-NOT)
* It will be drop to the first below sub-folder [Folder2] although the **below INFO message** suggests otherwise - that will be moved to MAIN folder [Tempo]

https://user-images.githubusercontent.com/60333254/150694171-5c312c85-fbcd-416a-86c4-c3ebc6d48c64.mp4

**Complete testing with personal comments**
------------
-    _apologies if something what is written there are incorrectly commented or points to a wrong conclusion_
-    _that is my only my personal thinking, and in advance - it doesn't mean to be as it is written in comments_

**As far as I noticed:**
If the name of the subfolder appears "Folder2", the content will be transferred there, ie. into that folder "Folder2"
Regardless of the later message (Tempo)
The same example, is in the above video **Full.mp4** on the beginning - There was Folder1
Also, on example video **OK.mp4** "Folder1" briefly appears but later it will be moved at correct way on the correct folder.

https://user-images.githubusercontent.com/60333254/150703951-ccb53c67-5ce1-4be2-9f8c-305a617fca60.mp4

Best regards, 
Jox.

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 22.1.24 and File operation add-ons.
Please try to update them.

If it doesn't work, try turning off file operation add-ons. (Multi thread, Multi process and ...)

Regards,

**Comment by JoxCoswit** [comment]
Gaku, 

As far as I could try it works perfectly! 😊

I will try to test a couple of time and of these next future days.
I just have a lot of maps to go through and It will be a great base for testing purpuse.
The situation will me monitored and how it behaves operations COPY/MOVE etc.
I understand it's new, so I'll be careful - ie. "I will work at my own risk".
As much as I’ve tried for now there shouldn’t be any unusual problems.

So, if there are no problems, you can consider this solved! 👍
After a few days if there are no problems I will close this case.
Or if someone notices something they can also comment here.

As for the added ADD-ONS, I use the standard ones, from your initial folder (My OS: Win10, 20H2, 64-BIT)
Yes I saw a new version of Multi-thead-it has been updated also. 
Mostly when I notice something I use the initial folder with all the new-updated data and settings which are included there by their default and how they relate or have behavior on working environment.

For now, as it stands, it should be consider - as fixed. 👌

Thanks!

Regards, 
Jox.

**Comment by JoxCoswit** [comment]
As there have been no problems, in these few past days, verified through intensive use, - i.e. after using each function copy or move it has been constant verification and validation of the transmitted content as well as checking functionality in different ways and how all of it behaves in various situations, no failure or errors were identified during that test period. 

In the conclusion it feels much better and more stable than solution before that.

This case will be closed as successfully resolved! ✔

Regards,
Jox.
