### ISSUE TITLE
QUERY. Open in another pane

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#547]
Hi Gaku, I'm using Tablacus Explorer and every day I see it more complete and with more functions. I have a query: I am working in dual pane mode. Is there a way that when I click on a folder that is open in a tab in the left pane, its contents (files or subfolders) open in a tab in the right pane? Thank you very much for the help.

**Comment by tablacus** [comment]
1. Install an add-on "Switch to next pane".
2. Try the following script.
https://gist.github.com/tablacus/bbad6d9ffb29029ca94f35f51c80f1dc

In the above case, "Open in next pane" will be added to the right-click menu. 

Regards,

**Comment by dieg467** [comment]
Great, that was exactly what I was looking for. I write all the steps I followed:
1) Install the “Switch to next pane” add-on.
2) Go to Tools --> Options --> Menu --> Contextual
3) Complete the window with:
Name: (Choosed by each user)
Filter: (leave it empty)
Type: JScript
Option: Copy and paste the following

let FV = GetFolderView(Ctrl, pt);
const Selected = FV.SelectedItems();
if (Selected.Count) {
  FV = Sync.SwitchPane.NextFV(FV);
  for (let i = 0; i < Selected.Count; i++) {
    NavigateFV(FV, Selected.Item(i), SBSP_NEWBROWSER);
  }
}

4) Click Add.
5) Click OK.
So it is added to the context menu. Right-clicking on a folder in the left pane, choosing the corresponding option, opens the content in the right pane, and vice versa.
Thank you again! Greetings!
