### ISSUE TITLE
Search: Open File Location not working

### ISSUE THREAD

**Issue by IboAU** [tablacus/TablacusExplorer#55]
Hi Gaku
Using TE ver. 15.11.8 with Win7(Home Premium) on Toshiba P500

After searching and displaying a list of files, a right-click open a context menu displaying "Open File Location". This should open a new ?tab/?instance of TE/?instance of Windows Explorer, showing the folder where the file is located. Instead, it does nothing.

**Comment by tablacus** [comment]
Thank you for the progress report.
I've fixed it on Tablacus Explorer 15.11.30

Best regards,
