### ISSUE TITLE
When the "lockedtabstop" add-on is enabled, shortcuts (.lnk) do not open properly in locked tabs.

### ISSUE THREAD

**Issue by yuru7** [tablacus/TablacusExplorer#550]
## 事象

「ロックされたタブを先頭に」アドオンを有効化状態で、ロックされたタブ上でショートカット（.lnk）を開くと、リンク先フォルダのタブがバックグラウンドで開かれ、右隣のロックタブがアクティブになってしまう。

![20220128_093205](https://user-images.githubusercontent.com/13458509/151466387-9a133551-be7d-43cb-870a-9a1f14f584c4.gif)

## 期待する動作

ロックされたタブ上でショートカット（.lnk）を開いたら、リンク先フォルダのタブが開かれ、該当のタブがアクティブになる。

## 備考

TE 22.1.19から発生している事象のようです。TE 22.1.18では期待の動作の通りとなります。

## 環境情報

```
TE64 22.1.25 Microsoft Windows 10 Home 64 ビット 21H1 (10.0.19043) Dark IE/11 JS/11.0.16384 ja_jp 120 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz Windows Defender カスペルスキー インターネット セキュリティ カスペルスキー インターネット セキュリティ
```

```
usercss 1.08,mouse 1.33,key 1.26,mainmenubutton 1.17,titlebar 1.09,tabs 1.26,favoritesbar 1.42,hotkey 1.01,undoclosetab 1.16,tasktray 1.15,treeview 1.43,importexplorer 1.08,split 1.24,statusbar 1.19,tabplus 1.91,tabposition 1.10,tabgroups 1.45,tablist 1.03,innerbreadcrumbsaddressbar 1.50,innerfilterbar 1.33,innerback 1.14,innerforward 1.16,innerup 1.10,innerrefresh 1.07,lockedtabstop 1.08,multithread 1.29,replaceslowcolumns 1.03,autodisableime 1.03,remember 1.42,darkmode 1.17,recentlyusedtabs 1.02,tabcolorplus 1.04,flat 1.20,segoeicons 1.03
```

**Comment by tablacus** [comment]
Tablacus Explorer 22.1.28で調整しました。
試してみてください。

https://github.com/tablacus/TablacusExplorer/releases/tag/22.1.28

**Comment by yuru7** [comment]
解消されたことを確認しました。いつもありがとうございます！

**Comment by yuru7** [comment]
（issue、再オープンしてしまって申し訳ありません）
一部、本件と関連しそうな不具合を発見しましたので、ご報告します。

ショートカット (.lnk) をホイールクリックで開く（右クリック > バックグラウンドで開く  の操作と同等）と、正しくショートカットが開かれないようです。
※TE 22.1.29 で確認しました

例）`Intel - ショートカット` をバックグラウンドタブで開いた場合
![image](https://user-images.githubusercontent.com/13458509/151783050-2ee7c446-2bd4-45e3-aa38-cb9329eb9b4e.png)

**Comment by yuru7** [comment]
TE 22.1.31 で解消されたことを確認しました。ありがとうございました🙇‍♂️
