### ISSUE TITLE
Taskbar button - Appearance

### ISSUE THREAD

**Issue by indi110** [tablacus/TablacusExplorer#552]
Hi, this is a great alternative to Windows Explorer.
I wanted to know how to change the appearance of the taskbar button so that it doesn't look like Windows Explorer.
So I don't get mixed up with them.
See the image attached.

![image](https://user-images.githubusercontent.com/98949761/152324537-d317e066-c3fa-4d58-8b40-c6ee32fa2aab.png)

**Comment by tablacus** [comment]
Please install an add-on "Tab design".

1. Open Tools -> Add-ons...
2. Click "Option" of "Tab design"
3. Click "Underline" then click "OK".
![image](https://user-images.githubusercontent.com/5156977/152361865-22576a8d-609c-4e8d-8e27-91d71e59761e.png)

Regards,

**Comment by indi110** [comment]
Hi, thanks for looking into this.
I was actually looking for the taskbar at the bottom.
In the example, the last 2 are Windows Explorer and Tablacus. They look similar.

The above though is actually quite useful and I will use this.

![image](https://user-images.githubusercontent.com/98949761/152362918-c9418b60-53c6-45aa-bea1-2cee2ae70b99.png)

**Comment by tablacus** [comment]
The presence / absence of the icon, the display position of the tab, and the fixed width are set from the "Tab Plus" option of the add-on.

![image](https://user-images.githubusercontent.com/5156977/152364295-5f8cb853-7d30-4a70-99c1-c009c398368f.png)

Regards,

**Comment by indi110** [comment]
Hi, sorry if I'm confusing you. This is the taskbar, which is not part of Tablacus, see below.
So, this is not a tab.

![image](https://user-images.githubusercontent.com/98949761/152365951-f6108e75-6c9a-48e5-a4d4-c65d2e42251f.png)

**Comment by indi110** [comment]
By the way, I've tried most of the alternative to Windows Explorer and this is the most comprehensive I think.
It takes a while to get used to the add-ons but then so many options are available.

**Comment by ccfs** [comment]
Use "Application Icon" add-on to change TE icon to something else.

Regards,

**Comment by indi110** [comment]
Thanks a lot, this is working.
Still can't get over how comprehensive this program is.

**Comment by ccfs** [comment]
TE wiki: https://github.com/tablacus/TablacusExplorer/wiki
TE add-on wiki: https://github.com/tablacus/TablacusExplorerAddons/wiki
TE add-on PDF: https://github.com/ccfs/TablacusExplorer/issues/1

**Comment by kettenfett** [comment]
I had previously changed it with the windows own function (see image), but the addon is much better.

by the way, I'm using this icon:
https://icons8.com/icon/EPllXGX0YEyq/kawaii-folders

![grafik](https://user-images.githubusercontent.com/23098362/152659832-ad5bf4fd-6797-4c1d-902c-baad83176030.png)
