### ISSUE TITLE
New tab - Add at End

### ISSUE THREAD

**Issue by indi110** [tablacus/TablacusExplorer#553]
Hi, is there a setting to add a new tab at the end of all other tabs?
Also, to make the filepath as chosen, such as Desktop.

**Comment by dieg467** [comment]
Hello, you have to install the "tab position" add-on. Then, in the options of this add-on select "last".

**Comment by dieg467** [comment]
To choose the path of the new tab go to Tools --> Options --> Tabs --> Browse.
From "Browse" you choose the folder that will open in the "New tab"

![image](https://user-images.githubusercontent.com/96446416/152423210-6b869fee-c855-4890-9f6e-771788774eb4.png)

**Comment by indi110** [comment]
Thank you very much.
This all worked out.
