### ISSUE TITLE
Tab color

### ISSUE THREAD

**Issue by indi110** [tablacus/TablacusExplorer#554]
Hi, is there an add-on which can change the color of text for a tab? This is for some tabs, but not all tabs.

I'm aware of the "Change tab color" which changes the background color.

**Comment by ccfs** [comment]
Currently only "Tab design" add-on lets you change text color of a tab. Example:
![image](https://user-images.githubusercontent.com/34089121/152510477-76968e40-1225-419f-9ecb-ab6c00d1232c.png)
The change is based on the relative position or the active/inactive state of a tab.

"Change tab color" and "Tab color plus" add-ons change color based on folder path and pattern. But they change background color. To change text color instead, enhancement will be requird.

Regards,

**Comment by indi110** [comment]
OK thanks for confirming.

**Comment by indi110** [comment]
Hi, I did the above for selected tabs, to change the colour of the font to blue. This part works.

```
color:blue !important;
border-bottom: 5pt solid #f07 !important;
```

But another add-on overrides this. Tab color plus.

The underline is preserved though.

![image](https://user-images.githubusercontent.com/98949761/153166684-74193b0f-f63a-4f50-893e-e8fcb37a970c.png)


![image](https://user-images.githubusercontent.com/98949761/153167181-dd626867-407b-477e-bfc1-7c9033276b32.png)

**Comment by ccfs** [comment]
TE and add-ons automatically chooses either black or white as text color according to any designated tab color. Apparently "Tab design" cannot override this scheme.

May you state exactly which color your want under what condition?

Regards,

**Comment by indi110** [comment]
I wanted a blue colour for any tab selected.
In the above snapshots, both tabs are selected. The second tab is affected by Tab color plus, as the file path conforms to the setting below.

"C:\Users\Test\New folder"  is a subset of "C:\Users\Test\*"
So "Tab color plus" overrides the coding above in "Tab design".

![image](https://user-images.githubusercontent.com/98949761/153332504-629304ba-d546-494e-a53f-02fc22a3304c.png)

**Comment by ccfs** [comment]
Which colors do you expect for a selected tab with path matching "C:\Users\Test*" ?
tab color = light grey, text color = blue (as in "Tab design")
tab color = #cdcdcd, text color = blue

**Comment by indi110** [comment]
Expect:
**tab color = #cdcdcd, text color = blue**

But not getting this.

**Comment by tablacus** [comment]
Please try to install an add-on "User style sheet".

Enter the following CSS in the text area. 
```css
.activetab .namecell {
  color: blue
}
```

![image](https://user-images.githubusercontent.com/5156977/153385289-c3630c36-4d66-4527-be9f-3c7f1fc4c879.png)

Regards,

**Comment by indi110** [comment]
Yes, thank you very much. It does work.

**Comment by ccfs** [comment]
This will give you the underline too.

.activetab {
  border-bottom: 5pt solid #f07
}
.activetab .namecell {
  color: blue
}

**Comment by indi110** [comment]
OK thanks.
