### ISSUE TITLE
Show frames

### ISSUE THREAD

**Issue by indi110** [tablacus/TablacusExplorer#556]
I want to show frames in general.
How do I do this?

At the moment, I'm using this button ... but it only shows on that specific tab.

![image](https://user-images.githubusercontent.com/98949761/153169986-335d95a6-aef0-4a5d-bcaf-bf611df0776e.png)

**Comment by ccfs** [comment]
Opt for "Show frames" in "Tools > Options > List >"

**Comment by indi110** [comment]
Hi, thanks.
But this is different for every tab.
Was there something to change for all at once?
Otherwise that's OK.

**Comment by tablacus** [comment]
Is Default checked?
![image](https://user-images.githubusercontent.com/5156977/153332734-aedf31a6-ff83-45d8-b88e-90b5ee90f136.png)

 Regards,

**Comment by indi110** [comment]
Hi, yes this is as above.

**Comment by ccfs** [comment]
The current tab ought to have "Show frames" OFF when you opt for "Show frames" in "Tools > Options > List". In case the option is  already ON, try click it twice to turn it OFF then ON before you click OK.

**Comment by indi110** [comment]
Yes thank you this seems to work.
