### ISSUE TITLE
Tab right-click menu

### ISSUE THREAD

**Issue by indi110** [tablacus/TablacusExplorer#557]
Hi, is there an add-on which allows you to right click on a tab and do any of the following:
- Duplicate tab (copy and paste).
- New tab to the Right of current tab.
- New tab at the End.

![image](https://user-images.githubusercontent.com/98949761/153171742-d6e99699-9947-48e8-90f6-3afc05f63d7c.png)

**Comment by ccfs** [comment]
There is no such add-on. To do those similarly:
- Duplicate tab: Select a tab and click the + tab
- Open new tab at end / on right: Use "Tab position" add-on to designate the default new tab position

**Comment by indi110** [comment]
OK thanks for confirming.
