### ISSUE TITLE
Copy function not working in adressbar breadcrumbs mode

### ISSUE THREAD

**Issue by kettenfett** [tablacus/TablacusExplorer#558]
**Plugin: Address bar 1.70** 

The copy funtion doesn't copy anything to the clipboard. I'd expect it to copy the current folder name to the clipboard.

The "Copy Full path" function works, though.

![grafik](https://user-images.githubusercontent.com/23098362/153473998-2a39dc0d-9053-452b-8ce3-26c6f7ab87dc.png)

TE64 22.1.23 Microsoft Windows 10 Pro N 64-Bit 20H2 (10.0.19042) Dark IE/11 JS/11.0.16384 de_de 96 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz Windows Defender

remember 1.42,mouse 1.33,key 1.26,everything 1.44,filterbar 1.38,addressbar 1.70,mainmenu 1.16,undoclosetab 1.16,tabplus 1.91,split 1.24,multithread 1.28,aboutblank 1.02,segoeicons 1.03,download 1.07,extract 1.14,darkmode 1.17,sizestatus 1.26,favoritesbar 1.42,toolbar 1.43,countbar 1.12,favoritesnewtab 1.02,preventduplicatetabs 1.19,preview 1.36,fixselection 1.16,innerup 1.10,innerback 1.14,innerforward 1.16,innerrefresh 1.07,innernewfolder 1.06,switchpane 1.05,totalfilesizesort 1.13,tabdesign 1.13,addonsupdater 1.10,takeoverfoldersettings 1.08,innersearchbar 1.13,fullpathbar 1.06,tabposition 1.10,lockedtabstop 1.08,appicon 1.03

**Comment by kettenfett** [comment]
I just udated to TE64 22.2.10 . Still not working.

**Comment by ccfs** [comment]
It is "copy to clipboard", just like you select the folder and press Ctrl+C. It is NOT "copy the folder name".

**Comment by kettenfett** [comment]
Oh, well this explains it. I fully expected it to copy the name, as this was the option in my last explorer alternative.

**Comment by ccfs** [comment]
Use a tool bar button /  hot key / menu option to "copy current folder name":

Type: JScript
Options: api.setClipboardData(GetFileName(GetFolderView().FolderItem.Path))

example:
![image](https://user-images.githubusercontent.com/34089121/154029294-75eeab52-f9c6-4247-9456-1b8b7b1deeec.png)
