### ISSUE TITLE
Add on "Tab color plus" - relationship to "User style sheet"

### ISSUE THREAD

**Issue by indi110** [tablacus/TablacusExplorer#561]
I'm using "Tab color plus" which helps me to group similar folders and subfolders together with a similar colour.
It's been on of the most useful add-ons.

**Is there any way to do this using the "User style sheet" add-on.**

I have been through this but can't see anything for tab name. Also need wildcard (*) character as well.
[https://tablacus.github.io/wiki/addons/usercss.html](url)

![image](https://user-images.githubusercontent.com/98949761/153621350-9afad490-ba1a-41c5-906d-6092aa027f4e.png)

**Comment by ccfs** [comment]
No way. "User style sheet" does not relate to your data.
Why can't you use "Tab color plus"?

**Comment by indi110** [comment]
OK no worries, thanks.

**Comment by indi110** [comment]
Is it possible to edit an XML or other file using Notepad.

I tried looking in "te220201\addons\Tab color plus".
But couldn't see anything.

**Comment by tablacus** [comment]
The settings are in the following folder.
Click Help -> About Tablacus Explorer -> Configure

![image](https://user-images.githubusercontent.com/5156977/153862107-728f3361-9f40-4f6c-9e6d-94523f5df0d6.png)

File name is `tabcolorplus.tsv`

Regards,

**Comment by indi110** [comment]
Great, thank you, this helps a lot.
