### ISSUE TITLE
Button for most commonly used add-ons

### ISSUE THREAD

**Issue by indi110** [tablacus/TablacusExplorer#562]
This query is actually because there are so many add-ons available.
I'm getting to the point where I can't remember which add-on does what.
I wanted to have a button, which will bring up common add-ons that I use.
Is this possible?

**Comment by ccfs** [comment]
The point is NOT whether an add-on is common or not. The point is whether you NEED it or not.
This doc will help: https://github.com/ccfs/TablacusExplorer/issues/1

**Comment by indi110** [comment]
Hi, I meant the button will show the add-ons that I choose.
I presume this is not possible?

**Comment by ccfs** [comment]
"Tools > Add-ons"

**Comment by indi110** [comment]
OK thanks. I understand that I'm asking too many questions.
