### ISSUE TITLE
“Tooltip preview” add-on conflict with FastStone app

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#565]
Hello Gaku. On Windows 10, I use the FastStone app as a viewer for jpeg, png, etc. images. After installing the “Tooltip preview” add-on in Tablacus Explorer, I cannot rotate 90º some images in FastStone.
When trying to rotate them, a window appears in FastStone saying “The image is being processed”, and after a few seconds another window appears saying that the file “Maybe it is read-only or in use by another program”. This happened to me with several images, and none of them were read-only. The other functions in FastStone do not present problems, there is only a conflict in the rotation.
I did this test:
1) I disabled “Tooltip preview” in Tablacus and images can be rotated 90º in FastStones.
2) I reactivated “Tooltip preview” in Tablacus, and images can no longer be rotated 90º in FastStones.
That's where I discovered the conflict. This happens with some images (jpeg, png) of different sizes, not all of them. I hope there is a solution for this problem. Thanks a lot!

![image](https://user-images.githubusercontent.com/96446416/154260331-f5071d69-eb81-4842-ad21-5d43a6caec05.png)

**Comment by tablacus** [comment]
I have adjusted it in Tablacus Explorer 22.2.16(Pre-release)
Please give it try.

https://github.com/tablacus/TablacusExplorer/releases/tag/22.2.16 

Regards,
