### ISSUE TITLE
eye candy: dropdown arrow wrong position

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#57]
Hello,
I'm seeing that the dropdown arrov in the address bar appears in the wrong position on startup.
Also in my setup with four explorer panels I see the left part of first tab is truncated:

![image](https://cloud.githubusercontent.com/assets/10347571/12320048/9aa00c8e-baa6-11e5-8e5d-26809f1d7eb2.png)

Then after clicking on the address bar the arrow moves to the corret position, on the far right side:

![image](https://cloud.githubusercontent.com/assets/10347571/12319882/822d65da-baa5-11e5-8fb0-e06b3cbc90f1.png)

**Comment by tablacus** [comment]
Hello,
I fixed these problems on Tablacus Explorer 16.1.14 and Inner Breadcrumbs Address Bar 1.12

Thank you,

**Comment by stefanocaselli** [comment]
Hi,
The tab in now visible correctly, however the arrow is fixed for just one
of my four explorer panels: the one in the bottom right part of the screen
(possibily the last that is being rendered by tablacus?)
Thanks.

2016-01-14 14:46 GMT+01:00 Gaku <notifications@github.com>:

> Hello,
> I fixed these problems on Tablacus Explorer 16.1.14 and Inner Breadcrumbs
> Address Bar 1.12
>
> Thank you,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tablacus/TablacusExplorer/issues/57#issuecomment-171648477>
> .
>



-- 

70% of all internet quotes are fake   - Albert Einstein
