### ISSUE TITLE
how to create a new folder？

### ISSUE THREAD

**Issue by LV36** [tablacus/TablacusExplorer#572]
how to create a new folder，there is no new in the right-click menu in te，which Addons is needed?

**Comment by tablacus** [comment]
No add-ons are required. Just right-click in the background of the list view.
![image](https://user-images.githubusercontent.com/5156977/155845345-3e5864d4-c543-46af-9ac3-8a20d2cbeed6.png)

You can also hold down [Ctrl] and press [K] to bring up the New dialog box.
![image](https://user-images.githubusercontent.com/5156977/155845388-89995c29-eadc-413c-b2d7-e8b19bf8fa23.png)

Regards,

**Comment by LV36** [comment]
Thanks a lot. The add-on "Quicker menu display" collapsed the "new".
