### ISSUE TITLE
Quick Notes

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#577]
Hello. Is there a "Quick Notes" add-on integrated to Tablacus Explorer? It's for creating a list of custom keyboard shortcuts and other Tablacus features that I want to be just a click away. Thanks.

**Comment by dieg467** [comment]
In the screenshot I simulated what the notepad could be, a pop-up window accessed by clicking the note button.

![Notas](https://user-images.githubusercontent.com/96446416/159273908-7f59389d-3b3f-4dd9-8b1a-4713dbcfaf95.png)

**Comment by tablacus** [comment]
I have created a new add-on.
Try it out.

Regards,

**Comment by dieg467** [comment]
Excellent Gaku!! On the screenshot you can see the new notes add-on. For now, I've added keystroke notes that I want to always have there, just one click away, in case I forget one. Thank you very much

![Add-on Notas](https://user-images.githubusercontent.com/96446416/160260340-ae8955ba-ba27-46dc-91c1-8738e99995b3.png)
!
