### ISSUE TITLE
Add-on list icons

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#578]
Hello Gaku. The add-on list can only display system icons, which are preloaded in Tablacus. If any add-on has a custom icon (such as an .ico file saved in the Images folder), then a different icon is displayed in the add-on list, as seen in the screenshot below. Will this difference in icons have an easy solution? Thank you very much.

![Iconos add-on](https://user-images.githubusercontent.com/96446416/159142056-da2387a7-cc04-42f4-8397-fecf5e0bd168.png)

**Comment by tablacus** [comment]
I have not yet encountered this problem.
![image](https://user-images.githubusercontent.com/5156977/159142112-ba599d3e-c31d-4ec4-86a3-7ff57fad543d.png)

Please read this and let me know your environment and settings.
[When reporting a problem, please be specific.](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/when-reporting-a-problem-please-be-specific.txt)

Regards,

**Comment by dieg467** [comment]
Hello, I am using Tablacus Explorer TE64, version 22.3.19, in the following system:
Microsoft Windows 10 Pro 64 bits, 21H2 (10.0.19044) IE/11 JS/11.0.16384 es_mx 96,
AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G
Windows Defender.

**Comment by tablacus** [comment]
Please tell me the icon settings. 
![image](https://user-images.githubusercontent.com/5156977/159165726-9da10c66-b583-4801-8682-64ecc460dfe4.png)

**Comment by dieg467** [comment]
The icon settings is:
![image](https://user-images.githubusercontent.com/96446416/159166714-2ed2545e-d7a9-4026-bcc9-fc957aab664a.png)

**Comment by ccfs** [comment]
@tablacus, TE has a problem in showing an add-on icon in the list if the icon path is QUOTED.
