### ISSUE TITLE
Request shortcut Down/Up arrows from Filter input

### ISSUE THREAD

**Issue by guilhas** [tablacus/TablacusExplorer#58]
Hello,

Amazing app as always.

Problem:
When I hit 'Ctrl - E' the cursor moves to the 'Filter box', I type what I want to search and then I cannot return to the filtered file list without clicking on a filename with the mouse.

Solution:
When the cursor is in the 'Filter box' pressing Down or Up arrows selects a file in filtered list.

I am using te160114.

Best regards,
Guilherme Lino

**Comment by tablacus** [comment]
Hello,

I've adjusted it on Filter bar 1.13.
Please update add-ons.

Thank you,

**Comment by guilhas** [comment]
You're dam fast, it's working nice.
Thank you,
