### ISSUE TITLE
Suggestion: Multi-layout function

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#580]
Hello Gaku. I have several layouts saved in my Tablacus configuration (for example, "Layout 1", "Layout 2", etc). "Layout 1" consists of 2 panels with a tab on each, "Layout 2" consists of 4 panels with a tab on each, etc. Also, I added buttons on the toolbar for each layout, so I can easily access each of them.
The problem is that if I have "Layout 1" open and click the button for "Layout 2", then "Layout 1" disappears, unless I open "Layout 2" in a new window. This is how I am currently doing it, and for this I installed the "multiple execution" add-on.
My suggestion is that you can open multiple layouts in one window, so when you open "Layout 2", you don't lose what's open in "Layout 1". Also, in order to be able to switch from one layout to another, you would need to have a "open layouts" bar or button or list, as the screenshots show. Is it possible to create something like this in Tablacus?
I clarify that I know the "tab group" function, but I am more familiar with layouts. Thank you very much.

**Screenshots 1 - LAYOUT 1 ACTIVE**
![Diseño 1](https://user-images.githubusercontent.com/96446416/161451899-43a60a76-c093-442a-8f85-2a2a3d277436.png)

**Screenshots 2 - LAYOUT 2 ACTIVE**
![Diseño 2](https://user-images.githubusercontent.com/96446416/161451765-8802df18-8376-4413-b14c-b064ab3ed8bc.png)

**Comment by dieg467** [comment]
Hello Gaku. I already installed the new add-on (Layout 1.00). Very good because I can see all the saved designs.
However, I am unable to achieve the following operation, which I describe in the following steps:
1º) I open TABLACUS.
2º) I open "LAYOUT 1", which consists of the tabs "TAB1-1", "TAB1-2".
3º) Now, in "LAYOUT 1" I open another tab "TAB1-3".
4º) I open "LAYOUT 2", which consists of the tabs "TAB2-1", "TAB2-2".
5º) I need to go back to "LAYOUT 1". When I come back, "TAB1-1", "TAB1-2", "TAB1-3" are still open.
6º) I close TABLACUS. The designs then return to their original saved state.
To switch from one design to another, you need a button that shows only the open designs, that is, those that are being used.
Do you plan to add this feature to the Layout add-on in the future?
Thank you very much.

**Comment by ccfs** [comment]
@tablacus, "Folder" option does not work. Please help to solve this problem. Thanks.

![20220408_153358](https://user-images.githubusercontent.com/34089121/162389404-d631fab0-6faa-406b-8c1c-51cce6a9af47.png)
![20220408_153424](https://user-images.githubusercontent.com/34089121/162389411-0d572bfb-8a24-43b4-b5ef-fd321f2c33f6.png)

**Comment by ccfs** [comment]
The above problem is solved in version 1.01. Thanks.

**Comment by dieg467** [comment]
The new "Layout" add-on makes it easier to manage the different layouts created. It's a very good start for this utility that allows you to access multiple instances with a single click. Thank you very much for the improvement. Greetings!
