### ISSUE TITLE
Font settings not applied to network drive tabs with drive letter

### ISSUE THREAD

**Issue by timarupopoka** [tablacus/TablacusExplorer#581]
アドオン「フォント設定」を導入しています。
NASのフォルダをタブで開いたままTEを再起動すると、そのタブだけフォント設定が反映されません。
そのタブで一度遷移操作を行えば、再びTEの再起動を行うまで反映され続けます。

ローカルのフォルダや、他のWindowsクライアントの共有フォルダ（非ドメイン環境）のタブではこの現象は発生しません。
また同じNASの全く同じpathでも、ロックまたは保護されているタブでは発生しません。

試したこと（改善されず）
- アクティブタブをローカルフォルダやロックされた同NASにしてからTEを再起動
- アドオンの並び順で、フォント設定を一番上や一番下に移動してみる

環境起因の可能性が高く大変申し訳ないのですが、ロックや保護されているタブでは発生しないことを手がかりにTE側で対応できないでしょうか？
よろしくお願いします。

TE64 22.3.27 Microsoft Windows 10 Home 64 ビット 21H1 (10.0.19043) Dark WebView2/99.0.1150.55 JS/Chakra.dll ja 96 Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz Avira Antivirus Windows Defender
xfinder 1.31,mouse 1.33,key 1.26,hidetitlebar 1.10,mainmenubutton 1.17,grabbar 1.12,minimizebutton 1.08,maximizebutton 1.09,closebutton 1.06,addressbar 1.70,filterbar 1.39,searchbar 1.12,back 1.18,forward 1.18,up 1.20,refresh 1.10,toolbar 1.44,darkmode 1.18,tabplus 1.94,tabcolorplus 1.06,tabdesign 1.16,tabgroups 1.45,protecttabs 1.07,undoclosetab 1.16,tabposition 1.10,aboutblank 1.04,countbar 1.12,sizestatus 1.27,attributescolor 1.07,filtercolor 1.02,extensioncolor 1.06,extensionicon 1.17,font 1.20,foldersettings 1.39,stripes 1.12,inactivepane 1.11,usercss 1.08,switchpane 1.05,switchprevpane 1.03,tooltippreview 1.27,touchex 1.10,clipboardimage 1.01,dragtop 1.03,renametoggle 1.00,betweenfilesfolders 1.01,movecontentup 1.02,ordercb 1.00,autodisableime 1.03,confirmdrop 1.02,addonswitcher 1.03,multithread 1.29,addonsupdater 1.10

**Comment by timarupopoka** [comment]
追加情報です。
どうやらドライブレターを使用して開いた場合に発生するようで、UNC形式で開いたタブでは発生しませんでした。
現象が出ていたなかったWindowsの共有フォルダにはUNCでアクセスしていたのですが、試しにドライブレターを割り当ててアクセスしたところ再現しました。

NG `Z:\Test`
OK `\\Server\Test`

またロック・保護されたタブはpathの形式にかかわらず常に正常に動作します。
以上が解決のヒントになれば幸いです。

**Comment by timarupopoka** [comment]
今朝フォント設定1.21がリリースされていることに気づきました。
更新時刻的に先の書き込み前のリリースだと思いますが昨日は気づきませんでした、申し訳ありません。

改めて検証してみたところ、問題のタブをアクティブにした状態でTEを再起動した場合、そのタブにはフォント設定が反映されるようになりました。
しかし非アクティブだったタブには反映されませんでした。
引き続きよろしくお願いいたします。

**Comment by timarupopoka** [comment]
更新ありがとうございます。フォント設定1.22の動作報告です。
TE再起動後、問題のタブを初めてアクティブにするときには依然フォント設定が反映されませんが、一度別のタブをアクティブにした後、再度問題のタブをアクティブにすると設定が反映されるようになりました。
1.21で改善された内容は正常に動作しています（デグレの発生なし）。

**Comment by ccfs** [comment]
Navigation pane cannot get the specified font just after TE starts up or "Show frame" is turned on. Please help to solve this problem. Thanks.

![20220413_122621](https://user-images.githubusercontent.com/34089121/163113797-aba8e9ef-a889-42d7-aee6-21f9723cc2a6.png)
![20220413_122642](https://user-images.githubusercontent.com/34089121/163113808-436184bb-dc0e-4b11-ade6-ed86887f901f.png)

**Comment by timarupopoka** [comment]
TE22.4.11に更新したところ、フォント設定が反映されるようになりました。
問題のタブをアクティブにした瞬間に一瞬だけ反映前の状態が見えますが、使う上で問題はありませんのでこれで解決とさせていただきます。
お忙しいところ対応ありがとうございました。

@ccfs 
Once I got TE up to date, my issue was resolved, so I am closing here. If your issue still remains, please open a new one.
