### ISSUE TITLE
Question: add separator

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#582]
Hello Gaku. In my horizontal Favorites bar I have created a menu with subfolders, which is displayed as a dropdown menu. I want to add a separator in that menu, like the one on the screenshot. Is that possible? Thank you very much.

![Separador](https://user-images.githubusercontent.com/96446416/162595279-6ac73cb5-fad5-4f6f-a60a-e3e183636ca6.png)

**Comment by tablacus** [comment]
1. Select "Type" to "Menus".
2. Click "Browse.."
3. Choose "Separator".

![image](https://user-images.githubusercontent.com/5156977/162618038-1aee8312-7c16-438b-b37b-7323146a5811.png)

Regards,

**Comment by dieg467** [comment]
Very very simple. And he asked me how I didn't see it on the menu . Thank you very much, now I was able to add the separators I needed!
