### ISSUE TITLE
Short separator

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#583]
Hello, I am using separators in the toolbar, but they look short as the screenshot shows. Can they look longer? Thank you.

![Separador](https://user-images.githubusercontent.com/96446416/163489815-51b03ecd-bdb6-456e-9c35-9d9613f215cd.png)

**Comment by dieg467** [comment]
My view has already adapted to the short dividers so I'm going to keep them that way. If long spacers are eventually added, I'll test them and compare. Tablacus Explorer has become the application that I use the most on a daily basis! Thank you very much.

**Comment by ccfs** [comment]
You can download a modified version [here](https://github.com/tablacus/TablacusExplorer/issues/692).
