### ISSUE TITLE
Question: "Open layout in new window"

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#584]
Hello. I am using the multiprocess add-on to open a folder in a new window. But I ask, is there any command or any way that directly allows "open layout in new window"? Thank you very much.

**Comment by ccfs** [comment]
Use this command line:
TE64.exe "Load layout,`LayoutFile.xml`"

example:
![image](https://user-images.githubusercontent.com/34089121/163698870-e30efdbd-2d30-4c65-a9f4-cafcf6d7f217.png)

**Comment by dieg467** [comment]
Great ccfs, it worked! Now I can have multiple open windows of Tablacus explorer with your command line:
**Type:** Exec
**Options:** Program path TE64.exe "load layout,XML layout path"

I discovered that it also works in the following way, by installing the Multiple execution add-on:
**Type:** Open in new Windows
**Options:** Program path TE64.exe "load layout,XML layout path"

You have to wait about 2 or 3 seconds for the new window to appear in the foreground.
Sometimes I get the "script error" that I show in the screenshot, using Type "Exec" or using "Open in new windows". In both cases, this error usually appears. However, I say "Yes" to continue running, and the new window with the layout opens and can be used without problems. I use Windows 10.
![Error script](https://user-images.githubusercontent.com/96446416/163720807-5876a285-2276-4c6b-b9f3-31dcfd50330e.png)

Thank you very much for the help!
