### ISSUE TITLE
Suggestion: Vertical link bar

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#590]
Hello Gaku. I have the link bar in a vertical position. For each link to show only the icon, I have to leave the "Name" box empty. The result is in the screenshot below.

![Linkbar1](https://user-images.githubusercontent.com/96446416/164741275-8462e754-54e3-47f5-9d11-931abaa048b1.png)

My suggestion is to have options for the name, such as "hidden", "show label", as the following screenshot shows:

![Linkbar2](https://user-images.githubusercontent.com/96446416/164741782-51d260b1-0495-487b-b80b-0efbcae6cddd.png)

Is it possible to do that in the link bar? Thank you very much.

**Comment by dieg467** [comment]
> ¿Cómo hacer que la barra de enlace esté en posición vertical?

Hello, you have to go to the options of this add-on, as follows:
Menu --> Tools --> Add-on --> Link bar --> Options (cogwheel button) --> Position tab.
From there the "Left Bar 1" position is chosen, as the screenshot shows.

![Barra enlace vertical](https://user-images.githubusercontent.com/96446416/165346571-78b9a82f-2f97-4d66-8823-061cc4013a1a.png)

**Comment by appft** [comment]
Thanks，it's working

**Comment by ccfs** [comment]
I have found a way to hide the button names while keeping the names in Options. Use "User style sheet" add-on and enter this:
```
.linklabel {
	display:none;
}
```
The tip pop-ups will still show the address though.

**Comment by dieg467** [comment]
Excellent ccfs! I can now see the name of each link when entering the "Link bar" properties, without that name showing in the vertical bar.
Thank you so much!

**Comment by ccfs** [comment]
Now you can opt out button names with the [patched version](https://github.com/tablacus/TablacusExplorer/issues/692) of Link bar.

**Comment by dieg467** [comment]
Thank you very much, ccfs. Tablacus Explorer gets better every day!
