### ISSUE TITLE
crashes and duplicates

### ISSUE THREAD

**Issue by wyekey** [tablacus/TablacusExplorer#591]
Should there be two xml files for every add-on ? For example, the add-on "remember" has config.xml in its add-ons folder, and remember.xml in the config folder. Rather than going through all the settings each time I download a new version, I've just been copying the config folder contents across, but now have regular crashes and wondered if this was the issue. I had hoped the add-on "multi-thread" would solve the crashes but it hasn't.

**Comment by duarteframos** [comment]
Not all, some addons don't need to save any particular settings, some others prefer saving data to [Tab Separated Values (TSV) files](https://github.com/tablacus/TablacusExplorerAddons/wiki/label).

You can go through the [Addon Wiki](https://github.com/tablacus/TablacusExplorerAddons/wiki) and see where each addon saves data. Some list _Config file_ or _Relevant Files_ section, though the list is probably not comprehensive.

Under the _Config_ folder most files have a relevant name.

**Comment by wyekey** [comment]
Thanks for the reply. As that's normal, I know it's not an issue.

**Comment by ccfs** [comment]
Use "Add-ons updater" add-on and update your TE through "Help > Check for updates" instead. Then you do not need to re-setup nor to copy the config folder every time.

I do not know why your TE crashes so I cannot advise any fix. Therefore the easiest solution is, hopefully the last time, to setup a new copy of TE and use it thereafter (do a backup before actual use for safety).

Regards,

**Comment by wyekey** [comment]
Thanks for giving details of the add-ons updater. After working through your instructions, I found I had not installed the main menu add-on ( to give my TE copy a sparse clean look ). But that also meant file/help etc. headings were not visible, including the ability to update online, so I was unaware of that function. This will help me a lot. Thanks again.

**Comment by ccfs** [comment]
Use "Main menu button" add-on and disable "Main menu". Then you can have a clean look while still have a way to access the menu.

**Comment by wyekey** [comment]
Thanks, an obvious tip I hadn't thought of.
