### ISSUE TITLE
Suggestion in the submenus

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#593]
Hello Gaku. I have a suggestion for the Favorites bar and link bar submenus. I have created the submenu you see on the screenshot.

![Submenu favoritos](https://user-images.githubusercontent.com/96446416/166821000-3d6500b1-2259-4732-9d2b-88e569040ba9.png)

When entering the Favorites settings, you can see a uniform list, where Menu/Open, Menu/Close and folders cannot be distinguished. I marked them on the screenshot below.

![Submenu lista](https://user-images.githubusercontent.com/96446416/166821045-a523ba41-469c-4bfb-8998-24e91c062c88.png)

My suggestion is that the Menu/Open and Menu/Close have a background color, which allows them to be differentiated from the folders, as seen in the following screenshot. Those colors can be default by Tablacus or custom.

![Submenu lista fondo color](https://user-images.githubusercontent.com/96446416/166821097-4118a1c9-9183-42fd-9312-418764200cfa.png)

Is it possible to do something like that? Thank you.

**Comment by dieg467** [comment]
Another option would be to use a tree format, or use indentation for folders and subfolders, as in the image.

![166821045-a523ba41-469c-4bfb-8998-24e91c062c88](https://user-images.githubusercontent.com/96446416/194784060-304f8303-60bf-4144-904c-002bbc0b7edb.png)

**Comment by ccfs** [comment]
I have enhanced TE with the last suggestion. You can download the modified version [here](https://github.com/tablacus/TablacusExplorer/issues/692).

**Comment by dieg467** [comment]
> He mejorado TE con la última sugerencia. Puedes descargar la versión modificada [aquí](https://github.com/tablacus/TablacusExplorer/issues/692).

Excellent ccfs. That is exactly the desired behavior for the favorites menu and submenu. Thank you very much for this patch!!
