### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by Markreif** [tablacus/TablacusExplorer#60]
Is it possible to include an add-on giving direct access to specific folders? For example, if I want to go straight to folder XYZ, it would be interesting to have a way to go straight to it with a single click instead of travelling through different directories.

**Comment by tablacus** [comment]
How should I implement that?
Thank you.

**Comment by Markreif** [comment]
I apologize for delay.
In the video I show you how that is done with WDE.
I simply drag a folder to the bar and, at any moment, clicking on the shortcut I can immediately return to that folder or any other with a shortcut.

http://www.mediafire.com/download/cxvl3vi9asf2nw2/20160515_164154.mp4

**Comment by tablacus** [comment]
I've adjusted it on Horizontal Favorites Bar 1.08.
Please update add-on.

Best regards,

**Comment by Markreif** [comment]
Great man! Thanks a lot.

**Comment by tablacus** [comment]
It is my pleasure.
Thank you.
