### ISSUE TITLE
Q: Recommended process to copy Tablacus configuration to new computer?

### ISSUE THREAD

**Issue by chrissv** [tablacus/TablacusExplorer#600]
Hello,
I have Tablacus running on computer A with various add-ons added.
I have a new computer B and I want to set up Tablacus the same way as computer A.

Is there a recommended process to get computer B configured exactly like computer A for Tablacus?

**Comment by tablacus** [comment]
Where is the installed folder?
Let me know if it's "Program files" or not.

Regards,

**Comment by tablacus** [comment]
### Apps and add-ons

(Old PC) Program Files
Save Installed folder to USB.

(New PC) Program Files
Restore Installed folder from USB.

### Configure files

(Old PC) Open Help -> About Tablacus Explorer
![image](https://user-images.githubusercontent.com/5156977/169294289-b239002d-0d73-428e-8aa9-aba4db158bfe.png)
Click Here and open the "Config" folder.
Move up three.
Save "Tablacus" folder to USB.

(New PC) Open Explorer
Enter `%appdata%` to address bar.
Restore "Tablacus" folder from USB.

**Comment by chrissv** [comment]
Thank you
