### ISSUE TITLE
How to open every folder in Windows by tablacus？

### ISSUE THREAD

**Issue by forestbat** [tablacus/TablacusExplorer#603]
My system version is Windows 11 build 22621.
Some programs such as Firefox/Chrome，Control Panel or Tencent QQ/Wechat still will open Explorer.exe to find their files，how to let them to open tablacus when click “open directory” or similar function in those programs？
And I have changed register in regedit like this：
![屏幕截图 2022-06-14 111540](https://user-images.githubusercontent.com/23413915/173486257-65ae51b9-4a20-4b4d-b620-df45957ab2d1.png)
Should I change these “Delegate Execute” to {ceff45ee-c862-41de-aee2-a022c81eda92} or other values？

**Comment by ccfs** [comment]
try "Open instead" add-on

**Comment by forestbat** [comment]
> try "Open instead" add-on

It's good,but it still can't resolve all my problem:Tencent QQ and Control Panel will still use Explorer.

**Comment by forestbat** [comment]
And if I open file directory in Firefox's download,it will cost long time to open tablacus if tablucus is not running.

**Comment by ccfs** [comment]
use "Launch the app on system startup" add-on to start TE when Windows starts
