### ISSUE TITLE
Rename a large number of images

### ISSUE THREAD

**Issue by microdockman** [tablacus/TablacusExplorer#604]
If there are too many files to rename, right-click the ''rename'' and it will take a long time to calculate and deselect suddenly, its significantly slower than the renaming of multiple files in Windows Explorer

**Comment by ccfs** [comment]
You can use "X-Finder" add-on to rename _selected items_ with serial numbers:

`Numbering: "Pattern", Start value, Increment`

Pattern:
%d = number
%`.n`d = number in `n` digits (with leading zero)

example:
![image](https://user-images.githubusercontent.com/34089121/177023047-c0357a52-0e5d-4f76-93ee-7ca59f1e496a.png)

see:
https://github.com/tablacus/TablacusExplorerAddons/wiki/xfinder
https://www.eonet.ne.jp/~gakana/xf.html (Japanese)
