### ISSUE TITLE
Start Tablacus maximized

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#607]
Hello, I installed the "Start setting" add-on so that Tablacus always starts maximized, but I don't know how to do it. Is there a special command to use? Thanks.

**Comment by ccfs** [comment]
Options: api.SendMessage(ui_.hwnd, WM_SYSCOMMAND, SC_MAXIMIZE, 0);

![image](https://user-images.githubusercontent.com/34089121/177023774-64a412ec-e435-4bef-98bc-4722354b4469.png)

**Comment by dieg467** [comment]
It worked! Thank you very much ccfs.
I would have tried to start maximized through the properties of the shortcut to Tablacus and it hadn't worked.
