### ISSUE TITLE
Add a hide or unhide the extension of the files could be cool.

### ISSUE THREAD

**Issue by 3230** [tablacus/TablacusExplorer#609]
Add a hide or unhide the extension of the files could be cool.
How could i do this in a script ?
Thank you !
Have a great day

**Comment by ccfs** [comment]
I tried your script but got an error. So I have corrected and simplified it as follows. Thanks.
```
const RegPath = "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\HideFileExt";
if (wsh.RegRead(RegPath) == 0) {
	wsh.RegWrite(RegPath, "1", "REG_DWORD");
} else {
	wsh.RegWrite(RegPath, "0", "REG_DWORD");
}
FV.Refresh();
```

**Comment by 3230** [comment]
Nice ! Have a good day ! Thanks too
