### ISSUE TITLE
Hangs when many files updated

### ISSUE THREAD

**Issue by vain0** [tablacus/TablacusExplorer#62]
Tablacus Explorer で開いているフォルダに含まれる多数のファイルに更新(作成/変更/削除)があると、マウスカーソルが処理中の表示と通常の表示を交互に繰り返す状態になり、Tablacus Explorer を再び操作できるようになるまで数分かかります。

- git checkout で大きい更新をとるときによく起こります。
- 別のタブでディレクトリツリーを開いています。(すべてのツリーを閉じた状態では試していません。)

**Comment by vain0** [comment]
すみません、最新版では直っていました。

**Comment by tablacus** [comment]
報告ありがとうございます。もしかして、ラベルのカラムを使ってますか？
最新版で直ったとすれば、原因がラベルのカラムのバグだった可能性が一番ありそうです。
ファイルに更新→ファイルを表示しなおす（ここにバグがあった）→不具合って感じです。

**Comment by vain0** [comment]
ひとまず出せる情報は出しておきます。

- リストビューは詳細表示にしていますが、ラベルのカラムは選択していません。
- プラグインはタブグループの1個だけを使っています。
- 問題の環境は 16.4.11, Windows 7 です。
- いま Windows 10 & 16.4.18 の環境で動かしていますが、git checkout してもかなり軽いです。条件が違うので再現できていないだけかもしれませんが……
