### ISSUE TITLE
TE stucks when do some operation

### ISSUE THREAD

**Issue by forestbat** [tablacus/TablacusExplorer#621]
When I do cut，copy or paste or open zip file from everything in tablacus，the TE will stuck and the mouse pointer will turn for a long time(about 10-20 seconds)，I think it's a terrible problem，how to solve it？

This is my system info：
TE64 22.9.5 Microsoft Windows 11 专业版 64 位 22H2 (10.0.22622) IE/11 JS/11.0.16384 zh_cn 120 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz Windows Defender

This is my plugin list：
mouse 1.33,key 1.26,addressbar 1.70,filterbar 1.39,back 1.18,forward 1.18,up 1.20,treeview 1.43,toolbar 1.44,mainmenu 1.16,titlebar 1.09,tabplus 1.96,multithread 1.29,remember 1.42,undoclosetab 1.16,aboutblank 1.04,segoeicons 1.04,openinstead 1.13,everything 1.45,teracopy 1.13,opencpinexp 1.02,tablist 1.04,fastlistmode 1.04,history 1.20,speeddial 1.15,split3 1.12,split6 1.10,split9 1.04,split 1.26,recentlyclosedtabs 1.10,foldersettings 1.39,preventduplicatetabs 1.19,addonsupdater 1.10,importexplorer 1.11,clipfolder 1.28,clipboardhistory 1.08,cut 1.05,copy 1.05,delete 1.07,tasktray 1.15,paste 1.06

**Comment by ccfs** [comment]
multithread and teracopy add-ons may interfere each other. Try disabling one of them.

**Comment by forestbat** [comment]
> multithread and teracopy add-ons may interfere each other. Try disabling one of them.

OK,I disabled teracopy and now speed of file operation became faster.
