### ISSUE TITLE
TE still stucks when rename file

### ISSUE THREAD

**Issue by forestbat** [tablacus/TablacusExplorer#623]
#621 Now when I want to rename my file, TE still stucks for serveral seconds(~5 seconds, shorter than 10 seconds), and stuck will also happen when I move/copy file between directories.

This is my system info：
TE64 22.9.5 Microsoft Windows 11 专业版 64 位 22H2 (10.0.22622) IE/11 JS/11.0.16384 zh_cn 120 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz Windows Defender

This is my plugin menu:
mouse 1.33,key 1.26,addressbar 1.70,filterbar 1.39,back 1.18,forward 1.18,up 1.20,treeview 1.43,toolbar 1.44,mainmenu 1.16,titlebar 1.09,tabplus 1.96,multithread 1.29,remember 1.42,undoclosetab 1.16,aboutblank 1.04,segoeicons 1.04,openinstead 1.13,everything 1.45,opencpinexp 1.02,tablist 1.04,fastlistmode 1.04,history 1.20,speeddial 1.15,split3 1.12,split6 1.10,split9 1.04,split 1.26,recentlyclosedtabs 1.10,foldersettings 1.39,preventduplicatetabs 1.19,addonsupdater 1.10,importexplorer 1.11,clipfolder 1.28,clipboardhistory 1.08,cut 1.05,copy 1.05,delete 1.07,tasktray 1.15,paste 1.06,fixwin11prev 1.06

**Comment by ccfs** [comment]
Are you still using TeraCopy (the application, not the add-on)?

**Comment by tablacus** [comment]
It's a work-around.

1. Please install an add-on "Startup settings".
2. Open options of Startup settings.
3. Change "Type" to `JScript`
4. Enter `api.SHChangeNotifyDeregister(te.Data.uRegisterId);` in Options.
5. Quit and restart Tablacus Explorer.

![image](https://user-images.githubusercontent.com/5156977/194704657-73ad5d90-d5ce-4fa1-a105-b998c418f9bb.png)

Regards,

**Comment by forestbat** [comment]
> Are you still using TeraCopy (the application, not the add-on)?

No.

**Comment by forestbat** [comment]
> It's a work-around.
> 
>     1. Please install an add-on "Startup settings".
> 
>     2. Open options of Startup settings.
> 
>     3. Change "Type" to `JScript`
> 
>     4. Enter `api.SHChangeNotifyDeregister(te.Data.uRegisterId);` in Options.
> 
>     5. Quit and restart Tablacus Explorer.
> 
> 
> ![image](https://user-images.githubusercontent.com/5156977/194704657-73ad5d90-d5ce-4fa1-a105-b998c418f9bb.png)
> 
> Regards,

I tried your settings, and I discovered that stuck which happened after raname disappeared, and when I move file from directory A to directory B, it won't stuck basically.

However, when I try to move file from B back to A, stuck still exists with 1-3 seconds.

**Comment by ccfs** [comment]
You may try "Multi process" add-on (and disable "Mult thread" add-on) to see if there is any effect.

**Comment by forestbat** [comment]
> You may try "Multi process" add-on (and disable "Multi thread" add-on) to see if there is any effect.

Now the problem disappeared，thank for you and tablacus's reply，however I will keep this issue open if there is any other people has same problem.

**Comment by forestbat** [comment]
Now I encountered a new problem：if you read or delete(and so on) plenty of files，such as insert a portable hard disk on your computer(it has GB of bytes)，TE will stuck for 5~20 seconds.
@ccfs @tablacus

**Comment by forestbat** [comment]
And when I'm deleting plenty of files，move file in another directory to 3rd directory can also lead to stuck.

**Comment by forestbat** [comment]
Now the problem looks like disappeared，so I will close it.
