### ISSUE TITLE
[Feature Request] Position option for "Inner New Folder"

### ISSUE THREAD

**Issue by SHHSSH** [tablacus/TablacusExplorer#627]
Hi Gaku & others,

I'm looking to request a feature of "Position" in the add on Inner New Folder.

<a href="https://ibb.co/6mCxXHT"><img src="https://i.ibb.co/47rG18X/capture-005-25102022-172608-copy.jpg" alt="capture-005-25102022-172608-copy" border="0"></a>

As you can see in the sceenshot above, I cannot effectively add the addon to my main region where I'm using Refresh & Up one folder level.

Thanks for any consideration, appreciate all that you do & love the software.

**Comment by ccfs** [comment]
The image is unclear. I cannot see exactly where you want to place the button.

**Comment by SHHSSH** [comment]
> The image is unclear. I cannot see exactly where you want to place the button.

Where the green refresh icon & upper one folder level is, just before "TDls" folder on my second row.

The "Position" option is enabled in many add-ons options, just not this one.

**Comment by ccfs** [comment]
A workaround is to add a button to Tool Bar:

![image](https://user-images.githubusercontent.com/34089121/198164991-67385ea4-774c-4df3-b327-6f0b35bc53c4.png)
