### ISSUE TITLE
Add-on failure -“Force refresh”and “close tab when deleting”

### ISSUE THREAD

**Issue by yaolion** [tablacus/TablacusExplorer#628]
system is win11 22h2 

“Force refresh”-Dragging files from different windows cannot take effect immediately

“close tab when deleting”-Doesn't work

I really like this software. I hope it can solve the problem~

![2022-10-27_11-57-10](https://user-images.githubusercontent.com/47139379/198188557-d2eef250-cefe-4fb9-bd0c-68892044ca03.png)
![2022-10-27_12-01-53](https://user-images.githubusercontent.com/47139379/198188595-ffafd923-68db-4316-ab5c-559fd4b42ae0.png)
![2022-10-27_12-14-31](https://user-images.githubusercontent.com/47139379/198189966-07056bae-7e83-4ea7-ba82-9f87ac9e6f1b.png)

**Comment by ccfs** [comment]
Regarding "close tab when deleting", the add-on seems to work if a folder is deleted by ANOTHER application, but NOT by TE.

**Comment by yaolion** [comment]
I modified the code myself to meet my own needs

**Comment by ccfs** [comment]
Can the problems be produced on Windows 7 with IE, which is my config? If so, can you share your modification so that I can include it in my [patches](https://github.com/tablacus/TablacusExplorer/issues/692)?

**Comment by yaolion** [comment]
Sorry, I haven't used github to view replies for a long time. Currently, the complete code I use to Force refresh js is as follows：

const Addon_Id = "forcerefresh";
if (window.Addon == 1) {
    const item = await GetAddonElement(Addon_Id);
    Addons.ForceRefresh = {
        Filter: await ExtractFilter(item.getAttribute("Filter") || "-"),
        Disable: await ExtractFilter(item.getAttribute("Disable") || "-"),
        Notify: 0,
        Timeout: GetNum(item.getAttribute("Timeout")) || 200,
        db: {},
        tid: {},
        Drop: GetNum(item.getAttribute("Drop")),
        refreshInProgress: false,

        Refresh: async function (FV) {
            const Id = await FV.Id;
            if (Addons.ForceRefresh.tid[Id]) {
                clearTimeout(Addons.ForceRefresh.tid[Id]);
            }
            Addons.ForceRefresh.tid[Id] = setTimeout(async function (Id) {
                delete Addons.ForceRefresh.tid[Id];
                if (await api.GetClassName(await api.GetFocus()) != WC_EDIT) {
                    
                    await FV.Refresh();
                }
            }, Addons.ForceRefresh.Timeout, Id);
        },

        ChangeNotify: async function (FV, pidls, lEvent) {
            if (((lEvent & SHCNE_RENAMEITEM | SHCNE_RENAMEFOLDER) && await api.ILIsParent(FV, await pidls[1], true)) || await api.ILIsParent(FV, await pidls[0], true)) {
                Addons.ForceRefresh.Refresh(FV);
            }
        },

        FO: async function (Dest) {
            const cFV = await te.Ctrls(CTRL_FV, false, window.chrome);
            for (let i = cFV.length; --i >= 0;) {
                if (await api.ILIsEqual(cFV[i], Dest)) {
                    Addons.ForceRefresh.Refresh(cFV[i]);
                }
            }
        },

        ManualRefresh: function (FV) {
            Addons.ForceRefresh.Refresh(FV);
        },

        StartFolderChangeWatcher: function (FV) {
            Addons.ForceRefresh.CheckFolderChanges(FV);
        },

        CheckFolderChanges: async function (FV) {
            if (!Addons.ForceRefresh.refreshInProgress) {
                Addons.ForceRefresh.refreshInProgress = true;
                const path = await FV.FolderItem.Path;
                if (path in Addons.ForceRefresh.db) {
                    const lastId = Addons.ForceRefresh.db[path];
                    const currentId = await FV.FolderItem.ModifyDate;

                    if (lastId !== currentId) {
                        Addons.ForceRefresh.db[path] = currentId;
                        Addons.ForceRefresh.Refresh(FV);
                    }
                } else {
                    Addons.ForceRefresh.db[path] = await FV.FolderItem.ModifyDate;
                }
                Addons.ForceRefresh.refreshInProgress = false;
            }
        },
    };

    let db = {
        "NewFile": SHCNE_CREATE,
        "NewFolder": SHCNE_MKDIR,
        "Delete": SHCNE_DELETE | SHCNE_RMDIR,
        "Rename": SHCNE_RENAMEITEM | SHCNE_RENAMEFOLDER
    };
    for (let n in db) {
        if (GetNum(item.getAttribute(n))) {
            Addons.ForceRefresh.Notify |= db[n];
        }
    }
    delete db;
    if (Addons.ForceRefresh.Notify) {
        AddEvent("ChangeNotify", async function (Ctrl, pidls) {
            const lEvent = await pidls.lEvent;
            if (lEvent & Addons.ForceRefresh.Notify) {
                const cFV = await te.Ctrls(CTRL_FV, false, window.chrome);
                for (let i = cFV.length; --i >= 0;) {
                    Addons.ForceRefresh.ChangeNotify(cFV[i], pidls, lEvent);
                }
            }
        });
    }

    if (Addons.ForceRefresh.Drop) {
        AddEvent("Drop", async function (Ctrl, dataObj, grfKeyState, pt, pdwEffect) {
            const nType = await Ctrl.Type;
            if (nType == CTRL_SB || nType == CTRL_EB) {
                let Dest = await Ctrl.HitTest(pt);
                if (!Dest) {
                    Dest = await Ctrl.FolderItem;
                }
                if (Dest) {
                    const path = await Dest.Path;
                    if (!await fso.FolderExists(path)) {
                        const dropTarget = await api.DropTarget(Dest);
                        if (dropTarget) {
                            Addons.ForceRefresh.ManualRefresh(Ctrl);
                            Addons.ForceRefresh.StartFolderChangeWatcher(Ctrl);
                            return;
                        }
                    }
                    Addons.ForceRefresh.FO(Dest);
                    Addons.ForceRefresh.StartFolderChangeWatcher(Ctrl);
                }
            }
        }, true);
    }

  
} else {
    const ar = (await ReadTextFile("addons\\" + Addon_Id + "\\options.html")).split(//);
    SetTabContents(0, "Tabs", ar[0]);
    SetTabContents(1, "General", ar[1]);
}

**Comment by yaolion** [comment]
> 这些问题是否会出现在 Windows 7 上，我的配置是 IE？如果是，您能否分享您的修改，以便我可以将其包含在我的[补丁](https://github.com/tablacus/TablacusExplorer/issues/692)中？

I saw through email today that one of the issues has been fixed. Thank you very much. This is the repair file (on Win11) that I used to solve the problem of Force refresh not working. I hope it can be helpful to you~
[forcerefresh.zip](https://github.com/user-attachments/files/15991293/forcerefresh.zip)

**Comment by ccfs** [comment]
Thanks. I am repairing "Force refresh" add-on. A patched version will be available some days later.

**Comment by ccfs** [comment]
The patched version of "Force refresh" is now available. You will need to revise the revamped options.
