### ISSUE TITLE
Spacer extension

### ISSUE THREAD

**Issue by Sibelius58** [tablacus/TablacusExplorer#630]
I am just writing to ask if there is a possibility to vary the (horizontal) space between icons (extensions) on the toolbar (or other bars). If not, I ask, as a layman, if it is not possible to work out an extension that introduces space between icons (extesions), a spacer, in short.
Thanks, regards

**Comment by ccfs** [comment]
Use "User style sheet" add-on:
![image](https://user-images.githubusercontent.com/34089121/205195802-c141c192-c0f5-4b41-b81f-e1c601b71c6b.png)
The above example adds 2 pixels at the left and right of each button. You can refer to "script\index.css" for the default settings.

You can use a tool bar button to open the add-on settings page quickly:
![image](https://user-images.githubusercontent.com/34089121/205196948-a3c4323a-8220-46ff-9fa3-546c026b4c1d.png)

see:
[TE Add-ons in Categories PDF](https://github.com/ccfs/TablacusExplorer/issues/1)
https://www.w3schools.com/css/css_padding.asp
