### ISSUE TITLE
Paste addon (icon) weird behavior

### ISSUE THREAD

**Issue by Sibelius58** [tablacus/TablacusExplorer#632]
The extension Paste has a strange behavior, at least in my system(s). When inactive, besides being grayed out, the icon is very small (see screen 1). When activated the icon becomes normal (see screen 2), I mean the same size of the others. The extension has not a special setting as concerns icon dimension (see screen 3).
It's meant as its defaut behavior? Could the grayed out dimension remain that in the settings (in my case 20px)
![1](https://user-images.githubusercontent.com/49116251/205339684-1e1e5549-a464-47ea-a8c3-c62f5c7cbb26.jpg)
![2](https://user-images.githubusercontent.com/49116251/205339697-7e433761-b6b7-4512-bd08-cc7a2cd5c7b9.jpg)
![3](https://user-images.githubusercontent.com/49116251/205339706-160949ce-220a-4e86-a3fd-d8a1cb8e4b41.jpg)

P.S. Obviously the Paste icon is a 48px PNG as the others

**Comment by ccfs** [comment]
This may be due to co-use of "User style sheet" (https://github.com/tablacus/TablacusExplorer/issues/630) . Please change the settings as follows:

![image](https://user-images.githubusercontent.com/34089121/205528397-a8abecee-3c4b-44a9-9095-eb2e933d64ab.png)
```
.button, .button1 {
	margin: 0 2px;
}

.hoverbutton, .activebutton {
	margin: 0 2px;
}
```

**Comment by Sibelius58** [comment]
Thanks again,
 the icon is perfect now, the issue becomes now the drop down menu of the address bar(s) that overlaps the border (see screenshots attached)
![2](https://user-images.githubusercontent.com/49116251/205591265-5787aa59-a5a0-4037-979c-7bceae2d2ab0.jpeg)
![1](https://user-images.githubusercontent.com/49116251/205591275-807cd9c3-9ebd-48ce-bd30-32130635fb86.jpeg)

**Comment by ccfs** [comment]
Try this. All 4 pixels of space are at the right of each button:
```
.button, .button1 {
	padding: 0;
	margin: 1px 5px 1px 1px;
}

.hoverbutton, .activebutton {
	margin: 0 4px 0 0;
}
```
see: https://www.w3schools.com/css/css_margin.asp

**Comment by Sibelius58** [comment]
Thanks very much for your assistance: we are almost there.
There is still some overlap with the drop down arrow in the address bar (see screenshots): could it be moved totally inside the border of the address bar?
![1](https://user-images.githubusercontent.com/49116251/205603311-2e979327-77df-4eca-8aa5-801f57631d3d.png)
![2](https://user-images.githubusercontent.com/49116251/205603317-e84840fe-03a9-479a-a016-966cffd29199.png)

**Comment by ccfs** [comment]
My last reply is the best way I can think of. You can consult other users or the application author @tablacus to see if they have an even better solution.

**Comment by Sibelius58** [comment]
I gave up and deleted the user sheet. I am still convinced that for some reason the Paste extension has some issues: even without user style sheet when grayed out the icon is smaller and out of axis, whichever its position in the toolbar. That doesn't happen to all the other icons.

**Comment by ccfs** [comment]
Conclusion:
1. My suggestion in (https://github.com/tablacus/TablacusExplorer/issues/630) to add space by changing "padding" is correct.
2. Some TE add-ons (e.g. "Paste", "Paste as link") have a problem in showing grayed icons (but some do not, e.g. "Back", "Forward").
3. "User style sheet" add-on does not cause the problem. It just makes the problem obvious.
4. Changing "margin" instead of "padding" as a workaround does not work well on the drop-down button of address bar.

**Comment by Sibelius58** [comment]
Thanks ccfs for your help and your summary.

**Comment by Sibelius58** [comment]
Gaku updated Paste addon (1.07): now everything is ok, even with user style sheet. I used ccfs initial suggestion (changing padding) and now my icons are nicely spaced. Thank you very much Gaku and ccfs!

P.S. That refers to "Paste" addon, don't know about "Paste as link"
