### ISSUE TITLE
favorites bar and side tree view sizing

### ISSUE THREAD

**Issue by astro46** [tablacus/TablacusExplorer#633]
I am using favorites bar 1.42 and side tree view 1.27  (i believe that these are addons that I am asking about.  addon names and descriptions are vague so it is hard to know exactly what they are referring to ).

I am viewing them on left side of tablacus window. favorites bar on top of side tree view.  I find that I can set the vertical size for both of them.  the problem I am having is that if the tablacus window vertical size changes, then the 2 addons don't adjust to match the new window size.  Sometimes there is empty space under side tree view, sometimes the bottom of tree is cut off (and, sometimes the vertical scroll bar is missing).

is there a way to tell the addons to auto adjust to window size?

**Comment by ccfs** [comment]
Specify their heights in percentage, e.g. 30% for "Favorites bar" and 70% for "Side tree view".

**Comment by astro46** [comment]
perfect.   just what I wanted. 
thank you.
would be good to suggest "%" or "number", in text, next to the box, in options.

**Comment by bblackmoor** [comment]
I have the updates ready to merge with the official repo.

**Comment by astro46** [comment]
> I have the updates ready to merge with the official repo.

i don't know what this means.  does it indicate something I could, or ought, to do? if so, what? Or is this message intended for someone more informed than me?

**Comment by bblackmoor** [comment]
> > I have the updates ready to merge with the official repo.
> 
> i don't know what this means. does it indicate something I could, or ought, to do? if so, what? Or is this message intended for someone more informed than me?


I do not know. I have not contributed to a project on Github before.

**Comment by bblackmoor** [comment]
This change is live.

![image](https://user-images.githubusercontent.com/33701300/211849629-dd307a07-2a0e-4263-a90c-7a8ca94c71cc.png)
