### ISSUE TITLE
preview 1.46,  possible to toggle off/on

### ISSUE THREAD

**Issue by astro46** [tablacus/TablacusExplorer#635]
Win10, x64.  
currently I have it enabled. It appears on right side of tablacus window. 

I am wondering if there is a switch available for taskbar for turning it on/off (similar to the icon for 'preview window').  or a setting, eg: under 'view' 

btw: i am not referring to 'preview window'  1.32.

**Comment by ccfs** [comment]
Enable "Add-on switcher" add-on. Use a tool bar button to toggle preview pane:

![image](https://user-images.githubusercontent.com/34089121/205530772-4d959828-ba6a-4be4-9fcc-827179af2db5.png)

see: https://github.com/ccfs/TablacusExplorer/issues/1

**Comment by astro46** [comment]
ccfs:  thanks.  took about half hour of searching and experimentation to figure out how to get to where your pic is from, and  to wiki help pages (flaw that I didn't think to look there earlier. I am the sort that always reads directions before assembly!) and experimentation to figure out positioning. 

TE is quite the brain exercise. 
I think i have it doing what I want. 
thanks again.
