### ISSUE TITLE
folder settings: 17 instead of "This PC"

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#64]
Hi,
maybe this is an error:
1) load the "This PC" special folder
2) open options dialog for "Folder Settings" addon
3) click "get the current folder view" button
4) I get a 17 in the Filter section, instead of "This PC".

**Comment by tablacus** [comment]
Thank you for a report.
There is nothing wrong with it.
The special folders are replaced with a number.(Internal code)
When you input "17" into an address bar, It move to a "This PC".

Best regards,

**Comment by stefanocaselli** [comment]
ok thank you.


2016-06-20 13:58 GMT+02:00 Gaku <notifications@github.com>:

> Thank you for a report.
> There is nothing wrong with it.
> The special folders are replaced with a number.(Internal code)
> When you input "17" into an address bar, It move to a "This PC".
>
> Best regards,
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tablacus/TablacusExplorer/issues/64#issuecomment-227122771>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ3kM28AZQpLqYgQiBbt4gMVa2Cxue8aks5qNoBugaJpZM4I5e0N>
> .
>



-- 

70% of all internet quotes are fake   - Albert Einstein
