### ISSUE TITLE
Add space to invoke Quicklook in treeview

### ISSUE THREAD

**Issue by jiewangjs** [tablacus/TablacusExplorer#641]
Hi, as I have stated in the title, if quicklook can be used within the treeview entries, it would be great.

**Comment by ccfs** [comment]
try this:
![image](https://user-images.githubusercontent.com/34089121/210955250-f64d628e-e8dc-4a85-aab0-fe65ed530f1e.png)
```
if (Common.SideTreeView) {
	Sync.QuickLook.SendMessage(null, "Switch", Common.SideTreeView.TV.SelectedItem.Path);
} else {
	Sync.QuickLook.SendMessage(null, "Switch", te.Ctrl(CTRL_FV).TreeView.SelectedItem.Path);
}
```

**Comment by jiewangjs** [comment]
As I haven't able to locate the exact dialog box as yours, I modified the above places and it didn't turn out well. Not sure what the problem is ?

| |


|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/6/2023 15:52 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [tablacus/TablacusExplorer] Add space to invoke Quicklook in treeview (Issue #641) |

try this:


if (Common.SideTreeView) {
	Sync.QuickLook.SendMessage(null, "Switch", Common.SideTreeView.TV.SelectedItem.Path);
} else {
	Sync.QuickLook.SendMessage(null, "Switch", te.Ctrl(CTRL_FV).TreeView.SelectedItem.Path);
}

**Comment by jiewangjs** [comment]
![image](https://user-images.githubusercontent.com/11204422/210961953-77f28ca0-bb8d-41ae-8bde-6aa75530011e.png)

![image](https://user-images.githubusercontent.com/11204422/210962049-f45346b2-e724-48d1-acf1-417ac7cb181d.png)

As I haven't able to locate the exact dialog box as yours, I modified the above places and it didn't turn out well. Not sure what the problem is ?

**Comment by ccfs** [comment]
You have got the correct place.
How "not well" was it? Any error message?

**Comment by jiewangjs** [comment]
![image](https://user-images.githubusercontent.com/11204422/210979443-95b06fe2-191b-4ab6-93f0-f9003243d7a1.png)
![image](https://user-images.githubusercontent.com/11204422/211008358-3b65da4f-e43a-4c1e-84b4-0993d781688d.png)
![image](https://user-images.githubusercontent.com/11204422/211008376-c088da1d-fd27-456d-b735-078080e40824.png)
![image](https://user-images.githubusercontent.com/11204422/211008459-4b60f141-84e2-4506-af7c-c3c70dbb520c.png)
I thougt it should work, but not. Not sure if some other configurations in my pc affect the outcome.

**Comment by jiewangjs** [comment]
> You have got the correct place. How "not well" was it? Any error message?

What version are you using ? I am using the lastest version. Already tested on two installations of different pc, neither works.

**Comment by jiewangjs** [comment]
I added some debug printout codes which are also displayed in the following image. 

![image](https://user-images.githubusercontent.com/11204422/211125759-04178250-1e7e-4ea7-b2ee-363ed9f99f84.png)
This image is what popped out when I pressed space in the treeview.
Maybe it contains some valuable info for the cause of disfunctionality.

**Comment by ccfs** [comment]
I did not actually invoke QuickLook, as I had uninstalled the latter for a long time. I just added some lines to a temporary copy of the add-on to see the path.

You can try to change the word "Switch" to "Toggle" to see if this works.

By the way, it is a bad idea to use the folder tree also as a file list (by ticking "Not folders" option of "Tree"). A folder tree can never work in the same way as a file list. Doing so just causes yourself trouble.

The normal way to get multiple panes of file lists is to use "Split" add-on.
