### ISSUE TITLE
Padding between icons in the toolbar

### ISSUE THREAD

**Issue by bblackmoor** [tablacus/TablacusExplorer#642]
First, thank you for this file manager . I have been seeking a Windows file manager that has tabs, dual panes, and a tree in each pane, for years. I have been looking for an open source file manager for Windows for even longer. I have been using Q-Dir, which is excellent, but not open source. I only learned about Tablacus Explorer yesterday, and only downloaded it today. It took some tinkering and Googling to figure out how to set it up to my liking, but to my surprise, that was possible! And it's fast! I keep expecting to find something I do not like, but I haven't yet. Thank you!

Second, is there a setting to adjust the horizontal spacing of the toolbar icons? I would like to add a few pixels between them.

![image](https://user-images.githubusercontent.com/33701300/211119069-c388e6f3-e4fd-41ea-8d12-9d9b501e86ce.png)

**Comment by ccfs** [comment]
see https://github.com/tablacus/TablacusExplorer/issues/630

**Comment by bblackmoor** [comment]
Do I need both of these addons?

https://tablacus.github.io/wiki/addons/usercss.html

https://tablacus.github.io/wiki/addons/tabdesign.html

**Comment by ccfs** [comment]
"User style sheet" add-on is sufficient for tool bar icon padding.

"Tab design" add-on is for customizing tab appearance. "User style sheet" add-on can also do this (and more) but you will need knowledge about CSS in TE.

**Comment by bblackmoor** [comment]
Thank you! This is outstanding.
