### ISSUE TITLE
Groups of addons

### ISSUE THREAD

**Issue by bblackmoor** [tablacus/TablacusExplorer#648]
Is it currently possible to have an addon which itself is a wrapper for other addons? So that if you update that addon, it updates the underlying addons (checking dependencies, etc.), in addition to anything new and specific to that wrapper addon?

If this is not currently a feature, perhaps it is something I could work on. What do you think?

**Comment by ccfs** [comment]
Currently there is not such feature on a per add-on basis. If you just want a quick way to update all installed add-ons, instead of clicking the Install buttons one by one on "Help > Get Add-ons" page, you can use "Add-ons updater" add-on. See https://github.com/ccfs/TablacusExplorer/issues/1.

**Comment by bblackmoor** [comment]
I will give this additional thought.
