### ISSUE TITLE
[IMPROVEMENT] Addon Quick notes

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#650]
Hello Gaku. I wish the "Quick Notes" addon had the option to customize the icon. Is it possible to add this improvement? Thank you.

![Quick notes](https://user-images.githubusercontent.com/96446416/212765245-af55bdbd-755e-422a-8266-7760b81e376a.png)

**Comment by tablacus** [comment]
Please try to update it.

Regards,

**Comment by dieg467** [comment]
Great thank you very much!!

![Icono notas](https://user-images.githubusercontent.com/96446416/212962897-d888b95c-24af-4319-8889-7108066c71fd.png)

**Comment by ccfs** [comment]
I have further modified the add-on to let you:
- choose the location of the button; and
- specify `-` for a menu separator line
