### ISSUE TITLE
Tablacus just hangs and does nothing

### ISSUE THREAD

**Issue by bblackmoor** [tablacus/TablacusExplorer#657]
I keep encountering an issue where, when I copy a file (with the intention to paste it elsewhere) Tablacus just spins in place and does nothing, for longer than I feel like waiting. Have others encountered this? If so, is there a fix for it?

**Comment by bblackmoor** [comment]
That screenshot does not show the blue "waiting" ring at the cursor. Sorry.

**Comment by ccfs** [comment]
You need to provide more info so that other persons can see what happened, e.g. screen dumps. Also choose Help > About, click the Copy button and paste your TE config info here.
