### ISSUE TITLE
Shift + mouse wheel to scroll horizontally.

### ISSUE THREAD

**Issue by Restricted18** [tablacus/TablacusExplorer#659]
How do I use Shift+mouse wheel to scroll horizontally?
I want to do this operation like in Cad or Browser.
(TE's split screen and tree folders are useful, but scrolling sideways is frequent.)
I set S8,S9 in add-on Mouse but could not find horizontal scrolling.

**Comment by ccfs** [comment]
add these 2 records:
![20230212_095915](https://user-images.githubusercontent.com/34089121/218288991-eb33968d-f5ad-40d1-b2f5-0fb1248dd581.png)
![20230212_095928](https://user-images.githubusercontent.com/34089121/218288993-eea03b1d-3542-417e-a5bd-fbd99f5d4d12.png)

They send `^{Left}` (Ctrl+Left) / `^{Right}` (Ctrl+Right) keys to a folder tree to scroll horizontally.

**Comment by ccfs** [comment]
The settings for file lists are a bit complicated. Shift+Left and Shift+Right keys are used to scroll horizontally in Details view, but are used for selection in other views. Therefore Shift+Wheel will be ignored for other views.

![20230212_152009](https://user-images.githubusercontent.com/34089121/218298793-32f18c89-a779-4f29-8550-eb7e85a2128c.png)
```
var TC = te.Ctrl(CTRL_TC);
if (TC)  {
  if (TC.Selected.CurrentViewMode == FVM_DETAILS) {
    wsh.SendKeys("+{Left}");
    return S_OK;
  }
}
return S_FALSE;
```
![20230212_152018](https://user-images.githubusercontent.com/34089121/218298794-037111e9-788d-487a-a7f7-43a544a5e54e.png)
```
var TC = te.Ctrl(CTRL_TC);
if (TC)  {
  if (TC.Selected.CurrentViewMode == FVM_DETAILS) {
    wsh.SendKeys("+{Right}");
    return S_OK;
  }
}
return S_FALSE;
```

**Comment by Restricted18** [comment]
Thank you for your excellent response.
This is exactly the setup I was looking for.
My deepest thanks to ccfs.

The file lists setting seems to sometimes move up and down at higher wheel speeds. Also, I would like the amount of movement to the left and right to be about 4 times greater than that caused by these settings, so perhaps it would be better if they were implemented natively in TE.

Anyway, thank you very much.
I will close this issue.

**Comment by ccfs** [comment]
You can specify how many times to repeat the keystroke, e.g. `^{Left 4}` / `^{Right 4}` / `+{Left 4}` / `+{Right 4}`.
I also get the file list moving up and down problem. This may be a problem of TE.

**Comment by ccfs** [comment]
I have finally solved the file list moving up and down problem. Here are the updated setup:

![List left](https://user-images.githubusercontent.com/34089121/218387038-4d298d97-11c9-40d1-8ec2-535f064d18c1.png)
```
FV.Focus();
setTimeout(async function () {
	if (FV.CurrentViewMode == FVM_DETAILS) {
		wsh.SendKeys("+{Left 4}");
	}
}, 99);
```
![List right](https://user-images.githubusercontent.com/34089121/218387048-e90dd96f-1ea4-472c-93a7-7ca90c2cebdb.png)
```
FV.Focus();
setTimeout(async function () {
	if (FV.CurrentViewMode == FVM_DETAILS) {
		wsh.SendKeys("+{Right 4}");
	}
}, 99);
```
