### ISSUE TITLE
[Improvement] Save icons and images in Tablacus

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#660]
Hello Gaku. I'm using Windows 10 and I changed the location of the "Pictures" folder, where all the pictures, photos, and icons I keep on my computer are. Many of those images and icons are what I use in Tablacus. The problem is, after moving the "Images" folder, all the custom icons I use in Tablacus were no longer visible. Instead, I was seeing this: [x].
Is it possible for Tablacus to automatically create a subfolder in your root, with all the icons and images used in it? That way they will not be affected by any changes made to the PC. Thank you so much.

**Comment by tablacus** [comment]
Please read this and tell me about your environment.
https://github.com/tablacus/TablacusExplorer/wiki/report-problem

What icons are you using?

Regards,

**Comment by dieg467** [comment]
Hello. My comment does not refer to any problem in Tablacus Explorer.
(1) Tablacus works perfectly.
(2) The original images and icons look perfect.
I use some custom icons in, which replace the original icons.

![image](https://user-images.githubusercontent.com/96446416/221052772-31b2b1f4-a450-4d4f-bb87-401f0b0c2aae.png)

These custom icons are stored in the Windows 10 "Pictures" folder, outside of the Tablacus folder directory.
When I moved the "Images" folder to another location on my computer, Tablacus no longer found them to display and when entering Tablacus, I only saw this: [x].
Is it possible for Tablacus to make a copy of the images and custom icons used with it, and store them in a subfolder within the Tablacus directory? In this way, they will always be available to be displayed by Tablacus.
Thank you so much!

TE64 23.1.31 Microsoft Windows 10 Pro 64 bits 22H2 (10.0.19045) IE/11 JS/11.0.16384 es_es 96 AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G Windows Defender

**Comment by tablacus** [comment]
My PC was able to display the icon even when it was placed in the Pictures folder. Here's what my settings look like.
How are you configuring your settings to try and display the icon?
![image](https://user-images.githubusercontent.com/5156977/221190755-855d5b4c-69e2-4d46-b6a7-2cb6c968ed8c.png)

Regards,

**Comment by dieg467** [comment]
EXAMPLE

ICON A
- Location on PC: C:\Windows\Pictures\icon A
- Path in Tablacus: C:\Windows\Pictures\icon A
RESULT: OK, it looks correct.

ICON A
- Location on PC: C:\Windows\User\Media\icon A
- Path in Tablacus: C:\Windows\Pictures\icon A
RESULT: [x] Not seen.
Tablacus can't find the file because it changed location on the PC, and Tablacus has the old path.

Therefore, I would like Tablacus to make a copy of the images and icons used in it, save them in a subfolder of its directory, and automatically associate the location of that copy in Tablacus.

**Comment by tablacus** [comment]
How about using the "Replace command" add-on to try replacing a string of path?

```
/^C:\\Windows\\Pictures\\/C:\Windows\User\Media\/i
```

![image](https://user-images.githubusercontent.com/5156977/221412267-6a8a5fe7-32e7-4f8e-8bc3-f173468c86be.png)

Regards,

**Comment by dieg467** [comment]
Great, I'm going to try that plugin!
Thank you very much Gaku!!
