### ISSUE TITLE
Remove drive letter from tab name 

### ISSUE THREAD

**Issue by PaduaPlay** [tablacus/TablacusExplorer#665]
Is there an option to remove drive letter from the tab name?

The add-ons 'change tab name' allow changing the tab name, but still retains the drive letter on the tab name.

Ability to  remove drive letter from tab name  allows a way to save space on the tab name width.

Thank you.

**Comment by ccfs** [comment]
Drive letter overlays on icon. It does not occupy any extra space. Therefore, to save space, you need to disable BOTH icon and drive letter in "Tab plus" add-on.
![20230601_092907](https://github.com/tablacus/TablacusExplorer/assets/34089121/390d3072-cfc7-4024-99e2-b7374828146a)
