### ISSUE TITLE
open a directory with comma from command line or another process fails

### ISSUE THREAD

**Issue by herbrot** [tablacus/TablacusExplorer#670]
this does not work:
TE64.exe "c:\temp\Test with , comma"

TE64 23.1.31 Microsoft Windows 10 Home 64-Bit 22H2 (10.0.19045) WebView2/114.0.1823.51 JS/Chakra.dll de 120 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz Windows Defender
filterbar 1.39,back 1.18,forward 1.18,up 1.20,treeview 1.43,toolbar 1.44,mainmenu 1.16,titlebar 1.09,tabplus 1.96,multithread 1.29,remember 1.42,undoclosetab 1.16,quicklook 1.11,hotbutton 1.13,run 1.07,menuimageplus 1.04,tooltippreview 1.27,preventduplicatetabs 1.19,innerup 1.10,everything 1.45,favorites 1.06,mainmenubutton 1.17,totalfilesizesort 1.13,innerbreadcrumbsaddressbar 1.50,modifydatecolor 1.09,gridlines 1.05,linkbar 1.33,foldermenufilter 1.04,takeoverfoldersettings 1.08,touchex 1.10,innerback 1.14,innerforward 1.16,innerrefresh 1.07,multiprocess 1.37,stripeslite 1.09,statusbarex 2.01,folderlistmenu 1.15,split 1.26,fastlistmode 1.04,foldersettings 1.39,itemscount 1.02,pathicon 1.21,clipfolder 1.28,enteredhistory 1.05,history 1.20,label 1.45,labelbutton 1.15,closewhendeleting 1.03,tabcolor 1.09,mouse 1.33,refresh 1.10,tabcolorplus 1.07,tabdesign 1.16

**Comment by tablacus** [comment]
I have made the necessary fixes on Tablacus Explorer version 23.6.25.
Please consider updating to the latest version.

Regards,

**Comment by herbrot** [comment]
Thank you very much, works perfectly.
Best Regards
