### ISSUE TITLE
Color label: The background color cannot be canceled

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#674]
I am using the "Color label" plugin to color the background of a file in the file list. From the context menu I choose "Color label" and then the corresponding color. However, if I want to remove the color and return to the file's default state (no background color), it's not possible.
Previously, I removed the background color by right-clicking on the file to open the context menu --> Color label --> Cancel. This no longer works.
What could be the problem? Thank you.
TE64 23.6.25 Microsoft Windows 10 Pro 64 bits 22H2 (10.0.19045) IE/11 JS/11.0.16384 es_es 96 AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G Windows Defender

**Comment by dieg467** [comment]
As an additional comment, it would be important that in the context menu, "Color label" had the options "Add color" and "Remove color".

**Comment by ccfs** [comment]
I suggest using the [previous version](https://github.com/tablacus/TablacusExplorer/files/11997260/colorlabels_109.zip) which works correctly.

**Comment by dieg467** [comment]
Indeed ccfs. When installing the previous version it works correctly.
Thank you so much!

**Comment by tablacus** [comment]
To return the color labels to their defaults, hold down the SHIFT key in the color selection dialogue and click the [OK] button.

Regards,

**Comment by dieg467** [comment]
Hello. Indeed, Tablacus! I updated the "Color label" plugin and to eliminate the background color, follow these steps: 1st) Enter the context menu. 2nd) Click on "Label Menu" to enter the Color window. 3º) Hold down the SHIFT key and click OK in the Color window.
The method works, it is simple, but more intuitive would be a submenu in "Color label" that shows "Add/change color", "Remove color".
Thank you so much!
