### ISSUE TITLE
Option descriptions

### ISSUE THREAD

**Issue by HyperCriSiS** [tablacus/TablacusExplorer#677]
Hi,

I really like this explorer, but I am having hard times even changing small things.
According to the descriptions in the options, I often have absolutely no clue what will be changed where.
Some pages are an absolute riddle :sweat_smile:
It would help tremendously if some descriptions would be longer and if there maybe would be a tool tip to explain what it does.

I wanted to hide the desktop in the tree view and to show network drives in the tree view but I could not find how to do this.
Is this even possible?

Thanks,
Hyper

**Comment by ccfs** [comment]
This [PDF](https://github.com/ccfs/TablacusExplorer/issues/1) will give you some hints about add-on options.

The "Remarks" column of this [translation ODS file](https://github.com/tablacus/TablacusExplorer/files/10609900/fr.23.1.31.updated.ods) (from [#466](https://github.com/tablacus/TablacusExplorer/issues/466)) contains some more hints about certain options. I am not the application owner therefore I cannot help you by enhancing TE.

You can use "Tools > Options > Tree > Root" to choose one or more tree roots (keep Ctrl key pressed when you click the Open button on the dialog box shown after clicking the Browse button). Example:
![image](https://github.com/tablacus/TablacusExplorer/assets/34089121/17cb170f-bc5c-4b70-8f27-a4002804e97b)

**Comment by duarteframos** [comment]
The author of TE is not a native English speaker.

**Comment by duarteframos** [comment]
The author of TE is not a native English speaker.
@ccfs PDF file helped me immensely, I've included a lot of that information over at the [wiki](https://github.com/tablacus/TablacusExplorer/wiki) and [addons wiki](https://github.com/tablacus/TablacusExplorerAddons/wiki) where it is more readily availabe and searchable.

You can propose improvements yourself, the wiki is open for editing.
Tablacus has been very receptive of documentation suggestions and contributions

**Comment by tablacus** [comment]
1. Open Tools → Options → Tree → Root
2. Enter the following items in the "Root" field
```
17
18
```
![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/11df898b-5c45-4643-abf0-d189a7c8a9ba)

17 is PC.
18 is Network.

![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/7fdf56e5-b0ba-47f4-960b-15f8ec33ed7c)

**Comment by HyperCriSiS** [comment]
Thanks 👍 That's a good example where a one liner for explanation one a list with the items would have helped a lot 😀

Is it possible btw to expand only certain entries? 
Expanded main tree is OK but I do not want the network drives to be expanded.

**Comment by ccfs** [comment]
Please show screen captures of your TE:
- Tools > Options > Tree
- Tools > Options > Tree > Root
- Tools > Add-ons > Tree view > Options
which show the options that affect how TE expands a folder tree.

Please also show screen captures (and keystrokes / mouse activities) of the steps to reproduce the problem.

**Comment by ccfs** [comment]
1. By default, TE automatically expands all tree roots upon startup and new tab. To turn this feature off, opt for "Visible" in "Tools > Options > Tree > Root".

2. TE will try to expand Y: branch of "This PC" in priority to Y: tree root. To solve this problem, specify Y:\ before "This PC" (17).

![image](https://github.com/tablacus/TablacusExplorer/assets/34089121/9d33a939-8943-4f4e-b086-3641aafd3942)

3. Use "Tree view filter" add-on to hide Y: and Z: branches of "This PC".

![image](https://github.com/tablacus/TablacusExplorer/assets/34089121/1f8f6f55-5d23-490a-8f8d-ea46214ed909)

**Comment by HyperCriSiS** [comment]
Thank you guys, but not needed anymore.
