### ISSUE TITLE
New Folder ver2 & Change Letter Case

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#679]
Hi Gaku,

I have a question about scripts.
I recently started using scripts, and found this one among others.

_**New Folder dialog - Tablacus Explorer**
https://gist.github.com/tablacus/ee77b6c9018e8267e419cac6e54e9e1b_

I wanted to ask you (if it is possible) to extend this script in such a way that pick-up previously "manually" selected objects (folder/folders, file/files...etc) and places them 'automatically' in that new folder? Otherwise, if nothing is selected, only a new folder is created. (_***Please see the detail description below, in a separate/detached part***_)

In the sketch below, I represented what it would look like to be:
![New Folder ver2](https://github.com/tablacus/TablacusExplorer/assets/60333254/0b8aa741-23a2-432e-b8bd-80fc752b41f4)

And as an additional script, I thought I'd ask - i.e. could it be done?
I meant a script that will 'automatically' change the size of case letters of objects (folders/documents/files).

Some script with which I can change the name of some folder or file.
When I click on the script to change the name according to the order:

- Sentence case: "**This is an example**"
- UPPERCASE: "**THIS IS AN EXAMPLE**"
- Proper Case/Title Case: "**This Is An Example**"
- lower case: "**this is an example**"

In the sketch below, I represented what it would look like to be:
![Case](https://github.com/tablacus/TablacusExplorer/assets/60333254/0f932636-8b1e-4d44-a52a-5db01a5b0740)

Thanks in advance!
And I also apologize if something similar already exists but unfortunately I couldn't find anything similar to it.

*************************************************
 "_**Otherwise, if nothing is selected, only a new folder is created.**_"

Let me briefly review the part _**without selecting**_:

If not selected, a new (empty) folder would be created.
As it is now the case (Script "A").

**1. Script with pop-menu** 
_Before creating a new folder, a name is specified._

I would like to ask you if you can also make two additional scripts:
(Script "B", Script "C")

**2. Script with new folder icons**
_A folder is created, the name is specified later._

**3. A script that ignores the command, if there is nothing selected.**
_no comment_

The reason is that I would like to see which of those three variants is best for me in practice when I am working with folders and documents. The picture is below where I have highlighted all three cases through the table:

The script is the same in the first part (object selected), only a slightly different variation when the object is not selected.

![Table](https://github.com/tablacus/TablacusExplorer/assets/60333254/c6f27248-43bc-4dce-9856-0e3026108c1e)

Best regards, 
Jox.

**Comment by ccfs** [comment]
```
// Create a folder and move any selected items to it
const currentPath = api.GetDisplayNameOf(FV, SHGDN_FORPARSING);
const Selected = FV.SelectedItems();
const prompt = (Selected && Selected.Count) ? "Move " + Selected.Count + " item(s) to new folder" : "New Folder" ;
InputDialog(prompt, "", function (r) {
  if (r) {
    let path = r.replace(/^\s+/, "");
    if (!/^[A-Z]:\\|^\\/i.test(path)) {
      path = BuildPath(currentPath, path);
    }
    CreateFolder(path);
    if (Selected && Selected.Count) {
      const oDest = sha.NameSpace(path);
      if (oDest) {
        oDest.MoveHere(Selected, FOF_ALLOWUNDO);
      }
    }
  }
});
```
I only have little knowledge in JScript therefore I cannot help in the case changing part.

**Comment by JoxCoswit** [comment]
Thank you for your help.
Yes, that would be exactly how I imagined it should work. 😀
That could be the solution to the first part of the 'automatic' move, i.e. script "A".

As for these two remaining cases i.e. script A and B, it would be a replacement for the previous shortcuts.
I would have one script for all, which will move files and with which I will create new folders.
For example: Sometimes I like to create folders first and after that assign a name later (that's what concerns about script "B").

As for the C script, I thought It would be in the menu for the control.
If I haven't first selected anything, it won't do anything, when it would be pressed.
I wouldn't create new folders with it but it would be use when there is something I want automatically put in folder.
For example: If I forget to select 'first' folder(s) or file(s) and if I press on it the script will be ignored and it won't do anything.

If maybe someone else have time to solve these remaining two cases and a script that would automatically resize the case.
I would be very grateful.... 😊

**Comment by JoxCoswit** [comment]
I did a lot today, so I can conclude from today's work:

1. Regarding the scripts "B" and "C", if you will have some time/ideas, how could be solved and that part... it would be great.
   If not, this solution, which is made by **ccfs**; it will be quite enough for me now.
   
    Mabe if some an idea how to solve to disable auto-refresh issue; but it's nothing so urgent.
     - It's not a problem when there are few files, but when there are a lot of them.
     - It takes me every time back to the beginning after moving the files, i.e. when the folder is created.

     What is interesting, when I create only a "new folder" (with the same function) -  it stays in place.
     
     So, when only a new folder is created, auto-refreshment does not happen at all.
     It only has an effect when folder is created with "the move" function; when a 'new folder' is created by the "moved files".

2. And If you have some solution how to change the size of the case with the help of a script it would be very helpful, also.
     It would save me a lot of time because my wish is to have all folders and files name with equal and same case format style.
      Now when I want to change it I have to transfer it to editor and then bring it back and that's a lot manual-repetitive tasks.

Best regards, 
Jox.

**Comment by ccfs** [comment]
Script "C":
```
// Move selected items to a new folder
const currentPath = api.GetDisplayNameOf(FV, SHGDN_FORPARSING);
const Selected = FV.SelectedItems();
if (Selected && Selected.Count) {
  InputDialog("Move " + Selected.Count + " item(s) to new folder", "", function (r) {
    if (r) {
      let path = r.replace(/^\s+/, "");
      if (!/^[A-Z]:\\|^\\/i.test(path)) {
        path = BuildPath(currentPath, path);
      }
      CreateFolder(path);
      const oDest = sha.NameSpace(path);
      if (oDest) {
        oDest.MoveHere(Selected, FOF_ALLOWUNDO);
      }
    }
  });
}
```
I do not have an idea for Script "B".

Change `CreateFolder(path);` to `fso.CreateFolder(path);` to avoid the auto-refresh. However you may not even see the new folder.

**Comment by JoxCoswit** [comment]
That's right, when using "`fso.`" the folder is not visible/displayed at all.
It would be necessary make refreshment each time manually to display and can be seen newly created folder at all. 🤔
This is not a solution, and it could hardly be used in practice.

I thought it would be like when a "new folder" is created.
As I would be say, about it: "to remain in place".

It's no problem. These both scripts work fine, as you prepared it so far.
That will be quite enough for my work.
As for script "B"; I'll use the standard shortcuts for that. 

Thanks again for your effort and help. 👍


P.S. I'll leave this issue still open for now, if someone offers a solution for the resizing script.

**Comment by ccfs** [comment]
I come up with 4 [scripts](https://github.com/tablacus/TablacusExplorer/files/12415838/batch.rename.zip) to change letter case.

This is to create a context sub-menu with 4 options (and hot keys) to change letter case. Note that I use "External script" add-on to run the scripts.
![20230823_140520](https://github.com/tablacus/TablacusExplorer/assets/34089121/fc53b4c7-ac1f-4e3f-bba1-3affad6d69c6)
![20230823_140526](https://github.com/tablacus/TablacusExplorer/assets/34089121/b6ce0b1c-7541-44ca-97b9-0dacf0be04ea)
![20230823_140532](https://github.com/tablacus/TablacusExplorer/assets/34089121/af2e7aa3-ad82-4d7d-84da-3f08be5fc946)
![20230823_140535](https://github.com/tablacus/TablacusExplorer/assets/34089121/4b9ef85a-1baa-42d1-8693-83fb5eefd240)
![20230823_140540](https://github.com/tablacus/TablacusExplorer/assets/34089121/b7cc74c2-d357-4ce6-a18b-973ba7685a36)
![20230823_140543](https://github.com/tablacus/TablacusExplorer/assets/34089121/bc985493-4ecb-4e6b-a416-f7a5dcd529a8)

**Comment by ccfs** [comment]
I don't know why they did not work. Anyway, please try these [revised scripts](https://github.com/tablacus/TablacusExplorer/files/12419652/batch.rename.zip).

Note that I have tested them with normal folders and search result lists. They probably will not work on special locations such as Recycle bin, libraries, network share list, etc.

**Comment by JoxCoswit** [comment]
I tried all four scripts ([revised scripts](https://github.com/tablacus/TablacusExplorer/files/12419652/batch.rename.zip)) and it's the same as last time.
- "**ren-uc.js**" and "**ren-tc.js**" - OK
- "**ren-lc.js**" , "**ren-sc.js**" don't work for me for some reason.

_"Note that I have tested them with normal folders and search result lists.
They probably will not work on special locations such as Recycle bin, libraries, network share list, etc."_

I tested the same in several different locations but it was the same every time.
Like last time, nothing appears to me, only a circle spins, and that's it.

I don't know what I could do differently.

The only thing I can do is test it on another computer, and then I'll let you know if it worked there or not.

Kind regards.

**Comment by JoxCoswit** [comment]
Dear @ccfs

I made a big mistake, I put the wrong label under type 🤦‍♂️ and that was my fault. 😔 
First I created it wrong, then I just pasted it (_revised scripts_) without checking first.
My apologies for that. 🙏

Sorry, it's all fine! 
- [scripts](https://github.com/tablacus/TablacusExplorer/files/12415838/batch.rename.zip)  ✔
- [revised scripts](https://github.com/tablacus/TablacusExplorer/files/12419652/batch.rename.zip) ✔


**Thank you again for these scripts, they helped me a lot.** ❤


Regards,
