### ISSUE TITLE
Tabs side bar

### ISSUE THREAD

**Issue by guilhas** [tablacus/TablacusExplorer#68]
Hello,

Would it be possible for an option to move tab bar from top to left side?

Example
Firefox
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

Visual studio
https://tabsstudio.files.wordpress.com/2010/06/vertical-tabs.png
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerTools2012

Regards,
Lino

**Comment by tablacus** [comment]
Install an add-on "Tab plus".
Then, set the option "Align" to "Left".
![1](https://cloud.githubusercontent.com/assets/5156977/20631875/8818269e-b37c-11e6-935f-99ac7f6e555a.png)
Like this
![2](https://cloud.githubusercontent.com/assets/5156977/20631905/bf4128e6-b37c-11e6-9df7-59a7310d170e.png)
Best regards,

**Comment by guilhas** [comment]
Thanks. Amazing.
