### ISSUE TITLE
Refresh disrupts the sorting in Downloads Folder

### ISSUE THREAD

**Issue by xfilesee34** [tablacus/TablacusExplorer#682]
When I press F5 in Downloads folder, the tablacus losts sort by name setting and groups the items by date. That is only observed in Downloads folder of windows 10.

**Comment by ccfs** [comment]
Please try to opt out "File Explorer Options" in "Tools > Options > List > Style". Then you may need to set up the folder view (view mode, columns, sorting and grouping) of Downloads folder, navigate away and back to ensure that TE keeps the view.
![20230829_111331](https://github.com/tablacus/TablacusExplorer/assets/34089121/f45ab77b-1f91-42e0-93ac-08d2016c5e89)

**Comment by xfilesee34** [comment]
thanks. that fixed my problem.
