### ISSUE TITLE
How to add 2 link bar : one at left vertical and one at right vertical ?

### ISSUE THREAD

**Issue by 3230** [tablacus/TablacusExplorer#684]
How to add 2 link bar : one at left vertical and one at right vertical ?
This addon is very good, i would like how to use it more than one.
Thanks !

**Comment by ccfs** [comment]
You can place Link bar at only one position. Alternatively, you can place "Horizontal Favorites bar" at another side, though the entries will also appear in Favorites menu.

**Comment by 3230** [comment]
Thank you ccfs, i will try it.

**Comment by ccfs** [comment]
The [patched version](https://github.com/tablacus/TablacusExplorer/issues/692) now supports multiple link bars.

**Comment by 3230** [comment]
Nice, thanks a lot !
Have a good day ccfs
