### ISSUE TITLE
Disable right click

### ISSUE THREAD

**Issue by beber75** [tablacus/TablacusExplorer#686]
Hi first of all sorry if it's not an issue.

I'm trying to get rid of the right click context view on files but without success (sorry, I can not upload attached files from my location).

I'v declared a GPO on user session by disabling in explorer file the context menu.
It's the "Remove File Explorer's default context menu" settings.
It works with explorer.exe but not with TablacusExplorer (that seems normal to me as it's not the same process).

Is there a way to achive the same thing in TablacusExplorer ?

Regards

**Comment by duarteframos** [comment]
Have a look at the addon [Quickmenu](https://github.com/tablacus/TablacusExplorerAddons/wiki/quickmenu) it doesn't remove the menu entirely, but makes it simpler by debloating installed menu entries.

Otherwise a simple workaround is disabling right click in the mouse options

**Comment by beber75** [comment]
Thanks for quick answer.
I've try the "disable mouse way"
I've disabled the mouse addon:
![disable mouse](https://github.com/tablacus/TablacusExplorer/assets/3411028/6a7b75a7-dd1f-4389-8705-e127343bead1)
I've looked at mouse  menu section:
![mouse menu](https://github.com/tablacus/TablacusExplorer/assets/3411028/69e38e8e-c8a7-4f91-a742-68be55e9aa3b)
But I still have the rieght click:
![right click](https://github.com/tablacus/TablacusExplorer/assets/3411028/108f35ea-443f-41a4-a495-73b6000cd1ff)
I'm certainly not looking at the right place.

**Comment by duarteframos** [comment]
That won't cut it, you would have to use the _Mouse_ addon, but it doesn't work as well as I thought it would.
The only way to work around it is to bind some other function to override the context menu, leaving it blank will still fall back to the menu.

**Comment by beber75** [comment]
> The only way to work around it is to bind some other function to override the context menu, leaving it blank will still fall back to the menu.

May I ask you how could I achieve that ? (or maybe it's only theoretical and not possible yet)

**Comment by beber75** [comment]
I've give a try to this method but as you mentionned, time to time I'm able to display the context menu.
I'll stick to your previous suggestion (even if it's not a comple disable) and use Quickmenu addon.

Thanks for your time.

**Comment by ccfs** [comment]
1. "Menu item filter" add-on
Add "Context", "Background" and "Tree" records with * *. Mouse right-click and keyboard "menu" key will be disabled for file list selection, file list background and folder tree respectively.
![20230927_165223](https://github.com/tablacus/TablacusExplorer/assets/34089121/f6a205eb-d0d6-4a8a-a4cd-7e268f2c299b)

2. "Key" add-on
Shift+F10 may also lead to a context menu. Add this record to disable it too.
Type: JScript
Options: return S_OK;
![20230927_164615](https://github.com/tablacus/TablacusExplorer/assets/34089121/f1f057fd-8745-420b-8ac7-059e40805372)

3. "User style sheet" add-on
If necessary, enter this to remove a menu in the main menu
#Menu`MenuName` { display: none; }

**Comment by ccfs** [comment]
some more:

**"Key" add-on**

Both Shift+F10 and Ctrl+Shift+F10 will lead to a context menu. Add 2 records to disable them.
Type: JScript
Options: return S_OK;
![key-F10](https://github.com/tablacus/TablacusExplorer/assets/34089121/1360c351-90a4-4cc7-9e3f-15ca42cbc957)

"Menu" key (named "Application" in TE) and its Ctrl/Shift/Alt combinations will lead to a context menu. Add 8 records to re-assign them to a function that shows a dialog box. (The key cannot be disabled.)
![key-App](https://github.com/tablacus/TablacusExplorer/assets/34089121/b37b1cac-b273-4e94-907d-9bddc2f9ce88)

**"Mouse" add-on**

Disable right button and its Ctrl/Shift/Alt combinations on file list, totally 8 records.
![mouse-list](https://github.com/tablacus/TablacusExplorer/assets/34089121/d2b58283-eea8-472b-bc2f-a54a849780b3)

Disable right button and its Ctrl/Shift/Alt combinations on folder tree, totally 8 records.
![mouse-tree](https://github.com/tablacus/TablacusExplorer/assets/34089121/017b6100-b19d-4cac-8116-dc386974ff58)

**Comment by beber75** [comment]
Thanks a lot, that's excactly what I whas looking for.

**Comment by ccfs** [comment]
I don't know any way to disable the menu. But you can use "Right button drag-and-drop menu" add-on to remove all items.

Remove all existing items, then add a separator.
![image](https://github.com/tablacus/TablacusExplorer/assets/34089121/01965a01-b6d9-4073-927e-fa0cf7516f4d)

You can cancel only.
![rb-dnd](https://github.com/tablacus/TablacusExplorer/assets/34089121/34d74572-4cce-47e4-94dc-e3b8815d6230)

**Comment by ccfs** [comment]
Just found out that you can set "Gestures" in "Tools > Options > General > Mouse" to "Priority" to disable right button drag-and-drop menu.
