### ISSUE TITLE
マウスドラッグ操作（範囲選択など）でマウス動作が引っ掛かって止まるようになる場合がある

### ISSUE THREAD

**Issue by ffbeso** [tablacus/TablacusExplorer#688]
以前からこの症状に悩まされていたのですが、ある程度症状の再現性が明確になってきたのでイシューとして投稿します。

### 環境
- WINDOWS11PRO Ver. 22H2
- ディスプレイ構成 2画面（メイン水平配置、サブ垂直配置）
- Tablacus 23.9.13

### 前提条件（以下の条件をすべて満たすと発症）
- サブディスプレイ画面内において
  -  メインディスプレイ画面内では今のところ再現できない
- Tablacusの分割機能の第１ウィンドウのみ
- Tablacusの第１ウィンドウにおいてスクロールバーが表示されかつ、スクロール位置は最上部以外（最上部では発症しない）

以上の条件下でマウスの範囲選択を行うと、ドラッグ操作をした瞬間か、いくつかのファイルを選択したところでマウスが止まり、ドラッグ操作のまま待機するとたまに動き、また止まるという症状が現れます。

### この症状に影響を与える条件
- ウィンドウサイズによる影響がみられる
  - 1/2、1/4スナップさせた状態がもっとも症状が顕著、範囲選択ができない
  - 1/2、1/4スナップと同じようなウィンドウサイズに手動で変更しても上記と同じ症状
  - 4/5ぐらいのサイズだと無症状のようだ（サブディスプレイは垂直配置のため縦長のウィンドウとなる）
  - 最大化の場合症状は緩和されるが、たまに引っ掛かる程度で一瞬待機すればまた動く
- Ctrlを押しながらドラッグ操作をすると改善する（Shiftは効果なし）

### その他検証事項
- 他のPCでも試しましたが症状は一緒だったのでハードウェアの影響はないと思われます
- アドオンの有無は関係なく、Tablacusが初期状態でも上記の前提条件が揃えば再現できました
- WINDOWSのウィンドウのスナッピング機能OFFは影響なし
- 分割アドオンなしのシングルウィンドウ環境でも発症する
- ファイルの表示の種類は影響なし（詳細表示がもっとも上下にスクロールを要するため発症頻度は多い）

なにが原因かわかるでしょうか。

Tablacusは常にサブディスプレイに表示させて使っています。開発とメンテナンスありがとうございます。
ですが、範囲選択ができないのはなかなかもどかしいです。とりあえずはCTRLを押して対応しようと思います。

**Comment by tablacus** [comment]
テストしてみましたが、特に問題が出ていません。もう少し詳しい情報が必要な気がします。
ドラッグで選択とは以下のような感じでしょうか？
![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/c9db5cfd-0e1d-448e-a053-0ac8152c3862)

**Comment by ffbeso** [comment]
そうです、画像のようなマウス選択です。

タスクマネージャーのプロセスを見ながらこの操作してマウスの引っ掛かり発生させ続けると、どうもTablacusとDesktop Windows managerのCPU使用率が跳ね上がってるのがわかりました（通常複数選択操作時0～10％、引っ掛かり発生時10～20％）
WindowsでGUI描画演出をOFFにしたり、描画エンジンのWebview2を最新にしたり削除しても変わらず。
常駐アプリも

他に同様の症状の人がいると、もう少し原因がわかりそうな気もしますが、いないということは私の環境依存の症状なのでしょうか。

現状を簡潔にまとめるとこのようになります。

発生条件：スクロール最上部以外、サブディスプレイのみ、第一ウィンドウ
悪化条件：アプリのウィンドウサイズまたは分割ウィンドウサイズが横長（1080*1920画面スナップ上下１/2で発生が顕著）
緩和条件：アプリのウィンドウサイズまたは分割ウィンドウサイズが縦長
改善条件：CTRLを押しながら操作

**Comment by ffbeso** [comment]
原因は不明なまま、発生しなくなったためクローズします。
