### ISSUE TITLE
Right click on files freezes & crashes Tablacus

### ISSUE THREAD

**Issue by shea-butter** [tablacus/TablacusExplorer#69]
Every time I right click on a file of any type to bring up the context menu, Tablacus freezes up & crashes. Right clicking on folders works as expected.

**Comment by tablacus** [comment]
I think that it is a malfunction of antivirus software or shell extension.
Anyway, Install an add-on "Quick menu".
![21](https://cloud.githubusercontent.com/assets/5156977/20689457/db5f5848-b608-11e6-96a9-d8f6e00dcb79.png)

What antivirus software do you use?
Best regards,

**Comment by shea-butter** [comment]
I have 2 work PCs running Win 7 that are affected by this issue & a home PC running Win 8 that is not. They all have AVG Free Antivirus installed. I will post again in the morning after I have tested if Quick Menu fixes the issue on the work PCs.

**Comment by shea-butter** [comment]
Seems to be working with Quick Menu...Thanks!

**Comment by tablacus** [comment]
My pleasure.
