### ISSUE TITLE
Open Instead 1.13 Opens Duplicate Tabs

### ISSUE THREAD

**Issue by craigalan** [tablacus/TablacusExplorer#691]
I am not sure when this started doing this, but for some time when using the Open Instead add-on, I get two tabs opening.  Here is what I am using listed below.  Any ideas on how to fix this or what may be causing it?

Open Instead 1.13

TE64 23.9.13 Microsoft Windows 10 Enterprise 64-bit 22H2 (10.0.19045) IE/11 JS/11.0.16384 en_us 96 Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz Windows Defender
addonsupdater 1.10,startup 1.11,mouse 1.33,key 1.26,filterbar 1.39,titlebar 1.09,mainmenu 1.16,toolbar 1.44,tabplus 1.96,tabcolor 1.09,extensioncolor 1.06,attributescolor 1.07,tabname 1.09,everything 1.46,favoritesbar 1.43,checkbox 1.13,inactivepane 1.11,innernewfolder 1.06,innerback 1.14,innerforward 1.16,innerup 1.10,innerrefresh 1.07,innerbreadcrumbsaddressbar 1.50,delete 1.07,virtualrecyclebin 1.05,statusbar 1.19,recentlyclosedtabs 1.10,undoclosetab 1.16,remember 1.42,previewwindow 1.32,importexplorer 1.11,mixedsort 1.13,badge 1.24,openinstead 1.13,treeview 1.44,history 1.20

**Comment by ccfs** [comment]
Try to disable "Import explorer" which has the same function as "Open Instead" except that you press a button to trigger.
If this does not solve the problem, please provide more details such as the steps to reproduce the problem.

**Comment by craigalan** [comment]
That did not work.  What I find odd, is that I haven't changed or added any add-ons.  I want to say that this started about 2 or 3 versions ago.

I also looked at Shell Execute Hook yesterday I disabled that as a test, nothing...but today I went back to look and now it has an "Update Available"  next to 32 bit...I am not sure how to update that though.  It is on 1.13

How does one update an Add-on other than by using the Add-on Updater add in?  I tried deleting it and re-adding it, but it still installs the same version. 

I am not sure if this could be the issue or not.

**Comment by ccfs** [comment]
That "Update Available" message is about the DLL files that TE copied to your Windows system32/SysWOW64 folders when you enabled the add-on. It is not about the add-on version. Please see the [PDF](https://github.com/ccfs/TablacusExplorer/issues/1) for details.

"Shell Execute Hook" add-on is not a prerequisite of "Open instead" add-on. Actually, the former seems to be not working since Windows 10 21H1. See add-on issue [#300](https://github.com/tablacus/TablacusExplorerAddons/issues/300). I suggest you to clear all "Registry" check boxes so that TE will remove the DLL files and disable the add-on.

Please show me the Options pages of the 3 add-ons on your TE for diagnosis.

**Comment by craigalan** [comment]
Which 3 add-ons are you referring to?  I have attached, Open Instead, Prevent Dupe and Import Explorer

I cleared the checks on the Shell Execute, rebooted and deleted that add-on.

Same issue, unless I have Prevent Duplicate Tabs on.


![Prevent Dup](https://github.com/tablacus/TablacusExplorer/assets/17946784/c541f65b-b8e3-44ef-b81f-59354511fcc8)
![Open Instead](https://github.com/tablacus/TablacusExplorer/assets/17946784/6279fb09-b651-4424-85c4-87dd46bc17b8)
![Import Ex](https://github.com/tablacus/TablacusExplorer/assets/17946784/4cd7a911-af7c-4a3b-bc01-0beb51736038)

**Comment by craigalan** [comment]
Thanks again, I appreciate your help and patience.

**Comment by ccfs** [comment]
I tried but could not reproduce the problem at my side.

To diagnose, I need:
1. all files in your TE config folder
2. steps and screen captures showing how you got the problem.

**Comment by craigalan** [comment]
Attached you will find the config folder as well as a short video of me opening a folder 3 different ways, all of which worked before with the Prevent Dupe Tab Add-on enabled. Obviously,  I have the "prevent duplicate tab" add-on off for this test

1) just opening explorer
2) opening a desktop shortcut
3) opening a folder from Everything Search.  .

https://github.com/tablacus/TablacusExplorer/assets/17946784/4adb7b39-ec23-45ba-a293-987e07abca23

[config.zip](https://github.com/tablacus/TablacusExplorer/files/13175850/config.zip)

Thanks again!

**Comment by craigalan** [comment]
Attached you will find the config folder as well as a short video of me opening a folder 3 different ways, all of which worked before with the Prevent Dupe Tab Add-on enabled. Obviously, I have the "prevent duplicate tab" add-on off for this test

just opening explorer
opening a desktop shortcut
opening a folder from Everything Search


[config.zip](https://github.com/tablacus/TablacusExplorer/files/13175903/config.zip)

https://github.com/tablacus/TablacusExplorer/assets/17946784/fc2a3434-e12f-47ab-b437-8a752bd576f0

**Comment by ccfs** [comment]
There may be a problem in "Open instead" add-on. Please try these modified versions:

[te230913-script.zip](https://github.com/tablacus/TablacusExplorer/files/13186414/te230913-script.patch.missing.select.zip)
[openinstead_113.zip](https://github.com/tablacus/TablacusExplorer/files/13186413/openinstead_113.patch.missing.select.zip)

You may also try unclearing "Special Folders" and "Take over the Explorer view".

**Comment by craigalan** [comment]
Unfortunately, that didn't work either.

First I tried just unchecking those options and then I tried the new script and add-on.  Still does the same thing.  I am good with just keeping the other add-on enabled to prevent duplicate tabs for now as it only seems to close the duplicate folder in the same pane.  It appears I can still open the folder in another pane, which is probably the only thing I would need.

I appreciate your help.  If you come up with any other thing that I could try, I have no problem testing, but the work around for the close dupe tab will work for me now.

**Comment by ccfs** [comment]
Please try these:

[te230913-script.zip](https://github.com/tablacus/TablacusExplorer/files/13186414/te230913-script.patch.missing.select.zip) (same as above)
[openinstead_113.zip](https://github.com/tablacus/TablacusExplorer/files/13194299/openinstead_113.patch.missing.select.dup.tab.zip) (UPDATED)
[importexplorer_111.zip](https://github.com/tablacus/TablacusExplorer/files/13194298/importexplorer_111.patch.zip)

**Comment by craigalan** [comment]
That appears to be working!  I assume the files in the Script folder with ORG are just he original back ups and aren't needed in that folder correct?

**Comment by ccfs** [comment]
Yes.
By the way, if you have concern about privacy, you can delete the config.zip above. Thanks.

**Comment by craigalan** [comment]
I am concerned about privacy, but how can that be related to the zip file?

**Comment by ccfs** [comment]
The config files contain all your favorites items and other settings. I used them to simulate your environment for testing. I don't know whether there is any personal info, but for privacy you may not want it be disclosed to the public.

**Comment by craigalan** [comment]
Got it. Prob nothing major there, but I removed the link from the post. Is there some place else that I should actually delete the file?

**Comment by ccfs** [comment]
I think it's gone now.

**Comment by craigalan** [comment]
Thanks again for all your help
