### ISSUE TITLE
Can't drag items to the Link Bar.

### ISSUE THREAD

**Issue by CampPixel** [tablacus/TablacusExplorer#694]
I've installed Tablacus on two machines to test the Link Bar. However when I try to drag any item to the bar I receive the prohibited 🚫 icon.

**Comment by ccfs** [comment]
The landing field is pretty small.
![20231106_133338](https://github.com/tablacus/TablacusExplorer/assets/34089121/2f4b4878-4a27-4b72-8d48-6bc43e7ff66e)

**Comment by CampPixel** [comment]
That was it. Thank you!
