### ISSUE TITLE
FastCopy Addon Not Listing Source Files

### ISSUE THREAD

**Issue by asaki-ukyo** [tablacus/TablacusExplorer#699]
Tablacus Explorer 23.9.13を使用しており、FastCopy 1.23アドオンに関して問題が発生しています。
具体的な状況を以下に記述します。

1. 現象の発生環境:
   - 使用しているバージョン: Tablacus Explorer 23.9.13
   - 問題が生じているアドオン: FastCopy 1.23

2. 問題の内容:
   - FastCopyをファイルのコピーと移動の際に自動起動するよう設定しています。
   - 問題: FastCopyは起動するものの、コピーまたは移動を行うファイル（Source）がFastCopyに正しく伝わっていません。
   - ただし、コピー/移動先のパス（DestDir）は正しく表示されます。

3. 追加情報:
   - この状態でFastCopyに手動でファイルを指定すると、問題なくコピー/移動が可能です。
   - この問題はFastCopyのバージョン4.2.1および5.4.3で発生しています。
   - 当初、FastCopy 4.2.1を使用していた際には問題はありませんでしたが、ある時点からこの問題が発生し始めました。
   - 問題発生の原因は不明で、特に思い当たる操作はありません。
   - 念のためFastCopyを5.2.1にアップデートしましたが、状況は改善されませんでした。
   - FastCopyのシェル拡張は使用せず、その他の設定もデフォルトのまま変更していない状態です。

この問題について、何か原因や解決策があればご教示いただけますと幸いです。

よろしくお願いします。

**Comment by tablacus** [comment]
こちらでテストしたところ、FastCopy ver 5.4.3で正常に動作しました。
こういう場合によくあるのが、実行権限の違いです。FastCopyを管理者権限で実行されていませんか？
実行権限が違う場合は揃えてみてください。

**Comment by asaki-ukyo** [comment]
実行権限については思い当たるところがありましたので発生直後に確認しておりましたが、
どちらも管理者特権は取得していませんでした。
また、先ほど試しても同様でした。
![20231209115821](https://github.com/tablacus/TablacusExplorer/assets/153290016/301dd8df-5a41-4922-8edd-f0bc1101f2d0)

他環境では正常に動作するようであれば環境依存の問題と思いますので、
使用を取りやめることとします。
ご回答ありがとうございました。

**Comment by tablacus** [comment]
コピーと移動でFastCopyを使いたいのであれば、Fire File Copyアドオンで dll に fastcopyのdll(32ビット/64ビット)を設定してクラスを`{72FF462B-AB7D-427A-A268-E22E414933D7}` にする方法もあります。

![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/bb5d9a08-389d-458d-a03d-4b25264dd26e)

**Comment by asaki-ukyo** [comment]
ご教示ありがとうございます。
頂戴した画像のとおり設定したところ、問題なくFastCopyでのコピー/移動を行えました。
とても助かります。
