### ISSUE TITLE
bug: change time stamp

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#70]
Hi, I found a bug in change time stamp plugin on windows with italian localization.
This is the dialog (I change the date *modified* day from 28 to 27)
![image](https://cloud.githubusercontent.com/assets/10347571/20722576/6b06b42e-b667-11e6-9721-0cd33f34eb59.png)
 This is what I get in the list view:
![image](https://cloud.githubusercontent.com/assets/10347571/20722623/9374c89c-b667-11e6-9d65-14990158bd78.png)
To get the correct value I have to swap day and month:

**Comment by tablacus** [comment]
I've adjusted it on "Change the Time Stamp" 1.07.
Please try updating.

Thank you,

**Comment by stefanocaselli** [comment]
thanks!

2016-11-30 14:21 GMT+01:00 Gaku <notifications@github.com>:
