### ISSUE TITLE
Add-on failure -“Force refresh”and “close tab when deleting”

### ISSUE THREAD

**Issue by yaolion** [tablacus/TablacusExplorer#703]
More than a year has passed, and the issue with the add-on still seems to have not been resolved.
[https://github.com/tablacus/TablacusExplorer/issues/628](url)

“Force refresh”-Dragging files from different windows cannot take effect immediately

“close tab when deleting”-Doesn't work

![198188595-ffafd923-68db-4316-ab5c-559fd4b42ae0](https://github.com/tablacus/TablacusExplorer/assets/47139379/b3b0333e-845d-4961-ac1e-d3970b85791f)

**Comment by yaolion** [comment]
I modified the code myself to meet my own needs

**Comment by ccfs** [comment]
"Close tab when deleting" add-on has been [patched](https://github.com/tablacus/TablacusExplorer/issues/692).
