### ISSUE TITLE
Autoplay media and images using mpv

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#705]
New add-on: [mpv](https://github.com/tablacus/TablacusExplorer/files/13804599/mpv_101.zip)

Click the button to browse your image/media files in a mpv window.
Later on you can detach the window from TE by:
. Ctrl+Click the button, or
. add-on command "mpv detach", which you can associate with a hot key or a tool bar button
and a new mpv window will open when you continues.

Note: Current mpv version 0.37 requires Windows 10 or newer. You can use version 0.36 for Windows 7.

**Comment by tablacus** [comment]
I have added the MPV add-on to the add-on page.
Thank you,

https://tablacus.github.io/TablacusExplorerAddons/

**Comment by ccfs** [comment]
I have updated the add-on to [version 1.01](https://github.com/tablacus/TablacusExplorer/files/13804599/mpv_101.zip). Thanks.
