### ISSUE TITLE
Script Error when I close the ‘Options’ with the OK button

### ISSUE THREAD

**Issue by segahir** [tablacus/TablacusExplorer#708]
オプションをOKボタンで閉じるとスクリプトエラーが出るようになってしまいました。
TablacusExplorer 起動時も同じエラーメッセージが表示されます。

解消手順をご教授ください。
![image](https://github.com/tablacus/TablacusExplorer/assets/157766471/78fd6f17-6fc1-45da-b211-832fa6b19241)

－エラーが表示されるまでにやったこと
"inner新規フォルダ"のアイコンを"icon:shell32.dll,155"に変更し、サイズを、20→32→64pxと変化させたかったのですが、どうやらアイコンサイズを32pxへの変更時にアドインの選択を誤り、"空フォルダ"アドインも"icon:shell32.dll,155"に変更し、こちらを64pxに変更してしまったのだろう。
「32pxへ変更してもアイコンサイズの変化が一見わからなかったので、64pxならどうか？」と思い、64px変更時の"OK"でスクリプトエラーが表示されたのだろうと思いますます。
以後はオプション、アドインをOKボタンで閉じるたび、またTEの起動時に毎回エラーになります。

上記操作後に改善するかと思い"最新版の確認"し、TEをアップデート。（更新できたので古いバージョンでしたがどのバージョンかは不明です。）しかし、依然として起動時とオプションOK時にスクリプトエラーとなる。

空フォルダアドインは、書き込み時は削除している。・

－Tablacus Explorerについて
TE64 23.9.13 Microsoft Windows 10 Pro 64 ビット 22H2 (10.0.19045) IE/11 JS/11.0.16384 ja_jp 96 12th Gen Intel(R) Core(TM) i5-1245U CrowdStrike Falcon Sensor Windows Defender
mouse 1.33,key 1.26,filterbar 1.39,back 1.18,forward 1.18,up 1.20,treeview 1.44,toolbar 1.44,mainmenu 1.16,titlebar 1.09,tabplus 1.96,multithread 1.29,remember 1.42,undoclosetab 1.16,aboutblank 1.04,segoeicons 1.04,download 1.08,extract 1.15,innersyncselect 1.01,colorlabelsort 1.00,colorlabels 1.12,font 1.25,pasteaslink 1.06,paste 1.07,stripes 1.13,openinstead 1.13,importexplorer 1.11,layout 1.02,t7zip 1.10,tablist 1.04,split 1.26,split8 1.04,split9 1.04,split6 1.10,split3 1.12,sizestatus 1.27,thumbnailengine 1.09,preview 1.46,previewwindow 1.32,innerfilterbar 1.34,label 1.45,multiprocess 1.37,copyfoldersettings 1.02,innerbreadcrumbsaddressbar 1.50,regexpincsearch 1.09,virtualrecyclebin 1.05,touchex 1.10,touch 1.12,forcerefresh 1.08,preventduplicatetabs 1.19,tabcolor 1.09,searchbymodified 1.04,addonsupdater 1.10,addfavorites 1.07,newtab 1.08,controlpanelbutton 1.10,systemfolders 1.12,innerup 1.10,innerrefresh 1.07,innernewfolder 1.06,innerback 1.14,innerforward 1.16,statusbar 1.19,restart 1.09,countbar 1.12,showfocusedframe 1.02,itemscount 1.02,refresh 1.10,appicon 1.03,clearfilterwithup 1.04,drivebar 1.18,checkbox 1.13,filterbutton 1.10,modifydatecolor 1.09,commandinaddress 1.01,folderbutton 1.11,labelsqlite3 1.08,closeonback 1.00,newtabonforward 1.00,tabgroupsbutton 1.02,favorites 1.06,properties 1.06,closeduplicatetabs 1.07,createdatecolor 1.05,labelgroups 1.03,wildcardselect 1.05,fixselectionrename 1.03,folderimage 1.09,movecontentup 1.02,cbcopy 1.06,fastlistmode 1.04,tabs 1.26,tabcolorplus 1.07,tabgroups 1.45,tabdrivename 1.05,sorttabs 1.04,drivebutton 1.11,dragtop 1.03,takeoverfoldersettings 1.08,folderfilter 1.00,foldermenusettings 1.02,foldersettings 1.39,fullpathbar 1.06,notepadalternative 1.03,searchbar 1.12,recentlyusedtabs 1.02,recentlyclosedtabs 1.10,closewhendeleting 1.03,autorestart 1.02,darkmode 1.18,protecttabs 1.07,foldericon 1.04,favbar 1.27,quicknotes 1.02,dragdropmenu 1.04,color 1.13,confirmdrop 1.02,flat 1.23,tabdesign 1.16,lockedtabstop 1.08,favoritesnewtab 1.02,samelockedtab 1.11

**Comment by ccfs** [comment]
Please apply this [patch](https://github.com/tablacus/TablacusExplorer/issues/692).

p.s. I do not speak Japanese. I tried to understand your post using Google Translate.

**Comment by segahir** [comment]
パッチを適用したらエラーの表示がなくなりました。
対応頂きありがとうございました。
