### ISSUE TITLE
Script Error - te240204/te240205

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#709]
Dear Gaku, 

I would just like to report one bug with the last two versions.
I use these useful scripts prepared by **ccfs** (https://github.com/tablacus/TablacusExplorer/issues/679)
_Please look for them at the end of the post._

In the version with yesterday's and today's date I get this message bellow.
When I use scripts for create new folder or move folders. 
I also tried the one from the day before yesterday and it's fine.

![Error](https://github.com/tablacus/TablacusExplorer/assets/60333254/e1b06ab0-73ed-454f-92fc-b4b5aeb4e3c3)

Which means:
- Version te240203 - 24.2.3 is OK ✅
- Version te240204 - 24.2.4 is NOK ⛔
- Version te240205 - 24.2.5 is NOK ⛔

This message appears when I want to create a new folder.
Or, when I want to group folders.

The script for changing the font size works without problems.

By the way the latest version I use for all my work is te230712 [23.7.12]
Everything works perfectly, and I never had any problems or difficulties 👍

Best regards.

**Comment by JoxCoswit** [comment]
**UPDATE**:

I created a plain text file with scripts for which it gives me an error. 
_Please find the file (zip) below:_

[Scripts for Moving and Create folders.zip](https://github.com/tablacus/TablacusExplorer/files/14177617/Scripts.for.Moving.and.Create.folders.zip)

At the end of the post there are scripts only for change letter case.
They work properly, ie. no script error.

**_Explanation_:**
Now I see there are no scripts on that post (https://github.com/tablacus/TablacusExplorer/issues/679) as a zip file.
It is embedded inside the post, in two parts.

Regards.

**Comment by tablacus** [comment]
I have fixed it on Tabacus Explorer 24.2.6.
Please give it try.
Regards,

**Comment by JoxCoswit** [comment]
Gaku, 

It was fixed with today's version
There were no problems now.


Thx!  😊
