### ISSUE TITLE
Hold down CTRL and copy the file exception

### ISSUE THREAD

**Issue by dasu88** [tablacus/TablacusExplorer#71]
Hold down Ctrl and copy the file, the progress window will be placed in the next layer of the window

OS: windows 10

The first action in the movie is a direct drag, there is a progress window in the first layer, the second action and the third action, are holding down the Ctrl drag ... progress window can not appear in the first layer.

https://youtu.be/Sg7csXG-1iY

**Comment by dasu88** [comment]
I'm sorry, I have been back to normal after re-boot ...
Let me observe for some time

**Comment by tablacus** [comment]
Do you use an add-on "Multi Process"?

**Comment by dasu88** [comment]
Yes, I have to use this plugin.

**Comment by tablacus** [comment]
All right.
If the problem happens again, Please stop using "Multi Process" and try "Multi Thread".

**Comment by dasu88** [comment]
Thank you, I will try again
These two plug-in What is the difference?

**Comment by tablacus** [comment]
"Multi Process" uses the different process.
"Multi Thread" uses the same process, but it uses the different thread. 

Best regards,
