### ISSUE TITLE
Phantom Auto-Refreshment / How to disable?

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#710]
Dear Gaku, 

I noticed it last time and now when I tested it again yesterday.
Last time, I commented on it with **ccfs**.

![Comment](https://github.com/tablacus/TablacusExplorer/assets/60333254/6f931a20-95d0-46ea-8caf-a0a5f7ff6753)

I think I saw what this could be about yesterday.

When I use the grouping script some **"auto-refresh"** occurs.

I think I found out what it is about, and the process is like this:

0. Initially, I unpack the package - eg "**te240206**" (_settings orginal_)
1. There are three folders
![Picture1](https://github.com/tablacus/TablacusExplorer/assets/60333254/8981fe2a-6fb8-46ee-9414-55959588a6ae)

2. I mark two folders, and run the grouping script.
3. Those two folders are neatly grouped into one folder (that's OK)
Arrangement as in the picture:
![Picture2](https://github.com/tablacus/TablacusExplorer/assets/60333254/10c9fc9c-1d4f-4891-800f-1e048d7fa7d9)

The next procedure is a little different, with a change to the **Layout**  (put any one, it doesn't matter)

In this example; I created one, i.e. the first "**1tab.xml**"

The procedure is repeated with the maps:

1. There are three folders
![Picture1](https://github.com/tablacus/TablacusExplorer/assets/60333254/782d0412-388e-43f0-adca-52caacca66b6)

2. I mark two folders, and run the grouping script.
3. Those two folders are neatly grouped into one folder (that's OK)

But unlike the previous one, now this **_phantom_ auto-refresh** occurs.

Arrangement as in the picture:
![Picutre3](https://github.com/tablacus/TablacusExplorer/assets/60333254/a44ab9b6-1041-437a-8ccb-71b7d834f514)

Why is this happening?
I would like the folder that was created not to change the folder order until I manually refresh it by myself.

The thing is sometimes it's hard like before for me to keep track of what I've done.

The only thing that has changed is that I have changed the "**Layout**".

If there are any questions, feel free to ask me.

Best regards.

**Comment by tablacus** [comment]
This happens if the move starts before the created folder appears, so I shifted the timing by about 2000ms.
```Create_Folder_and_Move_selected_items.js
// Create a folder and move any selected items to it
const currentPath = api.GetDisplayNameOf(FV, SHGDN_FORPARSING);
const Selected = FV.SelectedItems();
const prompt = (Selected && Selected.Count) ? "Move " + Selected.Count + " item(s) to new folder" : "New Folder" ;
InputDialog(prompt, "", function (r) {
  if (r) {
    let path = r.replace(/^\s+/, "");
    if (!/^[A-Z]:\\|^\\/i.test(path)) {
      path = BuildPath(currentPath, path);
    }
    CreateFolder(path);
    if (Selected && Selected.Count) {
      const oDest = sha.NameSpace(path);
      if (oDest) {
        setTimeout(function(oDest, Selected) {
          oDest.MoveHere(Selected, FOF_ALLOWUNDO);
        }, 2000, oDest, Selected);
      }
    }
  }
});
```
```Move_folder_into_New_folder.js
// Move selected items to a new folder
const currentPath = api.GetDisplayNameOf(FV, SHGDN_FORPARSING);
const Selected = FV.SelectedItems();
if (Selected && Selected.Count) {
  InputDialog("Move " + Selected.Count + " item(s) to new folder", "", function (r) {
    if (r) {
      let path = r.replace(/^\s+/, "");
      if (!/^[A-Z]:\\|^\\/i.test(path)) {
        path = BuildPath(currentPath, path);
      }
      CreateFolder(path);
      const oDest = sha.NameSpace(path);
      if (oDest) {
        setTimeout(function(oDest, Selected) {
          oDest.MoveHere(Selected, FOF_ALLOWUNDO);
        }, 2000, oDest, Selected);
      }
    }
  });
}
```
Regards,

**Comment by ccfs** [comment]
These [alternatives](https://github.com/tablacus/TablacusExplorer/files/14190951/Move.selected.items.to.sub-folder.zip) avoid 2000ms delay, but the new folder is restricted to a sub-folder (the original and the above versions can create a folder elsewhere).
- "select new":  The new sub-folder will be selected.
- "select unmoved": The new sub-folder will NOT be selected. If any item is not moved (e.g. being opened by another app), it will stay selected.

**Comment by tablacus** [comment]
999ms version.
```Create_Folder_and_Move_selected_items.js
// Create a folder and move any selected items to it
const currentPath = api.GetDisplayNameOf(FV, SHGDN_FORPARSING);
const Selected = FV.SelectedItems();
const prompt = (Selected && Selected.Count) ? "Move " + Selected.Count + " item(s) to new folder" : "New Folder" ;
InputDialog(prompt, "", function (r) {
  if (r) {
    let path = r.replace(/^\s+/, "");
    if (!/^[A-Z]:\\|^\\/i.test(path)) {
      path = BuildPath(currentPath, path);
    }
    CreateFolders(path);
    if (Selected && Selected.Count) {
      const oDest = sha.NameSpace(path);
      if (oDest) {
        setTimeout(function(oDest, Selected) {
          oDest.MoveHere(Selected, FOF_ALLOWUNDO);
        }, 999, oDest, Selected);
      }
    }
  }
});
```
```Move_folder_into_New_folder.js
// Move selected items to a new folder
const currentPath = api.GetDisplayNameOf(FV, SHGDN_FORPARSING);
const Selected = FV.SelectedItems();
if (Selected && Selected.Count) {
  InputDialog("Move " + Selected.Count + " item(s) to new folder", "", function (r) {
    if (r) {
      let path = r.replace(/^\s+/, "");
      if (!/^[A-Z]:\\|^\\/i.test(path)) {
        path = BuildPath(currentPath, path);
      }
      CreateFolders(path);
      const oDest = sha.NameSpace(path);
      if (oDest) {
        setTimeout(function(oDest, Selected) {
          oDest.MoveHere(Selected, FOF_ALLOWUNDO);
        }, 999, oDest, Selected);
      }
    }
  });
}
```
Regards,

**Comment by JoxCoswit** [comment]
**Thank you both for the offered solutions and effort**  😊

I tried both and both solutions are closest to my needs.
From **Gaku**, with delayed, and from **ccfs** ie. second, with unmoved.

Basically, I will combine both of your two solutions.
Depending on where I need which of this for works. 

That's settled. Excellent! 🥇

P.S. Gaku, I have two more questions; but it's not related to this - or yesterday's topics.
I haven't decided yet which one would be helpful to have.
When I decide I will open a new issue with a comment which is relate with that. 
Then you can see if any of it makes sense or not and whether any of these would be good for all.


Kind regards.
Jox.
