### ISSUE TITLE
The add-on that "opensinstead" seems to no longer work

### ISSUE THREAD

**Issue by madoka-dev** [tablacus/TablacusExplorer#711]
24.2.x以降、エクスプローラの代わりに開くアドオン（1.13）が動作しなくなっているようです。
Shell execute hookアドオンは試していないので不明です。

修正いただけると大変ありがたいのですが、Shell execute hookを使えばいいよ、などの代替手段を教えていただけるでも助かります。

**Comment by tablacus** [comment]
ありがとうございます。Tablacus Explorer 24.2.7で調整しました。
アップデートしてみてください。

**Comment by madoka-dev** [comment]
動くようになっておりました。
即修正していただきありがとうございます！

**Comment by madoka-dev** [comment]
クローズさせていただきますね
