### ISSUE TITLE
I want to exclude "Smartphone drive" from the add-on "Drive Bar", but I don't know how to do it.

### ISSUE THREAD

**Issue by tendvbs** [tablacus/TablacusExplorer#714]
アドオン"ドライブバー"を使っています。
スマートフォンをPCにUSB接続すると、スマートフォンの名前のドライブが追加されます。
それをドライブバー上で非表示にするための除外する方法がわからず少し困っています。

エクスローラ上のパスでは
PC\Xperia X Performance
のように表示されます。

実際に
ドライブバーの除外指定で以下のように指定していますが、除外されていないようです。

PC\
"PC\Xperia X Performance"
PC\Xperia X Performance\
Xperia X Performance
*Xperia X Performance*
*Xperia*
PC\Xperia*

環境：
TE64 23.9.13 Microsoft Windows 10 Pro 64 ビット 22H2 (10.0.19045) Admin IE/11 JS/11.0.16384 ja_jp 96 AMD Ryzen 5 3600X 6-Core Processor              Windows Defender Kaspersky Security Cloud
mouse 1.33,key 1.26,addressbar 1.71,filterbar 1.39,back 1.18,forward 1.18,up 1.20,delete 1.07,refresh 1.10,linkbar 1.33,treeview 1.43,toolbar 1.44,drivebar 1.18,mainmenu 1.16,titlebar 1.09,tabplus 1.96,multithread 1.29,undoclosetab 1.16,singleclickactivate 1.03,statusbar 1.19,split 1.26,sizestatus 1.27,sidetreeview 1.28,stripeslite 1.09,attributescolor 1.07,noinfotip 1.02,foldersettings 1.39,importexplorer 1.11,closewhendeleting 1.03,inactivepane 1.11,menuitemfilter 1.06,classicstyle 1.10,favoritesnewtab 1.02,clipboardimage 1.01,recentlyclosedtabs 1.10,searchbar 1.12,tabposition 1.10,tabcolorplus 1.07,extensioncolor 1.06,tabdesign 1.16,treeviewfilter 1.06

最後に、
Tablacus Explorerを大変便利に使わせていただいています。
ありがとうございます。

**Comment by tablacus** [comment]
「無効にする」を
```
::{*
```
これにするか

![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/4396c3f6-b640-4a31-886b-07b8e84064ba)

「フィルタ」を
```
?:\
```
これにしてみてください。

![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/7c08ac42-c917-421a-af17-e834e3ce175d)


どちらか片方でOKだと思います。

**Comment by tendvbs** [comment]
ご提示の前者の方法を使い、スマートフォンのドライブは表示されなくなり、問題は解決しました。
ご回答ありがとうございました。
これからも末永く使わせていただきます。
