### ISSUE TITLE
Tabs-flexibility and advanced tabs options.

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#716]
Dear Gaku, 

This is what I wanted to tell you, so I would like you to check yourself.

I noticed this last time I tested.

**What happened?**
I wanted to drag a folder into the tabs space (links) to open the folder in a new tab and instead of that I physically dragged the folder to the folder whose tab (link) was previously open.

_This happened to me several times during the test period._

I think this behavior is unexpected. Please, allow me to explain to you in detail... 

The problem is that more attention must be paid to avoid an undesirable situation such as an unplanned physical folder move, for example: “unplanned re-location of folder”. 

Instead of opening as a tab (link) the folder is physically moved to one of the open tabs (links).

It is only happen when it is dragged into a space where tabs (links) are already exist on tab-bar.

It is not happen if the folder is dragged into an empty field of tabs space-area at the end. 
In this case the file folder needs to be dragged all the way to the end of the tab-bar to be opened as tab.

- Within the image below I have described the situation (issue) visually for you. 
- I have also attached the state how it could be after a possible solution are implemented.

***

**Just to follow up on this case...**

Since I don't use add-ons like Tabs or Tab plus in daily work or on the daily basis.
I rather prefer the classic-basic 'raw' look of tabs layout as default without additional style format.

I work with the initial settings only when I notice that something is not right with my configuration.

The only thing in the classic-basic layout is missing, it is the possibility of tab(s) flexibility.

In other words:
_- the ability to move tabs left and right_
_- switch tabs between windows_
_- take a folder into the space of tabs (as link, to tab-bar)_
etc.

When not using Tabs or Tabs Plus, before menationed - it is not allowed / it's disabled.

I wanted to ask you if you could please make a some ‘elementary’ plugin (add-ons) that will allow only (add) that flexibility of tabs with classic-basic layout. 

It will only add tabs-flexibility without any other additional effects on the tabs as like: 
_resizing, size of tabs, style of font, icons... etc._

There is no extra style effects for the classic-basic (raw) look for layout of tabs.

It just adds the flexibility of tabs and enables working with them.

To keep everything as it is now only added possibility of tabs flexibility for the classic-basic tabs layout.

For me personally, add-ons are great things because they easily increase the capabilities beyond what the base model provides and also provide individual configuration according to the user's requirements, but sometimes they come with something that I personally can't influenced on it; such as Tabs and Tab plus - I can't have classic tab layout without any other additional tabs style format.

Because of that, I don't know, if it's better to add another just small add-on that will add only that tab flexibility; or, to add an option ‘as feature’ in settings for users who would like to have basic tab-layout without any other style formats (only ability of tabs-flexibility).

By default, of course, this feature (in settings) it would be turned off, so that it should not interfere with other add-ons such as Tabs, Tab plus, or any others.

Best regards, 
Jox.

****

**Detailed description:**

![Detailed description](https://github.com/tablacus/TablacusExplorer/assets/60333254/5918c2d9-490d-46a5-9922-4648320bcb51)

**Before & After:**  

_The red mark in the picture only indicates which of the cards is open - not an integral part of the request:_

**Example 1:**

![Example1](https://github.com/tablacus/TablacusExplorer/assets/60333254/f074eee5-2087-4fae-a9c8-aa5c054187fa)

**Example 2:**

![Example2](https://github.com/tablacus/TablacusExplorer/assets/60333254/3f650e9e-85c7-4339-839d-9f43dc3a65f5)

**Comment by tablacus** [comment]
Try to install Tablacus Explorer 24.2.16 and uncheck Add-ons → Tab plus → Darg-and-Drop → "Drop to Folder".
![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/f21ecb50-9e11-4e8e-bab3-09d42ed3484a)

Regards,

**Comment by JoxCoswit** [comment]
Yes, it looks great....! 😊
I confirm now it works as described previously.


I'm curious about one more thing...

_Why did I stop using Tab and Tabs plus?_

I've stopped using Tabs and Tabs plus as I said because I prefer the more classic look, and second is because it affects the size of the tabs. I don't know why, but when I use Tab plus (or Tabs) with font add-ons the size of the tabs changes.

So, unlike when I don't use Tab plus and/or Tabs, regardless of the size, the size of the tabs is fixed.

I made a couple of examples so you could have a look: 

- In Example 2, there is a visible change in the size of the tabs compared to Example 1.
- In Example 4, the change in tabs size is not visible compared to Example 3.
_(Examples are at the bottom)_

> In the second and fourth examples, the font size is increased.
 _There is no visible difference in the size of the tabs between the third and fourth examples._
 _The difference is more visible between the first and second examples._

As far as I have noticed...
Tabs are more fixed in size, when I don't use plugins like Tab plus and/or Tabs.

I don't know.... maybe it's just my wrong impression about it.

Is it all that possible without an add-ons like Tab plus?
Or, if it is possible, in Tab plus - somehow to disable and not to affect at the style or at the size of the tabs?

That's why I thought to keep everything like it is but only to add that flexibility which currently missing.

If it doesn't work out otherwise.... 
This will be enough too also.

**Thank you for what has been done so far!** 🙏


Example 1. 
![Tabs1](https://github.com/tablacus/TablacusExplorer/assets/60333254/ebe75c0f-b3ec-41c4-9326-1829beb88b35)

Example 2.
![Tab2](https://github.com/tablacus/TablacusExplorer/assets/60333254/2263e4ca-fe33-4a1e-8fb6-30f81d4eeedf)

Example 3.
![font1](https://github.com/tablacus/TablacusExplorer/assets/60333254/ee8f0b3a-5878-49ab-a477-40cefb020ca8)

Example 4.
![font2](https://github.com/tablacus/TablacusExplorer/assets/60333254/dde1dcbc-1242-411e-a6cc-5a4cb52078d7)



Best regards, 
Jox.

**Comment by JoxCoswit** [comment]
**Question**: What you have done now, can be done in separate add-on?

I'm not a programmer, so please don't misunderstand me.
Maybe I'm just looking at it the wrong way...

I apologize in advance if this is not exactly how I think of that.
If it is complicated with a lot of changes then it is not necessary.

The last solution will be enough.

I will see how to make it in the best way so that it fits my requirements.

The solution you made works and also covers everything I mentioned in the request.

Regards, 
Jox.

**Comment by JoxCoswit** [comment]
The difference between the two packages, regarding at notification messages.
Today I spotted this when I was checking the new version.

The message "**Move**" is displayed instead "**Forbidden**" & "**Link**"

P.S. Initial package, with initial settings.

![info](https://github.com/tablacus/TablacusExplorer/assets/60333254/5f10f172-9ad5-4c7f-88e5-ae9800199334)

**Comment by tablacus** [comment]
Please try to install "Tab design".
Enter the following string in "Default".
```css
border-radius: 0 0 0 0;
font-size: 80%;
```

![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/89462596-916a-41ab-96a1-c0126276ba68)

**Comment by JoxCoswit** [comment]
Perfect! 😃
That is much better now, thank you.

Regards, 
Jox.

**Comment by tablacus** [comment]
The "Tabs" add-on has also been updated and a "Drop to Folder" check has been added.
If you prefer the "Tabs" add-on, uncheck this and use it.

![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/0632f84e-ac61-4694-949b-5e70a2588dbc)

**Comment by JoxCoswit** [comment]
I used it before because of its flexibility.
As the tabs were too big for me, I stopped using them.
Before, I could not influence that the tabs do not increase.

**Questions refer to Tab plus and Tabs:**
Do they have to be used together or can they be used independently?
What is the difference between Tab plus and Tabs?

**I noticed some strange "glitch" when using Tabs.**
When I drag a file folder into the tab area where there is a previous tab, I get a weird glitch when using Tabs.
It's like he goes to the right and then comes back to the left. This does not happen to me with the Tab plus.

As far as I have noticed, Tab design has no effect on Tabs.
When I use Tab plus and Tabs together, there is no effect from Tabs.

Do they cancel each other out?
Should Tabs be used independently?
Why doesn't Tab design affect Tabs?

I tested only on the initial package where I used:
_Tab plus, Tabs, Font settings, Tab design._

**P.S. I confirm yesterday's problem is now fixed.**

**Comment by JoxCoswit** [comment]
As for this glitch, 
I wouldn't say it's bad, I'd rather say it's a bit unusual.

With Tab plus, that transition is smoother.

There is no visible effect on the tab transition.

**Comment by JoxCoswit** [comment]
_I found one little thing..._

The shortcut cannot be placed as a link - ie. open as a tab/link.
When the shortcut is placed in the tab bar at the empty area - it is not allowed.
(The forbidden sign appears) 

I think it would be good to include also and that possibility for all.
_when placed on empty area, on tab... and similar to that._ 

Because a link is essentially a shortcut.

So the shortcut could also be dragged to the tab-bar to open as a tab/link.

> Tested on the initial package, without any changes.
