### ISSUE TITLE
Duplicate separators

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#717]
Hello, I have the ccfs patches installed. One of them is for the "separators" for the "toolbar" and the "favorites bar". Today I updated Tablacus Explorer to the latest version and the separators were duplicated, as the image shows.
![Separadores duplicados](https://github.com/tablacus/TablacusExplorer/assets/96446416/c75156c4-d948-4b46-b6a2-5dd43bf5ea7d)

In the following image I show the contents of the Addon folder --> toolbar
![toolbar](https://github.com/tablacus/TablacusExplorer/assets/96446416/730668a4-3d2e-458b-ac70-ec7309ffc6ea)

What could have happened? Thank you.

**Comment by ccfs** [comment]
Try copying the patched version of "toolbar" and "favorites bar" to your TE folder.

**Comment by dieg467** [comment]
Indeed, ccfs. When copying the patch files to the Tablacus Explorer folder, the separators no longer appear duplicated.
Thank you so much!
