### ISSUE TITLE
Slight delay with transparent display - te240223

### ISSUE THREAD

**Issue by JoxCoswit** [tablacus/TablacusExplorer#724]
With the new version **te240223** there is some 'slight' delay with transparent display!?
_I don't know if it just seems to me or what?_

It seems to me that the previous versions opened much faster, instantly - without transparency, delay...etc.

If it can go back to before...it would be awesome! 🤗

Regards, 
Jox.

**Comment by JoxCoswit** [comment]
If you could please take a look at this, and check what this is about:

That happened to me a couple of times, but rarely - a few times.

I used to get this error message below or TA froze a couple of times and closed automatically.

It was happening after I run the grouping script and close the tab right after.

So, the script is properly executed and after that either an error appears - or it freezes and crashes.
(I used yours and the ccfs scripts, it behaves the same)

This does not happen if I wait 2-3 seconds and then close the tab.

I am most interested in what it could be and if anything can be done about it?

Now I use the method to wait a few seconds after executing the script and not rush to close the tab.
_In this case, there is no problem and no error appears._

I tried with the older version **te230712** and with the version **te240218**.
The error is the same, only the code line is different: 981 / 991

This is the error message with the version - **te230712**
![te230712](https://github.com/tablacus/TablacusExplorer/assets/60333254/f02aae6a-ae2a-4658-9afa-154cb0763476)

This is the error message with the version - **te240218**
![te240218](https://github.com/tablacus/TablacusExplorer/assets/60333254/4b941cac-81a0-4fb1-bf51-83e2dae8d458)

**Comment by ccfs** [comment]
Regarding the grouping script:
When you see the script (Move selected items to new folder) executed, it is actually not fully completed. It will _wait_ briefly and then select the new folder.
Please use "Move selected items to sub-folder" script which do _not wait_ and should not have the above problem.

**Comment by JoxCoswit** [comment]
@ccfs 

If I physically see the folder, does it that mean the folder hasn't actually been created yet?
That is the script has not finished yet? 

I'm looking at it, if the folder is created - the script is finished.

I will check again because these past few days I worked with both last scripts and even with your previous ones.

Otherwise scripts works fine only when I'm in a hurry and If I close the tab immediately and that it happened.

Because I looked if the folder is created that's it.

PS. _I have now expanded a bit on my previous comment._


Regards, 
Jox.

**Comment by JoxCoswit** [comment]
@ccfs

In your last scripts I didn't have an option to create only new folder when nothing is selected. 
So I used your previous one, and Gaku's last one with a delay.
Now I see that I had the same thing with both of them.

You're right, there was no error with this last one of yours.
An error occurred with your previous from the beginning.

I would like to ask you when you have time to add the option when nothing is selected to create only a new folder.

Thank you in advance...

Regards, 
Jox.

**Comment by JoxCoswit** [comment]
Gaku, 

Cool, I can confirm that it's fixed now.
I used your and ccfs previous scripts and now there is no error or freeze/crash.

I'd even say it's even faster now.

I also wanted to ask you if there is anything that can be done about case from yesterday.
It is noticeable not only on weaker configurations but also on better ones.

I don't know how to describe it...

Before it was instant & immediately.

Now It feels like it's dragging/laggy loading when the TA starts.

Regards,
Jox.

**Comment by ccfs** [comment]
[Create sub-folder with selected items.zip](https://github.com/tablacus/TablacusExplorer/files/14396934/Create.sub-folder.with.selected.items.zip)

**Comment by JoxCoswit** [comment]
@ccfs 

Thank you for that.
Much appreciated!  😊

Regards, 
Jox.
