### ISSUE TITLE
アドオン「Tree」を表示するとファイル操作が遅くなる

### ISSUE THREAD

**Issue by shinya823** [tablacus/TablacusExplorer#725]
Boxドライブ（ https://www.box.com/ja-jp/drive ）を利用している事が前提で
そのドライブ配下のファイル操作（フォルダ作成、ファイルのリネームなど）を
行った場合に限ってのことなのですが、標準のエクスプローラーを用いた操作と
比べるとかなりの遅延が発生しています・・・。
※マウスカーソルが待ち状態となり10秒以上応答がなくなります。

Tablacusには、それなりの数のアドオンも追加させて頂いていたため
ひとつひとつ有効／無効を行い切り分けを行ってみたのですが、
どうも「Tree」を表示させた状態で上記操作を実施すると遅延が発生するようです。
※逆に、起動時から非表示にして操作を行うと、遅延しませんでした。

なお１度でもこうなってしまうと（遅延が発生させてしまうと）
Tabcusを起動している限り、再度Treeを非表示に戻したとしても
遅延は解消しなくなるといった状況です。

この程度の調べ方で、Treeが怪しいというのは、大変恐縮なのですが
こちらの事象について、なにか考えられる理由や、対処法などはないでしょうか？

**Comment by tablacus** [comment]
1. 多分、標準のツリーを使われていると思うのですが、あっていますか？
標準ツリー/サイドツリー/フレームのツリーの3種類のツリーが存在します。

2. アドオンのツリーフィルタで「Box」を表示しない設定にした場合はどうなりますか？
![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/1f4722db-ea78-41c9-b4e9-350240dcd800)

**Comment by tablacus** [comment]
こちらの環境では起こっていないのですが、ツリーのアドオンが怪しい感じですね。
オプションの設定はどのような感じでしょうか？

![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/24cf013f-0a86-42a1-a46b-6771545e6fa0)

「フォルダーを展開する」「一覧」にチェックがある場合はツリーのアドオンを有効にしてから
それぞれチェックを外して同様に変化があるのか試していただけると幸いです。

**Comment by shinya823** [comment]
症状が発生している時点の設定は以下となっていましたので
　フォルダーを展開する：OFF
　一覧：ON
一覧をOFFへ変え、操作したところ、遅延なくリネームできました。

＃プログラムの事は疎いのですが、一覧をONにした場合
　　・フォルダやファイル操作のイベントに追従する何かがツリー上に発生している
　　・何かツリーに対し負担が掛かるような事がおきている
　といった挙動に見えました。

追伸：
標準ツリー/サイドツリーまでは昨日試しており、
応答の遅延が発生することは確認できていたのですが、
フレームなるものがあるのは知りませんでした。

先程、「フレームボタン」と「フレームペイン設定」の２つを
更にインストールし、【ナビゲーションウィンドウ】のみを表示させる様に
設定したところ、スムーズな応答が返ってきました。

ツリーの一覧をOFFにしてしまうと、
フォルダの展開がなくなってしまったため（左右の同期が取れなくなりましたので）
どうしようかと思っていたのですが、この方法ですと
ナビゲーションウィンドウのツリーとフォルダ／ファイルの同期も取れていますので
しばらくはこのアドインと設定で様子見させて頂こうかと思います。

![image](https://github.com/tablacus/TablacusExplorer/assets/161164523/bf68d5e6-27e0-4346-98af-764adf8938c0)
![image](https://github.com/tablacus/TablacusExplorer/assets/161164523/27bd8f45-ff2b-4bbc-9ff4-460d77a37820)

> 標準ツリー/サイドツリー/**フレーム**のツリーの3種類のツリーが存在します。
この情報から辿りつけた方法ですね。大変助かりました。
（どうもありがとうございました）
