### ISSUE TITLE
The search query in "Innersearchbar" is also reflected in "innerfilterbar" (it works synchronously)

### ISSUE THREAD

**Issue by madoka-dev** [tablacus/TablacusExplorer#726]
以前のバージョンでは発生していなかったと思うのですが以下のような状態が発生します。

1. Inner 検索バーで検索を実行
2. 検索結果が表示された後に、Inner フィルターバーで同じ文字列でフィルタが自動実行される（2回検索される）
3. このとき両方の入力フォームに同じ文字列が表示されています（Inner フィルターバーは自動入力されている）
4. 3の状態でInner フィルターバーを使ってフィルタしようとすると、 Inner 検索バーの文字列も同期してしまう（検索結果がクリアされる）

アドオンの設定などで解消できるのであればお知らせいただけるとありがたいです。

**Comment by tablacus** [comment]
検索中はフィルタできないので、検索中はフィルターバーが検索用に動作する仕様になっています。

**Comment by madoka-dev** [comment]
ご回答ありがとうございます。
2回検索処理が走るのも仕様なのでしょうか? ここが以前はなかったような気がしております。

**Comment by tablacus** [comment]
フィルターバーは1文字入力するごとにフォルダを読み直す仕様なので仕方ない部分かなと思います。
検索中のフィルタはExplorerBrowserのイベントが来ない関係で実現できていない部分ですが、結果フォルダ(IResultsFolder)を使うとか別の解決策を考えてみます。

**Comment by madoka-dev** [comment]
ありがとうございます。理解いたしました。
今回たまたま大量のファイルを検索した際に少し気になった程度ですので、いつか実装されたらいいなくらいの感覚でおります。
