### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by dzjdfzjhdeh** [tablacus/TablacusExplorer#73]
A little thing bothers me a lot. Otherwise the explorer would be perfect. If the window of the explorer is maximized. And I go with the mouse to the far right on the scrollbar of the file list. It is unfortunately not that I can scroll with a klick up or down. I have to go with the mouse 1 pixel to the left, it goes. Perhaps it is enough that the file list window is enlarged by 1 pixel on the right.

best regards

**Comment by tablacus** [comment]
Open "Tools" -> "Options..."
Click "Style(List)".
Check "No client edge".
![4](https://cloud.githubusercontent.com/assets/5156977/21388866/b82e2ae6-c7c1-11e6-97f9-85cc6ab9f9d3.png)
Click "Ok" & "Ok"
Restart Tablacus Explorer just in case.

Best regards,

**Comment by dzjdfzjhdeh** [comment]
Does not work with me unfortunately. Use windows 10.

**Comment by dzjdfzjhdeh** [comment]
![v2](https://cloud.githubusercontent.com/assets/24624060/21429026/42a610ee-c85d-11e6-9c19-456ed3ceea4c.jpg)

solution found.

List > Explorer Browser (* 7) > details

I had activated it. After deactivate it went.
