### ISSUE TITLE
Feature Request: Use proxy settings to check for the latest version.

### ISSUE THREAD

**Issue by AoiKagase** [tablacus/TablacusExplorer#735]
I want to check the latest version through a separate proxy.
For some reason, github.io is blocked on our network and we cannot check the latest version. (github.com is connected).
The browser uses a Sock5 proxy to bypass the problem, and I can update manually.
I wish I could specify the proxy in the same way as the browser if possible.

最新版のチェックに個別のプロキシを経由させたい。
施設内ネットワークにて何故かgithub.ioがブロックされており、最新版の確認が出来ない状態です。（github.comは繋がる）
ブラウザはSock5プロキシを使用して回避しており、手動での更新は可能なのですが
更新通知が来ないのでブラウザと同じようにプロキシ指定が出来ればなと思います。

**Comment by AoiKagase** [comment]
特殊な環境で説明が難しいのですが
通常はダイレクト接続ですが、アプリケーションや利用するWEBページがそれぞれ特定のネットワークからのみアクセスできる物が多く、
WEBページではChromeの拡張機能（SwitchyOmega）を使ってページによってプロキシ経路を切り替えたり
各アプリケーションごとのプロキシ設定を個別に設定して利用している状態です
（SocksProxyです。SwitchyOmegaではSOCKS4,SOCKS5が切り替えられるようになっています）
そこにTablacusも乗せられないかと思った次第です。

github.ioがブロックされて自動での更新通知が来なくなった、
他のアドオンもメニューから直接落とすことが出来なくなった事が今回の起因で
SocksProxyを使ってブラウザからのダウンロードは出来るので、
難しいようでしたらこのIssueは破棄していただいてかまいません。

（アドオンの「ダウンロード」もコマンド実行なだけでブラウザからＤＬと大差ありませんよね？
更新チェックのurlがgithub.comならブロックされてないので問題なく利用できそうなのですが・・・）

**Comment by tablacus** [comment]
更新チェックには基本的に`https://api.github.com/repos/tablacus/TablacusExplorer/releases/latest`を読み出しています。
上記が読み込めない場合(Windows XPなどは`https`がもう繋がらないので)代替として`http://tablacus.github.io/TablacusExplorerAddons/te/releases.json`を読み込みます。

アドオンの「ダウンロード」を使った場合は更新チェックもこのアドオンを使用しますので`cURL`のコマンドラインでプロキシを設定すれば大丈夫なのではないかと思います。

![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/d5686a28-7794-4997-92a5-7b43268ebea0)

**Comment by AoiKagase** [comment]
ありがとうございます。
解決しましたのでこのIssueはクローズさせていただきます。
