### ISSUE TITLE
Frame plus - New add-on to manage "Show frames" panes

### ISSUE THREAD

**Issue by ccfs** [tablacus/TablacusExplorer#743]
[frameplus_100.zip](https://github.com/tablacus/TablacusExplorer/files/14930864/frameplus_100.zip)

**Comment by Leo9idas** [comment]
I think we needed this ! Well done ! Two remarks for my use case.
1. When I open the preview panel and then the detail panel the preview panel remains open under the details.
2. When detail panel is opened then preview panel does not (detail is on top.
I think in your functions the previous panel should close before opening a new one.
I used your call/function "Sync.FramePlus.Toggle('DP', '$')" in my Linkbar menu. Is it ok to do that ?
Thank you !

**Comment by ccfs** [comment]
Each pane is independent. Turn one on will not turn another off.

Besides independency, do you mean that the positions of the panes are wrong? Can you show some screen captures of the problems and what you expect?

This add-on works in the way as if you used "Frame pane" add-on to toggle a pane setting then turned "Show frames" off and immediately on. Please let me know if you get the same problems with "Frame pane" (these two add-ons should not be enabled at the same time).

You can toggle a pane of the current tab by
Sync.FramePlus.Toggle('`pane`');
where `pane` = NP, TB, DP or PP

If you want to toggle 2 panes (DP and PP) in one step, this will be faster:
```
FV.Data['DP'] = (FV.Data['DP'] == EPS_DEFAULT_ON) ? EPS_DEFAULT_OFF : EPS_DEFAULT_ON;
FV.Data['PP'] = (FV.Data['PP'] == EPS_DEFAULT_ON) ? EPS_DEFAULT_OFF : EPS_DEFAULT_ON;
Sync.FramePlus.Apply(FV);
```

Besides, I guess that the "Tool bar" part does not work on Windows 8 and newer, because it is a "Ribbon" instead (see https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-iexplorerpanevisibility-getpanestate). Can you check this so that I can amend the add-on accordingly?

**Comment by ccfs** [comment]
Please try this version and see if it can solve the problem in webview, and my suspected problem in "Tool bar".
[frameplus_100a.zip](https://github.com/tablacus/TablacusExplorer/files/14944478/frameplus_100a.zip)

**Comment by Leo9idas** [comment]
Each pane is independent but when I have for example details pane open and I want preview pane to open then preview pane opens but is under details pane so it is not visible.

https://github.com/tablacus/TablacusExplorer/assets/37123757/b27aac9f-27b4-41ed-87fd-a52f7b128a56

The above video showcases the expected behavior (windows 11)

The next video shows how the addon works for me. It is working but as you will see the pane visibility order does not change and details pane stays always on top preventing the preview pane to show. Not a major problem but still :)

https://github.com/tablacus/TablacusExplorer/assets/37123757/2eb24527-2aad-4d2c-a7ba-cac1f8871aaf

Toolbar works just fine except when webview is enabled.
![TE64_kcRcNiwqwR](https://github.com/tablacus/TablacusExplorer/assets/37123757/c3e973f8-a0e9-4f28-9947-fe6809ef40db)

Thanks !

**Comment by Leo9idas** [comment]
> Please try this version and see if it can solve the problem in webview, and my suspected problem in "Tool bar". [frameplus_100a.zip](https://github.com/tablacus/TablacusExplorer/files/14944478/frameplus_100a.zip)

I didn't notice any visual difference with this version and with webview its still the same as my above post. In general webview breaks the menu system and the setting update for me.

**Comment by Leo9idas** [comment]
Something that I came across and you might find something useful because this is out of my league !
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/javascript/hostobjectasyncproxy

**Comment by ccfs** [comment]
Please see if this version can solve the Preview/Details Pane problem and webview problem.
[frameplus_101.zip](https://github.com/tablacus/TablacusExplorer/files/14956545/frameplus_101.zip)

I notice that the button faces on Windows 10 and 11 File Explorer are different from those in TE. Can you provide me their icon paths (icon:xxx,nnn) so that I can update the add-on accordingly? You can get them from the TE icon selection window (Tools > Menus > Select button). Thanks.

**Comment by Leo9idas** [comment]
1. Preview/Details Pane works ok now !
1.1 With Webview  buttons are displayed now, but when I click (normal version or patched version) usual error occurs.

![Screenshot 2024-04-12 125938](https://github.com/tablacus/TablacusExplorer/assets/37123757/df682724-2e21-41fd-abd8-bc85c44bd106)

![Screenshot 2024-04-12 130100](https://github.com/tablacus/TablacusExplorer/assets/37123757/0fe16831-e333-49f0-8214-b40e6fdefd95)

Please provide me a screenshot because I cant find/understand where the icon selection window is (Tools > Menus > Select button)

**Comment by Leo9idas** [comment]
Windows defender false alarm for script.js (not sync.js) In case affects anyone. (I have excluded already TE folder from defender)
![trojan warning1](https://github.com/tablacus/TablacusExplorer/assets/37123757/e0c76366-9462-4b3e-9fbc-8a934f88c036)

**Comment by ccfs** [comment]
Icon selection window:

![1](https://github.com/tablacus/TablacusExplorer/assets/34089121/63a034a0-3aab-453e-a931-f3558f11a3fc)
![2](https://github.com/tablacus/TablacusExplorer/assets/34089121/838516a9-48c7-4204-b87e-daf050d37520)
![3](https://github.com/tablacus/TablacusExplorer/assets/34089121/81c2a350-c8aa-4ae2-8bf8-85a5da0df7c9)

I need the icon paths of Navigation Pane, Tool Bar, Details Pane and Preview Pane of Windows 10/11 File Explorer. Currently the add-ons use the paths as on Windows 7, but may not be best fit for newer versions.

**Comment by ccfs** [comment]
Please see if this version can solve the webview problem.
[frameplus_102.zip](https://github.com/tablacus/TablacusExplorer/files/14971093/frameplus_102.zip)

Since the paths of svg icons are uncertain, I use icons in DLL for all 4 buttons.

All MENUS in TE and add-ons CANNOT use svg icons, because the menus are NOT WEB pages. On the contrary, TE window is a web page and thus the buttons on it can use svg icons.

**Comment by Leo9idas** [comment]
**### Works ok with webview enabled !** Only the icons that I underline show up strange.

![Screenshot 2024-04-14 191022](https://github.com/tablacus/TablacusExplorer/assets/37123757/c5b0dece-08a6-49a1-9ca5-848e777e81b3)

**Comment by Leo9idas** [comment]
I changed the two icons in script.js.
```
{Abbr: "TB", Title: "Tool bar",            Icon: WINVER > 0x601 ? "icon:imageres.dll,306" : "icon:shell32.dll,295"},
{Abbr: "DP", Title: "@shell32.dll,-31415", Icon: WINVER > 0x601 ? "icon:shell32.dll,304" : "icon:shell32.dll,256"},
```
![Screenshot 2024-04-14 195459](https://github.com/tablacus/TablacusExplorer/assets/37123757/a0e939d3-c734-447e-b92a-f79e5ca50346)

**Comment by ccfs** [comment]
I have updated the add-on about the two icons.
[frameplus_103.zip](https://github.com/tablacus/TablacusExplorer/files/14975096/frameplus_103.zip)

I searched the Internet for the icon numbers. I didn't know why the numbers were wrong, anyway.

**Comment by ccfs** [comment]
Some problems in button display under WebView is solved.
[frameplus_104.zip](https://github.com/tablacus/TablacusExplorer/files/15051077/frameplus_104.zip)

**Comment by nhm567** [comment]
Please help me how to preview PDF files in preview panel (Word, Excel, txt, bat files view well). Thanks!

**Comment by ccfs** [comment]
You probably need a PDF viewer such as Adobe Acrobat Reader.
