### ISSUE TITLE
Force Refresh add-on Not Supported %X-Finder% 

### ISSUE THREAD

**Issue by houxiren** [tablacus/TablacusExplorer#746]
Force Refresh add-on Not Supported %X-Finder% ,Is it a BUG or originally not supported this variable? Thank you.

In favorites, set %X-Finder%....\D\D directory, can open D:\D\D. 
in the Force Refresh add-on, setting %X-Finder%....\D\D does not automatically Refresh D:\D\D. 
in the Force Refresh add-on, setting D:\D\D , the Force Refresh add-on takes effect.

**Comment by tablacus** [comment]
I have fixed it on Force refresh v1.11.
Please try to update.

Regards,

**Comment by tablacus** [comment]
I have fixed it on Tablacus Explorer 24.5.3.
Please give it try.

https://github.com/tablacus/TablacusExplorer/releases/tag/24.5.3

Regards,

**Comment by houxiren** [comment]
Explorer 24.5.3 + Force refresh v1.11 fixed. 

Thank you for the quick fix, and thank you for developing such outstanding software!

Respect and gratitude!
