### ISSUE TITLE
Multiple shortcuts to Tablacus Layouts in the Windows 10 taskbar

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#748]
Hello, I have created several Layouts in Tablacus, which I access frequently. If I create shortcuts to some of them and want to add them to the Windows 10 taskbar, they are integrated into the Tablacus shortcut, not added like other standalone shortcuts.
Is it possible to create multiple Layout shortcuts to place on the Windows taskbar, each opening as a separate window? Thank you so much

**Comment by ccfs** [comment]
1. Enable "Multiple execution" add-on.
2. Create one shortcut (.lnk) file for each layout. Example:
- D:\test\te240511\TE64.exe "Load layout,D:\test\te240511\layout\layout1.xml"
- D:\test\te240511\TE64.exe "Load layout,D:\test\te240511\layout\layout2.xml"
3. Drag and drop the shortcut files to Windows task bar.

**Comment by dieg467** [comment]
Perfect ccfs!! That's exactly what I was looking for. Now I do have shortcuts to the designs that I use most directly on the taskbar. Thank you very much for your help, greetings!
