### ISSUE TITLE
Duplicate tab instead of new tab ? (solved)

### ISSUE THREAD

**Issue by niawag** [tablacus/TablacusExplorer#75]
Hi, I'm a new Tablacus user and I already like it!

I'm not sure this is an issue but I've searched a lot without success to "solve" this on my own.
When I want to open a new tab (+ button, ctrl+n, ctrl+t) I'd like it to show "My PC" but it will always duplicates the active directory (in the currently displayed tab).

Is it normal? Can I configure this behavior somewhere?

**Comment by tablacus** [comment]
Hi, Let's change the setting.
1.Open options.
2.Click Tabs on the left menu.
3.Input "17" on New Tab field.
( You may choose a folder with the button "Browse...". )
4.Clik "OK",
![12](https://cloud.githubusercontent.com/assets/5156977/22370984/c2488070-e4d7-11e6-859e-4cc7121aebe8.png)

Best regards,

**Comment by niawag** [comment]
Thanks a lot it's working! I tried that with the browse button but it wasn't working. Now it's working with "17" as well as with the browse button!

**Comment by tablacus** [comment]
My pleasure.
