### ISSUE TITLE
Clone file/folder

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#752]
Hello, is there a function in Tablacus Explorer that, through the context menu, allows you to clone or create a copy of a file or folder? Thank you so much!

**Comment by ccfs** [comment]
"Duplicate copy" add-on

**Comment by dieg467** [comment]
Hello ccfs. I installed the plugin, and to create the copy I must follow these steps.
1º) Right click on the file to open the context menu.
2º) Click on Copy.
3º) Right click on the file to open the context menu.
4º) Click on Paste.
Then, a small Tablacus window opens to assign a name to the copy.
5º) Give a name to the copy.
6º) Click on accept.
The copy was created.

My idea is that there is a plugin that adds the "Clone" function to the context menu, to make the process easier, like this:
1º) Right click on the "File" to open the context menu.
2º) Click on "clone".
Ready. The copy "File(1)" was created automatically.

Will this be possible? Thank you so much

**Comment by ccfs** [comment]
Set up the add-on like this:
![image](https://github.com/tablacus/TablacusExplorer/assets/34089121/f165206b-69ee-4602-bb5c-15ed795a05c0)
The small Tablacus window will still show up for confirmation.

**Comment by dieg467** [comment]
Perfect ccfs! I named it "Clone" and it appears with that name in the context menu. It works just as I wanted.
Thank you so much!
