### ISSUE TITLE
Is it possible to change the background color of only the active pane and active tab?

### ISSUE THREAD

**Issue by x03n046** [tablacus/TablacusExplorer#759]
分割アドオンでペインを複数表示した状態で
アクティブペインかつアクティブタブだけの背景色を変更したいのですが可能でしょうか

**Comment by tablacus** [comment]
スクリプトを使ったりCSSを工夫すればできると思いますが、アドオンのタブプラスのオプションのバックグラウンドにチェックを入れてアクティブ側のタブバーの色を変えたり、アドオンの非アクティブペインを入れて一覧で判別する運用の方が簡単だと思います。

![image](https://github.com/tablacus/TablacusExplorer/assets/5156977/7056d8d0-07cc-4825-a8e7-30b265e095f9)

**Comment by x03n046** [comment]
御確認頂きましてありがとう御座います。

要望通りの対応は難しそうなので
教えていただいた方法で代用したいと思います。
