### ISSUE TITLE
inner delete button

### ISSUE THREAD

**Issue by stefanocaselli** [tablacus/TablacusExplorer#76]
Hello,
please can you create a new addon: inner delete button (just like refresh o create directory buttons).
Many thanks.

**Comment by tablacus** [comment]
I will try to consider it.
Thank you,

**Comment by tablacus** [comment]
I've made an add-on "Delete".
This add-on can select "inner bar".
![10](https://cloud.githubusercontent.com/assets/5156977/23102592/26a04d68-f6ef-11e6-9598-f395684091fe.png)

Best regards,

**Comment by stefanocaselli** [comment]
works perfectly. thank you!

2017-02-19 14:04 GMT+01:00 Gaku <notifications@github.com>:
