### ISSUE TITLE
Some files with Chinese name cannot show in TE

### ISSUE THREAD

**Issue by toolyq** [tablacus/TablacusExplorer#762]
![image](https://github.com/user-attachments/assets/2d933968-6d89-4c52-a9f7-e042c4ce1649)

**Comment by ccfs** [comment]
Do the files have the HIDDEN attribute?
Please try ticking Options > List > Show all files.

**Comment by toolyq** [comment]
> Do the files have the HIDDEN attribute? Please try ticking Options > List > Show all files.

You are right, I will close this issue.
