### ISSUE TITLE
アドオンのエラー

### ISSUE THREAD

**Issue by santiago-cmac** [tablacus/TablacusExplorer#766]
Tablacus Explorerを使っていると、アドオンを入れようとしたら添付図のエラーが発生されます。
エラーの「はい」「いいえ」どちらを押しても特に何の変化も見られません。
自分はTablacus Explorerを使って大変便利なのでこのまま使いたいのですが、解決方法を教えていただけると幸いです。
[
<img width="373" alt="スクリーンショット 2024-08-05 105220" src="https://github.com/user-attachments/assets/cc755e7b-7c11-4069-b4ff-67836490b3c2">
](url)

**Comment by tablacus** [comment]
とりあえず、インターネット オプション→詳細設定→セキュリティ→TLS 1.2 の使用 と TLS 1.2 の使用 にチェックを入れてください。
![image](https://github.com/user-attachments/assets/73009d7e-7c2c-48aa-a1e0-bb62a9bb63c5)

**Comment by santiago-cmac** [comment]
ご返信ありがとうございます。
チェックが入れてありますが、まだアドオンできてないです。
<img width="335" alt="スクリーンショット 2024-08-07 105355" src="https://github.com/user-attachments/assets/d1c18d0b-3f0d-40a8-b44c-bb5f41bc4122">

**Comment by tablacus** [comment]
では、アドオンのページを開いて「ダウンロード」の`有効`にチェックしてください
![image](https://github.com/user-attachments/assets/d4d10e62-43ef-4523-adad-d4d2bc84e7ed)

次に「ダウンロード」の`オプション`をクリックしてください
![image](https://github.com/user-attachments/assets/ac8042dc-f929-4fed-a6ba-1c511ef3c428)

「cURL」をクリックして「OK」を押せばOKだと思います。
![image](https://github.com/user-attachments/assets/a926fdf2-cd89-455f-bcb8-2e837fcbd81e)

ダメだったら、「cURL」の代わりに「PowerShell (TLS 1.2)」を試してみてください。

**Comment by santiago-cmac** [comment]
解決できました。ありがとうございます。
上記の手続きをしたら、添付画像のエラーは発せしましたが、
![スクリーンショット 2024-08-09 110728](https://github.com/user-attachments/assets/f6c6feb1-9389-4477-8bb4-257307ae7d81)

Tablacus Explorer WebView2のlibフォルダを普通の Tablacus Explorerのフォルダーにコピーしたら、アドオンを追加できるようになりました。
