### ISSUE TITLE
TablacusExplorer doesn't see files (a lot of them)

### ISSUE THREAD

**Issue by Yoksven** [tablacus/TablacusExplorer#772]
(This was not a problem, but me messing things up. I can't delete this thread, so I'm writing this note)

[Here](https://i.ibb.co/3RLvYvh/Illustration02.jpg) on the left is a report from TablacusExplorer and on the right from the regular explorer. There are 114 files, but TablacusExplorer only sees 100. And I can confirm that it's not just a buggy report, files indeed are missing. There's nothing special about the missing files - they are the same file types as ones that are showing, and the naming convention is the same, so it's not some special character that causes it. They are just not there. And [here is a more extreme case](https://i.ibb.co/wMW38Ph/Illustration03.jpg) where in the regular explorer there are 713 files, but TablacusExplorer only sees 164 of them.

So far, I couldn't figure out why it is happening or how to make the files appear. Weirdly enough, copying a missing file from the regular explorer to TablacusExplorer does make it appear without creating a copy in the regular explorer, but I'm not gonna do that for all missing files in all folders.

It's honestly a deal breaker. Which is sad, because I really liked TablacusExplorer so far. I hope there is a solution for it or it can get fixed.

**Comment by Yoksven** [comment]
So, I copied files from that extreme case folder to TablacusExplorer and... it reported seeing 719 files. 7 more then the regular explorer. So I copied files from TablacusExplorer to the regular explorer and they did indeed appeared in the regular explorer... 7 extra files that weren't there. What is happening?

**Comment by Yoksven** [comment]
After messing around with those 7 files I've discovered two disturbing facts about TablacusExplorer. First, 4 of those files were files that I've deleted a long time ago. And second, the other 3 of those files were files that I've copied into the folder using TablacusExplorer (drag and dropped from desktop). For whatever reason they didn't show up in the regular explorer. 

The question still remains - what is happening? But for now I will stop using TablacusExplorer, because I don't want any of that shenanigans with files not showing in the regular one. I still hope there is a solution, but for now I will look elsewhere.

**Comment by Yoksven** [comment]
Not even folder structure is sacred. I'v just noticed that one folder that I moved to a different location is in it's old location in TablacusExplorer. And I moved it weeks before trying TablacusExplorer. I just... don't have words...

**Comment by Yoksven** [comment]
Okay. I've figured it out. I goofed. It was not related to TablacusExplorer. I've just goofed and opened a wrong backup copy in the tab. Phew. Everything is okay. It's all working fine. I just messed up my backups a bit.

**Comment by rrrevin** [comment]
Good catch. If you can't delete the issue, perhaps mark it as Closed.
