### ISSUE TITLE
Auto folder view doesn't seem to work

### ISSUE THREAD

**Issue by SpaceThing** [tablacus/TablacusExplorer#773]
Folder view set to **"auto"**
<img src="https://github.com/user-attachments/assets/e762fb78-c589-47e3-989d-ba5aed3f6fe1" width="500px">

Folder set as optimized for **"photos"**
<img src="https://github.com/user-attachments/assets/c01c23ec-f589-44af-805e-fdc9e0d06f7a" width="500px">

Still shown in **"details"** rather than **"icons"**
<img src="https://github.com/user-attachments/assets/49aa6396-b44c-40a1-8fb1-68e78f1999b4" width="500px">

**Comment by ccfs** [comment]
Default add-on "Remember folder view settings" will override this "Auto" setting.

**Comment by SpaceThing** [comment]
> Default add-on "Remember folder view settings" will override this "Auto" setting.

I tried to disabled it and restart TE but "auto" still seems not working😭
<img src="https://github.com/user-attachments/assets/0fad2a72-9a8a-41b7-b064-fb809af84ee2" width=500px>

**Comment by ccfs** [comment]
Please paste your TE info from Help > About into your reply.
Please also show me your settings on "Options > List > Style". Note that if you turn on any "Explorer browser" (except Content), "Auto" may not work.

**Comment by SpaceThing** [comment]
Oh my fault, I some how installed "Take over folder view setings" at the same time. Thank you
