### ISSUE TITLE
Label overlayed with file name

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#774]
Hi, I am using the "Label" plugin. In some folders, although the column width automatically increases when the file name is long, the label overlaps the file name. The image shows the situation. How can I fix this problem? Thanks.
![Label](https://github.com/user-attachments/assets/62cf53cf-8e45-49f7-935a-11c425bdb581)

**Comment by ccfs** [comment]
You can either
- widen the name column, or
- show the labels in a separated column (as below)

![1](https://github.com/user-attachments/assets/67d72e0b-7938-4e58-a406-114440b7dd51)
![2](https://github.com/user-attachments/assets/8f0a49cc-078e-4c4a-8e3c-6aa022164742)

**Comment by dieg467** [comment]
I usually use List view. I switched to Details view, increased the width of the Name column, so that the label was visible. However, when I switched back to List view, the column width was reduced and the label was overlapping again. What could have happened?

**Comment by ccfs** [comment]
(1) Column width of Details view does NOT apply to List view.
(2) Column width of List view usually follows the longest name in a folder and is NOT fixed overall.
You can try "List width" add-on and specify a fixed width, which will override (2) above.
Nevertheless, the overrlapping issue may still happen. There is not any complete solution.

**Comment by dieg467** [comment]
Thanks a lot ccfs. With the "List width" plugin I was able to set the proper width to the filename column in the List view so that the labels do not overlap the filename.
Thanks again for your help, regards!
