### ISSUE TITLE
Customizing "Label"

### ISSUE THREAD

**Issue by dieg467** [tablacus/TablacusExplorer#776]
Hi, I'm using the "Label" plugin a lot. Currently you can add a red text label. Is there a way to change: (1) Text color, (2) Text format (normal, bold, italic), (3) Label background color, (4) Shape of the label background color, such as rounded rectangle, angled edges, etc. Is this possible with CSS code or a plugin?
Thank you very much.

**Comment by ccfs** [comment]
(1) You can change text color through the Options page.
![20240901_144440](https://github.com/user-attachments/assets/c65cd0d5-05ec-4c65-a3fe-9e4412d6a450)

(2), (3) Enhancement to "Overlay label" add-on is required. ILLUSTRATION:
![20240901_144416](https://github.com/user-attachments/assets/b9dc15a8-662a-4859-ac4b-cd001e1e9da8)

(4) The shape is probably NOT able to be changed.

**Comment by dieg467** [comment]
Perfect, ccfs. You can customize the color of each label.
Hopefully in the future you will be able to select the font type, background color, and background shape, either with a plugin enhancement or via CSS code.
Thanks again!!

**Comment by ccfs** [comment]
This [modified version](https://github.com/user-attachments/files/16905425/overlaylabel_240906.zip) lets you:
- choose a font and its style for all labels
- choose text and background colors for each label

TE file lists are not in HTML, and thus cannot be styled with CSS.

**Comment by dieg467** [comment]
Awesome ccfs!! Now my virtual classes are labeled with their duration, I can put a background color on the label, and customize the font and its style.
Thank you very much for this patch!!
![image](https://github.com/user-attachments/assets/3207b07a-1f55-4794-baea-3c22a03e00f3)

**Comment by ccfs** [comment]
I have added padding options in the [latest version](https://github.com/tablacus/TablacusExplorer/issues/692). You can specify a space at left and right if you want a wider background color.

**Comment by dieg467** [comment]
Perfect, ccfs!! In the images you can see two padding options, one with 1 blank space on the left and 1 on the right, and another with 2 blank spaces on each side. The label looks more harmonious this way and the text stands out more visually, because it is further separated from the column on its right.
I also changed the font of the label to Roboto bold, size 11.
Thank you very much for this improvement!

![Lista archivos (Tablacus) con padding1](https://github.com/user-attachments/assets/8eb49b01-6612-4b36-b8a0-745b1f090300)

![Lista archivos (Tablacus) con padding2](https://github.com/user-attachments/assets/483e787f-3407-428d-b94b-6d055c0c6a08)

**Comment by dieg467** [comment]
A question. If I rename the folder, then all the tags on the files and subfolders in it are deleted. This happens with both the original version and the patched version of the "Tag" plugin. Is this the expected behavior? Or is there a way to prevent them from being deleted?

**Comment by ccfs** [comment]
"Label" add-on will update the path associated with a label when a folder is renamed (or moved). It will NOT update the paths of the items inside the folder. Those labels are not deleted, just still associate with the old paths.

I have enhanced the add-on so that you can opt to synchronize the items inside a folder, and keep the labels attached.
![20240911_154737](https://github.com/user-attachments/assets/647cd835-bb7e-471a-ba8c-73c7196ee6f1)

You will need to use the [patched version](https://github.com/tablacus/TablacusExplorer/issues/692).

**Comment by dieg467** [comment]
Awesome! Thank you very much ccfs for adding these features to the plugin. I am more and more satisfied with using Tablacus Explorer every day, it makes file and folder management much easier for me.
Thanks again!!

**Comment by dieg467** [comment]
Hi ccfs, I need help! When I want to add a new tag, which I have not used before and is not in the list of used tags, I get the following window: 'Input dialog2' is not defined as null.

![Input Label](https://github.com/user-attachments/assets/0cc11a9b-b47d-4b69-90ed-793ab1c182a4)

What could be the problem?

**Comment by ccfs** [comment]
You have to run "patch.cmd" to apply the whole [patch](https://github.com/tablacus/TablacusExplorer/issues/692), not just replacing the label add-on folder.
Make sure you make a backup of your TE folder before running "patch.cmd".

**Comment by dieg467** [comment]
Perfect! I ran the patch.cmd from the command prompt, added the path to Tablacus and the patch was installed and now the Etiqueta plugin works correctly.
Thanks a lot, ccfs!
