### ISSUE TITLE
[HELP] I accidently put main menu in the background. How to undo that?

### ISSUE THREAD

**Issue by Yoksven** [tablacus/TablacusExplorer#778]
As the title says. Now my main menu is unacceptable behind the tabs bar (and even if I close all tabs I still can't click on the menu, even if it's not covered by tabs). I now have no access to the main menu, so I can't go into the settings and undo it. I've tried every button on the keyboard in hope that one of them will be a hotkey for the settings, but nope. I'm trying to find where TE stores it's settings, so I could edit the file and undo it like that, but I can't find it anywhere.

**Comment by Yoksven** [comment]
I've tried copying "manimenu" addon from the zip file, but it had no effect.

**Comment by Yoksven** [comment]
Found it. It was in \AppData\Roaming\Tablacus\Explorer\config\addons.xml

**Comment by ccfs** [comment]
You can right-click TE icon and choose "Options" from the menu.
![opt](https://github.com/user-attachments/assets/1f36ec61-2ea8-460a-91bb-831461e8308a)

**Comment by Yoksven** [comment]
Cool. I didn't noticed that. Thanks.
