### ISSUE TITLE
Teracopy add on

### ISSUE THREAD

**Issue by thumbapps** [tablacus/TablacusExplorer#78]
One more thing...

Could you add Teracopy add on?

arigato!
Ronny
@thumbapps.org

**Comment by tablacus** [comment]
I'm gonna do it. 

p.s.
(cheat)
You can use TeraCopy with Add-on "Fire File Copy".
64bit
Class 
{A7645AF0-D6E8-48AF-8DFA-023B1CF660A7}

32bit
Class
{A7005AF0-D6E8-48AF-8DFA-023B1CF660A7}

If you install TeraCopy normal, ｔhe path can be omitted.
![1](https://cloud.githubusercontent.com/assets/5156977/23579122/f3db8664-0129-11e7-8dfb-e94f3d254652.png)

Best regards,

**Comment by thumbapps** [comment]
BTW I tried to use Fire FC but it won't run. Does it need Admin. privilege? Since the setup points to the .dll not the .exe file?

**Comment by tablacus** [comment]
Have you not installed an add-on "Multi thread" or "Multi process"?
These add-ons conflict.
Please disable these add-ons.

And, I've made an add-on "TeraCopy".

Best regards,

**Comment by dasu88** [comment]
I tried installing the tera copy plugin to get this error message
![2017-03-05_221738](https://cloud.githubusercontent.com/assets/23251263/23588030/cf845c00-01f1-11e7-8976-2f820bf5a55b.jpg)

**Comment by dasu88** [comment]
Just try it, the file name is teracopy100.zip is not teracopy_100.zip

**Comment by tablacus** [comment]
I mistook the file name.
I've adjusted it.
Please install it now.

Thank you,

**Comment by thumbapps** [comment]
Gaku, arigato!

**Comment by tablacus** [comment]
My pleasure,
