### ISSUE TITLE
Filename color by type

### ISSUE THREAD

**Issue by lededev** [tablacus/TablacusExplorer#787]
Eg. text file blue, video & audio file magenta, exe and dll green, others black.
Any suggestion?

**Comment by tablacus** [comment]
I would use an add-on ”Colored with extension”.

![image](https://github.com/user-attachments/assets/01e21ff0-7e82-423c-ab0f-417c9b412505)

![image](https://github.com/user-attachments/assets/c201121d-ac57-4707-b41c-08cd77e711cb)

![image](https://github.com/user-attachments/assets/ad5e6d35-2193-424e-b385-a5c611b3a835)
