### ISSUE TITLE
Tab key change active pane?

### ISSUE THREAD

**Issue by lededev** [tablacus/TablacusExplorer#788]
When I press Tab key or Shift+Tab shortcut or F6 or Shift+F6, TE not like TotalCommander/Q-Dir/FreeCommander/DoubleCommander change my current explorer pane/view to next/prev one.
How can I config for this feature? TIA.

**Comment by lededev** [comment]
I find the solution:
Add key value: Tab
type: Jscript
```javascript
let FV = GetFolderView(Ctrl, pt);
FV = Sync.SwitchPane.NextFV(FV);
if (FV) {
	FV.Focus();
}
```
Add key value: Shift+Tab
type: Jscript
```javascript
let FV = GetFolderView(Ctrl, pt);
FV = Sync.SwitchPrevPane.Exec(FV);
if (FV) {
	FV.Focus();
}
```

**Comment by ccfs** [comment]
Alternatively you can do the same by add-on commands "Switch to next pane" and "Switch to previous pane":
![20241124_082745](https://github.com/user-attachments/assets/72157dc8-9a0a-40ee-a45f-826c9a3b5713)
