### ISSUE TITLE
How to make active pane look different than others?

### ISSUE THREAD

**Issue by lededev** [tablacus/TablacusExplorer#789]
Also, how do I make the view where the input focus is located visually different from other inactive views? It's a bit difficult to determine which view gets focus right now. For example, I want the activation view to have a horizontal line above the activation tab, or let activation pane's tab bar background color change.

**Comment by tablacus** [comment]
I would install an add-on "Inactive pane".

**Comment by lededev** [comment]
Thanks for the hint, I'll reference this part of the code to implement an add-on that changes activation pane's tab bar background color. Change all inactive panes background redraw too much area on my layout.

**Comment by ccfs** [comment]
Alternatively you can use the [patched version](https://github.com/tablacus/TablacusExplorer/issues/692) and set background color of file list (and folder tree) of active pane
![20241125_092348](https://github.com/user-attachments/assets/11958c2f-c533-4e40-aa1f-e8a105e06cbb)
![20241125_092318](https://github.com/user-attachments/assets/441e2e82-756e-4a1a-b8bd-08c4db416ee0)
