### ISSUE TITLE
exec alert during update

### ISSUE THREAD

**Issue by tortino** [tablacus/TablacusExplorer#82]
Hello,
since a few releases when updating Tablacus I get an alert with message "Exec". Is this a bug?

![immagine](https://cloud.githubusercontent.com/assets/26486758/25181378/a885eb3a-2511-11e7-849c-d46ff40b068a.png)

**Comment by tablacus** [comment]
It's in the specifications.
Without this dialog, update fails in the environment where TeraCopy is installed.

http://www.codesector.com/teracopy

Thank you,

**Comment by tortino** [comment]
ok thanks.

**Comment by tablacus** [comment]
Thank you,
