### ISSUE TITLE
Search by label in a specific folder

### ISSUE THREAD

**Issue by xingxuanma** [tablacus/TablacusExplorer#83]
Can I do a search by label in a specific folder? 
For example, I have many labelled files/folders in different folders, and I want to search something by label in current folder (or some other specific folders). Can Tablacus Explorer do this? If so, what should I do? 

And I really want to know if I can search by several labels. 

Thank you

**Comment by tablacus** [comment]
How about an add-on "Label button"?
![6](https://cloud.githubusercontent.com/assets/5156977/25305359/de1bb432-27b4-11e7-80c2-1eecd1c3fc35.png)

Best regards,

**Comment by xingxuanma** [comment]
Um, I have got that add-on. What I mean is, for example, I have a file labelled "A" in a folder, and there is another file labelled "A" in another folder. When I search the label "A", the two files will appear in the search result. Now, I want only the file in the first folder to be displayed in the search result. How can I do that? 

Thanks

**Comment by tablacus** [comment]
List of items labeled "x86"
![image](https://cloud.githubusercontent.com/assets/5156977/25305641/5ac834c4-27ba-11e7-91ba-bc28f1ac937e.png)
Like this?
Use "Label button"　and click "x86".

Thank you,

**Comment by xingxuanma** [comment]
Yes, and now I only want the two folders in root c:\ display. How can I do this?

**Comment by tablacus** [comment]
I've adjusted an add-on "Label" 1.16.
Please try update it.
And input "label:x86 C:\\" into Address bar.

![image](https://cloud.githubusercontent.com/assets/5156977/25338769/5b71318c-293b-11e7-9714-ef2726efe7de.png)

Best regards,

**Comment by xingxuanma** [comment]
Oh, thanks a lot! You do me a big favor.

Thank you
