### ISSUE TITLE
Labels do not display when files moved

### ISSUE THREAD

**Issue by Sunsetra** [tablacus/TablacusExplorer#85]
I attach a  label to a file like this: 
![a](https://cloud.githubusercontent.com/assets/16215245/25562310/b85fb11c-2dbd-11e7-985d-e6e375903af2.png)
then I move it to another folder:
![b](https://cloud.githubusercontent.com/assets/16215245/25562311/bdb82f22-2dbd-11e7-91d0-4fb801638606.png)
the label disappears...

But I can also find the file by click the label button.

-----------------------
Um, I follow the steps above with a folder: 
![1](https://cloud.githubusercontent.com/assets/16215245/25562335/80566ada-2dbe-11e7-810b-66b61e1312a7.png)
and then I move the folder:
![2](https://cloud.githubusercontent.com/assets/16215245/25562336/8c9c5d04-2dbe-11e7-987f-b7860ec58bcf.png)
the label disappears. When I click the label button:
![3](https://cloud.githubusercontent.com/assets/16215245/25562344/d4e868d2-2dbe-11e7-9e08-a6046dee508b.png)
The folder becomes a unrecognizable file and cannot be opened.

**Comment by tablacus** [comment]
I will try to do future examination on that.
Thank you,

**Comment by xingxuanma** [comment]
That's very nice of you. I'm looking forward to your work.

Thank you

**Comment by tablacus** [comment]
I've adjusted it on Label 1.17.
Please update.

Best regards,

**Comment by xingxuanma** [comment]
OK, thank you.
