### ISSUE TITLE
Not really an issue - but I need ALOT of setting up help

### ISSUE THREAD

**Issue by CT71** [tablacus/TablacusExplorer#90]
Before I get too long winded into this I first wanted to know if help is even available through here?  I love the product, but without any real substantial help tutorials anywhere I've configured it to only about half way of how I'd like it to look and work, but the rest I just can't figure out at all.  Just to give you one example of the help I'm looking for.................I can't even figure out how to put a "move to" icon anywhere.  Thanks.

**Comment by tablacus** [comment]
1) Select Type to "Edit".
2) Click "Browse..." and select "Move to folder...".
![5](https://user-images.githubusercontent.com/5156977/28070450-ed9d3c2a-6687-11e7-93fc-ee8b8208f6d8.png)
How about this?

Best regards,

**Comment by CT71** [comment]
First of all, thank you for getting back to me and helping.  Second of all, I hope I can continue to use this because I really like what it "could" offer me, but man I'm not gonna lie, it's very very very non intuitive to the average computer user to try and figure out.  Even though I said I got it halfway to how I want it to look, I got there by not knowing a single thing of what I was doing and just stumbled upon getting half of it right.  I'm trying like heck to put this "move to" icon on here, and while I've managed to do it (there were a few things I still had to do that weren't in the picture) - but now I can't figure out how to put it next to the icons I already have on there, and I can't even figure out how I got those icons there in the first place, lol!  Even when I go into the options mode or add ons mode - for the life of me I don't see any way how I got the icons to where I got them.  Come the weekend I'm going to have to sit down when I have some more time and try to figure this part out.  I atleast now have the move to icon on here - just have to move it now, so I very much appreciate that - thank you.  Hopefully I can get it and then ask you a few more questions after that if I may.  I'm really into ease and simplicity in the layout, so the things I want are very very basic things, so hopefully you'll work with me a bit here.  Thanks a heck of a lot!

**Comment by tablacus** [comment]
How about this page?

[Customize Toolbar - Penflip](https://www.penflip.com/LightTempler/tablacus-explorer/blob/master/configuration/customize-toolbar.txt)

Thank you,

**Comment by CT71** [comment]
I remember seeing that page a few weeks ago when I d'loaded Tablacus but I didn't have the "reference" button so I gave up and just started trying anything and everything.  I'm not sure if I did anything to make the reference tab disappear, but I coulda swore that was one of the first things I tried and when I didn't have it, I gave up.  All I remember it looking like is just like the picture in your above post with the browse button there, and that's what mine looks like right now after I d'loaded the toolbar from the add ons list the other day.

**Comment by tablacus** [comment]
Now "Refrerence ..." is "Browse ...".
Please press "Browse ..." instead of "Refrerence ...".
![5](https://user-images.githubusercontent.com/5156977/28162894-ca2e03be-6803-11e7-803b-de72e01faafd.png)
Best regards,

**Comment by CT71** [comment]
Ah, got it.  Shoulda opened my eyes a little bit and looked into it a bit more.  Hopefully I have the time this weekend to have a second go round with the new info you've provided.  Appreciate you still taking the time with this.

**Comment by CT71** [comment]
Took me like 20 minutes to figure out how to add this screenshot, lol, didn't realize all you had to do was drag it here......good god, lol!

![capture](https://user-images.githubusercontent.com/25874701/28243599-c56d59c8-696c-11e7-8b14-dd49731df719.PNG)

So I definitely cannot figure out how to do what I want.  But I did realize a few things - I thought I was adding icons to the toolbar, but apparently I was (I think) adding them to the title bar.  But I don't see an options tab next to the title bar add on so I'm really not even sure.  But it doesn't matter - I don't care what I have to use to get the icons where I want them - what I'm trying to do is this:

I'd like the tab that says contacts to be to the left of the icon that is the picture of the tree.  And I'd like the three icons that are next to word "help" to be put on the same line as the other icons are (the tree, the back forward arrows, and the + sign.  So basically I'd like them all on the same row to the right of the tab.  And if possible I'd like to delete the whole "file, edit, view, favorites, tools, help" line.  It's just taking up space, and I have the main menu icon instead.  Oh and, how do you create the "view" icons that you have in your upper right screenshots here:

http://www.eonet.ne.jp/~gakana/tablacus/explorer_en.html

That one I actually haven't tried to do yet, so I apologize for asking without trying first.  Thank you.

**Comment by tablacus** [comment]
Open Toos->Addons and click Tool bar's "Options"
![10](https://user-images.githubusercontent.com/5156977/28248059-ee59ae16-6a77-11e7-8ae4-b079519e46d6.png)

Click "Position"
![11](https://user-images.githubusercontent.com/5156977/28248063-22faff9e-6a78-11e7-9e75-2725e1a33417.png)

Click where you want to place the toolbar.
![12](https://user-images.githubusercontent.com/5156977/28248066-5aace75e-6a78-11e7-8737-1abff80370de.png)

Click "Ok".

Best regards,

**Comment by CT71** [comment]
For me this is just not working.  I cannot get my page to look like your screenshot where you have all the icons in a row.  I've hit every configuration and now it's just moving things where I don't want them and I can't even get them back now.  Here's a screenshot of what mine looks like:

Should I start from the beginning again??  Should I delete Tablacus and re-download and start over?  It just seems like everything is out of whack.

![capture](https://user-images.githubusercontent.com/25874701/28250566-5c4fc930-6a07-11e7-99f3-6a4dc50afcf2.PNG)

**Comment by tablacus** [comment]
Toolbar won't move to Inner bar.
How about "Tool bar 3 Left" instead?
Or Main Menu move to "Tool bar 1 Left",

Best regards,

**Comment by CT71** [comment]
Ok, forgetting about toolbars, main menu's and everything else for just a moment.  Is there any way I can get all my icons that are on my picture above on the same horizontal line anywhere?  I realize I'm using the toolbar for a few of the icons and the "inner" add-ons for the other icons - but I don't care what functions are actually used to do this, just wondering if it can be done at all, with any mixture of functions and configurations.  Thanks.

**Comment by CT71** [comment]
Tablacus, I apologize if it seemed like I was becoming too pushy or asking you to do all the work for me.  This was not my intent at all.  Computer programs can overwhelm some of us and I was sincerely confused over what I was trying to do.  I started from scratch today - took my time and didn't freak out - and have gotten everything pretty close to how I wanted it.  I'm really loving this and there's still a ton of stuff that I have no idea what it is yet.  I hope you can accept my apology because I really like this explorer version and I'd still like to post some questions here in the future.  I promise they won't be like all the above questions - they'll be very simple straight forward questions from now on, lol.  Thanks alot.

**Comment by tablacus** [comment]
Well done.
I'm not good at English, so, I'm sorry that there is little explanation of the English version.

Thank you,

**Comment by CT71** [comment]
Thanks.
