### ISSUE TITLE
Mouse click delay on folder in detail view with "Single click activate" Style

### ISSUE THREAD

**Issue by seisen00** [tablacus/TablacusExplorer#91]
Hi Tablacus,

I am using single clicks in my Windows Explorer folder options and set Style in Tablacus List Style to "Single click activate" also (with a Details View) but if I click on any folder after that then Windows Explorer enters to folder immediately while Tablacus always waits a little and enters to folder only after that. If I enter to folder with Enter pressed in Tablacus then it enters immediately, so the problem with delay is present only with left mouse single click.

I've noted that Tablacus waits a time which is set for double-click in Windows settings. I mean, if I increase that time then Tablacus waits longer and if I decrease that time then Tablacus waits lesser before it enters to folder.

I think that for "Single click activate" Style Tablacus must not to wait any double-click timeout (as Windows Explorer is doing). If you have another option for that then please tell me where can I find it.

Could you please to fix this behaviour for "Single click activate" Style in Tablacus?

Thanks,
Andrey.

**Comment by tablacus** [comment]
I will try to check up on that.

Best regards,

**Comment by tablacus** [comment]
I've created an add-on  "single click activate fix".
Please try install it.

Best regards,

**Comment by seisen00** [comment]
Good job, With "Single click activate fix" addon there is no delays anymore with "Single click activate" Style.
Thank you.

**Comment by tablacus** [comment]
My pleasure.
