### ISSUE TITLE
[feature] Open in same tab

### ISSUE THREAD

**Issue by acambule** [tablacus/TablacusExplorer#93]
Hi there,

**Current**

- Open Folder on the treeview opens in _a new tab._
- Open Folder on the horizontal favourites bar opens in _a new tab_
- Open Folder by double click in the content pane opens in _a new tab_

**Wanted**
- By default the current tab should change its content to the new place, instead of opening a new tab.
- A new tab shall only be opened if explicitly asked
  - On the treeview and content pane by right click in context menu or middle mouse button  (that is   already possible)
  - On the favourites bar the same way by an context menu and/or
    using middle mouse button (i've seen that middle mouse button does that already)

thanks and regards
Antonio

**Comment by tablacus** [comment]
By default, they open in the same tab.
Are not you set to open with a new tab?

![4](https://user-images.githubusercontent.com/5156977/28876465-44e07602-77d4-11e7-96a1-480d3c443188.png)

Best regards,

**Comment by acambule** [comment]
Hi,

that option is not set! It is like in your screenshot.
I went through all options of the plugins and tablacus explorer and had seen this option too, and wondered why it was there... 

regards
Antonio

**Comment by tablacus** [comment]
Please enter the following string in the address bar.
`
javascript:alert(OpenMode)
`
![5](https://user-images.githubusercontent.com/5156977/28897176-7a2f99be-781a-11e7-8507-88a32b2570bd.png)

What number do you see?
![6](https://user-images.githubusercontent.com/5156977/28897240-cbc56934-781a-11e7-9b23-808e4c56e07e.png)
![7](https://user-images.githubusercontent.com/5156977/28897243-ceecc4c2-781a-11e7-92c5-64a53bf86c1a.png)

Best regards,

**Comment by acambule** [comment]
Hello again,

i've made a screenshot to show you the results:

![grafik](https://user-images.githubusercontent.com/22659382/28906977-e2071976-781b-11e7-8d5d-f2a72e69b756.png)

regards
Antonio

**Comment by tablacus** [comment]
Basically, Tab add-on and Tab plus add-on are not used at the same time.
So we have the same options.

Best regards,
