### ISSUE TITLE
[Issue] Create New Folder by Keyboard Shortcut

### ISSUE THREAD

**Issue by acambule** [tablacus/TablacusExplorer#94]
Hi,

i'm used to create new folders pressing CTRL+N. This does not work with tablacus.
I've tried to put some New Folder Items into Edit Menu and giving it different keyboard shortcuts.
But none of them work. Here some screenshots:

![grafik](https://user-images.githubusercontent.com/22659382/28908622-eb667940-7824-11e7-93bf-46b9cdc32556.png)

![grafik](https://user-images.githubusercontent.com/22659382/28908650-0bc4e87a-7825-11e7-85c5-e26db8aaa971.png)

Clicking on the Items in Menu work. Using the shortcuts in content panel does not work.

thanks and regards
Antonio

**Comment by tablacus** [comment]
If it does not work please use the add-on "Key".

![8](https://user-images.githubusercontent.com/5156977/28922217-2f68ece4-7894-11e7-9df4-0bfeaa93fcca.png)

Best regards,

**Comment by acambule** [comment]
Great, that works, at least with the tablacus style new folder.

**Comment by tablacus** [comment]
My pleasure.
