### ISSUE TITLE
Recent error Change adapter settings 

### ISSUE THREAD

**Issue by guilhas** [tablacus/TablacusExplorer#96]
Hello,

When in "Control Panel\All Control Panel Items\Network and Sharing Center"
And click "Change adapter settings"
Show Tablacus window with error:
> An error has occurred in the script on this page.
> Line: 2577
> Error: Object doesn't support property or method 'SelectedItems'
> URL: file:///C:/Program Files/te161011/script/common.js

Regards,

**Comment by tablacus** [comment]
I will try to fix it.

Best regards,

**Comment by guilhas** [comment]
Fixed
