### ISSUE TITLE
How to hide the operation message

### ISSUE THREAD

**Issue by dasu88** [tablacus/TablacusExplorer#97]
![2017-08-16_152529](https://user-images.githubusercontent.com/23251263/29352007-ab199e30-8297-11e7-91e0-b263e36de4b2.jpg)

This message will appear when you select a file with a mouse and keyboard, even if I have installed noinfotip, can I make it not appear?

**Comment by tablacus** [comment]
Please try to update Tablacus Explorer 17.8.16.

Best regards,

**Comment by dasu88** [comment]
![2017-08-18_101415](https://user-images.githubusercontent.com/23251263/29441507-50a620aa-83fe-11e7-8cff-4a740827e8af.jpg)

謝謝你的回覆
當我按住滑鼠左鍵，仍出現如圖的訊息

**Comment by tablacus** [comment]
Are you using an add-on "Long press"?
That's it.
I will try to consider it.

Best regards,

**Comment by tablacus** [comment]
Please try check Options -> Mouse -> No infotip
![19](https://user-images.githubusercontent.com/5156977/29494988-998d9e12-85f0-11e7-932e-54e8732b2441.png)

Best regards,

**Comment by dasu88** [comment]
I'm remove Long press, and now it's ok ... thanks...

**Comment by tablacus** [comment]
My pleasure.
